### ISSUE TITLE
Change ELB Healthcheck to SSL to avoid APIServer log TLS handshake spamming

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/cluster-api-provider-aws#1000]
/kind feature

**Describe the solution you'd like**
When the healthcheck protocol is TCP the APIServer logs are
constantly spammed with Handshake EOF errors.
```
I0811 22:52:53.992577       1 log.go:172] http: TLS handshake error from 10.0.1.129:4224: EOF
I0811 22:52:54.630065       1 log.go:172] http: TLS handshake error from 10.0.1.203:16836: EOF
I0811 22:53:03.992780       1 log.go:172] http: TLS handshake error from 10.0.1.129:4240: EOF
```

**Anything else you would like to add:**
This doesn't cause any degradation in functionality, it just makes the APIServer logs really noisy and harder to find things when debugging. Setting the healthcheck target to `SSL:6443` rather than `TCP:6443` resolves this.

**Environment:**

- Cluster-api-provider-aws version: `master`
- Kubernetes version: (use `kubectl version`): v1.14.4 
- OS (e.g. from `/etc/os-release`): `Ubuntu 16.04.6 LTS (Xenial Xerus)`

**Comment by jayunit100** [comment]
This makes using custom TLS Algorithms a little trickier bc we have to match the ELB to support whatever TLS algorithms we use.  Any way we can revert ?
