### ISSUE TITLE
Enhance the generate-yaml.sh script

### ISSUE THREAD

**Issue by rbankston** [kubernetes-sigs/cluster-api-provider-aws#1007]
/kind feature

**Describe the solution you'd like**
When using the generate-yaml.sh script I'd like the output directory to match the cluster name so I could generate new clusters using the script without having to move or delete the previous running of that script as long as the $CLUSTER_NAME variable had been changed

**Anything else you would like to add:**

```
# Directories.¬
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"¬
DIR=${DIR:=${SOURCE_DIR}}¬
OUTPUT_DIR=${OUTPUT_DIR:-${DIR}/out}¬
```

to:

```
# Directories.¬
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"¬
DIR=${DIR:=${SOURCE_DIR}}¬
OUTPUT_DIR=${OUTPUT_DIR:-${DIR}/out/${CLUSTER_NAME}}¬
```

**Environment:**
- Cluster-api-provider-aws version: v0.3.7
- Kubernetes version: (use `kubectl version`): 1.14.4
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by ncdc** [comment]
We don't have generate-yaml.sh any more. @vincepri is this still relevant in the current state of things?

**Comment by vincepri** [comment]
We do have `examples/generate.sh`. In general, I don't know if we should go out of our way to support the examples, apart from basic ones. I think the issue reported might be solved later on with clusteradm or similar tools

**Comment by ncdc** [comment]
@rbankston would you be ok closing this in favor of the proposed work in https://docs.google.com/document/d/1FvdObVNkZt9aHAZ-7X-UKS-VjWx3e0UJzuoKVeNXAaE/edit?

**Comment by rbankston** [comment]
@ncdc would be 100% okay in favor of that. Closing now.
