### ISSUE TITLE
[0.3] Add unit test for missing instanceID on delete

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1012]
**Describe the solution you'd like**
We should add a unit test for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/984, which guards against missing InstanceID when we're in the deletion process.

The PR should be against the `release-0.3` branch.

/kind cleanup
/good-first-issue
/help

**Comment by ncdc** [comment]
@vincepri ok to close?

**Comment by vincepri** [comment]
Yep

/close
