### ISSUE TITLE
Unit testing for AWSMachine controller

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1035]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We should have some more comprehensive unit testing around AWSMachine reconciliation, perhaps using mocks and stuff. 

We should test AWSMachines as they move through phases.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by liztio** [comment]
/unassign
/remove-lifecycle active

This is a hairy problem. The machine controller has several hundred-line functions, takes in multiple giant blocks of mutable state, and has almost no modularity. I don't have any confidence in my ability to write tests that will actually get used.

**Comment by liztio** [comment]
![image](https://user-images.githubusercontent.com/33235082/66498065-7709de80-ea8b-11e9-84ce-a3996ffe6634.png)
here's my diagram of the requirements of just one reconcile function

**Comment by liztio** [comment]
/assign
/lifecycle active

past!liz was a coward, present!liz is forging onwards
