### ISSUE TITLE
add opportunity to modify listeners for ELB

### ISSUE THREAD

**Issue by dinomiteX** [kubernetes-sigs/cluster-api-provider-aws#1057]
/kind feature

**Describe the solution you'd like**
I would like to have the opportunity to add listeners to the ELB of the controlpanel. 
At the moment its only one listener with port 6443, and this is hardcoded at [https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/87331ba1900892bb04be5ef58ba993ee78ae8be6/pkg/cloud/services/elb/loadbalancer.go#L138](url)

and the reconciling only uses this default configuration to create ELBs [https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/87331ba1900892bb04be5ef58ba993ee78ae8be6/pkg/cloud/services/elb/loadbalancer.go#L39](url)

correct me if im wrong but it seems like there is no way to modify this, even if you set the ProviderSpecs correctly  
**Anything else you would like to add:**
For automation purpose its nice to have this feature, because some companies have restricted firewalls and proxies.

**Environment:**
- Cluster-api-provider-aws version: v0.3.7

**Comment by detiber** [comment]
You are correct. This gets a bit more complicated in v1alpha2, though with the separate bootstrap provider. I'm wondering if we need to add an optional field to the `Cluster` object to allow for overriding the API port in a single location that can be referenced from the infrastructure provider cluster, infrastructure provider machine, and the bootstrapping provider?

@vincepri @ncdc thoughts?

**Comment by vincepri** [comment]
Would it make sense to add the port field under `Cluster.Spec.ClusterNetwork`? I'd fine adding the field (without the related logic) for now and then address that after v1alpha2 is released.

**Comment by detiber** [comment]
Seems as good a place as any to me until we have proper control plane management.

**Comment by dinomiteX** [comment]
Sounds good for me, thanks

**Comment by vincepri** [comment]
@dinomiteX #1126 adds support to customize the APIServer load balancer port as we discussed, is this sufficient to fix your issue?

**Comment by dinomiteX** [comment]
@vincepri I will check it thank you

**Comment by dinomiteX** [comment]
This looks pretty good, i will close this issue. :)
