### ISSUE TITLE
Deleting Cluster results in failed AWSMachine deletion

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1059]
/kind bug

**What steps did you take and what happened:**
- created a single control plane cluster
- attempted to delete the cluster with `kubectl delete cluster`
- AWSMachine controller fails to delete with the following error 
```
E0822 19:09:57.136753       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="Machine.cluster.x-k8s.io \"test-a\" not found"  "controller"="awsmachine" "request"={"Namespace":"default","Name":"test-a"}
```
- This further blocks deletion of the AWSCluster because of dependency issues.

**What did you expect to happen:**
Cluster and AWSMachine deletion to be successful

**Environment:**

- Cluster-api-provider-aws version: latest from master
- Kubernetes version: (use `kubectl version`): v1.14.4

**Comment by vincepri** [comment]
I guess this is because the Machine has been deleted and we always try to fetch it?

**Comment by detiber** [comment]
This seems to be resolved with the latest changes to cluster-api for v1alpha2
/close
