### ISSUE TITLE
Machine deletions fails if there is no ELB

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#1084]
/kind bug

**What steps did you take and what happened:**
I deleted AWS resources manually and then initiated machine and cluster deletion from CAPA.
As a result of this what I saw is delete machine deployments failing continuously because of:
```
I0814 17:10:39.243788       1 instances.go:67] [machine-actuator]/cluster.k8s.io/v1alpha1/4d95faba9cb7ee388671ac3cef6ee79b39c25f15/bf038fa5/worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh "level"=2 "msg"="Looking for existing machine instance by tags"  
I0814 17:10:39.288157       1 machine_controller.go:181] Deleting node "ip-10-0-0-20.us-west-2.compute.internal" for machine "worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh"
E0814 17:10:39.301721       1 machine_controller.go:183] Error deleting node "ip-10-0-0-20.us-west-2.compute.internal" for machine "worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh": Delete 
https://bf038fa5-apiserver-261840232.us-west-2.elb.amazonaws.com:6443/api/v1/nodes/ip-10-0-0-20.us-west-2.compute.internal
: dial tcp: lookup bf038fa5-apiserver-261840232.us-west-2.elb.amazonaws.com
on 10.96.0.10:53: no such host
```

**What did you expect to happen:**
What I expected was that deletions would succeed since the resources are NOT FOUND.

**Anything else you would like to add:**
Also, If I delete the ELB, it could be recreated, unless the Cluster is being deleted. That said, it would also mean a different DNS name, which imply that anything referencing the old DNS name would need to be updated, which may not be done automatically. That would include the kubeconfig secret, but more importantly the client config/kubeadm config for all of the existing Machines in the cluster.

**Environment:**

- Cluster-api-provider-aws version: v0.3.7
- Kubernetes version: (use `kubectl version`): 1.14.1
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
How would we connect to the cluster without an elb? 🤔

**Comment by vivgoyal** [comment]
@vincepri Should we reconcile elb on "NotFound" and then try deletion?
Also what more worrying is the part I mentioned in "Anything else you would like to add".

**Comment by ncdc** [comment]
I filed https://github.com/kubernetes-sigs/cluster-api/issues/1446 to try to delete the Node multiple times, then move on without considering it an error.

**Comment by ncdc** [comment]
The node deletion issue was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/1452, which will be in a future CAPI v0.2.x release. @vivgoyal PTAL and let us know if you think that's sufficient. Thanks!

**Comment by vivgoyal** [comment]
Looks good to close. I haven't tested it yet though. If I find any issues, I can anyday open a new one.

**Comment by ncdc** [comment]
Let's leave it open until you can test it with CAPI v0.2.3 or newer (v1alpha2)

**Comment by vincepri** [comment]
This should have been fixed

/close
