### ISSUE TITLE
NPE if MachineVersion is not set.

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1092]
/kind bug

**What steps did you take and what happened:**
I tried to create a machine and got an NPE because I forgot to set the Machine version.

**What did you expect to happen:**
I expected a default value

**Anything else you would like to add:**
This is the line throwing the NPE https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/89e8ab62a6ee0de8f6644ae44cb7f224fc202f38/pkg/cloud/services/ec2/instances.go#L126

**Comment by ncdc** [comment]
@chuckha please update the link to the source code line to a specific commit (you can press `y` in the browser and it will change from `master` to a commit) - thanks!

**Comment by chuckha** [comment]
yes, very good call. thx

**Comment by tahsinrahman** [comment]
@chuckha @ncdc if you’re not working on this, can take this? Thanks!

**Comment by chuckha** [comment]
@tahsinrahman yes, absolutely

/assign @tahsinrahman

**Comment by chuckha** [comment]
The lifecycle active is for @tahsinrahman so that other people do not swoop in and take this issue away from them.

**Comment by tahsinrahman** [comment]
In kubeadm bootstrapper does the following
- kubernetes version defined in `machine.Spec.Version`, not in kubeadm cluster config, uses the `machine.Spec.Version`
- Not defined in `machine.Spec.Version`, but defined in kubeadm cluster config, then it uses kubeadm cluster config
- Defined in both `machine.Spec.Version` and kubeadm cluster config, then it uses the kubeadm config
- Not defined anywhere, then kubeadm defaults to a value itself

For aws provider, the `machine.Spec.Version` must be defined, and it must match the bootstraper version, as we're using it for AMI lookup. So
- the the `machine.Spec.Version` should be updated/reconciled from bootstrap provider to set it to correct version, or
- `machine.Spec.Versoin` should be a required field, and bootstrap provider must use the version defined here

**Comment by ncdc** [comment]
Worth pointing out: we only do an AMI lookup if you haven't specified an AMI to use in your AWSMachine spec.

**Comment by tahsinrahman** [comment]
IMO, both the versions should be consistent. If one take precedence over the other, the other field should be updated

**Comment by ncdc** [comment]
cc @chuckha @fabriziopandini - PTAL at the logic described above and let me know if you have any thoughts.

**Comment by fabriziopandini** [comment]
> the machine.Spec.Version should be updated/reconciled from bootstrap provider to set it to correct version

If for the AWS providers only there are specific consistency requirements around versions, at least at a first sight, I find a little bit weird to delegate the enforcement of such requirements to the bootstrap provider. So I don't think the bootstrap provider should update in any case `machine.Spec.Version`.

**Comment by ncdc** [comment]
For CAPA, if machine.spec.version is nil or empty, possible options could include:

1. Set the AWSMachine's status.error* fields to indicate a permanent failure
1. Record an event on the AWSMachine indicating the Machine needs a version
1. Record an event on the Machine indicating it needs a version

Does any of these make sense? Anything I'm missing?

**Comment by detiber** [comment]
@ncdc I'd like to avoid 1, since manually fixing it would require a user to remove ErrorMessage/ErrorReason in addition to adding the version.

I like the idea of 2 or 3, but it is not persistent, so maybe we need a `Conditions` field or similar to record it in a more persistent way?

**Comment by detiber** [comment]
Alternatively, we could register a validation webhook as part of deploying CAPA that could enforce the requirement.

**Comment by ncdc** [comment]
I originally left out the webhook as an option because I didn't think it would cover all the cases, but now I'm thinking it should work.

Are we able to state that webhooks are required for correct operation? In other words, can we assume that things like machine.spec.version will always be populated because the validating webhook guards against that?

**Comment by vincepri** [comment]
Is the webhook you're talking about a CAPI one or an additional one that CAPA runs only on Machines that are attached to AWSMachines?

**Comment by ncdc** [comment]
CAPA on Machines with infra ref = AWSMachine

**Comment by detiber** [comment]
I think once we have webhooks it is more than reasonable to say that they are required for correct operation

**Comment by ncdc** [comment]
🎶 to my ears

**Comment by joonas** [comment]
@tahsinrahman is this something you're still interested in implementing?

**Comment by ncdc** [comment]
Recording some Slack discussions: because we can't control or guarantee the order that the Machine & AWSMachine are created, and we also don't have an OwnerReference until after the AWSMachine is initially persisted, I don't think this is a very easy problem to solve. We could instead:

1. Mark the AWSMachine as terminally failed and require the user to delete it, update the machine with a version, and create a new AWSMachine
1. Don't NPE, but instead emit an event when we hit this scenario

I think option 1 has a better UX because events are not always the first thing people look at, and they have a TTL.

**Comment by ncdc** [comment]
Trying to minimize the scope of 0.5, so I'm going to move this to Next. If we get a fix in before the release, that's great too. We can document this is a known issue until a fix is in place.

/milestone Next
