### ISSUE TITLE
Inconsistent json fields

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1093]
/kind bug

**What steps did you take and what happened:**
I expected the same field to be represented by the same key:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/89e8ab62a6ee0de8f6644ae44cb7f224fc202f38/api/v1alpha2/awscluster_types.go#L38

and 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/89e8ab62a6ee0de8f6644ae44cb7f224fc202f38/api/v1alpha2/awsmachine_types.go#L82

Should be the same.

/priority longterm-important
/milestone v0.4.x

**Comment by chuckha** [comment]
actually i suppose this is an api change

/milestone Next

**Comment by vincepri** [comment]
Let's fix it before release?

**Comment by detiber** [comment]
+1 to fixing before release
