### ISSUE TITLE
UMBRELLA: Add common aws code.

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#11]
Common utilities and wrappers can be incorporated now and doesn't need to wait on some of the design fronts.  

We can distill and crib from kubicorn/prototypes/kops etc. 

/assign @chuckha 

Subtickets:

- [x] #23 VPC
- [ ] #24 Instance
- [x] #28 Internet Gateway
- [x] #29 Subnet
- [x] #30 RouteTable
- [x] #35 NAT Gateway
- [x] #36 Security Groups
- [x] #37 ELB

**Comment by timothysc** [comment]
This can be an umbrella ticket that needs to be broken down.

**Comment by vincepri** [comment]
@detiber I think me might be able to close this, given that most of the work is in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/19

**Comment by randomvariable** [comment]
This looks like a
/close

to me
