### ISSUE TITLE
Default Cluster Region?

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1100]
/kind bug

**What steps did you take and what happened:**
It would be great to default the AWScluster's Region to whatever the credentials are set to. I'm probably missing some context for why this isn't defaulted.

**Comment by detiber** [comment]
I'm fine with this approach, but we'll need a way to detect that the region is actually set for the provided credentials, otherwise we'll likely get an error when attempting to create the session.

**Comment by ncdc** [comment]
Let's test encoding the credentials secret with a region + making AWSCluster.spec.region optional and see if it works.

**Comment by rosskukulinski** [comment]
I'm confused by this.  AWS credentials are global and work across all AWS regions. Furthermore, we want a management cluster to support provisioning clusters in different regions.

**Comment by detiber** [comment]
This is more about having a default and not requiring that a specific region be set in config. The ability to override region should not be impacted

**Comment by randomvariable** [comment]
Don't think there's been much demand for this beyond testing, so maybe
/close 
for now.
