### ISSUE TITLE
sshKeyName on awsmachine should adopt sshKeyName on awscluster

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1101]
/kind bug

The sshkeyname for cluster and machine should match because the sshkeyname used for the cluster is used on the bastion while the sshkeyname used for the machine is used on the actual instance. If they are different then you will need two keys to get onto an instance. One to ssh to the bastion and then one to ssh from the bastion to the instance. 

Are we intentionally allowing this use case for some reason? I'm trying to think of a deployment model that might use this but I'm coming up short.

I suggest we copy the keyname from the cluster to all the machines associated with the cluster.

**Comment by detiber** [comment]
I would suggest this defaulting path:
- If user set (on either AWSCluster or AWSMachine) honor it
- If not set on AWSMachine, and set on AWSCluster, use value from AWSCluster
- If not set on AWSMachine, and not set on AWSCluster, use default value from shared constant

**Comment by ncdc** [comment]
Should we consider removing the ssh key name from AWSMachine?

**Comment by vincepri** [comment]
Folks might want to use different SSH keys depending on the MachineDeployment

**Comment by ncdc** [comment]
Good point
