### ISSUE TITLE
The readme on the docs directory is pointing to broken link for getting started guide. 

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api-provider-aws#1117]
/kind bug

**What steps did you take and what happened:**
Open docs directory github. click 

**What did you expect to happen:**
The getting started link must point to https://cluster-api.sigs.k8s.io/user/quick-start.html. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
This is fixed.
/close

**Comment by joonas** [comment]
Fixed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1111
