### ISSUE TITLE
Make the webhook server port configurable via flag

### ISSUE THREAD

**Issue by joonas** [kubernetes-sigs/cluster-api-provider-aws#1120]
/kind feature

**Describe the solution you'd like**

It was [pointed out](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1116#discussion_r322925177) that in some cases the [default value (443)](https://github.com/kubernetes-sigs/controller-runtime/blob/699340657992a5ffe4d400a9f68330420fb4a689/pkg/webhook/server.go#L42) for the [webhook server port](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options.Port) can be problematic, so we should should make this [configurable via a flag](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L125-L131).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by luigi-riefolo** [comment]
@joonas I'd like to work on this. Could you please provide an example of the desired functionality and/or how to run it?

**Comment by joonas** [comment]
@luigi-riefolo Great!

I believe what we should look at doing is adding a new flag (say `webhook-port`) that you can pass in to the CAPA manager (see how [existing flags are setup](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L54-L110)), which then subsequently gets passed down as an option when [initializing the controller-runtime manager](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L125-L131). 

Note, we should default the new flag with the [existing default value](https://github.com/kubernetes-sigs/controller-runtime/blob/699340657992a5ffe4d400a9f68330420fb4a689/pkg/webhook/server.go#L42).

Is that enough context to get you started?

**Comment by tahsinrahman** [comment]
@joonas  should we set default value to `443`? then it'll always fail if we don't define value via flag

**Comment by detiber** [comment]
@tahsinrahman I think having the default be `443` for the binary would be good, then we can add a kustomize patch to config/default/ to override the argument to a more appropriate port for our use case.

**Comment by ncdc** [comment]
Wouldn't it make more sense to use a higher port so it doesn't require root? I'd go with 8443 for the  default (assuming no conflicts with e.g. the metrics server or something else).

**Comment by vincepri** [comment]
+1 on having a higher port and use non-root user

**Comment by wfernandes** [comment]
@luigi-riefolo Could you `/assign` and `/lifecycle active` this issue if you are actively working on it?

**Comment by luigi-riefolo** [comment]
@joonas it is

**Comment by luigi-riefolo** [comment]
@joonas which version should I use as base branch for the PR?
master: does not contain `clusterctl`, therefore `make create-cluster-management` fails
release-0.3:  does not contain [main.go](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L54-L110) with all the flags you were referring to

**Comment by joonas** [comment]
@luigi-riefolo I would recommend working against the `master` branch (for the current `v1alpha2` release). 

`clusterctl` has been moved from the provider-specific code to [core cluster-api](https://github.com/kubernetes-sigs/cluster-api/tree/master/cmd/clusterctl) instead, so you would have to first get a copy of it from the `cluster-api` repository.

@detiber @ncdc @vincepri thoughts on having a script in this repo that would fetch `clusterctl`?

**Comment by vincepri** [comment]
While we don't ship clusterctl as part of the release, the Makefile builds it in a local directory before using it https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/Makefile#L109-L110

**Comment by luigi-riefolo** [comment]
@vincepri the above make target generates this error:

```
go build -o bin/clusterctl sigs.k8s.io/cluster-api/cmd/clusterctl
build sigs.k8s.io/cluster-api/cmd/clusterctl: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.1.2+incompatible (/home/luigi/go/pkg/mod/github.com/!azure/go-autorest@v11.1.2+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.0 (/home/luigi/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0)
Makefile:110: recipe for target 'bin/clusterctl' failed```

any idea?

**Comment by vincepri** [comment]
That's unfortunate, can you file a different issue? Seems something broke somewhere in modules

**Comment by vincepri** [comment]
Filed https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1169
