### ISSUE TITLE
Controller log names are too verbose

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1121]
We have log "names" (`r.Log.WithName()`) that are too verbose. Here is an example for the AWSCluster controller, and we have a similar issue with AWSMachine.

```
controllers/AWSCluster/awscluster-controller/namespace=default/awsCluster=capi-quickstart/infrastructure.cluster.x-k8s.io/v1alpha2/cluster=capi-quickstart
```

If we break that apart:

1. `controllers/AWSCluster` comes from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/main.go#L142
1. `awscluster-controller` is a repeat of the previous name, and it comes from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L57
1. `namespace=default` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L58)
1. `awsCluster=capi-quickstart` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L59)
1. `infrastructure.cluster.x-k8s.io/v1alpha2` we should either remove or include what this is (`apiVersion=infrastructure.cluster.x-k8s.io/v1alpha2`) (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L71)
1. `cluster=capi-quickstart` is ok (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a745288a721d0509fe853ff271683f7973302914/controllers/awscluster_controller.go#L83)

One other thing that's a little confusing is that the "name separator" is `/`, and some of our names have slashes in them. So it makes it hard to know where the separation of each name segment is.

/kind cleanup
/help
/good-first-issue
/priority important-longterm
/milestone Next

**Comment by detiber** [comment]
In addition to seeing if we can change the separator, I would also like to see us remove separate entries for namespace and name, and rather collapse them down to a single reference to `namespace/name`

**Comment by ncdc** [comment]
We currently use klogr, which hardcodes the separator to `/`

**Comment by ncdc** [comment]
```
// WithName returns a new logr.Logger with the specified name appended.  klogr
// uses '/' characters to separate name elements.  Callers should not pass '/'
// in the provided name string, but this library does not actually enforce that.
```

hmmm

**Comment by vincepri** [comment]
We should definitely remove the APIVersion from the field, doesn't really provide any useful information IMO

**Comment by tahsinrahman** [comment]
do we want to keep the both?
```awsCluster=capi-quickstart
cluster=capi-quickstart```

**Comment by tahsinrahman** [comment]
what about keeping the name as `AWSCluster` or `awscluster-controller`, and use other info as `log.WithValues`?

**Comment by vincepri** [comment]
I'd keep only the controller name, the AWSCluster, AWSMachine, and specify the other fields as part of the WithValues calls as you mentioned
