### ISSUE TITLE
Specify existing ENI as primary interface for new EC2 instance

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1135]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We have a handful of use cases where we need to specify an existing ENI when creating a new EC2 instance. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I believe this would be another field in AWSMachine to be passed through the EC2 runInstance call. 

I confirmed that terminating an instance does not delete the primary ENI if the ENI was explicitly specified, which is good. I believe there is some homework to do around security groups - would deleting the AWSMachine warrant detaching cluster security groups from the ENI?

**Environment:**

- Cluster-api-provider-aws version: latest and greatest
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by detiber** [comment]
Since this is proposing the addition of another field, I'm wondering if v0.4.x is appropriate here.

**Comment by vincepri** [comment]
Adding a new field should be ok, as long as it's contained within CAPA and doesn't change the default behaviors

**Comment by rudoi** [comment]
/assign
/lifecycle active

:D

**Comment by ncdc** [comment]
@rudoi are you still working on this?
/milestone v0.5.0

**Comment by ncdc** [comment]
@rudoi ping?

**Comment by rudoi** [comment]
oh this is totally done and merged already @ncdc. sorry i missed the ping!

/close
