### ISSUE TITLE
BYO security groups

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/cluster-api-provider-aws#1137]
/kind feature

**Describe the solution you'd like**
In our organization security group management is tightly controlled - it is not possible to grant processes or users the permission to manage security groups. They are pre-provisioned through a partially manual process. There are also specific security groups our organization requires attached to all instances, so we need to bring those into the mix as well. I would like to be able to specify the particular security groups existing in our VPCs which should be attached to the instances and load balancers created by CAPA.

`AWSMachineSpec` already has an `AdditionalSecurityGroups` property, so my proposal is to add an optional `CreateSecurityGroups` flag to the `AWSCluster.Spec.NetworkSpec` struct. The flag would default to `true`, and when set to `false` the controller would not attempt to create security groups and instead only use the groups defined in `AdditionalSecurityGroups`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.4.0
- Kubernetes version: (use `kubectl version`): v1.15.3 
- OS (e.g. from `/etc/os-release`): darwin

**Comment by arzarif** [comment]
I think it'd be valuable to consider this request together with:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/392

Seems like both requests would inform the requirements associated with any redesign of CAPA's management of security groups.

**Comment by vincepri** [comment]
@andrewmyhre Sounds like a good feature to implement, although the proposed solution seems to be a little different with how the current APIs are implemented. Would you be able to write-up a more detailed proposal taking into account the current behavior that we have today for bringing in your vpc or subnets.

**Comment by andrewmyhre** [comment]
So, I've finally been able to dig in and get more familiar with the controller implementation and I agree.

In our organization there are specific security groups that must be applied to every instance, but only instances - not load balancers. Applying them to load balances as well might be fine but I would rather adhere to least-privileges.

We compose security groups together on our kubernetes instances, like this:

Etcd nodes:
- sg_all_instances
- sg_node
- sg_etcd

Master nodes:
- sg_all_instances
- sg_node
- sg_master

Worker nodes:
- sg_all_instances
- sg_node
- sg_worker

Etcd instances have their own group due to us running them as an external federation, but I we want to move to collating them with our master nodes so we'll combine those groups. That should leave us in a position to just specify a single group per role which would fit the existing data structure.

So really what we're after is to be able to specify _overrides_ for the various roles, either as a new map on the AWSCluster type or as a []string on the AWSMachine type. The latter would provide a great deal of flexibility I think.

**Comment by andrewmyhre** [comment]
So, setting desired security groups on AWSMachine resources makes AWSCluster reconciliation a little tricky. It would need to skip that reconciliation for role security groups if the machines had security groups provided.

**Comment by vincepri** [comment]
It sounds like we might need a new field to specify the authoritative list of security groups of a Machine, while in the current state, we only allow users to _add_ new ones

**Comment by vincepri** [comment]
@r5sec5cyl  Are you planning to work on this feature? If so, use `/lifecycle active`

**Comment by r5sec5cyl** [comment]
Both the [reconciler](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/83fceb0/controllers/awsmachine_controller.go#L364) (via [ensureSecurityGroups](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/83fceb0/controllers/awsmachine_security_groups.go#L47)) and [CreateInstance](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/83fceb0/pkg/cloud/services/ec2/instances.go#L201) use [GetCoreSecurityGroups](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/83fceb0/pkg/cloud/services/ec2/instances.go#L241) to provide the base security groups. This function accepts [MachineScope](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/83fceb0/pkg/cloud/scope/machine.go#L89) as input which has values for clusterv1.Machine and infrav1.AWSMachine.

Would it make more sense if core security groups were considered default security groups with a flag inside `Machine` or `AWSMachine` for `ignoreDefaultSecurityGroups`? `GetCoreSecurityGroups` would then just return an empty slice when that flag is true.

**Comment by r5sec5cyl** [comment]
> @r5sec5cyl Are you planning to work on this feature? If so, use `/lifecycle active`

Thank you @vincepri - I made the update

**Comment by r5sec5cyl** [comment]
I believe we can classify configurations into three types:
1. non-BYO SG configurations - default SGs are acceptable, do NOT have own SGs
2. plus-BYO SG configurations - default SGs are acceptable, have own SGs
3. only-BYO SG configurations - default SGs are NOT acceptable, have own SGs

Assumptions:
 - This affects all instance types and clusters.
 - Any solution should be backwards compatible and not affect existing usage.
 - SecurityGroups are defined at the cluster level and the instance level.
 - There are three places affected by SGs in the logic: provisioning an instance, ensuring correct SGs during normal reconciliation, detaching during reconciling deletion of instance.

Proposed solutions:
1. Create authoritative SG config that overrides default SGs
    - e.g. `NetworkSpec` to include `SecurityGroupOverrides` slice of SG ARNs
2. Enable ability to turn off default SGs
    - e.g. `AWSMachineSpec` or `NetworkSpec` to include `IgnoreCoreSecurityGroups` flag

Effectively, both solutions provide a mechanism to stop core security groups from being created. The first provides a location for the user-defined SGs to be listed, while the latter uses `AdditionalSecurityGroups` to source those SGs.

Would one of these strategies make sense for a solution to this, or would some other solution make more sense for the long term goals?

**Comment by voor** [comment]
@r5sec5cyl How are you progressing on this feature?

**Comment by detiber** [comment]
> Proposed solutions:
> 
> 1. Create authoritative SG config that overrides default SGs
>    
>    * e.g. `NetworkSpec` to include `SecurityGroupOverrides` slice of SG ARNs

Rather than a slice, how about a map using the internal "role" name of the security group as the key. Not sure if we could use security group IDs rather than ARNs, as they might be nicer for users to handle as well.

This would also potentially allow for users to byo only a subset of the security groups and we would know where to apply the appropriate security groups as needed.


> 2. Enable ability to turn off default SGs
>    
>    * e.g. `AWSMachineSpec` or `NetworkSpec` to include `IgnoreCoreSecurityGroups` flag
