### ISSUE TITLE
v1alpha2 delete hangs when create the AWSMachine with wrong invalid key

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#1138]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Create a cluster and AWSCluster object. 
2. create controlplane AWSmachine with invalid SSH
3. delete the Cluster object by using "kubectl cluster delete ".

The deletion of AWSCluster object hangs.
I can see the AWSmachine object is not deleted. Manually run `kubectl delete awsmachine XXX` still hangs

**What did you expect to happen:**
The cluster should be able to be deleted if AWSmachine was created with wrong ssh key

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I have manually deleted the finalizer of the awsmachine and is able to delete the machine. It is safe because the machine was never created in the first place. However, since the machine was not created, it should be able to be deleted.

**Environment:**

- Cluster-api-provider-aws version:  0.4.0
- Kubernetes version: (use `kubectl version`):  1.15
- OS (e.g. from `/etc/os-release`):  us.gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller:v0.4.0

**Comment by liztio** [comment]
I'm unable to reproduce this, I suspect #1144 fixed it. @Lokicity Are you able try again with v0.4.1?

**Comment by Lokicity** [comment]
Could you please let me know the exact capi/capa version for this fix? Is it published?

**Comment by liztio** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.4.1 should have it, and any capi version that supports v1alpha2 should work, try https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.2.3

**Comment by ncdc** [comment]
@Lokicity have you had a chance to test this again?

**Comment by detiber** [comment]
@Lokicity is this still an issue?

**Comment by Lokicity** [comment]
Yes, if the cluster is created with wrong key, deletion hangs

```

E0310 04:38:23.698898       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster c7673bee99c7e5f260f93605ca3e11e936dfce3e/01e313zs4ewhf43wng2m83p3dx: failed to delete vpc \"vpc-0d2b22ae83959a24d\": DependencyViolation: The vpc 'vpc-0d2b22ae83959a24d' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: e1147957-f027-4756-b0b1-9d32a0da88da"  "controller"="awscluster" "request"={"Namespace":"c7673bee99c7e5f260f93605ca3e11e936dfce3e","Name":"01e313zs4ewhf43wng2m83p3dx"}
--
 

```
