### ISSUE TITLE
Debugging hanging deletes is hard

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1139]
/kind bug

It is hard, given the error logs today, to understand what is happening when a Cluster fails to delete. CAPA/CAPI/CABPK do not provide insight into what is hanging when it gets deleted.

I want to know what **exactly** is trying to be deleted. If it's hanging, the last log I should see is "trying to delete ..." or similar. 

If we were able to understand why deletes are hanging then we could provide an even more useful error message. Perhaps we can add a timeout to the delete that provides the user with action if the timeout is reached.

/priority important-soon
/milestone v0.4.x

**Comment by chuckha** [comment]
cc @lokicity

**Comment by chuckha** [comment]
This might be resolved with increasing verbosity of the manager to at least -v=2

**Comment by Lokicity** [comment]
I have a machine stuck in `deleting` state for quite a while. After turning capa to v=2, in one iteration, it provided the log
```
yangshan-a02:bar yangshan$ kubectl logs capa-controller-manager-84cb77b4bd-rvx75 -n capa-system-2 -f | grep capi-quickstart-controlplane-ha0
I0918 00:05:03.925376       1 awsmachine_controller.go:169] controllers/AWSMachine/awscluster-controller/namespace=bar/awsMachine=capi-quickstart-controlplane-ha0/infrastructure.cluster.x-k8s.io/v1alpha2/machine=capi-quickstart-controlplane-ha0/cluster=capi-quickstart-ha/awsCluster=capi-quickstart-high "level"=0 "msg"="Handling deleted AWSMachine"  
I0918 00:05:03.925546       1 instances.go:42] controllers/AWSMachine/awscluster-controller/namespace=bar/awsMachine=capi-quickstart-controlplane-ha0/infrastructure.cluster.x-k8s.io/v1alpha2/machine=capi-quickstart-controlplane-ha0/cluster=capi-quickstart-ha/awsCluster=capi-quickstart-high "level"=2 "msg"="Looking for existing machine instance by tags"  
I0918 00:05:04.019210       1 controller.go:242] controller-runtime/controller "level"=1 "msg"="Successfully Reconciled"  "controller"="awsmachine" "request"={"Namespace":"bar","Name":"capi-quickstart-controlplane-ha0"}
```

It added the line ```"Looking for existing machine instance by tags"  ``` but still not clear on why the machine is stuck in deleting

**Comment by randomvariable** [comment]
@Lokicity There's a possibility you are hitting this:
```
machineScope.V(3).Info("Unable to locate instance by ID or tags")
```
in which case you need to bump to `-v=3`

Intending to add an event for this as well.

If it isn't the instance not existing, then if you have a test case, would appreciate it.
