### ISSUE TITLE
set capa controller set with hostnetwork with true

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#1140]
/kind feature

the CAPA controller pod generated by the CAPA controller STS.

The robustness of the capa controller depends on the robustness of the container network and the VPC network. If hostnetwork set with `true`, the robustness of the capa controller depends only on the robustness of the VPC network.

This can improve the robustness of the system.

**Comment by detiber** [comment]
I worry a bit about this requested change, especially if multiple cluster-api related controller managers are also configured this way on smaller management clusters. We'll quickly get into port conflicts around the default port values.

**Comment by ncdc** [comment]
My stance: if you want to use hostNetwork, you may make that change in your deployments, but I'd prefer we continue to use pod networking as the default.

**Comment by vincepri** [comment]
Closing this given that folks can use kustomize to patch the default yaml files

/close
