### ISSUE TITLE
Set up tags required for cloud provider integration

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#1142]
/kind feature

the alb-ingress-controller need set correct tag with the subnet, and the EKS Cluster set the follow tags too.

```
kubernetes.io/role/internal-elb must be set to 1 or `` for internal LoadBalancers
kubernetes.io/role/elb must be set to 1 or `` for internet-facing LoadBalancers
```

**Comment by randomvariable** [comment]
Docs are:
* https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery
* https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
