### ISSUE TITLE
Should we wait on AWS operations to complete when reconciling?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1145]
In #1144, there was some discussion about whether we should wait for AWS operations to complete, or if we should check their status the next time we reconcile. For example, when terminating an ec2 instance, should we wait for it to finish before returning a reconcile result, or should we return early, and the next time we reconcile the AWSMachine, check the termination status.

I'd like to propose one additional alternative to consider, although I'm not sure if it's feasible with controller-runtime: when we need to wait for an AWS operation, spawn a goroutine that waits for the AWS operation to complete, and then enqueues the related object (AWSMachine/AWSCluster). This would avoid having to wait until the next resync (10 minutes).

cc @rudoi @detiber

**Comment by ncdc** [comment]
That's fine, too, although I 100% want to get rid of RequeueAfterError and have things return a real `Result` instead with the requeue after details.

**Comment by vincepri** [comment]
FWIW, in GCP we wait for operations to finish before giving up, although we raised the default concurrency to 10 for each controller. In this way, we have enough space for operations to take place, but we also allow for each operation to finish properly

**Comment by detiber** [comment]
Upping the concurrency only buys us so much for scalability, requeueing while we are waiting potentially buys us a lot more.

**Comment by randomvariable** [comment]
I think we are going to be moving to removing the waiters and requeing, so this will probably be in conflict.

/close 
for now.
