### ISSUE TITLE
Allow customizing the control plane ELB listen port

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/cluster-api-provider-aws#1157]
/kind feature

**Describe the solution you'd like**
Our existing Kubernetes infrastructure has adopted the convention that control plane load balancers listen on port 443 rather than 6443. We'd like to be able to keep this convention as we adopt cluster-api, so we can avoid modifying our architecture specifications and security groups (in our organization these are heavy processes which require input from multiple divisions).

**Environment:**

- Cluster-api-provider-aws version: v0.4.0
- Kubernetes version: (use `kubectl version`): v1.15.3
- OS (e.g. from `/etc/os-release`): ubuntu 16.04

**Comment by detiber** [comment]
This should already be possible by setting `Cluster.Spec.ClusterNetwork.APIServerPort`

**Comment by andrewmyhre** [comment]
Ah you're right, this was added to master recently. Closing.
