### ISSUE TITLE
Expand e2e test to support deploying and scaling of MachineDeployments

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1160]
/kind feature

**Describe the solution you'd like**
Building on https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1122, extend the e2e tests to also deploy and scale MachineDeployments

/priority important-soon
/milestone v0.4.x

**Comment by ncdc** [comment]
This is done
/close

**Comment by ncdc** [comment]
@detiber if we need to forward port to master, could you please create a new issue?
