### ISSUE TITLE
make bin/clusterctl fails with go mod errors

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1169]
/kind bug

**What steps did you take and what happened:**
Run `make bin/clusterctl`:
```
go build -o bin/clusterctl sigs.k8s.io/cluster-api/cmd/clusterctl
build sigs.k8s.io/cluster-api/cmd/clusterctl: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.1.2+incompatible (/home/luigi/go/pkg/mod/github.com/!azure/go-autorest@v11.1.2+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.0 (/home/luigi/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0)
Makefile:110: recipe for target 'bin/clusterctl' failed
```

**What did you expect to happen:**
Build to succeed

**Anything else you would like to add:**
This error was likely introduced when we started importing kubeadm provider as a depedency to this repository, which had a mistmatched version of Azure autorest library.

**Comment by ncdc** [comment]
@vincepri I have a fix for this locally. It requires copying the `replace` directives in CAPA for k8s.io/api, k8s.io/apimachinery, and k8s.io/client-go to CAPI's go.mod. With those in place, I'm able to `make bin/clusterctl`. I'm not yet sure if there are any negative implications.

**Comment by vincepri** [comment]
Maybe this is more of a CAPA issue than CAPI?

**Comment by ncdc** [comment]
All CAPI & CAPA `make test` pass

**Comment by vincepri** [comment]
Sounds good

**Comment by vincepri** [comment]
/assign @ncdc 

:)

**Comment by ncdc** [comment]
We're using a newer version of client-go in CAPA (because of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1124/files#r329224733)

**Comment by ncdc** [comment]
Alternatively we make installing `clusterctl` a prerequisite to be able to use the make targets that need it?

**Comment by vincepri** [comment]
Yeah, that could work

**Comment by vincepri** [comment]
Actually, we might just want to wait for the next release of controller-runtime, which updates the dependencies https://github.com/kubernetes-sigs/controller-runtime/commit/18b1edf84c456b3fb7d85e67a248642a5aee39c3
