### ISSUE TITLE
Extend FAQ

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1171]
/milestone v0.4.x
/kind documentation
/priority important-soon
/assign
Rather than creating several dozen issues, just going to add them add them as comments

**Comment by randomvariable** [comment]
- [ ] Can't access the created cluster, can't add worker nodes because TCP port 6443 is firewalled
- [ ] Token lifetime
- [ ] Reconciliation limits

**Comment by ncdc** [comment]
Going to reevaluate for v1alpha4 planning.
/milestone Next
