### ISSUE TITLE
Allow specifying control plane load balancer subnets

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/cluster-api-provider-aws#1180]
/kind feature

**Describe the solution you'd like**
In our organization subnet creation is tightly controlled. We are given a set of subnets in our VPCs which we are permitted to use. There are also subnets we are not permitted to use.
I would like to be able to specify existing subnets by ID in the AWSCluster spec, which may not be public and may not be named or tagged by any convention (relating to CAPA anyway), for the control plane load balancer to use (machine subnets can already be specified, is my understanding).

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 0.4.1
- Kubernetes version: (use `kubectl version`): 1.15.3 / 1.15.0
- OS (e.g. from `/etc/os-release`): ubuntu 1604

**Comment by ncdc** [comment]
Can we close this in favor of https://github.com/kubernetes-sigs/cluster-api/issues/1647?

**Comment by joonas** [comment]
@andrewmyhre please take a look at the above

**Comment by andrewmyhre** [comment]
Hi, yes we can close this.
