### ISSUE TITLE
Add v1alpha3 API types

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1202]
We need to create the v1alpha3 API version to allow for breaking API changes in the next minor version.

- Copy types from api/v1alpha2.
- Rewrite imports.
- Set the storage version to v1alpha3 types.
- Make sure the generated CRDs contain both v1alpha2 and 3.

/kind feature
/milestone v0.5.0
/priority important-soon

**Comment by tahsinrahman** [comment]
hi @ncdc can i work on this issue? :)

**Comment by ncdc** [comment]
Sure thing!
