### ISSUE TITLE
RFE: Rationalize / dedupe clusterctl across providers

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#121]
/kind feature

**Describe the solution you'd like**
There should be only 1 clusterctl and many providers that can plugin to a single clusterctl.  

From the consumer perspective this can be a issue if they wish to support multiple providers from a single CLI.

**Comment by moshloop** [comment]
Shouldn't this move to CAPI?

**Comment by ncdc** [comment]
This probably should be closed, right? We have at least one issue in CAPI to cover this.

**Comment by detiber** [comment]
+1 on closing
