### ISSUE TITLE
Automation of Publishing Artifacts 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#122]
**Describe the solution you'd like**
In an ideal world we would like to publish the following artifacts

--> Containers & AMI [Stable/Testing(alpha/beta/rc)/Periodic(sha)]
@dims - Where do we want to host this stuff.

Annotated Tags applied to the promotion of artifacts 
-alpha/beta -> Testing 
- vX.Y.Z -> Stable 

NOTE: This will affect test integration with kubeadm 

/kind feature

**Comment by dims** [comment]
Added it to the infra team meeting agenda tomorrow.

**Comment by timothysc** [comment]
@dims can we sync on this topic

**Comment by chuckha** [comment]
xref https://github.com/kubernetes-sigs/kind/issues/197

**Comment by dims** [comment]
@timothysc ack. just waiting for things to get started ... k8s-infra-team meeting is next wed.

**Comment by chuckha** [comment]
@dims @timothysc did anything come out of your sync?

**Comment by randomvariable** [comment]
As on #580, setting the version number in `.bazelrc` will allow Bazel to be able to push images to a registry and generate `/out` with the binary artifacts to put on Github.

**Comment by chuckha** [comment]
Ok it looks like we have a path forward!

https://github.com/kubernetes/k8s.io/issues/158#issuecomment-462047593

allows us to join a group and have access to a gcr bucket. We can use that for the images and we can use GitHub for the files & binaries.

/lifecycle active

I'm going to work on getting a release automated for v1alpha1

**Comment by chuckha** [comment]
The eventual goal will be to learn enough to upstream it back to cluster-api
