### ISSUE TITLE
Add additional printer columns to the CRDs

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/cluster-api-provider-aws#1227]
/kind feature

**Describe the solution you'd like**
Add additional printer columns to the CRDs

**Anything else you would like to add:**
As a user, I was somewhat surprised when I did `kubectl get awsmachine` and noticed a bunch of instances that I thought I had deleted.

I believe the underlying problem is that these machines will be listed as long as the AWS API returns them in our queries.

I think adding an additional column to the output of `kubectl get awsmachine` that shows the instance state would improve the UX.

**Comment by ncdc** [comment]
+1 to your suggestion.

FYI, `AWSMachine` is a standalone custom resource in Kubernetes. While it does have a 1:1 relationship with an ec2 instance, we'll continue to list an `AWSMachine` as long as it exists in etcd. It's possible, for example, to terminate an ec2 instance, but an `AWSMachine` will be there until someone (user) / something (controller) deletes it.

**Comment by amila-ku** [comment]
i would like to work on this.

**Comment by ncdc** [comment]
Thanks!
/assign @amila-ku 

Please comment `/lifecycle active` when you start working on this.
