### ISSUE TITLE
Unable to generate examples with cert-manager definitions

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api-provider-aws#1233]
/kind bug

**What steps did you take and what happened:**
When I run the following command:
`CAPI_BRANCH=master SSH_KEY_NAME=my-ssh-key CLUSTER_NAME=oct21-cluster make generate-examples`
I get the following output:
```
rm -rf examples/_out/
rm -f examples/provider-components/provider-components-*.yaml
go build -o bin/clusterawsadm ./cmd/clusterawsadm
./examples/generate.sh
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/cluster.yaml
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/controlplane.yaml
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/machinedeployment.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  502k  100  502k    0     0  3327k      0 --:--:-- --:--:-- --:--:-- 3328k
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-cluster-api.yaml from cluster-api - master
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0   2786      0 --:--:-- --:--:-- --:--:--  2774
100 96201  100 96201    0     0   119k      0 --:--:-- --:--:-- --:--:--  119k
Downloaded /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-kubeadm.yaml from cluster-api-bootstrap-provider-kubeadm stable branch - v0.1.2
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/provider-components/provider-components-aws.yaml
Error: accumulating resources: merging resources from 'provider-components-cluster-api.yaml': may not add resource with an already registered id: apiextensions.k8s.io_v1beta1_CustomResourceDefinition|~X|kubeadmconfigs.bootstrap.cluster.x-k8s.io
Generated /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/provider-components.yaml
WARNING: /Users/wfernandes/workspace/cluster-api-provider-aws/examples/_out/provider-components.yaml includes AWS credentials
```

**What did you expect to happen:**
I was expecting the `examples/_out/provider-components.yaml` to include all the cert-manager CRD definitions, etc...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: master (172c72508a4eef74d937845329aa9e0d652dcd12)

/cc @tahsinrahman

**Comment by tahsinrahman** [comment]
as cabpk is already merged to capi, capi now generates cabpk manifests too
this error is coming from this line https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/24430fd9c01755cdfadd921a212370afb44e1de0/examples/generate.sh#L132

as capi master now generates cabpk manifests, we don't need to download from old cabpk repo

**Comment by wfernandes** [comment]
@tahsinrahman @ncdc Do we need to support the variable `CAPI_BRANCH=stable` in `examples.generate.sh`?

So for example, when we run `make generate-examples` it builds the aws provider components by running `kustomize build config/default`. These components include references to cert-manager objects like `Issuer` and `Certificate`.
However, this check below only adds the CAPI cert-manager components if `CAPI_BRANCH=master`.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d7806edd0d9a3f3a3b6bf9a42bb084c2a9a6c396/examples/generate.sh#L110-L112 

Currently, if I kubectl apply examples/_out/provider-components.yaml` I get the following errors:
```
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
```

I don't think it necessary for the master branch of the aws provider to handle the release branches of the capi provider differently. Any thoughts?

Overall for this bug, I'm trying to remove the bootstrap components from being added to `examples/_out/provider-components.yaml` since they are already included in the cluster-api-provider-components.yaml.

**Comment by tahsinrahman** [comment]
@wfernandes this should be fix now, can you check it again?

**Comment by wfernandes** [comment]
@tahsinrahman So it still fails because the `cluster-api-provider-components.yaml` contains objects referring to `Issuer` and `Certificate`. These objects were defined in `cert-manager.yaml` however as per this commit (https://github.com/kubernetes-sigs/cluster-api/commit/e0fb83a839b2755b14fbefbe6f93db9a58c76952) cert-manager components are no longer being shipped with cluster-api.

**Comment by wfernandes** [comment]
@tahsinrahman Let me know if that makes sense. I can provide more detailed steps for reproduction if you'd like.

**Comment by wfernandes** [comment]
Actually I have a "simple" workaround for this. I'll create a PR asap. Thanks.
