### ISSUE TITLE
Document how to use IAM Roles for Service Accounts for management cluster auth.

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1236]
/kind feature

**Describe the solution you'd like**
Now that https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1234 has merged, we should document how to use the IAM Roles for Service Accounts feature for authentication rather than the current documented approach of using KIAM for role assumption.

Additional information here: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by johnharris85** [comment]
It's on my list to dig into IRSA this week, so might as well take this docs issue. When I looked at it briefly over the holidays it looked insanely complex though :man_shrugging:

**Comment by randomvariable** [comment]
Yeah, it did. Can pair for a bit on this if you want?

**Comment by randomvariable** [comment]
Think we can close this one out, as it'll be superseded by #1753 
/close
