### ISSUE TITLE
Set user-agent for calls to AWS

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1242]
/kind feature

**Describe the solution you'd like**
For debugging, I go through CloudTrail logs in Athena, e.g.

``` sql
SELECT eventtime,
         eventsource,
         eventname,
         useragent
FROM "cloudtrail"."cloudtrail"
WHERE awsregion='us-east-1' limit 1000
```

eventtime | eventsource | eventname | useragent
-- | -- | -- | --
2019-10-22T13:42:17Z | ec2.amazonaws.com | DescribeInstances | kubernetes/v1.15.3 aws-sdk-go/1.16.26 (go1.12.9; linux; amd64)
2019-10-22T12:34:16Z | elasticloadbalancing.amazonaws.com | RegisterInstancesWithLoadBalancer | aws-sdk-go/1.20.19 (go1.12.9; linux; amd64)

Core Kubenetes components identify themselves as
`kubernetes/v1.15.3 aws-sdk-go/1.16.26 (go1.12.9; linux; amd64)`

but CAPA uses the default 
`aws-sdk-go/1.20.19 (go1.12.9; linux; amd64)`

A sample UA could be:

`aws.cluster.x-k8s.io/0.5.0 aws-sdk-go/1.20.19 (go1.12.9; linux; amd64)`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.4.3
- Kubernetes version: (use `kubectl version`):  N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by aaroniscode** [comment]
going to give this one a try
/assign @aaroniscode 
/lifecycle active

**Comment by randomvariable** [comment]
@aaroniscode I was experimenting with adding logging to the AWS SDK handlers, which is also where you'd add the user-agent string, so have some bits that might be useful in https://github.com/randomvariable/cluster-api-provider-aws/commit/08afc7105f622c67c4d3cd6e941d05ba24efd6e2

**Comment by aaroniscode** [comment]
thanks @randomvariable 

I got it working over the weekend, but didn't like that I had to add a function to the `cmd/versioninfo` package as the version stuff didn't really belong there and was looking at options.

If your code, you have refactored that into a separate version package. Should I wait for you to merge that code and I'll just use that version package?

**Comment by randomvariable** [comment]
@aaroniscode Nah, just steal it. I can work on something else.

**Comment by ncdc** [comment]
@aaroniscode still working on this?

**Comment by aaroniscode** [comment]
@ncdc  I was 90% done on the PR and got pulled into other items.  My goal is to get done this week or weekend. If I can't find the time, I'll post what I did.

If you are on a time crunch to get this done, just let me know and I'll let you know whether I can create time to make it happen.

**Comment by ncdc** [comment]
No rush - just checking in!
