### ISSUE TITLE
Add README to ./cloud/aws

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#125]
/kind docs

What is an actuator? what is a controller? How much of this is boiler plate? The meat of the code is here, some explanations would be useful.

**Comment by phyber** [comment]
Some or all of this may end up being covered by the [gitbook PR](https://github.com/kubernetes-sigs/cluster-api/pull/566) in cluster-api. The documentation I had worked on was also subsumed and improved in that PR. Once that is merged, we should see what's left to document and decide where it should live.

**Comment by randomvariable** [comment]
I think then we want to document AWS specific stuff. @vincepri is doing a refactor so makes sense to defer until we get to a steady state.

**Comment by timothysc** [comment]
TODO - audit, eval, and link out to other docs.

**Comment by ashish-amarnath** [comment]
This does a pretty good job of explaining this https://kubernetes-sigs.github.io/cluster-api/.
