### ISSUE TITLE
Events are being split between Machine and AWSMachine

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1274]
/kind bug
/priority important-soon

Events coming from AWSMachine controller are being written inconsistently to either Machine or AWSMachine objects. We should make sure to write only to one of the objects, possibly AWSMachine and provide a consistent user experience

**Comment by randomvariable** [comment]
Got any examples?
Grepping for `recorder.event` showed everything going to AWSMachine

**Comment by randomvariable** [comment]
Update: machine controller uses AWSMachine, stuff in the services code tends to use Machine.
