### ISSUE TITLE
Throttling errors on DescribeLoadBalancers

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1275]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Reviewing CloudTrail logs for an account with around 20 provisioned clusters, frequent ThrottlingException events are found in for the `DescribeLoadbalancers`, which are then surrounded by `AccessPointNotFoundException`

**What did you expect to happen:**
Not throttling at this level (20 clusters).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.4.x
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
@randomvariable what was the concurrency in use where this was seen?

**Comment by vivgoyal** [comment]
Default, i.e. 1

**Comment by rudoi** [comment]
Worth mentioning that EC2 actually batches Describe calls together: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html

So while the errors may be most prominent for DescribeLoadBalancer, I believe all describe requests count. Also, these limits are scoped per account, not by role/user/etc. :\

**Comment by randomvariable** [comment]
We will probably need to sort out metrics in #78 before resolving this entirely.

**Comment by randomvariable** [comment]
> So while the errors may be most prominent for DescribeLoadBalancer, I believe all describe requests count. Also, these limits are scoped per account, not by role/user/etc. 

Noted. AWS TAM had told us the same. DescribeLoadBalancer is in the elasticloadbalancing API not EC2, which is why I think it's of special interest and seems to be rate limited to a greater extant than EC2.

**Comment by vivgoyal** [comment]
Another case I am currently trying is simultaneous reconciliations. I tried 50, then 30, then 25. In all 3 cases, I hit Throttling errors on DescribeLoadBalancers. Still trying to figure out how many simultaneous reconciles can be supported without throttling.

**Comment by rudoi** [comment]
Ah, you're totally right. elasticloadbalancing not included.

**Comment by ncdc** [comment]
Trying to de-scope v0.5.
/milestone Next

**Comment by stefanSpectro** [comment]
Can this be reopened??  This was never resolved was it?
