### ISSUE TITLE
Our exponential backoff isn't running as long as we need it to

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1283]
/kind bug

**What steps did you take and what happened:**
1. Create a Cluster + AWSCluster
1. Occasional timeouts performing AWS operations, such as tagging a route table using retries
1. Timeout occurred after ~ 1 minute

**What did you expect to happen:**
1. Timeout should have been longer (9.5 minutes based on what's coded) (although it really should be 5 minutes)

**Anything else you would like to add:**
`wait.ExponentialBackoff` stops waiting with a timeout error as soon as the supplied backoff hits its `Cap`, which we hit on the 6th step.

**Environment:**

- Cluster-api-provider-aws version: v0.4.3

/priority important-soon

Need to backport the fix to v0.4.x after it lands in master

**Comment by randomvariable** [comment]
Related to #539
