### ISSUE TITLE
`const`ify providerconfig/types

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#129]
/kind feature

A lot of the fields in cloud/aws/providerconfig are strings right now. Using custom types with `const` values would make it more obvious what expected values and default values are.

**Comment by randomvariable** [comment]
Some, but not all of this was done in various PRs in the lead up to TGIK.

**Comment by chuckha** [comment]
we lint for this now. i believe this was fixed and not closed at some point in the past.
