### ISSUE TITLE
Expose ability to filter the image lookup based on base OS

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1291]
/kind feature

**Describe the solution you'd like**
Currently we hardcode the naming convention of the Ubuntu images built by the image-builder for our image lookups, instead we should expose selection of the underlying base OS to the users to allow them to consume any of the images that we publish (Ubuntu, CentOS, Amazon Linux 2).

We should add a field to the AWSMachineSpec for `ImageLookupBaseOS` and provide defaulting to the existing images. I don't think we should provide rigid validation of this field, since it is something that could potentially be customized by users who fork image-builder.

We should probably also expose this as a field on AWSClusterSpec to provide cluster-wide defaulting for the base OS to use in filtering images.

**Comment by alexbrand** [comment]
I'd like to work on this one.
/assign

**Comment by alexbrand** [comment]
@detiber How do we want to handle base OS version?

**Comment by detiber** [comment]
@alexbrand I think it'll have to be part of the "Base OS" name.

The other alternative would be to have a separate field, but that would require dynamic defaulting, which I'm not sure we want to take on.

My initial reaction is that we can take a simplistic approach and document the naming used by the image-builder for the first iteration:
- ubuntu-18.04
- centos-7
- amazon-2

**Comment by alexbrand** [comment]
Got it. At the moment, base OS name and base OS version are treated separately throughout the codebase. For example: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/ami.go#L53

I'll have to see how big of a refactor would be required to treat base OS name and version as a single unit. I am open to ideas if you have thought about this already, or if I am going down the wrong path.
