### ISSUE TITLE
Better name for `/cloud/aws/services`

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#130]
/kind feature

This name is very confusing and overloaded. A better name is needed.

Bikeshed away!

**Comment by liztio** [comment]
Also discuss what `/services` should be: is it a wrapper? Is it for reconciliation? Right now it does both, but these should be separated out.

**Comment by chuckha** [comment]
It originally was a wrapper

It has become more than that and I almost want another layer between the two. The ec2 wrapper and then the infra that defines a cluster which uses the ec2 wrapper.

* network
* control plane
* nodes
* security/iam

I could see this being a good point for the variants to plug into. The actuator uses the infra interface and then the infra implementation uses the ec2 wrapper or the eks wrapper or the ...

**Comment by chuckha** [comment]
/close

this is no longer relevant, please reopen if a name change is needed
