### ISSUE TITLE
volumes dynamically provisioned in different zone from the nodes zone blocked statefulset pods to come up

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api-provider-aws#1331]
/kind bug

**What steps did you take and what happened:**
I have done the following after creating the cluster
1. Created the management cluster
2. Created Cluster API infrastructure
3. Created CABPK infrastructure
4. Created AWS user stack
5. Set AWS Credentials as Environment variables
6. Created CAPA infrastructure
7. Created Cluster
8. Created subnets(private&public with Auto assign public IPv4 enabled) for AZ us-east-2b
9. Updated the route tables subnet associations to associate newly created subnets
10. Added us-east-2b to Avalability Zones of LoadBalancer
11. Enabled Cross-Zone Load Balancing for the LoadBalancer
12. Deployed control plane 0 without specifying AZ
13. Deployed control plane 1 by mentioning AZ us-east-2b
14. Deployed MachineDeployment in us-east-2b with replica 1
15. Scaled up the MachineDeployment to replicas 3 and verified all the nodes are created in us-east-2b
16. Deploy statefulset on CAPA cluster with replicas3

For pod1 statefulset created in same AZ where in for pod2, volume created in us-east-2a which failed to Bound PVC to pod due to **volume node affinity conflict**

**What did you expect to happen:**
Volumes should get provisioned dynamically and should be attached the pods which should be up and running eventually

**Anything else you would like to add:**
![volumes-details](https://user-images.githubusercontent.com/45227921/68294091-5007f200-00b5-11ea-8063-01a9fba42159.png)
[pending-pod-describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/3814127/pending-pod-describe.txt)
[pv-describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/3814128/pv-describe.txt)
[pvc-describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/3814129/pvc-describe.txt)

**Environment:**

- Cluster-api-provider-aws version: v0.4.4
- Kubernetes version: (use `kubectl version`): Client v1.13.3, Server v1.15.3
- OS (e.g. from `/etc/os-release`): darwin-x86_64

**Comment by ncdc** [comment]
@randomvariable to take a look
/assign @randomvariable
