### ISSUE TITLE
Categorize events to distinguish between create/delete events. 

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api-provider-aws#1344]
/kind feature

**Describe the solution you'd like**
Currently events are generated on Machines/Clusters but not enough metadata is available as to what type of event it is. We would like to categorize if events are related to creating or deleting the resources. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by joonas** [comment]
Also being discussed in CAPI: https://github.com/kubernetes-sigs/cluster-api/issues/1743

**Comment by ncdc** [comment]
xref https://github.com/kubernetes-sigs/cluster-api/issues/1743#issuecomment-568040912
xref https://github.com/kubernetes-sigs/cluster-api/issues/1743#issuecomment-573149601

/milestone Next

**Comment by vincepri** [comment]
Closing in favor of condition work in next cycle 

/close
