### ISSUE TITLE
Events not generated when Create/Release/Disassociate elastic IP fails

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api-provider-aws#1346]
/kind bug

**What steps did you take and what happened:**
Tried the create a new cluster on an AWS account where elastic IP limit is already reached 

**What did you expect to happen:**
An event generated that the Elastic IP could not be created. 

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by amy** [comment]
@harishspqr To replicate the issue, can you go into more detail about how you're hitting the elastic IP limit in relation to cluster api? Thank you.

**Comment by harishspqr** [comment]
Its easy to replicate by creating many elastic IPs manually on an AWS account with elastic IP limit set to a low value like 5 as is the case with mine. If your account limit is high you can adjust it by going to the account settings.
