### ISSUE TITLE
Audit CAPA code to generate events for all AWS calls (write operations) if missing

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api-provider-aws#1347]
/kind bug

**What steps did you take and what happened:**
It was noticed that the CAPA does not generate events for some of the AWS calls that fails. 
It would be good to audit the CAPA code to generate events if missing. 

**What did you expect to happen:**
Events are generated any time an AWS call fails (if it matters).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
This is still a nice to have, but it won't be a release blocker. If we don't do this for v1alpha3, the plan is to close it and switch to status conditions.

**Comment by vincepri** [comment]
Closing in favor of condition work in next cycle 

/close
