### ISSUE TITLE
[0.4] test/e2e/go.mod has the wrong module name

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1359]
/kind bug

**What steps did you take and what happened:**
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/test/e2e/go.mod#L1 has the module name as `bhargavmad/cluster-api-provider-aws/test/e2e`.

**What did you expect to happen:**
The name should be `sigs.k8s.io/cluster-api-provider-aws/test/e2e`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: `release-0.4` branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
/assign @detiber 
/lifecycle active
/help cancel
/good-first-issue cancel

I assume these tags are appropriate?

**Comment by randomvariable** [comment]
/close
fixed in #1360
