### ISSUE TITLE
Deleting the control-plane AWS instance of a cluster in provisioned state repeatedly creates many more controlplanes

### ISSUE THREAD

**Issue by harishspqr** [kubernetes-sigs/cluster-api-provider-aws#1368]
/kind bug

**What steps did you take and what happened:**
Create a cluster 
Delete the controlplane instance in AWS. 

**What did you expect to happen:**
Cluster API provider AWS creates a new instance for controlplane and updates the API endpoint. 
Instead the API end point is apparently not updated and CAPA repeatedly creates new instances for controlplane until AWS instance limit is hit. 

**Anything else you would like to add:**
Once the controlplane instance is deleted, its not possible to delete any machinedeployments on that cluster. 
From CAPI logs:

"controller-runtime/controller "msg"="Reconciler error" "error"="unable to get node \"ip-10-0-0-48.us-east-2.compute.internal\": Get https://tk-test-2-apiserver-559576175.us-east-2.elb.amazonaws.com:6443/api/v1/nodes/ip-10-0-0-48.us-east-2.compute.internal: dial tcp: lookup tk-test-2-apiserver-559576175.us-east-2.elb.amazonaws.com on 10.96.0.10:53: no such host"  "controller"="machine""

**Environment:**

- Cluster-api-provider-aws version: cluster-api-controller:v0.2.5, cluster-api-aws-controller:v0.4.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@harishspqr I'm pretty sure this is the same issue that we just fixed in v0.4.5. Could you please test with the newer version and report back if that fixes the problem? Thanks!

**Comment by ncdc** [comment]
Also: do the CAPA pod logs look similar to what's in #1351?

**Comment by ncdc** [comment]
We're still looking into this. However, I did want to clarify something:

> What did you expect to happen:
> Cluster API provider AWS creates a new instance for controlplane and updates the API endpoint.
Instead the API end point is apparently not updated

If something or someone outside of CAPA deletes an ec2 instance for an AWSMachine, CAPA is supposed to set AWSMachine.Status.ErrorMessage/Reason and that Machine + AWSMachine is considered in a terminal error state.

CAPA must not create a new ec2 instance to replace a manually-delete one. It also must not update the APIEndpoints.

**Comment by randomvariable** [comment]
> If something or someone outside of CAPA deletes an ec2 instance for an AWSMachine, CAPA is supposed to set AWSMachine.Status.ErrorMessage/Reason and that Machine + AWSMachine is considered in a terminal error state.

This should be fixed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1369

**Comment by harishspqr** [comment]
Sure. I ll verify it on v0.4.5 and comment here.

**Comment by ncdc** [comment]
1369 is not in a release yet. So the bug might still be in v0.4.5. But please try to reproduce and gather full logs + `kubectl get cluster-api -o yaml` + gathering events would be useful too. Thanks!

**Comment by ncdc** [comment]
@harishspqr could you please retest with v0.4.6?

**Comment by harishspqr** [comment]
Sure.

**Comment by ncdc** [comment]
@harishspqr any updates here?

**Comment by harishspqr** [comment]
@ncdc @randomvariable 
I tried reproducing this on v0.4.6. This time I didn't hit the original issue reported here but instead found that only the bastian node was created and no controlplane nor workers were created after they are terminated. Should we close this and file a different issue ?

**Comment by randomvariable** [comment]
@harishspqr Yes, if you can get the logs for the new weirdness, that'd be appreciated.
