### ISSUE TITLE
Cluster deletion fails when VpcID is an empty string

### ISSUE THREAD

**Issue by williamsandrew** [kubernetes-sigs/cluster-api-provider-aws#1375]
/kind bug

This seems similar to the v1alpha1 issue here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/943.

If a cluster cannot be created due to hitting a VPC limit, the VPC ID field will remain blank and will then block deletion of the cluster. The workaround appears to be dropping the finalizer. 

```
E1125 13:52:24.440431       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster 10fac61f2591ca284ba10e0e4375c89534ae7a60/e2e-lcm-20191125-ilap: failed to create new vpc: failed to create vpc: VpcLimitExceeded: The maximum number of VPCs has been reached.\n\tstatus code: 400, request id: ff48270e-fa1d-4324-9e71-3c416d27ea31"  "controller"="awscluster" "request"={"Namespace":"10fac61f2591ca284ba10e0e4375c89534ae7a60","Name":"e2e-lcm-20191125-ilap"}
E1125 13:56:19.071775       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster 10fac61f2591ca284ba10e0e4375c89534ae7a60/e2e-lcm-20191125-ilap: failed to describe cluster-owned security groups in vpc \"\": InvalidParameterValue: vpc-id\n\tstatus code: 400, request id: 1c0a5745-bcf8-4fba-a35f-9e9398c12bf2"  "controller"="awscluster" "request"={"Namespace":"10fac61f2591ca284ba10e0e4375c89534ae7a60","Name":"e2e-lcm-20191125-ilap"}
```

Discussion here: https://kubernetes.slack.com/archives/CD6U2V71N/p1574704015458800

**Environment:**

- Cluster-api-provider-aws version: 0.4.4
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`):

**Comment by aaroniscode** [comment]
@randomvariable happy to work on this ... not sure if you started work already.

FYI -- I was just testing some event code and ended up testing this same issue. The VPC couldn't be created because of VPC limit, but I was able to delete the `Cluster` object. This was on `master`.

**Comment by detiber** [comment]
@aaroniscode @randomvariable is on vacation, feel free to pick this up if you plan on working on it before the holidays are over :)

**Comment by aaroniscode** [comment]
/assign
/lifecycle active

Also I was able to reproduce the behavior on `master`. Not quite sure how I was able to delete before as I mentioned above. It's possible I deleted quickly the first time and was able to start the delete before the controller had hit a certain point.
