### ISSUE TITLE
AWSCluster AdditionalTags aren't reconciled on the API Server ELB

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1376]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I added some tags to the cluster via the AWSCluster's AdditionalTags field. This correctly added tags to security groups and EC2 instances, but not the API Server ELB.

**What did you expect to happen:**
API Server ELB to be tagged.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think we just may have to add some tag reconciliation for the load balancer. 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@rudoi what CAPA version, please?

**Comment by rudoi** [comment]
@ncdc oh, sorry, `0.4.6`.

**Comment by rudoi** [comment]
I don't think the reconciliation loop actually checks the tags: 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2e77a1b1cecdd8c96a0b860c8658c1bd498a981f/pkg/cloud/services/elb/loadbalancer.go#L42-L89

/assign
/lifecycle active
