### ISSUE TITLE
Images should be discoverable

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#138]
/kind bug

**What steps did you take and what happened:**
There is no way to filter for images built with the packer script from this project. I looked for a script to do this in heptiolabs/wardroom that @liztio mentioned but could not find it.

**What did you expect to happen:**
I expect our images to be tagged with something easy to filter on.

**Anything else you would like to add:**
There are a bunch of hacks to work around this issue. Namely hardcoding AMIs.

**Comment by randomvariable** [comment]
Try to avoid using tags to match on images because:

Tags don't get copied when the AMI is copied, for which an example use case is that a user wants encrypted root volumes, which means they must own the AMI.

Below is a slightly modified copy of a proposal we had earlier:

#### AMI Name:

```
Cluster API <Channel> <APIVersion> <Platform> <Distribution> <Distribution Version> <Processor Architecture> <Hypervisor Type> <Disk Type> <Additional Upstream Distribution Version Information>
```

#### Tags:

- Cluster API's Version
- platform codename (on Linux: same as LSB Distributor ID)
- upstream version (eg 6.5)
- build timestamp


##### Semver Format:

```
<Major Version>.<Minor Version>.<Patch release>+<ISO8601 UTC YYYYMMDDThhmmZss timestamp of build time>
```

#### Examples:

`Cluster API Stable 13.0.0+20180902T134701Z Linux CentOS 7.4 x86_64 HVM EBS 1602`

`Cluster API Alpha 14.2.1+20180902T134715Z Win64 Windows_Nano_Server 2016 x86_64 HVM EBS`

#### Constraints

AWS is case-sensitive, so case must be preserved. Having both CentOS and centos should not be allowed.

### Rationale:

We encode as much as possible into the AMI name because tags may be lost, and creation dates will definitely be lost as they are copied into customer accounts.

This has some side benefits:
In the EC2 console, someone can easily see the age of the AMI.

**Comment by randomvariable** [comment]
We should rename the issue description so it's clear that it's about image discovery, not just a hard requirement to tag.

**Comment by chuckha** [comment]
@randomvariable I like your proposal. I think I have a few modifications and would like to get your feedback on it:

* Channel -- we don't really have channels (this is like, nightly, stable, beta, I'm assuming) so we can nix this field. It looks like you've done so in your example
* APIVersion -- This should be the kubernetes version, not the cluster-api-provider-aws version since the AMI is only concerned with k8s version.
* Platform -- This will always be linux for right now. If we decide to support windows server in the future we can add it when necessary.
* Distribution -- We only support Amazon Linux, Ubuntu and CentOS for now, but it should be there to filter on.
* Distribution Version -- Yep, we want to filter on this.
* Processor Architecture -- I don't see us needing to filter on processor arch right now.
* Hypervisor Type -- Let's add this and disk type when we support more than hvm-ssd.
* Disk Type -- see hypervisor note
* Additional upstream distribution version information

I propose we have a naming scheme like this `Cluster API <Kubernetes Version>+<timestamp of build time> <Distribution> <Distro version>`

If @detiber also has thoughts that would be great. I don't have a ton of real life experience with what people might want to filter on. I'm erring on the side of YAGNI and am willing to deal with rebuilding images with a new naming convention later *if* we ever need to.

**Comment by detiber** [comment]
> @randomvariable I like your proposal. I think I have a few modifications and would like to get your feedback on it:
> 
> * Channel -- we don't really have channels (this is like, nightly, stable, beta, I'm assuming) so we can nix this field. It looks like you've done so in your example
> * APIVersion -- This should be the kubernetes version, not the cluster-api-provider-aws version since the AMI is only concerned with k8s version.
> * Platform -- This will always be linux for right now. If we decide to support windows server in the future we can add it when necessary.

Platform is already a queryable filter

> * Distribution -- We only support Amazon Linux, Ubuntu and CentOS for now, but it should be there to filter on.
> * Distribution Version -- Yep, we want to filter on this.
> * Processor Architecture -- I don't see us needing to filter on processor arch right now.

Architecture is already a queryable filter

> * Hypervisor Type -- Let's add this and disk type when we support more than hvm-ssd.

Hypervisor is already a queryable filter

> * Disk Type -- see hypervisor note

root-device-type is a queryable filter

> * Additional upstream distribution version information
> 
> I propose we have a naming scheme like this `Cluster API <Kubernetes Version>+<timestamp of build time> <Distribution> <Distro version>`

I'm not sure we have to encode the timestamp of the build, since we can sort the responses based on creation time.

> 
> If @detiber also has thoughts that would be great. I don't have a ton of real life experience with what people might want to filter on. I'm erring on the side of YAGNI and am willing to deal with rebuilding images with a new naming convention later _if_ we ever need to.

**Comment by chuckha** [comment]
I'm in communication with the CNCF and k8s-infra in order to acquire credentials necessary to get these images to a shared place. We can then also filter on OWNER and that will be great.
