### ISSUE TITLE
Don't store sensitive information (certificates) in ec2 user data

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1387]
/kind feature

**Describe the solution you'd like**
We need to stop storing sensitive information (certificates, keys, etc) in ec2 user data, as users with `ec2:DescribeInstances` permission or users running pods that can access the ec2 metadata service have access to this sensitive information.

Previous idea:
Clear out the user data post-boot by calling ModifyInstanceAttributes, but that only works for stopped VMs.

**Comment by vincepri** [comment]
Maybe the same annotation can also be used to disable this behavior? In the past looking at the user data has been useful for debugging purposes.

**Comment by detiber** [comment]
@vincepri the same data should still be available on the Machine resource and/or referenced secret, so I don't think we necessarily lose much for debugging here.

**Comment by vincepri** [comment]
Fair enough :)

**Comment by aaroniscode** [comment]
@ncdc While trying to implement this got an error back from the AWS API. It appears that userData cannot be modified on a running instance.

Was able to replicate the error using the AWS CLI
```
aws ec2 modify-instance-attribute --instance-id "i-0da3bb5d62678bfd2" --user-data "Value="

An error occurred (IncorrectInstanceState) when calling the ModifyInstanceAttribute operation: The instance 'i-0da3bb5d62678bfd2' is not in the 'stopped' state.
```

Looked in the docs, and while it doesn't explicitly say modifying can't be done on a running instance, it instructs you to stop the instance to modify userData

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-view-change

Let me know how you want to proceed with this issue.

**Comment by ncdc** [comment]
@aaroniscode thanks for looking into this, and it's unfortunate we can't use this easy fix.

I'm going to retitle/rewrite this to be more generic and hand it over to @randomvariable for the time being.
