### ISSUE TITLE
Clusterawsadm: Enable adding of additional policies to control plane & node roles

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/cluster-api-provider-aws#1390]
/kind feature

**Describe the solution you'd like**
A situation I've come across a few times is having a common policy / set of policies that I want to add to my control plane and / or node instances. Right now that's an activity after the fact to attach those policies to the relevant roles (or the alternative of generating the capa policies and manually creating my roles ahead of time). 

Wondered what folks thought about adding something like `--additional-cp-policies` and `--additional-worker-policies` flags to `clusterawsadm alpha bootstrap create-stack` so those policies could be attached at create time through the CloudFormation stack?

**Anything else you would like to add:**
I'm happy to work on this if folks think it's a good idea.

**Environment:**

- Cluster-api-provider-aws version: 0.4.7
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by detiber** [comment]
I think this seems like a reasonable request.

How long do you think it would take for you to knock out an implementation @johnharris85 (mainly for figuring out if it should be in the v0.5.0 milestone or next)?
