### ISSUE TITLE
Forward port of 1394 - EC2 root volume should inherit additionalTags from instance

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1392]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Additional tags should pass through to EC2 instance root volumes. This makes analyzing resources in a shared account much simpler. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I already have this working in a branch, but wanted to allow for any discussion.

**Comment by ncdc** [comment]
SGTM. @randomvariable?

**Comment by randomvariable** [comment]
This is fine, since the affected resource is static and chargeable.

**Comment by randomvariable** [comment]
Is there a case for v1alpha3 to have a rootDevice map, rather than separate fields for size, tags, etc...

**Comment by rudoi** [comment]
I think there is. I almost implemented it that way but realized that would be breaking against v1a2. Instead of doing a standard forward-port, I'd be happy to implement it as a struct for master.

**Comment by detiber** [comment]
@rudoi any objections if I bump this to the v0.5.x milestone rather than v0.4.x?

**Comment by detiber** [comment]
Moving to v0.5.x to track forward porting the feature support from #1394 
/milestone v0.5.x

**Comment by ncdc** [comment]
@rudoi to double check against the main branch to see if this has been implemented (in a slightly different way than v1alpha2).

**Comment by rudoi** [comment]
Confirmed that this hasn't been done for v1alpha3+ and should probably stay open.

**Comment by randomvariable** [comment]
Assigning myself in lieu of @ankitasw
