### ISSUE TITLE
Ability to configure node disks

### ISSUE THREAD

**Issue by AlainRoy** [kubernetes-sigs/cluster-api-provider-aws#1403]
/kind feature

**User Story**
When creating nodes in a cluster, it would be useful to be able to request disk characteristics to control performance, space, and cost. Specifically, it would be good to be able to configure:

* Root disk size (I think this is already possible)
* Disk type (gp2, etc)
* IOPS

**Comment by johnharris85** [comment]
Add encryption to this list as well?

**Comment by ncdc** [comment]
@rudoi you still planning on working on this?

**Comment by johnharris85** [comment]
I have some availability next week, so if you don't have cycles @rudoi I might be able to pick this up.

**Comment by rudoi** [comment]
@johnharris85 please feel free! I apologize I missed these notifications. I'm happy to still work on this but likely won't get to it within the next week.
