### ISSUE TITLE
Add unit test for MachineScope.GetBootstrapData()

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1410]
To ensure we don't regress on base64 encoding

/help
/good-first-issue
/milestone v0.5.0
/priority important-longterm

**Comment by vincepri** [comment]
We should also have a unit test in one of the create instance mock functions

**Comment by neeleshkorade** [comment]
> We should also have a unit test in one of the create instance mock functions

@vincepri could you elaborate this bit more? Particularly- could you point me to a `create instance mock function`?

**Comment by vincepri** [comment]
I was talking about this function https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/instances_test.go#L262. You can either add a new test or modify an existing one to test the behavior we expect.

**Comment by ncdc** [comment]
@neeleshkorade are you still interested in working on this?

**Comment by neeleshkorade** [comment]
Yes, I am. I am traveling so couldn’t get to it.  Would be great if you
could allow me couple days more.

**Comment by ncdc** [comment]
Sure thing - just checking in. Thanks!

**Comment by randomvariable** [comment]
@neeleshkorade maybe worth holding on slightly. i've had to refactor those calls a bit to clean up the use of Secrets Manager in #1490

**Comment by neeleshkorade** [comment]
Thanks @randomvariable will wait for #1490 to go in
