### ISSUE TITLE
Our awserrors.IsNotFound() doesn't work for at least ec2 instances

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1411]
/kind bug

**What steps did you take and what happened:**
If you terminate an ec2 instance out of band (manually i.e. CAPA didn't do it) and wait long enough such that the instance is no longer returned by a DescribeInstances call, this logic does not work correctly:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e19e0e50ada52312f7c1b5decc761e0700f17d5b/pkg/cloud/services/ec2/instances.go#L89-L92

The error returned by ec2 looks like this:

```
InvalidInstanceID.NotFound: The instance ID 'i-xxxxxxxxxxxxx' does not exist
    status code: 400, request id: ...
```

Note the status code is 400. Our `awserrors.IsNotFound()` has this:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e19e0e50ada52312f7c1b5decc761e0700f17d5b/pkg/cloud/awserrors/errors.go#L105-L111

We don't match on `http.StatusNotFound` (400 != 404). And `IsInvalidNotFoundError` does this:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e19e0e50ada52312f7c1b5decc761e0700f17d5b/pkg/cloud/awserrors/errors.go#L124-L133

We probably need to also check for `InvalidInstanceID.NotFound`

**What did you expect to happen:**
The `InstanceIfExists` call should return `nil, nil` in this scenario.

**Environment:**

- Cluster-api-provider-aws version: v0.4.7 & master

**Comment by ncdc** [comment]
Or maybe we need to do a regex match on `^Invalid[^.]+\.NotFound$`?

**Comment by vincepri** [comment]
I'd just add another case for now, unless you prefer the regex thing

**Comment by cpanato** [comment]
Can i pick this one and try?

**Comment by ncdc** [comment]
Please do!

**Comment by cpanato** [comment]
@ncdc can i reach you in the K8s slack to ask a few questions?

**Comment by ncdc** [comment]
@cpanato sure thing! #cluster-api-aws channel

**Comment by cpanato** [comment]
PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1480
