### ISSUE TITLE
Machine phase stuck in "provisioned" after NAT gateway reconcilation

### ISSUE THREAD

**Issue by bhargavmad** [kubernetes-sigs/cluster-api-provider-aws#1413]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Created a workload cluster with a single ControlPlane and a MachineDeployment with 2 replicas
2. Manually deleted the NAT Gateway of the cluster
3. Tried to create a new MachineDeployment within the same cluster

**What happened**:
1. A new NAT gateway gets created
2. New EC2 instances created and running
3. The machines are stuck in "provisioned" phase.
4. Hence not able to see the new nodes as part of the workload cluster

**What did you expect to happen:**
1. New NAT gateway gets created
2. All the machines of the new MachineDeployment in "running" phase

**Environment:**

- Cluster-api-provider-aws version: 0.4.7
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.10

**Comment by vincepri** [comment]
/priority awaiting-more-evidence

If you remove the NAT gateway, the instances are not going to be able to communicate with the load balancer, which uses an external public IP.

**Comment by bhargavmad** [comment]
> If you remove the NAT gateway, the instances are not going to be able to communicate with the load balancer, which uses an external public IP.

Okay. The NAT gateway is being created once again when i try to create a new MachineDeployment. This means that the new machines should be using the new NAT and everything should run as if nothing happened. Right?

**Comment by vincepri** [comment]
I need to double check, but I don't think CAPA is smart enough to detect changes to the NAT gateway currently. It'll definitely create it, but the routing tables aren't getting updated. Which means that the outgoing traffic will be lost.

Can you check the routing tables for the subnet in question and see if the route is still pointing to the old gateway?

**Comment by bhargavmad** [comment]
@vincepri Yes. The route table is still pointing to the old NAT gateway and route status says `blackhole` 
I updated the route table manually and the machine status eventually changed to `running`

**Comment by vincepri** [comment]
I'll take a look later today
