### ISSUE TITLE
Cross-Zone Load Balancing is disabled for Load Balancer when cluster crated with Multi AZ configuration

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api-provider-aws#1416]
It is observed that when Created the cluster with Multi AZ configuration, the load balancer which was provisioned have Cross-Zone Load Balancing Disabled.

For better Load Balancing and HA, it would be good to enable Cross-Zone Load Balancing

**Comment by vincepri** [comment]
We can probably add a flag to give the option to enable this, following https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-disable-crosszone-lb.html?icmpid=docs_elb_console.

/kind feature
/priority important-longterm
/milestone v0.4.0
