### ISSUE TITLE
Route Tables created for every subnet configured in cluster networkspec

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api-provider-aws#1417]
/kind feature

On deploying a cluster with multi AZ support by adding subnet configuration, the VPC have route tables created for every subnet configuration rather than associating Multiple subnets to the route tables.

`apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: capi-qs1
  namespace: test-kr
spec:
  region: us-east-2
  sshKeyName: default
  networkSpec:
    subnets:
      - availabilityZone: "us-east-2a"
        cidrBlock: "10.0.0.0/24"
      - availabilityZone: "us-east-2a"
        cidrBlock: "10.0.1.0/24"
        isPublic: true
      - availabilityZone: "us-east-2b"
        cidrBlock: "10.0.2.0/24"
      - availabilityZone: "us-east-2b"
        cidrBlock: "10.0.3.0/24"
        isPublic: true
      - availabilityZone: "us-east-2c"
        cidrBlock: "10.0.4.0/24"
      - availabilityZone: "us-east-2c"
        cidrBlock: "10.0.5.0/24"
        isPublic: true
`
For the above configuration 2 route tables where public subnets & private subnets be associated with each of them.

As of now 6 route tables are getting created.

- Cluster-api-provider-aws version: v0.4.6
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): darwin x86_64

**Comment by vincepri** [comment]
Is there an actual benefit of having 1 single route table for all subnets instead one each? The current design follows AWS' best practices when creating a VPC. For any other configuration users should bring their own pre-created externally managed network.

/priority awaiting-more-evidence
