### ISSUE TITLE
CI presubmits should make sure that test/e2e/... compiles

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1429]
#1426 passed all presubmits but broke compilation of test/e2e. We should verify that all the test code can build and compile in our presubmits (but leave running the tests to other jobs).

**Comment by evalsocket** [comment]
@detiber  Can this be assigned to me?

**Comment by ncdc** [comment]
@evalsocket have you started working on this?

**Comment by varunpurohit76** [comment]
@ncdc  i see that the previous person assigned to this has unassigned them from this issues.
can i take this up? although, if assigned this would be my first issue. So i would need some help and context.

**Comment by randomvariable** [comment]
@varunpurohit76, sure you can pick it up.

If you join the Slack, we can chat in https://kubernetes.slack.com/archives/CD6U2V71N otherwise, just ping in this thread when you start the issue.


/assign @varunpurohit76

**Comment by varunpurohit76** [comment]
hi @randomvariable can you give me a little context here. does presubmits refet to [TestGrid-sig-aws-cloud-provider-aws](https://testgrid.k8s.io/sig-aws-cloud-provider-aws)?
if that's the case i see `pull-cluster-api-provider-aws-e2e` in [cluster-api-provider-aws-presubmits.yam](cluster-api-provider-aws-presubmits.yaml) running `./scripts/ci-e2e.sh` which should run e2e tests.

**Comment by ncdc** [comment]
@varunpurohit76 the tests for this repo are in this dashboard: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws. I would say it might make sense to have this covered by either [pull-cluster-api-provider-aws-build](https://github.com/kubernetes/test-infra/blob/f8343b83589874eb484a7121dadcd0b69fc1c6ef/config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml#L16), or [pull-cluster-api-provider-aws-test](https://github.com/kubernetes/test-infra/blob/f8343b83589874eb484a7121dadcd0b69fc1c6ef/config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml#L3).

**Comment by varunpurohit76** [comment]
hi @ncdc @randomvariable 

I am planning to add e2e test build in pull-cluster-api-provider-aws-build which triggers `./scripts/ci-build.sh` 
Will keep the following hierarchy in makefile for `make binaries`
binaries
  -  managers
  - clusterawsadm
  - (+) e2e

.PHONY e2e will do `ginkgo build -tags=e2e  ./test/e2e/...`

**Comment by randomvariable** [comment]
use `go` instead of `ginkgo`, but that should otherwise be sufficient :+1:

**Comment by ncdc** [comment]
I'm pretty sure you need to do `go test -c -o /dev/null ./test/e2e/...`
