### ISSUE TITLE
Adopt the Cluster API e2e testing framework

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-aws#1435]
/kind feature

**Describe the solution you'd like**
CAPA should likely adopt the CAPI e2e testing framework to:
* Provide consistent e2e expectations across infrastructure providers
* Ensure the e2e framework covers all platforms

**Anything else you would like to add:**
CAPV recently made the switch to the CAPI e2e testing framework, so perhaps https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/691 can provide some help if any issues are encountered.

**Comment by prksu** [comment]
@akutz @ncdc can i go for it?

**Comment by detiber** [comment]
@prksu We're looking at trying to forward port some of the testing from the `release-0.4` branch before we attempt migrating to the new testing framework. https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1501 is the first PR for the forward porting attempts.

**Comment by randomvariable** [comment]
e2e_new tests use the clusterctl framework now.

/close
