### ISSUE TITLE
Implement equality method for Ingress Rule

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#145]
/kind feature

Follow up from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/141#discussion_r222014810

**Comment by randomvariable** [comment]
Related: #94

**Comment by vjdhama** [comment]
@detiber @davidz627 @vincepri I would like to pick this up, if not already picked up.

**Comment by detiber** [comment]
@vjdhama sounds good, when you do start working on it, please add a comment to this issue with `/lifecycle active` on it's own line so that the bot can update the labels and let others know that it is actively being worked on.

**Comment by davidz627** [comment]
@vjdhama did you tag the wrong David? I don't know what this is :)

**Comment by vjdhama** [comment]
@davidz627 My bad. Apologies.
