### ISSUE TITLE
Wrong security group assigned to load balancer

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#1452]
/kind bug

**What steps did you take and what happened:**
I modified the ELB listening port to 443 which by default is 6443. The control plane came up but I was not able to connect to the cluster using the kubeconfig. I verified that kubeconfig had the correct port value.
Further investigation showed that wrong security group is assigned to the load balancer. Today it reuses the control plane security group and it works in general because it uses port 6443.

**What did you expect to happen:**
I expected the kubeconfig connection to cluster work seamlessly.

**Anything else you would like to add:**
Probably we should add a separate security group for load balancer itself.

**Environment:**

- Cluster-api-provider-aws version: 0.4.6

**Comment by vincepri** [comment]
How was the ELB listening port modified to 443?

Usually we suggest using `spec.clusterNetwork.apiServerPort`, which is exposed [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/controllers/awscluster_controller.go#L164) in `AWSCluster.Status.APIEndpoints` and used [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/pkg/cloud/services/elb/loadbalancer.go#L240) to setup the listener. 

That said, it does seem that the load balancer shares the `controlplane` security group with the control plane nodes, but it doesn't setup the exposed port to be accessible from outside.

**Comment by vivgoyal** [comment]
I used spec.clusterNetwork.apiServerPort to specify the ELB listening port.
