### ISSUE TITLE
Allow configuration of allowed CIDR in ingress rule

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/cluster-api-provider-aws#1473]
/kind feature

**Describe the solution you'd like**

It seems to be hardcoded at the moment

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/75271f7b51f4a1e358792754a1c890b167d62460/pkg/cloud/services/ec2/securitygroups.go#L370

Would be nice to make it configurable.

**Anything else you would like to add:**

None

**Environment:**

Not relevant

**Comment by ncdc** [comment]
The line you referenced is for the bastion host. Is this a request specifically for the bastion host?

We also have a WIP in #1189 to allow you to specify the ingress CIDR blocks for the control plane load balancer.

**Comment by yujunz** [comment]
It could be two different configuration. I was looking for the equivalence to https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#sshaccess
and https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#kubernetesapiaccess

**Comment by ncdc** [comment]
Let's add a field to AWSCluster.Spec.Bastion to make the CIDR blocks configurable. We presumably need to keep the default behavior, where unspecified means 0.0.0.0/0. If we add

```go
CIDRBlocks []string `json:"cidrBlocks,omitempty"`
```

I _think_ that we can distinguish between `nil` (use 0.0.0.0/0) and `[]` (don't add any ingress rules). Does that work for everyone?

@vincepri @detiber @randomvariable @rudoi

**Comment by vincepri** [comment]
Do we need to have `[]string` become `*[]string`?

**Comment by aaroniscode** [comment]
I also free up next week and can work on it then.

**Comment by randomvariable** [comment]
makes sense, modulo `[]string` vs `*[]string`

**Comment by vincepri** [comment]
If we remove the `omitempty` part, we might be able to use `[]string` and defaulting webhook which (on create) can check if the field is nil or not and default it to `[]string{0.0.0.0/0}`. This way, in the reconciler code we can treat `len(0)` and `nil` slices the same (no rules).

**Comment by ncdc** [comment]
I tested `[]string` and it works as I want with `omitempty` and distinguishing `nil` vs `len(x) == 0`

**Comment by ncdc** [comment]
Do we instead want to say that `nil` and `[]` are identical?

**Comment by vincepri** [comment]
Not sure, the intent might be to set the slice to an empty block to avoid any ssh allow rule

**Comment by randomvariable** [comment]
>  set the slice to an empty block to avoid any ssh allow rule
This one, for sure. Shall we try `CIDRBlocks []string `json:"cidrBlocks,omitempty"`` and back out if necessary. It won't be a massive change in the PR if it turns out not to be right.

**Comment by ncdc** [comment]
```go
func TestAndy(t *testing.T) {
	sc := runtime.NewScheme()
	if err := AddToScheme(sc); err != nil {
		panic(err)
	}

	codecFactory := serializer.NewCodecFactory(sc)

	y := []byte(`
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
spec:
  bastion:
    enabled: false
    cidrBlocks: []
`)
	awsc := &AWSCluster{}
	if err := runtime.DecodeInto(codecFactory.UniversalDeserializer(), y, awsc); err != nil {
		panic(err)
	}

	fmt.Printf("nil: %t\n", awsc.Spec.Bastion.CIDRBlocks == nil)
	fmt.Printf("len: %d\n", len(awsc.Spec.Bastion.CIDRBlocks))

	y = []byte(`
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
spec:
  bastion:
    enabled: false
`)

	awsc = &AWSCluster{}

	if err := runtime.DecodeInto(codecFactory.UniversalDeserializer(), y, awsc); err != nil {
		panic(err)
	}

	fmt.Printf("nil: %t\n", awsc.Spec.Bastion.CIDRBlocks == nil)
	fmt.Printf("len: %d\n", len(awsc.Spec.Bastion.CIDRBlocks))
}
```

Yields:

```
=== RUN   TestAndy
nil: false
len: 0
nil: true
len: 0
```

To fully test this, we'd need to go through the apiserver and see if it changes the behavior any.

**Comment by vincepri** [comment]
That works out if using `kubectl`. What about external controllers? If we have `omitempty` the field in question will be always taken out of json serialization.

**Comment by ncdc** [comment]
Right, so it works on the way in, but not on the way out - when you `json.Marshal()` the `AWSCluster`, there's no way to distinguish between `nil` and `[]`. 😦 

If we get rid of `omitempty`, we can distinguish - it's either marshaled as `null` or `[]` but it's always present.

**Comment by ncdc** [comment]
Alternatively, we could add some `bool` field to indicate we don't want it, and use that instead of trying to distinguish between unspecified and an empty array.

**Comment by cdenneen** [comment]
@yujunz did you ever get something to be able to specify CIDR for kubernetesApiAccess? Seems like that might have been overlooked as part of this request.

> It could be two different configuration. I was looking for the equivalence to https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#sshaccess
> and https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#kubernetesapiaccess

Right now I'm stuck modifying the cluster security group after creation to add our CIDR range for our Direct Connect (machines part of VLANs from Direct Connect cannot be currently associated with an AWS Security Group so that's why I cannot pre-create a SG and add that to the cluster creation).
