### ISSUE TITLE
Tags on resources are being updated during reconciliation even if those tags are not changed.

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes-sigs/cluster-api-provider-aws#1499]
/kind bug

In our environment, we are noticing that tags on some AWS resources are being updated even if there is no change in them. It happens when there are external tags on those AWS resources created by some external entities dynamically. 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Created external tags on some AWS resources like security groups for example. There was no change in cluster created/managed tags but during reconciliation, we are seeing that those tags are still being updated even if there is no change.

**What did you expect to happen:**
Tags should not be updated if there is no change.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The code where it is happening is here:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/tags/tags.go#L58-#L60

And here is the patch we are using to handle this:
https://github.com/aveshagarwal/cluster-api-provider-aws/commit/358028f9688a94939876bfe862cef4bc2e3fefc0

**Environment:**
AWS

- Cluster-api-provider-aws version: 
latest

- Kubernetes version: (use `kubectl version`): 

1.15, 1.16

- OS (e.g. from `/etc/os-release`):

**Comment by aveshagarwal** [comment]
@ncdc

**Comment by ncdc** [comment]
cc @vincepri @randomvariable

**Comment by ncdc** [comment]
cc @rudoi

**Comment by vincepri** [comment]
Is this something you can use `AdditionalTags` for? https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awsmachine_types.go#L53

The code behaves according to our initial spec, which is to always overwrite the whole set of tags. This behavior was preferred because the call to change tags applies to the whole set, you can't set/unset a specific tag for a resource afaik.

**Comment by aveshagarwal** [comment]
> Is this something you can use `AdditionalTags` for? https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awsmachine_types.go#L53

We have looked into additional tags, but in our environment, those external tags are created by external processes dynamically and are random, and we do not have any control on them. 

> The code behaves according to our initial spec, which is to always overwrite the whole set of tags. This behavior was preferred because the call to change tags applies to the whole set, you can't set/unset a specific tag for a resource afaik.

In our testing, we have seen that it only affects the set of tags being updated (if there is any change) and not other external tags, so works as expected.

**Comment by vincepri** [comment]
Got it! Seems we should be able to add a check to `Ensure` to only apply the tags if they're not a subset of the current ones.

**Comment by aveshagarwal** [comment]
So here are the code changes we are using right now https://github.com/aveshagarwal/cluster-api-provider-aws/commit/b65a99b54f00b6885fe56546d06e1a3ef19506b8

If it looks good, i can create a PR.

**Comment by ncdc** [comment]
The [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) say this:
> Adds or overwrites the specified tags for the specified Amazon EC2 resource or resources.

It definitely sounds like it only affects the tags you specify in the input, and that it's not a wholesale delete-all followed by a set operation.

@detiber or @randomvariable do you concur? Also, @aveshagarwal your commit seems reasonable to me. It'd be nice to have some tests for this, too (I realize there aren't any now).

**Comment by aveshagarwal** [comment]
> The [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) say this:
> 
> > Adds or overwrites the specified tags for the specified Amazon EC2 resource or resources.
> 

Exactly that is our undrstanding too.


> It definitely sounds like it only affects the tags you specify in the input, and that it's not a wholesale delete-all followed by a set operation.
> 
> @detiber or @randomvariable do you concur? Also, @aveshagarwal your commit seems reasonable to me. It'd be nice to have some tests for this, too (I realize there aren't any now).

Sure, i can add unit tests for this.

**Comment by detiber** [comment]
> It definitely sounds like it only affects the tags you specify in the input, and that it's not a wholesale delete-all followed by a set operation.

Indeed, that is my understanding as well.

**Comment by randomvariable** [comment]
Concur with everything here :)

**Comment by rudoi** [comment]
+1 from me here as well. We've never hit this in our environment because we manage all of our tags through the AWSCluster object.

**Comment by aveshagarwal** [comment]
PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1504
