### ISSUE TITLE
Missing nodepool instance is not replaced

### ISSUE THREAD

**Issue by temujin9** [kubernetes-sigs/cluster-api-provider-aws#1505]
/kind bug

**What steps did you take and what happened:**
Followed the Cluster API quickstart instructions. Once the MachinePool instance was connected and healthy, deleted its corresponding instance from the AWS console.

**What did you expect to happen:**
After a reasonable delay, the awsmachine should be replaced.

**Anything else you would like to add:**
The awsmachine does notice loss of the machine it corresponds to, but Ready stays true in Status, which may be part of this failure mode.
```
neliot@neliot-IT-USA-05118:~$ kubectl describe awsmachine capi-quickstart-worker-662bk
Name:         capi-quickstart-worker-662bk
Namespace:    default
Labels:       <none>
Annotations:  cluster-api-provider-aws: true
API Version:  infrastructure.cluster.x-k8s.io/v1alpha2
Kind:         AWSMachine
Metadata:
  Creation Timestamp:  2020-01-30T17:41:00Z
  Finalizers:
    awsmachine.infrastructure.cluster.x-k8s.io
  Generate Name:  capi-quickstart-worker-
  Generation:     2
  Owner References:
    API Version:           cluster.x-k8s.io/v1alpha2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineSet
    Name:                  capi-quickstart-worker-664c4f9c68
    UID:                   d44e967c-82fa-483c-967c-865c7b31965d
    API Version:           cluster.x-k8s.io/v1alpha2
    Kind:                  Machine
    Name:                  capi-quickstart-worker-664c4f9c68-9r9jp
    UID:                   707cbb37-e09d-4220-8edc-526759d8599e
  Resource Version:        51480
  Self Link:               /apis/infrastructure.cluster.x-k8s.io/v1alpha2/namespaces/default/awsmachines/capi-quickstart-worker-662bk
  UID:                     b7950b1f-c140-4d0f-b1a2-71a6c8580675
Spec:
  Iam Instance Profile:  nodes.cluster-api-provider-aws.sigs.k8s.io
  Instance Type:         t3.large
  Provider ID:           aws:////i-0c0105b2c7078a2eb
  Ssh Key Name:          pure-clusterapi-test
Status:
  Error Message:   EC2 instance state "terminated" is unexpected
  Error Reason:    UpdateError
  Instance State:  terminated
  Ready:           true
Events:
  Type     Reason                         Age                From                   Message
  ----     ------                         ----               ----                   -------
  Normal   SuccessfulCreate               46m                aws-controller         Created new node instance with id "i-0c0105b2c7078a2eb"
  Warning  InstanceUnexpectedTermination  32m (x2 over 32m)  awsmachine-controller  Unexpected EC2 instance termination
```

**Environment:**

- Cluster-api-provider-aws version: 
Version Info: GitReleaseTag: "v0.4.8", MajorVersion: "0", MinorVersion:"4", GitReleaseCommit:"113f0148ffd47d", GitTreeState:"dirty"

- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): 
VERSION="18.04.3 LTS (Bionic Beaver)"

**Comment by ncdc** [comment]
Hi @temujin9, thank you for your report.

Cluster API does not currently support automatically deleting failed machines and replacing them. We have work in flight for our next release that will add a new machine health check feature that hopefully will cover this. We have also updated Cluster API to update the phase (e.g. ready or not) instead of it always saying ready.

This is not an issue specific to cluster-api-provider-aws and there isn't anything we can do in this repository to fix this. I'd like to refer you to https://github.com/kubernetes-sigs/cluster-api/issues/1990 and https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191030-machine-health-checking.md. If those look like they address your issue, would you please consider closing this and trying out the machine health check bits as they become available?

**Comment by temujin9** [comment]
Ah, fair. Documentation mislead me about it being implemented already.

I'll close this, and watch that instead.

**Comment by ncdc** [comment]
@temujin9 which documentation?

**Comment by temujin9** [comment]
@ncdc I'm not finding it, might have been just my own misreading. If I find it later I'll ping here.
