### ISSUE TITLE
Remove deprecated AvailabilityZone field on machine spec

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1508]
Please see this comment for context: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1507#discussion_r373213811

I believe it's safe to simply remove the `AvailabilityZone` field, but @vincepri or @detiber can correct me if I'm wrong. No deprecation policy needs to be maintained here as these are alpha types.

/milestone v0.5.0
/priority important-soon
/kind cleanup

I'm marking this important soon so we get rid of it before the next release so we don't carry a deprecated field along.

**Comment by detiber** [comment]
+1 on removal, since we have a field to replace the contents we can just handle the automatic migration with conversion without needing to deal with the deprecated field in v1alpha3.
