### ISSUE TITLE
Handle backup/restore of ImageLookupBaseOS field during conversion

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1510]
/kind bug

We currently aren't handling the backup/restore of the ImageLookupBaseOS field on Machine/Cluster resources. We'll need this for release to avoid lossy conversions

/priority important-soon
/milestone v0.5.0

**Comment by randomvariable** [comment]
/lifecycle active

fixed up in #1490
