### ISSUE TITLE
Add docs for consuming existing AWS infrastructure

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/cluster-api-provider-aws#1511]
**Describe the solution you'd like**
The current quickstart / docs assume CAPA will be creating all infrastructure (VPC etc).

We should add a section describing the requirements (resources / tags / etc...) for consuming existing infrastructure. 

cc/ @scottslowe

/kind feature

**Comment by scottslowe** [comment]
I'd like to take a crack at this one, if that's OK.

**Comment by detiber** [comment]
@scottslowe It's all yours :)
/assign @scottslowe 
/lifecycle active

**Comment by scottslowe** [comment]
@detiber My thought was to approach this with a file in the `docs` directory, along with a link from `README.md` in the same directory. Later, we can determine if this is something that needs to be added to the CAPI book. Does that sound reasonable?

**Comment by detiber** [comment]
@scottslowe sounds good to me.

**Comment by scottslowe** [comment]
#1560 is open to address this issue, and is ready for review/comments/feedback.

**Comment by detiber** [comment]
Bumping from the v0.5.0 milestone and moving to v0.5.x
/milestone v0.5.x
