### ISSUE TITLE
Panic Error during cluster provisioning 

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api-provider-aws#1522]
/kind bug

Running E2E tests through test grid and seeing all the tests are failing as the cluster provisioning is not getting completed. 

Expectation: Cluster provisioning should be completed with no issues.

When checked the CAPA logs, observed that panic error occurred during ClassicELBProvisioning blocking the provisioning and below is the error message:

`I0204 20:47:19.973318       1 gateways.go:127] controllers/AWSCluster "msg"="Created internet gateway for VPC" "awsCluster"="test-infra-4ea5w9" "cluster"="test-pbns3i" "namespace"="test-m2mxai" "vpc-id"="vpc-0dfe9fc7257c1c47f"
I0204 20:47:20.242964       1 gateways.go:159] controllers/AWSCluster "msg"="attached internet gateway to VPC" "awsCluster"="test-infra-4ea5w9" "cluster"="test-pbns3i" "namespace"="test-m2mxai" "internet-gateway-id"="igw-089b0298a49b15f18" "vpc-id"="vpc-0dfe9fc7257c1c47f"
I0204 20:47:21.307392       1 natgateways.go:197] controllers/AWSCluster "msg"="Created NAT gateway for subnet, waiting for it to become available..." "awsCluster"="test-infra-4ea5w9" "cluster"="test-pbns3i" "namespace"="test-m2mxai" "nat-gateway-id"="nat-0fabdc56d4990b33d" "subnet-id"="subnet-0f9b203c8a230f30a"
I0204 20:49:07.259894       1 natgateways.go:204] controllers/AWSCluster "msg"="NAT gateway for subnet is now available" "awsCluster"="test-infra-4ea5w9" "cluster"="test-pbns3i" "namespace"="test-m2mxai" "nat-gateway-id"="nat-0fabdc56d4990b33d" "subnet-id"="subnet-0f9b203c8a230f30a"
E0204 20:49:11.210800       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 222 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18f7420, 0x2c7dab0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18f7420, 0x2c7dab0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).getAPIServerClassicELBSpec(0xc0006b38d0, 0x1b86153, 0x1a, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:271 +0x43b
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).ReconcileLoadbalancers(0xc0006b38d0, 0x0, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:47 +0xa2
sigs.k8s.io/cluster-api-provider-aws/controllers.reconcileNormal(0xc00066d000, 0xc0004ca1f8, 0x1f24d00, 0xc0004ca208, 0x1f1fa60)
	/workspace/controllers/awscluster_controller.go:155 +0x158
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSClusterReconciler).Reconcile(0xc00067eed0, 0xc000489300, 0xb, 0xc000701900, 0x11, 0xc0007a3c00, 0x0, 0x1e9e180, 0xc000583f60)
	/workspace/controllers/awscluster_controller.go:100 +0x65c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000684b40, 0x197a260, 0xc00038e120, 0x2ca2500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000684b40, 0xc000508d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000684b40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000252620)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000252620, 0x3b9aca00, 0x0, 0x1, 0xc00014c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000252620, 0x3b9aca00, 0xc00014c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16c291b]

goroutine 222 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18f7420, 0x2c7dab0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).getAPIServerClassicELBSpec(0xc0006b38d0, 0x1b86153, 0x1a, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:271 +0x43b
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).ReconcileLoadbalancers(0xc0006b38d0, 0x0, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:47 +0xa2
sigs.k8s.io/cluster-api-provider-aws/controllers.reconcileNormal(0xc00066d000, 0xc0004ca1f8, 0x1f24d00, 0xc0004ca208, 0x1f1fa60)
	/workspace/controllers/awscluster_controller.go:155 +0x158
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSClusterReconciler).Reconcile(0xc00067eed0, 0xc000489300, 0xb, 0xc000701900, 0x11, 0xc0007a3c00, 0x0, 0x1e9e180, 0xc000583f60)
	/workspace/controllers/awscluster_controller.go:100 +0x65c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000684b40, 0x197a260, 0xc00038e120, 0x2ca2500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000684b40, 0xc000508d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000684b40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000252620)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000252620, 0x3b9aca00, 0x0, 0x1, 0xc00014c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000252620, 0x3b9aca00, 0xc00014c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328`

- Cluster-api-provider-aws version: v0.4.8
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sirao** [comment]
All components logs can be accessed here: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1501/pull-cluster-api-provider-aws-e2e/1224792986341085184/artifacts/logs/

**Comment by ncdc** [comment]
We fixed this yesterday: #1521
