### ISSUE TITLE
Machine NodeRef is not getting assigned as the request to LB is timing out

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api-provider-aws#1530]
Run the E2E tests.

Should be able to create the control plane after successful completion cluster provisioning.

In CAPI logs, below error messages seen:
`E0206 09:16:47.033204       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="Get https://test-31mn8o-apiserver-182030076.us-west-2.elb.amazonaws.com:6443/api?timeout=32s: EOF"  "controller"="machine" "request"={"Namespace":"test-2b1mak","Name":"test-dizm60-0"}
E0206 09:22:42.263517       1 machine_controller_noderef.go:79] controllers/Machine "msg"="Failed to assign NodeRef" "error"="Get https://test-31mn8o-apiserver-182030076.us-west-2.elb.amazonaws.com:6443/api?timeout=32s: EOF" "cluster"="test-31mn8o" "machine"="test-dizm60-0" "namespace"="test-2b1mak" `

All components logs can be accessed at: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1501/pull-cluster-api-provider-aws-e2e/1225289059950137344/artifacts/logs/

**Environment:**

- Cluster-api version: v0.2.6
- Minikube/KIND version: 1.5.3
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by ncdc** [comment]
Since this is a test against the master branch, I assume the CAPI version is not v0.2.6 but actually CAPI for v1alpha3, right?

**Comment by ncdc** [comment]
I don't see `journalctl` log output in the prow artifacts. I don't think we'll be able to debug without that. Any chance you can adjust the PR to do more log gathering, similar to what's in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/aad48bd4140f10703d6f05bc83a66a284350734a/hack/ci/e2e-conformance.sh#L32-L93?

**Comment by ncdc** [comment]
It's possible this is running into a newly discovered issue with moving the bootstrap data to AWS Secrets Manager (a 10kb limit). We'll be filing an issue for that shortly.

**Comment by sirao** [comment]
> Since this is a test against the master branch, I assume the CAPI version is not v0.2.6 but actually CAPI for v1alpha3, right?

Yes. CAPI for v1alpha3.

**Comment by detiber** [comment]
I believe this is related to using an AMI that does not contain the CLI tooling: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1555

If there is an additional issue, please re-open.
/close
