### ISSUE TITLE
Validation exception because secret crosses 10k limit on creation of a machine

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#1531]
/kind bug
I am seeing validation exception because secret crosses 10k limit on creation of a machine.
"msg"="Reconciler error" "error"="ValidationException: 1 validation error detected: Value at 'secretBinary' failed to satisfy constraint: Member must have length less than or equal to 10240\n\tstatus code: 400

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Used release 0.4 staging image to create a cluster
Probably we should add it into multiple secrets and bind them together.

**Environment:**

- Cluster-api-provider-aws version: 0.4 staging -> 0.4.9
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
AWS Secrets Manager maxes the secret data at 10240 bytes per secret. Will need to chunk, store multiple secrets, and then stitch back together in the cloud-init script.
