### ISSUE TITLE
cleanup: enable `unused` linter

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1537]
After #1535, we updated the golangci-lint to the latest version and matched the upstream Cluster API format for the linter, it seems there were a bunch of linters missing.

- Head over to [.golanci-lint.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml) in the root of this repository.
- Remove the linter from the `linters.disable` list.
- Run `make lint-full`.
- Fix the reported errors with the suggestions.
- Submit a PR with the changes.

Feel free to reach out at any time if you need guidance or help.

/kind cleanup
/help
/good-first-issue
/milestone Next
/priority backlog

**Comment by ernestas2k** [comment]
@vincepri 

`
cmd/release/main.go:417:2: field `stagingRegistry` is unused (unused)
cmd/release/main.go:424:22: func `makebuilder.cmdWithStagingEnv` is unused (unused)
`

should we provide buildStaging() that uses cmdWithStagingEnv() and the stagingRegistry field or actually remove the stagingRegistry field and cmdWithStagingEnv func?

**Comment by detiber** [comment]
@chuckha might have some opinions on this

**Comment by chuckha** [comment]
I'm in favor of deleting that `cmd/release` directory. it should be entirely unused and unmaintained at this point.

**Comment by ernestas2k** [comment]
semi-automatic section, which mentions the cmd/release should also go away? https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/releasing.md

**Comment by chuckha** [comment]
@ernestas2k Yeah, but I haven't done a release here in forever.

@detiber, @vincepri or @ncdc can definitively answer.

**Comment by ernestas2k** [comment]
In case of `cmd/release` actually being unused - the pull request is ready to remove it and the associated documentation.
