### ISSUE TITLE
cleanup: enable `scopelint` linter

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1542]
After #1535, we updated the golangci-lint to the latest version and matched the upstream Cluster API format for the linter, it seems there were a bunch of linters missing.

- Head over to [.golanci-lint.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml) in the root of this repository.
- Remove the linter from the `linters.disable` list.
- Run `make lint-full`.
- Fix the reported errors with the suggestions.
- Submit a PR with the changes.

Feel free to reach out at any time if you need guidance or help.

/kind cleanup
/help
/good-first-issue
/milestone Next
/priority backlog

**Comment by teaguecole** [comment]
Hey @vincepri since these cleanups are relatively small issues, would it be okay to combine them all in to 1 PR or do you want to save some for other new contributors? If not I am more than happy to do it all at once?

**Comment by detiber** [comment]
@teaguecole feel free to combine multiple in a single PR as long as the changeset is still relatively easily reviewable

**Comment by teaguecole** [comment]
Ill stick with scopelint for now just incase someone else comes by and wants to take one.  If I finish this, ill move on to the next...
