### ISSUE TITLE
Some AMIs missing aws cli tools

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api-provider-aws#1555]
/kind bug

The new Secret Manager work requires the AWS cli tooling to be installed on the machine, but the AMIs packed before the Oct 25th update, seen in [the history](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commits/master/docs/amis.md) no aws cli tooling is installed.

@detiber suggested that it would be possible to rebuild the older AMIs to ensure the required dependencies are present. 

Slack thread for more context: https://kubernetes.slack.com/archives/CD6U2V71N/p1581526919261400

**Comment by detiber** [comment]
Rebuilding AMIs:
v1.15.0
v1.15.0
v1.15.0

**Comment by detiber** [comment]
All of the above mentioned images should be published and available now.
/close
