### ISSUE TITLE
Credentials from secret don't always work in aws container

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/cluster-api-provider-aws#1556]
/kind bug

**What steps did you take and what happened:**
Trying to follow the quickstart with a patched version of aws provider for development, keep getting error trying to list VPCs during initial cluster creation: "NoCredentialProviders: no valid providers in chain. Deprecated."

I created the credentials like normal; I decoded the secret that was mounted into the container, the credentials are correct.  If I set the credentials as ENV vars in the container directly (AWS_REGION, etc), the credentials work fine and I don't see the error.

**What did you expect to happen:**
Credentials should work without having to specify the env vars.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: Parent commit d84856972a3e5c910578de0e88d83f859136a179 (tag: v0.4.9, k8s/release-0.4)
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`):  RHEL CoreOS / OpenShift 4.2

**Comment by sethp-nr** [comment]
I'm able to use a mounted credential against master currently. Yesterday I ran into a similar problem because I had credentials that looked like this:

```
[my-cool-profile-name]
aws_access_key_id=xxx
aws_secret_access_key=xxx
aws_session_token=xxx
aws_security_token=xxx
```

when I changed them to be 

```
[default]
aws_access_key_id=xxx
aws_secret_access_key=xxx
aws_session_token=xxx
aws_security_token=xxx
```

I was able to list VPCs again with master. Alternatively, I suspect that setting `AWS_PROFILE=my-cool-profile-name` would have been sufficient.

**Comment by michaelgugino** [comment]
My credentials secret is the default profile.  There is aws_access_key_id, aws_secret_access_key, and region.  This was all created following the steps in the quick start.

**Comment by sethp-nr** [comment]
Hmm, sounds like you're having a different issue, then. For what it's worth I just tried the [steps in the quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterawsadm) using a built-from-master `clusterawsadm` binary and I'm still not able to reproduce the issue you cited.

**Comment by randomvariable** [comment]
@michaelgugino are there any modifications to the user as which the container is running in your environment? the default image is still running as root, so `/root/.aws/config` is expected. Need to dig into the default credential chain in the SDK, but it maybe failing to a `getent` for the user name?

**Comment by randomvariable** [comment]
Actually, probably better in your environment to directly set the `AWS_SHARED_CREDENTIALS_FILE` variable to the config file you're using. That should make it work without any lookup of the home directory.

**Comment by michaelgugino** [comment]
> @michaelgugino are there any modifications to the user as which the container is running in your environment? the default image is still running as root, so `/root/.aws/config` is expected. Need to dig into the default credential chain in the SDK, but it maybe failing to a `getent` for the user name?

I think you might be on to something here.  I'm building with buildah rather than docker, so there might be some differences in user bits.  I'll try to look into this further.

**Comment by bagnaram** [comment]
I'm experiencing a similar issue with reading profiles via the `AWS_CONFIG_FILE`. When I leave out the `AWS_SHARED_CREDENTIALS_FILE` and specify a profile via shared config, the controller pod fails to associate it. 

/home/.aws/config:
```
[profile mycorp]
role_arn = arn:aws:iam::xxxxxx:role/svc.cluster-api-provider-aws
region = us-west-1
source_profile = xxxxxx
[profile xxxxxx]
aws_access_key_id = xxxx
aws_secret_access_key = xxxxxx
```

controller deployment:
```
        - name:  AWS_CONFIG_FILE
          value: "/root/.aws/config"
        - name: AWS_PROFILE
          value: "mycorp"
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
```

**Comment by randomvariable** [comment]
/area security

Thanks for the update. Will try and resolve over the next few days.

If you're interested, also putting together a proposal that will address these UX issues as part of #1552, but that will be targeted for v1alpha4 timeframe probably. User stories / requirements / wishes welcome.

**Comment by bagnaram** [comment]
#1590 has been submitted. Session creation appears to happen during inception, which ignores additional options like credentials region, and profile loaded from the environment and shared config.

**Comment by bagnaram** [comment]
#1590 has been submitted. Session creation appears to happen during inception, which ignores additional options like credentials region, and profile loaded from the environment and shared config.

**Comment by randomvariable** [comment]
After some experimentation in #1717, this was found to work as is. If there's still a problem, please reopen.

/close
