### ISSUE TITLE
Documentation for testing

### ISSUE THREAD

**Issue by teaguecole** [kubernetes-sigs/cluster-api-provider-aws#1579]
/kind documentation

**Describe the solution you'd like**
Currently there is no clear documentation on the process of testing your changes locally that a newcomer could follow. I could see this documentation being part of `CONTRIBUTING.md` or `README.md` along with `Getting involved and contributing`.

**Comment by randomvariable** [comment]
I think this is mostly done. Thanks @richardcase !

/close
