### ISSUE TITLE
Broader CNI Test coverage

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-aws#1588]
/kind bug

**What steps did you take and what happened:**

A couple of recent bugs point to holes in the way we default to certain CNI providers, which bake assumptions into how we deal w/ AWS Security groups and so on.

**What did you expect to happen:**

CAPA deployments should be as CNI / LB/ etc Agnostic as possible.

**Anything else you would like to add:**

@randomvariable  to add deets

**Comment by randomvariable** [comment]
/help

The process will be to add tests to https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/master/test/e2e to create the necessary security groups for the CNI, add them to the relevant machinetemplates and exercise pod networking, as well as network policy where appropriate.

**Comment by randomvariable** [comment]
The Amazon VPC CNI should be one of the targets.

**Comment by jayunit100** [comment]
- I see the cni var in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/test/e2e/ , so thats easy.
- For AWS VPC CNI, i dont see any security groups in the e2e/ code above.  Am i looking in the wrong place?

**Comment by randomvariable** [comment]
@jayunit100 After #1760 goes in, you should be able to run

AWS_REGION=${YOUR REGION OF CHOICE} make test-conformance-new E2E_CONF_PATH=${Path to custom Clusterctl e2e conf} KUBETEST_CONF_PATH=${Path to custom kubetest conf}

with the latter defined in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1760/files#diff-69dbeb2da3531f6ba0edb7b84e892613 and https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1760/files#diff-61349ee9990a2cb59acf6d9f5a3fe555

**Comment by randomvariable** [comment]
#1745 has more info but is otherwise a dupe, so going to

/close
