### ISSUE TITLE
Apply example addons fails with: missing required field "versions"

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1595]
/kind bug

**What steps did you take and what happened:**
Create a new cluster with the latest master version of CAPI and CAPA, apply addons.

```
$ k apply -f examples/addons.yaml
configmap/calico-config created
error: error validating "examples/addons.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

**What did you expect to happen:**
Addons should work properly

**Comment by detiber** [comment]
We need to update the version of Calico to resolve this

/priority important-soon
/milestone v0.5.0
/help

**Comment by detiber** [comment]
With the new `clusterctl` v2 workflow, do we need to have an `addons.yaml` file anymore? I'm wondering if it would make more sense to point docs and testing use cases towards an upstream release of Calico rather than duplicating one here...

@ncdc @vincepri @chuckha @randomvariable thoughts?

**Comment by ncdc** [comment]
+1 remove, docs only

**Comment by ncdc** [comment]
Really all of `examples` needs to go away in favor of clusterctl v2 templates + docs for things like calico (until we have post-create add thunk)

**Comment by detiber** [comment]
We no longer have addons.yaml, but still need to follow up on documenting how to deploy a cluster, which will likely tie into the implementation of https://github.com/kubernetes-sigs/cluster-api/issues/2434

**Comment by randomvariable** [comment]
Somehow missed this one.

I've updated the CAPV docs to not refer to the sample addons and will also delete it.

I did independently bump Calico before it was removed in #1601, so think this one can
/close

**Comment by randomvariable** [comment]
Also, @ncdc noted that we should do something about the conformance templates in #1610
