### ISSUE TITLE
Cloud-init module

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#16]
todo - fill in here 
/assign @chuckha

**Comment by randomvariable** [comment]
An idea for improving on polling and timeouts for success or failure of the node:

1. Bake `rando_name.timer` systemd-timer unit that communicates status using the AWS CLI, reading an EnvFile with the SNS topic (probably some bash thing).

2. User is required to add IAM policy for actuator to create SNS and SQS queues with a prefix that belongs to the cluster, e.g.:

For Cluster API:
``` json
{
   "Version":"2012-10-17",
   "Statement":[{
      "Effect":"Allow",
      "Action":["sns:CreateTopic","sns:ListTopics","sns:SetTopicAttributes","sns:DeleteTopic"],
      "Resource":"arn:${Partition}:sns:${Region}:${Account}:kubernetes.io-cluster-<name>-*"
      }
   ]
}
```
For worker nodes:
``` json
{
   "Version":"2012-10-17",
   "Statement":[{
         "Effect":"Allow",
         "Action":"sns:Publish",
         "Resource":"arn:${Partition}:sns:${Region}:${Account}:kubernetes.io-cluster-<name>-instance-status-*"
      },
   ]
```

3. Actuator creates SNS and SQS queue and processes messages, updating status appropriately.

4. SNS ARN injected into user data, written to `/etc/default/rando_name`

5. Machine bootstraps. Success condition reached.

Valid states: `NOT_BOOTSTRAPPED`, `IN_PROGRESS`, `SUCCESS`, `FAILED`

An example notification:
``` shell
aws sns publish --topic-arn $SNS_TOPIC_ARN --message "error: failed to run Kubelet: failed to create kubelet" --message-attributes '{"instance-id":{"DataType":"String","StringValue":"i-84384834343"},{"bootstrap-state":{"DataType":"String","StringValue":"FAILED"} }'
```

Standard SQS queues with the raw message delivery subscription to the SNS topic will be fine.

**Comment by randomvariable** [comment]
For distribution of the bootstrap token:

1. User creates the following IAM policies:

For worker nodes:
``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameter*"
            ],
            "Resource": [
              "arn:${Partition}:ssm:${Region}:${Account}:/parameter/kubernetes.io/cluster/${name or id}/bootstrap_token"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": ""arn:${Partition}:kms:${Region}:${Account}:key/${key ID}"
        }
    ]
}
```

Anything running cluster API:
``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:PutParameter",
                "ssm:GetParameter*",
                "ssm:DeleteParameter",
            ],
            "Resource": [
              "arn:${Partition}:ssm:${Region}:${Account}:/parameter/kubernetes.io/cluster/${name or id}/bootstrap_token"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:Encrypt"
            ],
            "Resource": ""arn:${Partition}:kms:${Region}:${Account}:key/${key ID}"
        }
    ]
}
```

2. During bootstrap of control plane, use the AWS CLI to upload the bootstrap token, and on the
worker nodes, use the same to download.

There's a slight issue in that the key ID will need to be resolved from the SSM parameter alias.
Think we might need a CLI tool to spit out the IAM policies that need to be applied here.
