### ISSUE TITLE
Examples should ship with KCP for v1alpha3

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1605]
/kind feature

**Describe the solution you'd like**
The examples directory contains manifests users can use to spin up a new cluster. Instead of using simple machines, we should rely on KCP functionality in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/examples/controlplane/controlplane.yaml

**Comment by detiber** [comment]
@vincepri I'm working on this currently as a part of #1500 

/priority important-soon
/milestone v0.5.0-rc.0
/assign
/lifecycle active
