### ISSUE TITLE
can not open link

### ISSUE THREAD

**Issue by ttonline6** [kubernetes-sigs/cluster-api-provider-aws#1609]
#https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/userdata-privacy.md
http://169.254.169.254/latest/api/token，can not be reached

**Comment by sethp-nr** [comment]
Where are you trying to open the metadata link from? I'm able to access it from one of my EC2 instances just fine:

```
$ curl -vX OPTIONS http://169.254.169.254/latest/api/token
*   Trying 169.254.169.254...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> OPTIONS /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.48.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Allow: OPTIONS, PUT
< Content-Length: 0
< Content-Type: text/plain
< Date: Mon, 02 Mar 2020 17:45:23 GMT
< Connection: close
< Server: EC2ws
<
* Closing connection 0
```

All addresses that start with 169.254.x.x are [link-local](https://en.wikipedia.org/wiki/Link-local_address) and so can only be answered from another service running on the same network segment (e.g. plugged into the same router). If you're trying to access the EC2 metadata API from anywhere but an EC2 instance, it's unlikely that you'll have such a service to respond.

Alternatively, is it possible that you have some kind of security group set up on the EC2 instance that prevents outbound connections to `169.254.0.0/16` addresses?

**Comment by randomvariable** [comment]
/close 
for lack of update.
