### ISSUE TITLE
Cluster and some objects stuck in "Deleting" state

### ISSUE THREAD

**Issue by scottslowe** [kubernetes-sigs/cluster-api-provider-aws#1611]
/kind bug

**What steps did you take and what happened:**
I used `kustomize build . | kubectl apply -f -` to apply some manifests to my management cluster. Immediately after applying the manifests, I realized there was an error, so I quickly ran `kustomize build . | kubectl delete -f -` to "revert" my changes.

**What did you expect to happen:**
Both Kubernetes and AWS objects that had been created would be deleted.

**Anything else you would like to add:**
Only some objects still show up in Kubernetes when running `kubectl get`. Objects that remain:

* Cluster
* Machines
* AWSMachines

Objects that are not present (but _were_ present in the manifests):

* AWSCluster
* MachineDeployments
* KubeadmConfig
* KubeadmConfigTemplates

All associated AWS objects either were never created (given the minimal time difference between the `kubectl apply` and the `kubectl delete`) or were successfully deleted. Either way, they are not present in AWS.

Logs from the CAPI and CAPA controllers are attached.

[2020-03-02-capa-controller-manager-logs.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/4276958/2020-03-02-capa-controller-manager-logs.txt)

[2020-03-02-capi-controller-manager-logs.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/4276960/2020-03-02-capi-controller-manager-logs.txt)

**Environment:**

- Cluster-api-provider-aws version: v0.2.9 (capi-controller-manager), v0.4.9 (capa-controller-manager)
- Kubernetes version: (use `kubectl version`): v1.16.4 (management cluster)
- OS (e.g. from `/etc/os-release`): macOS Mojave (`kubectl` client), Ubuntu 18.04.3 (management cluster nodes)

**Comment by randomvariable** [comment]
/assign
/lifecycle active

reading through the logs

**Comment by randomvariable** [comment]
i think you determined the root cause for this @scottslowe ?

**Comment by scottslowe** [comment]
@randomvariable I did not determine the root cause; I had to remove the finalizer on some stuck objects, and then everything proceeded. However, it is acceptable to close this issue since the problem was in fact resolved.

**Comment by detiber** [comment]
/close

Not able to currently reproduce and cannot troubleshoot system it occurred on. Please re-open if this issue crops up again.
