### ISSUE TITLE
Evaluate conversion webhook behavior based on liggitt's review of Cluster API

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1616]
- Take into account the feedback Jordan Liggitt gave during the API review session for Cluster API and ensure that we address the same issues here as well

Cluster API review feedback notes: https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#heading=h.2zz7is11zbh5

/priority important-soon
/milestone v0.5.0

**Comment by detiber** [comment]
I just went through and I believe for the support cases that we have (i.e. we don't expect v1alpha3 types to be created and reconciled by a v1alpha2 controller), I think we are mostly in good shape here.

I also verified that we have matchPolicy configured for Equivalent.

I did find one issue with opeanpi validation, and that is with `v1alpha3.awsMachine.spec.RootVolume.Size` having an openapi default of 8 and the associated `v1alpha2.awsMachine.RootDeviceSize` not having any openapi default set.

**Comment by detiber** [comment]
@ncdc could use your input to determine if the above is a potential release blocking issue or one that we can address if it becomes a problem later.

**Comment by detiber** [comment]
One potential fix for this that I can think of is that if we are converting from v1alpha2 -> v1alpha3 and RootDeviceSize == 0, we can override RootVolume.Size to 8, which would at least cover the default case. I'm not sure that we'd want to override it if a user explicitly set it to a value other than 0 (since we can't differentiate explict 0 from omitempty 0).

**Comment by ncdc** [comment]
Are there negative implications of having an alpha3 type with a 0 root volume size?

**Comment by detiber** [comment]
Not necessarily that I'm aware of, other than it wouldn't pass validation.

But @randomvariable might have more context than I do here.

**Comment by rudoi** [comment]
> Are there negative implications of having an alpha3 type with a 0 root volume size?

Yeah it would not pass validation. This was one of those fields in v1alpha1/2 that we marked immutable, so errors get thrown if what gets returned from EC2 is not the same as what's in the spec.

**Comment by detiber** [comment]
@rudoi Do we ever expect there to be a case other than 0 where there would be a valid v1alpha2 type that would have a RootDeviceSize < 8? I'm just trying to gauge how much of an edge case we are potentially looking at for this failure mode.

**Comment by rudoi** [comment]
@detiber only if someone wanted a smaller root volume, but I think it would be fair to just forget about that case.

**Comment by detiber** [comment]
Thanks!

Closing this issue in light of the previous discussion. If for some reason this edge case becomes an issue we can address it then.

/close
