### ISSUE TITLE
Test failure: periodic-cluster-api-provider-aws-e2e-conformance-master

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1624]
From e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-master/1235921055223123969:

```
+ ./scripts/ci-e2e-conformance.sh
/usr/local/bin/runner.sh: line 101: ./scripts/ci-e2e-conformance.sh: No such file or directory
```

/kind failing-test

**Comment by ncdc** [comment]
I think we need to forward-port the following:

From the Makefile in release-0.4:
```
.PHONY: test-conformance
test-conformance: ## Run conformance test on workload cluster
	PULL_POLICY=IfNotPresent $(MAKE) docker-build
	cd $(TEST_E2E_DIR); go test -v -tags=e2e -timeout=4h . -args -ginkgo.v -ginkgo.focus "conformance tests" --managerImage $(CONTROLLER_IMG)-$(ARCH):$(TAG)
```

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/scripts/ci-e2e-conformance.sh

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/test/e2e/conformance_test.go

Is that accurate, @detiber?

**Comment by detiber** [comment]
This should be fixed with the work that is being done in #1596

**Comment by jayunit100** [comment]
- yeah were doing the same thing in 1596, 
- the taxonomy of it is that this snippet came from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1586/files#diff-b67911656ef5d18c4ae36cb6741b7965R97 originally, 
- which as andy points out is a port of the 0.4 conformance stuff.
```
       	PULL_POLICY=IfNotPresent $(MAKE) docker-build
	cd $(TEST_E2E_DIR); go test -v -tags=e2e -timeout=4h . -args -ginkgo.v -ginkgo.focus "conformance tests" --managerImage $(CONTROLLER_IMG)-$(ARCH):$(TAG)
```

will keep everyone posted on when this work is complete, it feels like were close to getting it to work now, i have about 50% of the tests passing, inspecting why a cluster continues to fail.

**Comment by detiber** [comment]
This has now been resolved
/close
