### ISSUE TITLE
Tracking issue for ETCD stall error, CAPI #2591

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-aws#1627]
/kind bug

**What steps did you take and what happened:**

see https://github.com/kubernetes-sigs/cluster-api/issues/2591

Note we don't yet have CAPA evidence of this bug directly.

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
/close

Issues are specific to CAPZ and CAPV.
