### ISSUE TITLE
Conversion webhooks may not actually be active

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1629]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Arising from CAPV testing, I found that the conversion webhooks weren't active because at no point did we call v1alpha2.Infra*.SetupWebhookWithManager.

Same appears to be the case for CAPA.

**What did you expect to happen:**
Conversion webhooks are registered

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.5.0-rc.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
At least for CAPA, it looks like we are doing the webhook scaffolding around SetupWebhookWithManager on the v1alpha3 types vs the v1alpha2 types. This seems to align with the kubebuilder docs.

**Comment by randomvariable** [comment]
In CAPV, that's what I thought, but got errors in kind's api server log. It might be that without actual validation webhooks the server doesn't start, hence slighly hedging my bets with "may"

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/815 is what i've done.

**Comment by detiber** [comment]
Logs from CAPA v0.5.0-rc.1:

> kubectl logs -n capi-webhook-system capa-controller-manager-69d5459f8f-9qw6l -c manager 
I0310 09:49:29.246544       1 listener.go:40] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"="127.0.0.1:8080"
I0310 09:49:29.246924       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineTemplate"}
I0310 09:49:29.246968       1 webhook.go:123] controller-runtime/builder "msg"="Registering a validating webhook"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineTemplate"} "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachinetemplate"
I0310 09:49:29.247000       1 server.go:115] controller-runtime/webhook "msg"="registering webhook"  "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachinetemplate"
I0310 09:49:29.247058       1 server.go:115] controller-runtime/webhook "msg"="registering webhook"  "path"="/convert"
I0310 09:49:29.247435       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{"creationTimestamp":null},"spec":{"template":{"spec":{"ami":{},"cloudInit":{}}}}}
I0310 09:49:29.247461       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineTemplateList"}
I0310 09:49:29.247479       1 webhook.go:113] controller-runtime/builder "msg"="skip registering a validating webhook, admission.Validator interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineTemplateList"}
I0310 09:49:29.247576       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{},"items":null}
I0310 09:49:29.247603       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSCluster"}
I0310 09:49:29.247621       1 webhook.go:113] controller-runtime/builder "msg"="skip registering a validating webhook, admission.Validator interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSCluster"}
I0310 09:49:29.248023       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{"creationTimestamp":null},"spec":{"networkSpec":{"vpc":{}},"controlPlaneEndpoint":{"host":"","port":0},"bastion":{"enabled":false}},"status":{"ready":false,"network":{"apiServerElb":{"attributes":{}}}}}
I0310 09:49:29.248052       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachine"}
I0310 09:49:29.248075       1 webhook.go:123] controller-runtime/builder "msg"="Registering a validating webhook"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachine"} "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachine"
I0310 09:49:29.248091       1 server.go:115] controller-runtime/webhook "msg"="registering webhook"  "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachine"
I0310 09:49:29.248181       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{"creationTimestamp":null},"spec":{"ami":{},"cloudInit":{}},"status":{"ready":false}}
I0310 09:49:29.248201       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineList"}
I0310 09:49:29.248220       1 webhook.go:113] controller-runtime/builder "msg"="skip registering a validating webhook, admission.Validator interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSMachineList"}
I0310 09:49:29.248300       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{},"items":null}
I0310 09:49:29.248321       1 webhook.go:92] controller-runtime/builder "msg"="skip registering a mutating webhook, admission.Defaulter interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSClusterList"}
I0310 09:49:29.248336       1 webhook.go:113] controller-runtime/builder "msg"="skip registering a validating webhook, admission.Validator interface is not implemented"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AWSClusterList"}
I0310 09:49:29.248399       1 webhook.go:141] controller-runtime/builder "msg"="conversion webhook enabled"  "object"={"metadata":{},"items":null}
I0310 09:49:29.248420       1 main.go:231] setup "msg"="starting manager"  
I0310 09:49:29.248801       1 internal.go:356] controller-runtime/manager "msg"="starting metrics server"  "path"="/metrics"
I0310 09:49:29.248801       1 server.go:135] controller-runtime/webhook/webhooks "msg"="starting webhook server"  
I0310 09:49:29.249591       1 certwatcher.go:127] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I0310 09:49:29.249819       1 server.go:176] controller-runtime/webhook "msg"="serving webhook server"  "host"="" "port"=9443
I0310 09:49:29.249835       1 certwatcher.go:83] controller-runtime/certwatcher "msg"="Starting certificate watcher"  

Not sure entirely what is up with the log messages for the conversion webhooks as they are enabled, but it appears that they are enabled.

**Comment by detiber** [comment]
I just verified this against a v0.5.0-rc.1 cluster by passing in the manifests from the `release-0.4` branch, and they were properly converted to v1alpha3 during creation.

**Comment by detiber** [comment]
Closing, since I was able to successfully create a Cluster using the v1alpha2 manifests.

/close

**Comment by randomvariable** [comment]
Got to it before I did, thanks!
