### ISSUE TITLE
Provide documentation of IAM roles

### ISSUE THREAD

**Issue by opowbow** [kubernetes-sigs/cluster-api-provider-aws#1632]
/kind feature

**Describe the solution you'd like**
A list of the IAM roles required to provision a cluster with CAPA

**Anything else you would like to add:**

**Environment:**

**Comment by detiber** [comment]
We don't have documentation around this today, but as a temporary workaround, you could extract the information from the generated cloudformation template that is created by `clusterawsadm alpha bootstrap generate-cloudformation`

**Comment by randomvariable** [comment]
Close. Superseded by #2268
