### ISSUE TITLE
docs/accessing-instances.md is out of date

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1638]
/kind documentation

docs/accessing-instances.md is out of date and needs to be updated for both Session Manager-based access, and bastion access using the new clusterctl workflows.

/priority important-soon
/milestone v0.5.x

**Comment by scottslowe** [comment]
@detiber I can update the docs for access using Session Manager, but I'm not familiar with which `clusterctl` workflows you're referencing. Can you point me in the right direction?

**Comment by detiber** [comment]
@scottslowe it should probably reference the use of `clusterctl create` rather than just `clusterctl`, since `clusterctl` no longer performs the bootstrapping and pivoting phases automatically to create a cluster. This section of the QuickStart is an example of the use of `clusterctl create`: https://cluster-api.sigs.k8s.io/user/quick-start.html#create-your-first-workload-cluster

**Comment by scottslowe** [comment]
OK, I think I have a feel for some of the changes that need to be made. I'm going to take a crack at this.

/assign
