### ISSUE TITLE
userdata should not be compressed

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/cluster-api-provider-aws#1639]
/kind bug

**What steps did you take and what happened:**
I wrote a bootstrap provider for coreos ignition. But I failed to create ec2 instance because user data is gzip compressed and ignition failed to read it.

**What did you expect to happen:**

It's bootstraper's responsibility to decide whether it should compress userdata or not 
**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v0.4.10
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): container linux

**Comment by rudoi** [comment]
Do you have any logs from the instance you can share? It's my understanding that EC2 uncompresses the user data on the way to the host. 

Possibly relevant: https://github.com/coreos/bugs/issues/741

**Comment by MartinForReal** [comment]
Thanks for the quick response! I found the following description from AWS documentation. 

> User data must be base64-encoded. The Amazon EC2 console can perform the base64-encoding for you or accept base64-encoded input.
> User data is limited to 16 KB, in raw form, before it is base64-encoded. The size of a string of length n after base64-encoding is ceil(n/3)*4.
> User data must be base64-decoded when you retrieve it. If you retrieve the data using instance metadata or the console, it's decoded for you automatically.
> User data is treated as opaque data: what you give is what you get back. It is up to the instance to be able to interpret it.
> If you stop an instance, modify its user data, and start the instance, the updated user data is not executed when you start the instance.
you can check this out [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-add-user-data.html)

So from my understanding, it is cloud-init that supports user data in gzip format. [link](https://cloudinit.readthedocs.io/en/latest/topics/format.html) 

I don't think aws provider should interfere with how the toolkit process their user data .
@rudoi How do you think of this idea?

**Comment by MartinForReal** [comment]
related code are as follows:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/40985d540f5805a7f52a4226c076e184465491d0/pkg/cloud/services/ec2/instances.go#L203

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/15da39360ff1d942b39da6fa9d93e08e517bafa1/controllers/awsmachine_controller.go#L491

**Comment by randomvariable** [comment]
Two things:

* We initially gzipped that data to squeeze into the userdata size limit (despite the certs themselves not being compressible).
* The AWS Secrets Manager support, which is now on by default necessarily requires cloud-init at the present moment because Ignition doesn't support multi-part mime documents: https://github.com/coreos/ignition/issues/849. Given that in this instance, the actual userdata is then moved into chunks in each AWS Secrets Manager entry, we now don't strictly need gzipped userdata when Secrets Manager is enabled.

I suspect we would add a field to AWSMachine to optionally disable gzipped userdata for Ignition.

**Comment by MartinForReal** [comment]
Ignition has support for remote config files. I can upload a remote file to a s3 bucket or an HTTP website. 
In my scenario, I upload ignition files to s3 buckets and ignition will download these files at startup. And I think it works well for me. 

> I suspect we would add a field to AWSMachine to optionally disable gzipped user data for Ignition.
I think this will work for me. 

I would like to submit code patches if we both agree.

**Comment by randomvariable** [comment]
Yup, that works. Can you make it an optional field, like "uncompressedUserdata", or some such?

**Comment by MartinForReal** [comment]
/ assign
/ lifecycle active
