### ISSUE TITLE
Support multi-AZ with default AWSCluster configuration

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#1643]
/kind feature

**Describe the solution you'd like**
When a user creates an AWSCluster with the default configuration, we should determine the number of AvailabilityZones available in the chosen region and create a public/private Subnet pair for each available AZ.

This might require modifications to the way that we are currently handling NAT gateways ala #1323 , since us-east-1 has 6 availability zones and will exhaust the default elastic IP quota.

In order to facilitate this, we will also need to add some subnetting logic to the controller to equitably split the vpc cidrBlock. Public subnets should get a much smaller address space than private subnets, possibly a /31, /30, or /29 to give 2, 4, or 8 available addresses for public subnets. Where private subnets should be fitted to the largest cidr block possible for the remaining address space in the vpc cidrBlock

**Anything else you would like to add:**
This would greatly increase UX around deploying HA clusters.

**Comment by benmoss** [comment]
The minimum size for a subnet is `/28`

**Comment by benmoss** [comment]
What would you think about this solution: split the default VPC (10.0.0.0/16) into N+1 subnets, where N is the number of AZs in the region. Then we'd take the first subnet and split that further into N subnets, using each of these for the public subnets.

This would mean for us-east1 (with 6 AZs) we'd get

```
us-east-1a-public: 10.0.0.0/22
us-east-1b-public: 10.0.4.0/22
us-east-1c-public: 10.0.8.0/22
us-east-1d-public: 10.0.12.0/22
us-east-1e-public: 10.0.16.0/22
us-east-1f-public: 10.0.20.0/22
unused: 10.0.24.0/22
unused: 10.0.28.0/22
us-east-1a-private: 10.0.64.0/19
us-east-1b-private: 10.0.96.0/19
us-east-1c-private: 10.0.128.0/19
us-east-1d-private: 10.0.160.0/19
us-east-1e-private: 10.0.192.0/19
us-east-1f-private: 10.0.224.0/19
```

for us-east1 (3 azs) we'd get:

```
us-east-2a-public: 10.0.0.0/20
us-east-2b-public: 10.0.16.0/20
us-east-2c-public: 10.0.32.0/20
unused: 10.0.48.0/20
us-east-2a-private: 10.0.64.0/18
us-east-2b-private: 10.0.128.0/18
us-east-2c-private: 10.0.192.0/18
```

**Comment by benmoss** [comment]
I am also wondering if this change forces us to implement cleanup for subnets that already exist, for the sake of upgrading clusters to this new layout

**Comment by detiber** [comment]
The proposal for splitting up the subnets sounds good to me.

I'm not sure we should worry about handling any cleanup for pre-existing subnets, but we'd likely want to retain some type of backward compatibility for existing clusters with the original subnet configuration.

I think that todo might be from when we stored subnet information in status vs spec.

**Comment by benmoss** [comment]
Do we want to name the subnets now like `$clustername-1a-public`? Right now they'll be `$clustername-{public,private}`.

**Comment by detiber** [comment]
I think `$clustername-$az_suffix-{public,private}` should work, where az_suffix is [a,b,c,...]. I don't think there is any need to encode the region suffix in there as well.

**Comment by benmoss** [comment]
The pre-existing subnets situation causes this to get a little trickier than I anticipated. Can I get some advice on how to handle these situations?

- One subnet exists on the spec and/or in EC2, but it's one of the old defaults. Trying to merge the new layout and the old layout is going to require a bunch of extra logic. Deleting it and just creating the new layout seems like the simpler choice. That assumes it's *possible* to delete it though, not sure how feasible that'll be in practice.
- Both old default subnets exist. I think we want to just leave them alone and leave them in the old layout, but worth confirming.

**Comment by detiber** [comment]
We can't really delete the subnet out from under folks, since it will be in use with existing instances that comprise the control plane for the cluster.

**Comment by benmoss** [comment]
Well I was thinking that the only way you'd get into situation 1 would be if something interrupted the CAPA controller, since otherwise it should have two

**Comment by benmoss** [comment]
- we want to keep reconciling the old subnet patterns if they exist in the cluster
- create one NAT gateway per public subnet, which will break on us-east1 for now
- if user brings their own VPC, don't create any subnets. this is a behavior change, we used to check if they had any public subnets or any private subnets and create them from our defaults if either are missing.
- open question if subnets that are ec2-classic will be returned by the API if a user has them enabled, we should try to filter them out

**Comment by randomvariable** [comment]
BTW, there was an early implementation of subnetting in https://github.com/kubernetes-sigs/cluster-api/pull/503 which we ultimately didn't use. Was originally going to create `/17` VPCs, with subnets of `/19`, which was a tradeoff between keeping the ELB service happy and minimising CIDR space when people wanted to use things like DirectConnect or VPNs.

**Comment by benmoss** [comment]
So I started with this very nice clean implementation of splitting up the subnets [here](https://github.com/benmoss/cluster-api-provider-aws/blob/1a7180d49cd871327a38d01039b292b3c5efc151/internal/subnet/subnet.go).

Several COVID years later I emerge with [this mess](https://github.com/benmoss/cluster-api-provider-aws/blob/a3157261292b40373902a08188c68f11fe6c717e/internal/subnet/subnet.go) that works but is probably incomprehensible, unmaintainable and super inefficient.

Maybe someone else more qualified at this wants to take a shot? Maybe I am overcomplicating the problem by trying to solve the preexisting subnet problem generically? I can't think of how even if we take it as a given that our preexisting subnets are determinate we can make it simpler, but subnet bit math is perhaps not my forté.

**Comment by detiber** [comment]
@benmoss thanks for the work you've done on this so far. I was made aware of another potential complication that we'll need to address if we change from using ELB Classic like we do today to using an NLB, so we'll probably want to revisit this with that in mind once things have slowed down a bit.

**Comment by richardcase** [comment]
I've been looking at the subnet logic as part of #1534 as EKS requires at least 2 subnets in different AZs. 

The logic i have used  is slightly different to whats described above in that it splits the VPC CIDR into equal parts. And to make the implementation easier the number of parts is a power of 2.

**Comment by richardcase** [comment]
I played around with the function i used and the 6 AZs and i output:

```bash
Subnet (Public) 0 - 10.0.0.0/22
Subnet (Public) 1 - 10.0.4.0/22
Subnet (Public) 2 - 10.0.8.0/22
Subnet (Public) 3 - 10.0.12.0/22
Subnet (Public) 4 - 10.0.16.0/22
Subnet (Public) 5 - 10.0.20.0/22
Subnet (Private) 0 - 10.0.32.0/19
Subnet (Private) 1 - 10.0.64.0/19
Subnet (Private) 2 - 10.0.96.0/19
Subnet (Private) 3 - 10.0.128.0/19
Subnet (Private) 4 - 10.0.160.0/19
Subnet (Private) 5 - 10.0.192.0/19
```
(there will be some unused addresses due to the power of 2 logic)
