### ISSUE TITLE
Customizable image lookup format

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1644]
/kind feature

**Describe the solution you'd like**
As a Kubernetes distribution maintainer, I would like to be able to customize the image lookup format so that I can still use the image lookup mechanism even if my image names don't match the current hard-coded format.

**Anything else you would like to add:**
We should ideally come up with a way to have this configured globally for a single CAPA deployment.

**Comment by bagnaram** [comment]
Is this referring to the AMI image `capa-ami-%s-?%s-*` default lookup by instance creation?

**Comment by detiber** [comment]
@bagnaram yes that is correct.
