### ISSUE TITLE
Reconciling a cluster after manually deleting resources in AWS console broken

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#165]
/kind bug

**What steps did you take and what happened:**
Manually deleting the VPC (or other components) in ec2 causes the cluster reconciliation to break

**What did you expect to happen:**
The cluster actuator should either throw a non-retryable error (setting ErrorMessage/ErrorReason on the cluster status) or re-create the missing resources.

Current workaround is to edit the cluster object and cleanup the status to allow for the actuator to recreate the resources.

**Comment by vincepri** [comment]
- [ ] VPC
- [ ] Subnets
- [ ] Internet Gateway
- [ ] NAT Gateway
- [ ] Routing Tables
- [ ] Routes
- [ ] Security groups

**Comment by vincepri** [comment]
I went through each resource and they seem to be recreated appropriately on reconcile.
Feel free to reopen if the issue happens again.
/close
