### ISSUE TITLE
Cluster failed to describe VPCs

### ISSUE THREAD

**Issue by bluefriday** [kubernetes-sigs/cluster-api-provider-aws#1652]
/kind bug

**What steps did you take and what happened:**
I'm new at cluster-api-provider-aws. 
I converted my local exist k8s cluster to management cluster (follow : quick start.)
But failed to run cluster.yaml (below my controller-manager log)
I think it is network issue. but I'm not sure..

Please help me any advice. thanks.

**What did you expect to happen:**
Cluster running on workload successfully.

**Anything else you would like to add:**
-

**Environment:**
```
NAME                                       PHASE
cluster.cluster.x-k8s.io/capi-quickstart   Provisioning

NAME                                                         CLUSTER           READY   VPC   BASTION IP
awscluster.infrastructure.cluster.x-k8s.io/capi-quickstart   capi-quickstart

NAME                                                      PHASE       REPLICAS   AVAILABLE   READY
machinedeployment.cluster.x-k8s.io/capi-quickstart-md-0   ScalingUp   1

NAME                                                             PROVIDERID   PHASE
machine.cluster.x-k8s.io/capi-quickstart-md-0-75648fff48-2bln4                Pending

```

```
$ kubectl logs -f -n capa-system capa-controller-manager manager


E0319 08:16:22.943701       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster default/capi-quickstart: failed to describe VPCs: failed to query ec2 for VPCs: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 10.96.0.10:53: server misbehaving"  "controller"="awscluster" "request"={"Namespace":"default","Name":"capi-quickstart"}
I0319 08:16:22.943966       1 awscluster_controller.go:138] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="capi-quickstart" "cluster"="capi-quickstart" "namespace"="default"
```

- Cluster-api-provider-aws version: AWS Provider v1alpha3 (v0.5)
- Kubernetes version: (use `kubectl version`): 1.17.0
- OS (e.g. from `/etc/os-release`): Centos7

**Comment by detiber** [comment]
@bluefriday did you run `clusterawsadm alpha bootstrap create-stack`? It looks like the quickstart doesn't make it overly clear that it is a required step, but it is listed in the linked pre-requisites doc: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/prerequisites.md

**Comment by detiber** [comment]
I filed https://github.com/kubernetes-sigs/cluster-api/issues/2721 to improve the the quickstart docs around the missing step.

**Comment by bluefriday** [comment]
> @bluefriday did you run `clusterawsadm alpha bootstrap create-stack`? It looks like the quickstart doesn't make it overly clear that it is a required step, but it is listed in the linked pre-requisites doc: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/prerequisites.md

@detiber 
Yes I already ran command 'clusterawsadm alpha bootstrap create-stack'
this command listed resources in the stack.. but still not work.

I tried for using v0.5.2(clusterawsadm)  and v0.3.3(clusterctl). but same result.

**Comment by bluefriday** [comment]
> @bluefriday is this still an issue?
> 
> Based on the logs you provided:
> 
> ```
> E0319 08:16:22.943701       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster default/capi-quickstart: failed to describe VPCs: failed to query ec2 for VPCs: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 10.96.0.10:53: server misbehaving"  "controller"="awscluster" "request"={"Namespace":"default","Name":"capi-quickstart"}
> ```
> 
> The "server misbehaving" part of the error message makes me wonder if it's either hitting a transient AWS issue or maybe there is something odd going on related to dns or proxy configuration.

@detiber Thanks you!! As you said to me, It was my local proxy server issues.
I'll close this issue.
