### ISSUE TITLE
Use naive TCP instead of SSL for ELB health checks

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-aws#1657]
/kind bug

**What steps did you take and what happened:**

I ran ELB's with apiserver arguments which include a small set of cipher's not in the AWS 2016 defaults

What happened --- the ELBs never send traffic to apiservers, which means kubelets never register their static pods, and scheduler/kcm never get to start doing anything - so you just have an orphan API Server talking to ETCD, and cluster is effectively dead.

**What did you expect to happen:**

ELBs to happily handshake with my apiserver and forward traffic along.

**Environment:**

- Cluster-api-provider-aws version: v1alpha3 (.4)
- Kubernetes version: (use `kubectl version`): 1.17 
- OS (e.g. from `/etc/os-release`): any

**Comment by detiber** [comment]
/close
Closing, since this would cause log spamming related to the health checks. Longer term we want to explore migrating over to using an NLB for the load balancer, but there are other challenges that we need to solve related to handling in hairpinning before we can make that switch.

**Comment by seh** [comment]
> Longer term we want to explore migrating over to using an NLB for the load balancer, but there are other challenges that we need to solve related to handling in hairpinning before we can make that switch.

@detiber, is there an issue tracking this potential move to using an NLB?

**Comment by detiber** [comment]
@seh https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1484 is probably the closest issue we have for supporting NLBs

**Comment by Ankitasw** [comment]
@sedefsavas just to clarify, we have not changed the scope of this issue right, we want classic ELB health check to use TCP instead of SSL, that's all?
