### ISSUE TITLE
Support selection/limiting of private subnets to use for control plane replicas

### ISSUE THREAD

**Issue by stevenolen** [kubernetes-sigs/cluster-api-provider-aws#1659]
/kind feature

**Describe the solution you'd like**
The ability to select or limit the acceptable private subnets and/or failure domains where kubeadm control plane instances may be placed.

**Anything else you would like to add:**
The current behavior results in _any_ private subnet within a vpc being selected for control plane instances. In my vpc environment there are 5 availability zones with private subnets in each, but it is preferred to only place control plane instances in 3 of those 5. This is particularly difficult since my account's `us-east-1e` availability zone does not support newer instance types, and so setting my control plane instance type to `c5.xlarge` (or any c5-family instance) results in randomly being unable to start a 3rd instance if a `us-east-1e` subnet is selected for a control plane instance placement.

**Environment:**

- Cluster-api-provider-aws version: `v0.5.1`
- Kubernetes version: (use `kubectl version`): `1.15`
- OS (e.g. from `/etc/os-release`): `ubuntu 18.04`

**Comment by ncdc** [comment]
@vincepri and I had previously talked about one possibility: using tags in AWS on the subnets to indicate which ones you want to use for the control plane / failure domains.

**Comment by stevenolen** [comment]
that would definitely work in my case!

**Comment by detiber** [comment]
Tags are definitely an option, but I think I'd like to keep a more explicit option available as well, since in some environments it may be difficult to have pre-existing subnets modified to add tags for our use.

**Comment by andrewmyhre** [comment]
In our case we can't tag subnets, so we'd prefer to be able to specify the subnets to be used in the `AWSCluster.Spec.NetworkSpec.Subnets` and have the subnets reconciliation phase filter to just those specified. Like this: https://github.com/andrewmyhre/cluster-api-provider-aws/commit/e23bd3873d765d280fefbd84d1c3aa209c524469

**Comment by stevenolen** [comment]
for what it's worth -- I'm running 0.6.4 now and this appears to be no longer applicable. AWSCluster's `spec.networkSpec.subnets` is used in control plane node placement!
