### ISSUE TITLE
Default resync period of 10 minutes appears to actually be 20 minutes?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1660]
/kind bug

**What steps did you take and what happened:**
1. Deploy CAPA (don't change the default `--sync-period` value)
1. Create a Cluster/AWSCluster/Machine/AWSMachine
1. Resyncs appear to happen every ~20 minutes

**What did you expect to happen:**
1. Resyncs happen every ~10 minutes

**Anything else you would like to add:**
Scratching my head on this one...

**Environment:**

- Cluster-api-provider-aws version: v0.5.1

**Comment by ncdc** [comment]
/assign @detiber 
mind looking at this, or delegating?

**Comment by detiber** [comment]
Yes, I will dig into this further

**Comment by detiber** [comment]
Closing, since we don't seem to be able to reproduce. Please re-open if the issue persists.
/close
