### ISSUE TITLE
AWSMachine controller sometimes (albeit rarely) appears to be reading stale cached Cluster data

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1661]
/kind bug

**What steps did you take and what happened:**
1. Use `clusterctl` to create an AWS cluster
1. Use `clusterctl` to move everything into the new AWS cluster
1. The AWSMachines in the new AWS cluster remain "not ready" until the next full resync

**What did you expect to happen:**
1. The AWSMachines should update to ready quickly (almost immediately), because all the infra is already provisioned, running, and ready.

**Anything else you would like to add:**
This is what's getting tripped up:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a33342eeb2fb0e0682ba6bf90745df1954a458c5/controllers/awsmachine_controller.go#L343-L345

The most recent time I saw this, I'm almost 100% certain that the AWSCluster was ready and the Cluster's InfrastructureReady field was also true. There's a chance I misread one of the data points, but I'm pretty sure this was the case. The CAPA pod log repeatedly logged that the cluster infra wasn't ready, and then eventually stopped. After waiting for a resync (~18 minutes), it then processed everything correctly and everything was marked ready.

As an aside, and not that this would necessarily help, but maybe we should check the AWSCluster's ready field, instead of the Cluster's infra ready field?

**Environment:**

- Cluster-api-provider-aws version: v0.5.1

**Comment by detiber** [comment]
Can't appear to reproduce, closing
/close
