### ISSUE TITLE
Allow AWSIAMUserBootstrapper to be disabled during bootstrap create-stack

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1664]
/kind feature

**Describe the solution you'd like**
Certain enterprise environments do not allow the creation of AWS::IAM::User, instead asking for the bootstrapping process to be conducted from an EC2 instance with the necessary roles applied to it.  Additionally, the user is **only** required for the bootstrapping process, and could be safely deleted afterwards.  By separating the lifecycle of the IAM User from the rest of the roles, we could safely create and destroy the user separately, or even opt for an installation process that never used the user in the first place.

**Anything else you would like to add:**
Possibly update the documentation to reflect deleting or disabling the access keys after the initialization of the management cluster.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
I think it might be worth it to consider splitting out the bootstrap user creation to a separate step, that way the stack doesn't need to be modified for disabling the user.

**Comment by ncdc** [comment]
@randomvariable we can close this with the clusterawsadmv2 work, right?

**Comment by randomvariable** [comment]
Yes! I missed some of the issues in the mop up, thanks!
/close
