### ISSUE TITLE
Improve Validation around fields that are passed in as AWS API parameters

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1668]
/kind bug

Create AWSCluster with following:
```
# Note the tab character at the end
    sshKeyName: cluster-api-provider-aws\t
```

Receive the following issues:
```
capa-controller-manager-77868584f-pc776 manager E0327 14:11:12.959129       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run instance: InvalidParameterValue: Invalid value 'cluster-api-provider-aws\t' for keyPairNames. Text is not in valid ISO 8859-1 (Latin 1) encoding\n\tstatus code: 400, request id: cbe7897a-ece5-4eef-9695-a7741f87e90e"  "controller"="awsmachine" "request"={"Namespace":"default","Name":"east-control-plane-vzsm2"}
```

**What did you expect to happen:**
Would prefer better feedback in the admission webhook stating that `sshKeyName` contains invalid characters.

**Anything else you would like to add:**
AWS Documentation is wrong, and they should feel bad.

**Environment:**

- Cluster-api-provider-aws version: `v0.5.1`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by evalsocket** [comment]
@detiber can this assign to me ? if no one is working on it ?

**Comment by detiber** [comment]
@alexander-demichev Are you still working on this, or can I re-assign to @evalsocket?

**Comment by alexander-demichev** [comment]
feel free to take it

**Comment by ncdc** [comment]
@evalsocket have you started working on this?

**Comment by evalsocket** [comment]
Yes
