### ISSUE TITLE
Failed to Create clusterctl inventory CRDs component

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/cluster-api-provider-aws#1676]
/kind bug

**What steps did you take and what happened:**

Followed the Quickstart in the docs line by line exactly and I got this error when running: 
`clusterctl init --infrastructure aws`

> Error: action failed after 10 attempts: failed to create clusterctl inventory CRDs component: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition, /providers.clusterctl.cluster.x-k8s.io: n
o matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1

However the following did work out:
`clusterawsadm alpha bootstrap create-stack`

I have no idea how to debug this? Not much errors or logs to work with . . .

**What did you expect to happen:**

I expected to see the output the Quickstart said I would see. 

**Anything else you would like to add:**

I am using an EKS instance which only has a few things installed. Pretty new from a few days ago. 

**Environment:**

- Cluster-api-provider-aws version: 

> clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.3", GitCommit:"ecff70af1b839c4086335234d88b1b8c00c3383c", GitTreeState:"clean", BuildDate:"2020-03-27T22:25:55Z", GoVe
rsion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}

- Kubernetes version: (use `kubectl version`): 

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersi
on:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:
54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): 

> MacOS Catalina 10.15.4

**Comment by detiber** [comment]
@kferrone The management cluster must be at least Kubernetes v1.16.

@vincepri We should probably make this more clear in the QuickStart

@fabriziopandini we should also probably add a validation step in `clusterctl` for this as well.

**Comment by kferrone** [comment]
Oh, bummer. This means this project will not work for EKS as 1.15 is the highest version offered as far as I know.

**Comment by kferrone** [comment]
Looks like lot's of peeps are waiting for EKS to support v1.16
[[EKS]: Support for Kubernetes 1.16](https://github.com/aws/containers-roadmap/issues/487)

**Comment by fabriziopandini** [comment]
the validation step in clusterctl  just merged
https://github.com/kubernetes-sigs/cluster-api/pull/2842

**Comment by detiber** [comment]
Now that kubernetes-sigs/cluster-api#2842, closing since v1.16 is a requirement for the management cluster.
/close
