### ISSUE TITLE
Consider reflecting VPC DHCP dns options in machine status DNS addresses

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#1691]
/kind bug

**What steps did you take and what happened:**
Have a VPC with custom DNS DHCP options, e.g domainName `agl.com` https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html

Machine addresses do not reflect this additional DNS addresses as the node would do via the controller manager cloud provider 
https://github.com/kubernetes/kubernetes/blob/6b13befdfb3e30862dc86fd1c7739f58901f0bae/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1400-L1479:
Node:
```
status:
  addresses:
  - address: 10.0.137.6
    type: InternalIP
  - address: ip-10-0-137-6.agl.com
    type: Hostname
  - address: ip-10-0-137-6.agl.com
    type: InternalDNS

```

**What did you expect to happen:**
We might want to consider honour this source, include the additional DNS addresses and be more consistent with cloud provider.

Accessing the metadata though would require to run the aws machine controller pod in the host network. Alternatively we could consider infer this information from the regular aws API and construct the ips known format, the likes of:

```
	vpc, err := r.awsClient.DescribeVpcs(&ec2.DescribeVpcsInput{
		VpcIds: []*string{newestInstance.VpcId},
	})
	if err != nil {
		return err
	}

	dhcp, err := r.awsClient.DescribeDHCPOptions(&ec2.DescribeDhcpOptionsInput{
		DhcpOptionsIds: []*string{vpc.Vpcs[0].DhcpOptionsId},
	})
	if err != nil {
		return err
	}

	klog.Infof("DHCP %+v", dhcp.DhcpOptions[0].DhcpConfigurations[0])
	for _, i := range dhcp.DhcpOptions[0].DhcpConfigurations {
		if *i.Key == "domain-name" {
			klog.Infof("Domain value %v", i.Values)
		}
	}
        // construct additional DNS addresses
```

**Anything else you would like to add:**
At some point having DHCP options awareness and reflecting it on the machine.status addresses might come in handy for scenarios where users wanting to adopt pre-existing vpcs.

Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/70#issuecomment-614057170

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
@enxebre this is ancient now, do we want to get this in for v1alpha4?

**Comment by enxebre** [comment]
Closing this due to age
/close

**Comment by ron1** [comment]
@enxebre Would it make sense to re-open this issue now that it appears a fix is in development?

**Comment by jparrill** [comment]
Hey @enxebre, @ron1 I've fixed this Issue in this PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4841. could we close this?

**Comment by enxebre** [comment]
/closed
by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4841
