### ISSUE TITLE
API for CloudFormation generation and application

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1699]
/kind feature

### Describe the solution you'd like

clusterawsadm was introduced as a kind of quick start tool to get started with CAPA with the correct AWS permissions.

It is however the canonical source of permissions CAPA uses to access AWS resources, but is not necessarily the easiest to consume in a programmatic fashion.

Options have been added ad-hoc to support an increasing number of use cases to deal with the lack of initial flexibility designed into it.

The idea here is to provide an API that allows downstream consumers to be able to consume clusterawsadm programatically and keep in lockstep with changes with CAPA.

## Requirements

* Provide a consumable API for generating and applying the CAPA CloudFormation template
* Retain idempotent application of the CF template
* Allow a consumer to "version" the template and roles
* Allow a consumer to disable components they might not need
* Support multiple AWS partitions (Govcloud, China, Secret etc...)
* Allow for a customisable IAM role prefix

## CLI

For the following subcommands of `clusterawsadm alpha bootstrap`:
- generate-cloudformation
- generate-iam-policy-docs
- create-stack

Deprecate current set of flags. 

Add a new `--config` flag that takes a file input of the following type:

```yaml
kind: IAMConfiguration
version: infrastructure.cluster.x-k8s.io/v1alpha3
spec: <see below>
```
with the following spec:

``` go
type AWSIAMConfigurationSpec struct {
  // AccountID is the AWS Account ID for which a CloudFormation template can be generated
  AccountID string
  // Partition is the AWS-wide partition in which this account exists.
  Partition string // default: aws
  // NameSuffix will be appended to every IAM role, user and policy created by clusterawsadm
  NameSuffix string // default: ".cluster-api-provider-aws.sigs.k8s.io"
  // ControlPlane represents the IAM role for control plane instances
  ControlPlane AWSIAMControlPlaneSpec
  // Node represents the IAM role for 
  Nodes AWSInstanceProfileSpec
  BootstrapUser AWSInstanceProfileSpec
}

type AWSIAMUserSpec struct {
  // If disabled, the IAM user will not be created
  Enable bool // default: false
  // Allows the user name to be customised. NameSuffix will be ignored
  UserName string // defaulted for the specific case
  // ExtraPolicyAttachments is a list of additional policies to be attached to the IAM role
  ExtraPolicyAttachments []string
  // Extra groups is a list of groups to add this user to.
  ExtraGroups []string
  // ExtraStatements are additional IAM statements to be included inline for the user.
  ExtraStatements []iam.StatementEntry
}

type AWSIAMControlPlaneSpec struct {
  AWSInstanceProfileSpec
  // AttachCAPAControllerPolicy controls whether or not the policy that enables Cluster API Provider AWS will also be attached to the control plane role
  AttachCAPAControllerPolicy bool // default: true
}

type AWSInstanceProfileSpec struct {
  // Enable controls whether or not the policy, role and instance profile will be created
  Enable bool // default: true
  // ExtraPolicyAttachments is a list of additional policies to be attached to the IAM role
  ExtraPolicyAttachments []string
  // ExtraStatements are additional IAM statements to be included inline for the role.
  ExtraStatements []iam.StatementEntry
  // CloudProvider controls whether or not the CPI policy will be attached, only generated or not included at all.
  CloudProvider string // enum of [ "attached", "generate-only", "none" ]
  // PolicyName allows the individual policy name to be customised NameSuffix will be ignored.
  PolicyName string  // defaulted for the specific case
  // RoleName allows the individual Role Name to be customised. NameSuffix will be ignored.
  RoleName string  // defaulted for the specific case
  // TrustPolicy allows the consumer to specify the trust policy document required for role assumption scenarios.
  TrustPolicy iam.PolicyDocument
}

```

The types will exist under `api/v1alpha3/iam` (could also be `cmd/clusterawsadm/api/v1alpha3`). controller-gen will not generate a CRD from this directory.

Generator functions will be created for these structs, defaulting them in a `.New()` function.

`pkg/cloud/services` will become a managed package with maintained interfaces (open to suggestions on a different location).

Logic in `cmd/clusterawsadm/cmd/alpha/bootstrap`  will be moved into `pkg/cloud/services` and wrapped in the CLI as needed.

/assign
/lifecycle active
/priority important-soon

**Comment by ncdc** [comment]
A few comments:

- If you want to default a boolean to true, it needs to be a `*bool` so you can distinguish between unset and false. We may want to examine each boolean field and decide about positive vs. negative language (e.g. enable vs disable).

- I see you have NameSuffix - any use for NamePrefix?
