### ISSUE TITLE
DNS resolution should take host operating system into account

### ISSUE THREAD

**Issue by katiekeel** [kubernetes-sigs/cluster-api-provider-aws#1700]
/kind bug

**What steps did you take and what happened:**
I was following the [Quick Start Guide](https://cluster-api.sigs.k8s.io/user/quick-start.html) and my cluster was hanging right after the `Apply the workload cluster` step. After running `kubectl apply -f capi-quickstart.yaml`, my cluster remained in the `Provisioning` phase.

```
$ kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioning
$ kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            READY   INITIALIZED   REPLICAS   READY REPLICAS   UPDATED REPLICAS   UNAVAILABLE REPLICAS
default     capi-quickstart-control-plane  
```

I went to investigate and noticed the `capa-controller-manager` pod was showing the same error loop in its logs:

```
capa-controller-manager-599ccd4476-w586h manager I0424 19:49:57.794993       1 awsmachine_controller.go:355] controllers/AWSMachine "msg"="Reconciling AWSMachine" "awsCluster"="capi-quickstart" "awsMachine"="capi-quickstart-md-0-99x84" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-75648fff48-6nvf8" "namespace"="default"

capa-controller-manager-599ccd4476-w586h manager I0424 19:49:57.795170       1 awsmachine_controller.go:379] controllers/AWSMachine "msg"="Cluster infrastructure is not ready yet" "awsCluster"="capi-quickstart" "awsMachine"="capi-quickstart-md-0-99x84" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-75648fff48-6nvf8" "namespace"="default"

capa-controller-manager-599ccd4476-w586h manager I0424 19:49:59.424214       1 awscluster_controller.go:175] controllers/AWSCluster "msg"="Waiting on API server ELB DNS name to resolve" "awsCluster"="capi-quickstart" "cluster"="capi-quickstart" "namespace"="default"

capa-controller-manager-599ccd4476-w586h manager E0424 19:49:59.465705       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="AWSCluster.infrastructure.cluster.x-k8s.io \"capi-quickstart\" is invalid: status.ready: Required value"  "controller"="awscluster" "request"={"Namespace":"default","Name":"capi-quickstart"}
```

I googled the `Waiting on API server ELB DNS name to resolve` error and it led me to [this line](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L175) in the provider code.

So I went to my AWS console and my ELB had indeed been created with queryable DNS. `dig` in my terminal on it produced the expected result of its IP address. 

Then I did some research and found [this in the Go docs](https://golang.org/pkg/net/#hdr-Name_Resolution):

```
By default the pure Go resolver is used, because a blocked DNS request consumes only a goroutine, while a blocked C call consumes an operating system thread. When cgo is available, the cgo-based resolver is used instead under a variety of conditions: **on systems that do not let programs make direct DNS requests (OS X)**, when the LOCALDOMAIN environment variable is present (even if empty) ... The resolver decision can be overridden by setting the netdns value of the GODEBUG environment variable (see package runtime) to go or cgo, as in:

export GODEBUG=netdns=go    # force pure Go resolver
export GODEBUG=netdns=cgo   # force cgo resolver:
``` 

Then I created [this simple script](https://play.golang.org/p/wvtNXYQzZol) to test the behavior of `LookupIP` outside of the cluster-api context.

And as per the docs, it failed with the pure go resolver: 

```
$ export GODEBUG=netdns=go
$ go run godns.go
[]
lookup capi-quickstart-apiserver-1524711131.us-east-1.elb.amazonaws.com on 10.167.0.1:53: no such host
```

But succeeded with the cgo resolver:

```
$ export GODEBUG=netdns=cgo
$ go run godns.go
[3.230.41.137]
<nil>
```

I'm not a Go expert but I can't imagine it would be that hard to force the cgo resolver, or simply put in a conditional to test for OS X.

**What did you expect to happen:**

For the workload cluster to spin up successfully :)

**Environment:**

- Cluster-api-provider-aws version: 0.5.2
- Kubernetes version: (use `kubectl version`): 1.14.9
- OS (e.g. from `/etc/os-release`): Mac OS X Catalina 10.15.4

**Comment by vincepri** [comment]
Interesting, I have also used this workflow before but it worked properly 🤔 

@katiekeel was your controller running outside of a container? I'm not sure if this problem is actually OS-related, or more of a networking configuration

**Comment by katiekeel** [comment]
@vincepri Nope, unless I'm misunderstanding your question, the logs I posted for `capi-controller-manager` were indeed in the normal container that Cluster API spins up.

**Comment by vincepri** [comment]
Got it, thanks for the confirmation — in that case if everything was running in a container, I'd double check the network configuration on the host machine.

**Comment by bagnaram** [comment]
@katiekeel  I am curious if there are any unsupported configurations in your `/etc/resov.conf` that would cause the go resolver to tailspin? Based on the response of `10.167.0.1:53` being the AWS DNS provided by the subnet is this the command that worked for you?
`dig capi-quickstart-apiserver-1524711131.us-east-1.elb.amazonaws.com @10.167.0.1`
