### ISSUE TITLE
Move e2e tests to clusterctl framework

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1701]
With the introduction of the new clusterctl test framework, we should draw a plan of action and publish a gap-analysis of the current e2e tests CAPA has today, and how we can port them to the new framework.

/kind cleanup
/assign @gab-satchi 
/cc @fabriziopandini @detiber

**Comment by fabriziopandini** [comment]
Happy to help if required!
FYI https://github.com/kubernetes-sigs/cluster-api/pull/2943 has an example of E2E config file for AWS

**Comment by vincepri** [comment]
/milestone v0.5.4

/lifecycle active
for @gab-satchi

**Comment by gab-satchi** [comment]
- [x] Gap analysis - [gdoc](https://docs.google.com/spreadsheets/d/1PD6qFljm0G46h4OQKIii2plQEUhBJ9xfm40l6T7Uixw/edit#gid=0)
- [x] Port CAPA e2e tests over to new e2e flow (1 to start)- PR #1716 
- [ ]  CAPA CI script and CI config
- [ ]  test-infra prow job for new e2e tests
- [ ]  Move all e2e tests to use new framework
- [ ]  Remove old CAPA e2e package
- [ ]  Switch prow to use new job as main e2e
