### ISSUE TITLE
Stopping a bastion instance from the AWS console results in CAPA creating a second bastion instance

### ISSUE THREAD

**Issue by ashoksekar07** [kubernetes-sigs/cluster-api-provider-aws#1703]
/kind bug

**What steps did you take and what happened:**
Create a cluster using CAPA. Go to AWS console and stop the bastion instance.

**What did you expect to happen:**
CAPA should reconcile this bastion instance and start it again. Or create a new one and delete the existing instance.

But CAPA left the old instance as such and created a new instance which I don't think is the ideal behavior.

**Environment:**

- Cluster-api-provider-aws version: 0.4.10
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):  Amazon Linux 2

**Comment by vincepri** [comment]
This has been fixed on master, should be good to close

**Comment by bagnaram** [comment]
I was looking through master, and I saw a TODO section https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/bastion.go#L79

I was thinking of adding the ability to rectify between the status and the instance, in regards to powering it up and so on.

**Comment by vincepri** [comment]
@bagnaram The fix I mentioned is in https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/ce642e8a40a67d43810972b8fbe7a4a2223773c6

**Comment by bagnaram** [comment]
I assumed it would power back based on the contents of this issue. Anyhow, the filter is addressed in that patch

**Comment by vincepri** [comment]
Going to close this for now given that it has been fixed.

@ashoksekar07 can you re-evaluate using the master image?

/close
