### ISSUE TITLE
Allow Specifying Internal Subnets for Control Plane 

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1715]
/kind feature

As a `controlPlaneLoadBalancer` with a `scheme` set to `internal` I would like to be able to specify which subnets that load balancer goes into, because there are security controls expecting it to go into certain subnets.

**Describe the solution you'd like**
Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1714 it's currently just looping through the internal subnets, I'd like to be able to map it intentionally.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by bagnaram** [comment]
I believe in unmanaged mode you can specify the subnets intentionally in the `awscluster.spec.networkSpec.subnets`

**Comment by voor** [comment]
@bagnaram That might fit the use case -- are you saying that if you specify the VPC ID you can specify a subset of subnets to use?  @scottslowe made it seem like if you specify a VPC ID it'll ignore the subnets and populate it automatically.

**Comment by scottslowe** [comment]
@voor @bagnaram It is my understanding (based on conversations I had while creating the content for #1560) that a) the list of subnets isn't required when operating in unmanaged mode, *and* b) you can't "constrain" CAPA to use only a subset of the subnets by providing the list (it will use all discovered subnets regardless of what you provide).

**Comment by voor** [comment]
Just want to confirm that specifying the VPC ID will overwrite and otherwise ignore whatever is in the subnet section.  If you try to set something as `isPublic` for example, it'll just overwrite it with the actual state of the world.

**Comment by scottslowe** [comment]
@voor That is my understanding, yes, although I have not specifically tested the behavior.

**Comment by randomvariable** [comment]
Fixed in #1931
