### ISSUE TITLE
Implement AWSMachinePools using ASG

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-aws#1722]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Implement AWSMachinePool using [Auto Scaling Group](https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroup.html). The AWSMachinePool implementation should follow the same package / group structure as CAPI and be added to the `exp` package, the experimental feature package. The feature should be gated using the `MachinePool` flag used in CAPI.

See also: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/483 and [CAPI Machine Pool Proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190919-machinepool-api.md)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by krmayankk** [comment]
@gab-satchi  are you working on this already or plan to work on it ? when can we get this feature ?

**Comment by rudoi** [comment]
We're actually working on this currently as part of adding EKS Support (it should still work with the Kubeadm provider).

**Comment by randomvariable** [comment]
Fixed in #1860
