### ISSUE TITLE
Allow clusters to be created when named starting sg-

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1725]
/kind bug

**What steps did you take and what happened:**
Create a cluster with the prefix `sg-`

The controller will fail with the following error:
```
1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster default/sg-cluster: failed to create security group \"bastion\" in vpc \"vpc-0db5779f71b3ed663\": InvalidParameterValue: Value (sg-cluster-bastion) for parameter GroupName is invalid. Group names may not be in the format sg-.\n\tstatus code: 400, request id: 525f5d67-7926-42f0-931e-0def5cab93da"  "controller"="awscluster" "request"={"Namespace":"default","Name":"sg-cluster"}*
```

**What did you expect to happen:**
The cluster gets created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The restriction is listed in API docs at https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSecurityGroup.html

**Environment:**

- Cluster-api-provider-aws version: 0.5.3
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by sethp-nr** [comment]
I have no objection to changing the name going forward, but I do wonder what we should do with existing clusters?

**Comment by randomvariable** [comment]
If existing clusters had their names reconciled, would this be an issue?

If so, we could special case only the `sg-` name.

**Comment by detiber** [comment]
+1 to special casing `sg-`, since any clusters that would exist with that prefix would be failed clusters that would now finish provisioning with the update and existing functional clusters wouldn't be affected.

**Comment by sethp-nr** [comment]
As far as I know, it's not possible to change the name of a security group. The reconcile would have to be something like "create new, assign to all the right places, drop old" – which could run into trouble around limits, multiple ENIs, etc.

Special-casing seems like the way to go, IMO.
