### ISSUE TITLE
[RFE] Multi-AZ MachineDeployment

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api-provider-aws#1727]
/kind feature

**Describe the solution you'd like**

As a user, I would like a way to opt-in to some kind of automatic AZ allocation strategy for my Machines so I can avoid managing them 1:1 per AZ.

**Anything else you would like to add:**

As discussed in the CAPA meeting today, there are quite a few wrinkles here around latency, EBS volumes, etc. It would be nice to run this as an "experiment" to more fully discover some of those concerns, but we don't have any prior art on an experimental change to an existing data model. 

**Speculative design:**

We do have the capability to add experimental reconciliation behind feature gates (as well as entirely new types like `MachinePool`), so here's a rough sketch of how we might approach multi-AZ deployments experimentally:

1. If a feature flag is set, CAPA installs a mutating webhook for Machines that reads an annotation `cluster.x-k8s.io/failure-domain-strategy`
2. If that annotation is set to `best-effort-cross-zone`, then it reads the Machines belonging to the same MachineSet and finds the zone with the fewest Machines allocated
3. It overrides the spec.failureDomain on the Machine 

This would probably make more sense as a feature flag on the MachineSet controller, but I wanted to at least write down the sketch. Since CAPA currently "prefers" the failure domain set on the AWSMachine, we could re-work the above logic to all take place against AWSMachine resources if it makes more sense to do it in an infrastructure-specific way.

/priority important-longterm

**Comment by randomvariable** [comment]
Will include as use case in #1484
