### ISSUE TITLE
Need to reconcile instances better

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#173]
/kind bug

We aren't tagging or looking up instances by tag, so we end up creating a new one each iteration.

**What did you expect to happen:**
I expect instances to be reused if tagged appropriately

**Comment by randomvariable** [comment]
Tasks related to this I think are:
* Add kubernetes.io/cluster/<cluster-name>/machine/<machine-name>
* Add glog.V(2) logging to the instances code
* Get instance profiles working
* If it's an API Server, then register with the ELB

**Comment by phyber** [comment]
- [x] glog added to more of instance code in #183
