### ISSUE TITLE
Allow `AwsMachineTemplateSpec` to update tags

### ISSUE THREAD

**Issue by detro** [kubernetes-sigs/cluster-api-provider-aws#1738]
/kind feature

**Describe the solution you'd like**
Today, if we make changes to `AwsMachineTemplateSpec` of any kind, we get back the error:
```
// ... snip ...
awsMachineTemplateSpec is immutable
// ... snip ...
``` 

This is the current (desired?) implementation: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/9d05351c4fd97c627a854d6b64f55557f689a030/api/v1alpha3/awsmachinetemplate_webhook.go#L60

While I feel this makes perfect sense (it's a "physical" instance that is being spawned), Tags are a special case. Within a large organization (like mine, New Relic) tagging is a crucial aspect of keeping AWS organised, and tag schemes are bound to change at some point.

Right now, when this happens, we have to manually go and use the AWS Tag Editor: with too many clusters and nodes, this doesn't scale anymore.

**Anything else you would like to add:**
In case there is a reason this is NOT a desirable feature, please let me know.
Otherwise, I plan to try to implement the feature myself and submit a PR.
It should be "relatively easy".

PS I have indeed looked through the PRs and Issues and I couldn't find an equivalent to this one. But if I missed it and created a duplicate, please link and close this one.

**Environment:**

- Cluster-api-provider-aws version: ANY
- Kubernetes version: (use `kubectl version`):  ANY
- OS (e.g. from `/etc/os-release`): ANY

**Comment by detiber** [comment]
@detro there is an existing issue where others are working on just this: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1711

Closing this issue and let's continue the discussion on #1711 
/close

**Comment by detro** [comment]
Ah, thank you and sorry: I missed it.
Yep, that is precisely the issue. Will follow #1711
