### ISSUE TITLE
Ability to run conformance tests with different CNI

### ISSUE THREAD

**Issue by antoninbas** [kubernetes-sigs/cluster-api-provider-aws#1745]
/kind feature

**Describe the solution you'd like**
I would like the ability to run conformance tests with CAPA using a different CNI provider than Calico. This would enable defining additional [K8s CI jobs](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws) using different CNIs.

[scripts/ci-e2e-conformance.sh](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/scripts/ci-e2e-conformance.sh) is used to run the conformance tests, by invoking the `test-conformance` make target. This leads to the creation of a cluster on which the K8s conformance tests are run. The `--cniManifests` [flag](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v0.5.4/test/e2e/aws_test.go#L66) exists to control which CNI is deployed in the cluster. It defaults to the top-of-tree manifest URL for Calico.

I would like to be able to set an environment variable (e.g. `CNI_MANIFESTS`) that would be recognized by the Makefile, which in turn would propagate that variable's value to the Go tests using the `--cniManifests` flag. If the environment variable is unset, the Makefile would omit the flag altogether and the current behavior would be preserved.

This new environment variable could in turn be used to define new K8s CI jobs.

**Anything else you would like to add:**
It is possible that support for this feature depends on #1744 , since running the tests with different CNI providers will require the ability to configure security groups differently. Once that issue is addressed, it seems that the value of `--cniManifests` will need to influence security group configuration when creating the cluster used to run tests.

I am happy to work on this after #1744  is addressed. If someone has a better solution than the one described above (environment variable), I'm happy to adapt the approach.

**Comment by rudoi** [comment]
Possibly related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1588.

**Comment by randomvariable** [comment]
Moving conformance to clusterctl via #1760 should help with this as it should allow a template for arbitrary CNIs to be passed in.

**Comment by randomvariable** [comment]
@antoninbas left instructions on how to proceed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1588#issuecomment-649412550 

Would add the relevant files and a new script in `scripts/ci-`
