### ISSUE TITLE
Validate AWS tags

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1746]
/kind feature

**Describe the solution you'd like**
When we create resources in AWS we add a number of Tags to the resources. There are certain restrictions on the tags, such as a maximum of 256 characters for a tag value.

There are variouus places in the code where we create these tags, for example:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d4ade5922e04a2327f4043effd16252126dea223/pkg/cloud/services/ec2/subnets.go#L323
and we should probably validate the tags we want to create.

The details around the limits and requirements can be found in the AWS documentation:
https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by rudoi** [comment]
/assign 

Will add context here such that this could be good-first-issue.

**Comment by evalsocket** [comment]
@detiber @rudoi Can this assign to me ?

**Comment by detiber** [comment]
/assign @evalsocket 

@evalsocket I believe you should be able to self-assign issues as long as you've commented on the issue (a comment with just `/assign` on it's own line should be sufficient to meet the requirement and for the bot to do the assignment)

**Comment by evalsocket** [comment]
@richardcase what should we do if validation failed. Should we skip the tag or through the error?

**Comment by richardcase** [comment]
I would say throw an error. The reason being that a lot of people rely in tags for assigning costs to different teams and without the lables it will cause headaches.

**Comment by VibhorChinda** [comment]
Hii @Ankitasw @richardcase I was looking into the description of this issue and understood the following :
1. Tags are created for the resources which we create in AWS [System tags (AWS: prefix), user tags]
2. We need to validate the tags which user creates for the resources. Following the rules mentioned here under "Tag naming limits and requirements" [https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html#tag-best-practices](url)

So the possible solution can be creating a function which treats a tag as a simple string and check all the rules on it.

Please guide, if I am thinking in right direction or not. 
And if yes how can I achieve this :))

**Comment by richardcase** [comment]
@VibhorChinda - yes thats correct. For the implementation, we need to ensure that it can be used everywhere where a user can specify tags (and arguably also to the autogenerated tags as well). One thing to be aware of is that we have a [Tags struct](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/tags.go) that we use in the code and this may help with the implementation.

**Comment by VibhorChinda** [comment]
> @VibhorChinda - yes thats correct. For the implementation, we need to ensure that it can be used everywhere where a user can specify tags (and arguably also to the autogenerated tags as well). One thing to be aware of is that we have a [Tags struct](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/tags.go) that we use in the code and this may help with the implementation.

@richardcase thanks for this ig now ik what I can do :)

**Comment by VibhorChinda** [comment]
@richardcase @Ankitasw have a look at this [function ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/tags.go#L77) What I am thinking is that we just need to increase the checks in this function.

If we go with above approach, I can implement all check other than below.

"Tag keys and values are case sensitive. As a best practice, decide on a strategy for capitalizing tags, and consistently implement that strategy across all resource types. For example, decide whether to use Costcenter, costcenter, or CostCenter, and use the same convention for all tags. Avoid using similar tags with inconsistent case treatment."

How can I know the best practise being followed for adding a check for the above validation ?? :))

**Comment by Ankitasw** [comment]
I think we can add this validation as well in our tags like to check whether camel case is followed or not, but we need to decide on which type of tag naming we want to follow like Costcenter, costcenter, or CostCenter. Can we take this up in CAPA office hours today to get the feedback from others as well?

**Comment by VibhorChinda** [comment]
Makes sense @Ankitasw once we know what type of naming convention to follow we could add validation for this also :))

But on the other side if I think that we follow CamelCase convention, 
"CostCenter" should be ideal tag but how will I know that which character has to be in uppercase if I traverse through the list of tags.

Idk If I could make you understand my point here, but will discuss in office hours ig.

PS : Rest all tests I will implement in the validate function now ✌🏻

**Comment by Ankitasw** [comment]
> But on the other side if I think that we follow CamelCase convention,
"CostCenter" should be ideal tag but how will I know that which character has to be in uppercase if I traverse through the list of tags.

Yes that's why I said we need a common consensus on how we want to follow, if you could join today's office hours, it would be helpful, but it's totally up to you. I can start the discussion in CAPA office hours as well.

**Comment by VibhorChinda** [comment]
> > But on the other side if I think that we follow CamelCase convention,
> > "CostCenter" should be ideal tag but how will I know that which character has to be in uppercase if I traverse through the list of tags.
> 
> Yes that's why I said we need a common consensus on how we want to follow, if you could join today's office hours, it would be helpful, but it's totally up to you. I can start the discussion in CAPA office hours as well.

I will join, will discuss on this.  :)

**Comment by sedefsavas** [comment]
@VibhorChinda there is an extra # in `Fixes`  section of the PR definition, that is why the issue is not closed automatically.

/close
