### ISSUE TITLE
Single cluster can hit rate limiting by continuously attempting EC2 instance registration against ELB

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1751]
/kind bug
/help

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running e2e tests
See many `SuccessfulAttachControlPlaneELB` events, interspersed with `FailedAttachControlPlaneELB`
```
	message: Failed to register control plane instance "i-03a4545af5c5855e0" with load balancer: failed to describe classic load balancer "votta5hv10rk9t4lssguwjsa7o0r-k8s" attributes: Throttling: Rate exceeded
	status code: 400, request id: 714e1627-5fb8-4725-aed7-9a098d6a78a2
```

**What did you expect to happen:**
Completes successfully, with no rate limiting

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
`elbsvc.RegisterInstanceWithAPIServerELB(i)` does not check first if the instance is registered. Although this is not an issue operationally, it counts as a write request against the ELB. There should be a check that it is already registered prior to attempting again.

**Environment:**

- Cluster-api-provider-aws version: v0.5.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@randomvariable so we need to describe the load balancer first, check the response's list of instances, and only proceed if the new instance is not already in the list?

**Comment by randomvariable** [comment]
I think so.
