### ISSUE TITLE
Deleting a cluster in an unmanaged VPC attempts to release elastic IP addresses

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/cluster-api-provider-aws#1755]
/kind bug

**What steps did you take and what happened:**
1. Provisioned a cluster in an unmanaged VPC
2. Delete the cluster

In my case, because the `ec2:DescribeAddresses` IAM action is blocked, the operator was unable to complete reconciliation due to an `UnauthorizedOperation`.

**What did you expect to happen:**
The cluster would be deleted

**Anything else you would like to add:**
During provisioning the step to allocate elastic IPs is invoked from the `reconcileNatGateways()` function, which is skipped when the VPC is unmanaged. When deleting a cluster the `releaseAddresses()` function is called directly from the `DeleteNetwork()` function which also calls `deleteNatGateways()`. Instead, `deleteNatGateways()` should probably be invoking `releaseAddresses()` as it already checks for an unmanaged VPC.

**Environment:** AWS

- Cluster-api-provider-aws version: v0.5.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
This feels related to #1752 in some way.
