### ISSUE TITLE
Constant attempts to patch AWSCluster to set AvailabilityZoneUsageLimit and AvailabilityZoneSelection to null

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1757]
/kind bug

**What steps did you take and what happened:**
1. Create a normal cluster
1. Run `kubectl get awscluster -w`
1. You'll see that it is updated about once a second, but the only things that change are generation and resourceVersion

**What did you expect to happen:**
1. No constant updates

**Anything else you would like to add:**
1. @vincepri and I enabled audit logging and discovered events like this:

```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Request",
  "auditID": "7cb7fb43-b02d-4495-86b6-5ea1a4e3a3f1",
  "stage": "ResponseComplete",
  "requestURI": "/apis/infrastructure.cluster.x-k8s.io/v1alpha3/namespaces/default/awsclusters/andy",
  "verb": "patch",
  "user": {
    "username": "system:serviceaccount:capa-system:default",
    "uid": "7f286c55-d41c-40da-8cfe-a4d48b31e2fb",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:capa-system",
      "system:authenticated"
    ]
  },
  "sourceIPs": [
    "10.244.0.18"
  ],
  "userAgent": "manager/v0.0.0 (linux/amd64) kubernetes/$Format",
  "objectRef": {
    "resource": "awsclusters",
    "namespace": "default",
    "name": "andy",
    "apiGroup": "infrastructure.cluster.x-k8s.io",
    "apiVersion": "v1alpha3"
  },
  "responseStatus": {
    "metadata": {},
    "code": 200
  },
  "requestObject": {
    "spec": {
      "networkSpec": {
        "vpc": {
          "availabilityZoneSelection": null,
          "availabilityZoneUsageLimit": null
        }
      }
    }
  },
  "requestReceivedTimestamp": "2020-06-19T20:56:49.541849Z",
  "stageTimestamp": "2020-06-19T20:56:49.562848Z",
  "annotations": {
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"capa-manager-rolebinding\" of ClusterRole \"capa-manager-role\" to ServiceAccount \"default/capa-system\"",
    "mutation.webhook.admission.k8s.io/round_0_index_0": "{\"configuration\":\"capa-mutating-webhook-configuration\",\"webhook\":\"default.awscluster.infrastructure.cluster.x-k8s.io\",\"mutated\":false}"
  }
}
```

We are constantly trying to patch availabilityZoneSelection and availabilityZoneUsageLimit to null.

This is because when we create and describe the VPC in AWS, we instantiate a new `VPCSpec`:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c718d8e8aaf2b5634cf7b233834818ff07d9d613/pkg/cloud/services/ec2/vpc.go#L195-L199

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c718d8e8aaf2b5634cf7b233834818ff07d9d613/pkg/cloud/services/ec2/vpc.go#L264-L268

And then we copy this newly-created `VPCSpec` into the AWSCluster, overwriting the existing values retrieved from the apiserver:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c718d8e8aaf2b5634cf7b233834818ff07d9d613/pkg/cloud/services/ec2/vpc.go#L86

Because of this, we are losing the values of availabilityZoneSelection and availabilityZoneUsageLimit, so the patch helper tries to clear them out during every reconcile. These 2 fields have OpenAPI defaulting, which prevents their values from being cleared out, but this flow results in an infinite loop of patching attempts.

In the long term, we probably should update our logic so instead of creating entirely new VPCSpecs and overwriting the existing field in the AWSCluster, we copy the described values into AWSCluster.Spec.NetworkSpec.VPC.

**Environment:**

- Cluster-api-provider-aws version: commit c718d8e8

**Comment by ncdc** [comment]
FYI @richardcase

**Comment by ncdc** [comment]
@richardcase are you still planning to work on this?

**Comment by ncdc** [comment]
I have a small fix that works as a band-aid until we can rework this part of the code, if you're busy.

**Comment by richardcase** [comment]
Go for it @ncdc. I probably can’t look at it until Friday.

**Comment by ncdc** [comment]
Thanks!
/assign
/lifecycle active
