### ISSUE TITLE
CAPA consuming a good portion of AWS API limits

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api-provider-aws#1764]
When we recently shipped a tool that collected monitoring data from the same APIs, we noticed that our monitoring data had lots of holes in it from rate limiting. Via cloudtrail, we saw that CAPA was making ~80% of the API calls during one of these gaps, and ~90% of the calls being made in our account were `DescribeInstances` and `DescribeNetworkInterfaces`.

It looks like the current implementation of the reconciler operates on a single entity at a time – running at least one Describe or mutate call per AWS* object. This is an inefficient use of the API limits relative to batching these calls, so I'm here to propose that we introduce this notion to the various Service interfaces, starting with `DescribeNetworkInterfaces` and `DescribeInstances`.

An example implementation might look something like:

```
type ENIResponse struct {
	interfaces []*ec2.NetworkInterface
	err        error
}

type ENIRequest struct {
	instanceID string
	out        chan ENIResponse
}

func (s *Service) getInstanceENIs(instanceID string) ([]*ec2.NetworkInterface, error) {
	ch := make(chan ENIResponse)
	s.eniRequests <- ENIRequest{
		instanceID: instanceID,
		out:        ch,
	}
	ret := <-ch
	return ret.interfaces, ret.err
}

func (s *Service) runGetENIs() {
	for {
		items, timeout := []*string{}, time.After(1*time.Second)
		resp := map[string][]chan ENIResponse{}

		func() {
			for {
				select {
				case item := <-s.eniRequests:
					items = append(items, aws.String(item.instanceID))
					resp[item.instanceID] = append(resp[item.instanceID], item.out)
					if len(items) > 1 {
						return
					}
				case <-timeout:
					return
				}
			}
		}()

		if len(items) < 1 {
			continue
		}

		input := &ec2.DescribeNetworkInterfacesInput{
			Filters: []*ec2.Filter{
				{
					Name:   aws.String("attachment.instance-id"),
					Values: items,
				},
			},
		}

		output, err := s.scope.EC2.DescribeNetworkInterfaces(input)
		if err != nil {
			for _, chs := range resp {
				for _, ch := range chs {
					ch <- ENIResponse{err: err}
				}
			}
			continue
		}

		ifaces := make(map[string][]*ec2.NetworkInterface, len(items))
		for _, iface := range output.NetworkInterfaces {
			if iface == nil {
				continue
			}

			id := *iface.Attachment.AttachmentId
			ifaces[id] = append(ifaces[id], iface)
		}

		for id, chs := range resp {
			for _, ch := range chs {
				ch <- ENIResponse{interfaces: ifaces[id]}
			}
		}
	}
}
```

AWS' documentation: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html

What do you think?

**Comment by randomvariable** [comment]
Funnily enough, me and @ncdc were having this same discussion 24 hours ago.

**Comment by detiber** [comment]
I've also been wondering if it would make sense for us to implement some type of a caching interface, which might work out well with a background process that could aggregate and batch updates for the cache.

We'd still likely need to do some assurances that we aren't inspecting data that is too stale, especially in the case of resync-based reconciliations.

**Comment by sethp-nr** [comment]
Yeah, the interaction between the arrival of a watch notification and any cache expiry mechanism is something that'd take a little bit of thought.

Credit to @dthorsen for the idea to batch up the calls internally – even by waiting just a few seconds, we should be able to coalesce a fair number of concurrent calls together.

**Comment by randomvariable** [comment]
These initial changes sound good.

I was also thinking of explicitly copying the old Netflix Edda model, continuously reading all resources in batch - esp. for taggable resources, given that we have a known set of tags that identify them as being managed by Cluster API. That, plus EventBridge to reduce the delta between reconciliations.

Another one is to implement the controller runtime rate limiters. Particularly once we have multi-tenancy in, it should be possible to rate-limit at the account level.

**Comment by randomvariable** [comment]
Also, high time we did #78
