### ISSUE TITLE
Review potential bug in ec2svc.InstanceIfExists()

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1769]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Extracting comment by @detiber from #1740 :

I think I found a potential pre-existing bug... It looks like we are swallowing up errors when we attempt to do a lookup for a specific instance ID (ec2svc.InstanceIfExists()), when the AWS api returns a NotFound error. I'm not sure that is the behavior that we want, since:

* It introduces a potential re-entrancy bug related to the eventual consistency of the AWS APIs, where we could potentially create more than one instance for a given machine
* It could potentially lead to the replacement of an instance that was terminated and purged, when it shouldn't.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.5.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
> If we do not act on ec2svc.InstanceIfExistsNotFound error then there may be a case where the instance is never created correctly and hence not reconciled. Is it ok to wait until next reconcile in this case?

Possibly, but depending on how much time has elapsed it might still hit the same issue.

What we likely really need to do is generate a client token value and store it prior to creating the resource (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html).

We could potentially use the resource UID as the client token, but that could present issues related to `clusterctl move`

**Comment by sedefsavas** [comment]
Actually this issue does not exist because there is a check above `findInstance()` during `reconcileNormal`
`if machineScope.HasFailed()`. When an instance has an ID but is not healthy (terminated etc.), it never continues to `findInstance()` and checks ec2svc.InstanceIfExists().

Also, if providerID is missing, it fails at the beginning of `findInstance()` and sets InstanceNotFound condition.

So, I think this is not a bug.

**Comment by randomvariable** [comment]
Thanks for investigating. I suspect we would have seen reports in the wild about it. I think we've also been insulated since instance-ids are created immediately, just with incomplete info (which caused a bunch of bugs in the past).

Going to mark closed unless someone sees it come up again.

/close
