### ISSUE TITLE
Remove ancient docker image from Github packages view

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1771]
/kind bug
/priority important-soon

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
New Github UI is showing an ancient package:
![image](https://user-images.githubusercontent.com/1441070/85707365-0539f980-b6db-11ea-9c50-7e9c9f71f2fe.png)

**What did you expect to happen:**
Shouldn't be there.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
@detiber @vincepri was this from a prior experiment? Weirdly, I can edit the description but not remove the version.

**Comment by detiber** [comment]
Unless things have changed, there is no way to delete a github package and I'm not currently seeing any way to hide it.

**Comment by vincepri** [comment]
I was able to hide the package view from the side list in CAPI, let me see if I can do the same here

**Comment by vincepri** [comment]
Done, ptal @randomvariable

**Comment by randomvariable** [comment]
It's gone. Thanks @vincepri !

/close
