### ISSUE TITLE
Implement subnet filter capability currently in the API for AWSMachineTemplate

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1776]
/kind feature

**Describe the solution you'd like**
I need to specify which subnets my [AWSMachineTemplate](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml#L200-L233) can land in.  Currently, that capability is restricted to just the [`.spec.template.spec.subnet.id`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml#L231-L233) field, I would like to expand this to include the already existing [`filters`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml#L208-L230) object that lives in the spec.  This would allow me to optionally tag, or look up subnets where I do not know the `id` ahead of time (either because it's dynamically created, or I am using the same templates for multiple deployments).

Reference: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml#L200-L233

**Anything else you would like to add:**
Does not require changes to the CRDs, as the `filters` object is already there.

**Environment:**

- Cluster-api-provider-aws version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by voor** [comment]
Regarding a comment from slack: 
> We'll need to make sure to do some extra validation and guard rails to make sure that we don't match multiple subnets, but seems reasonable for byo uses
Want to make sure to explicitly state that since `AWSMachineTemplate` is leveraged in `KubeadmControlPlane` this would *resolve* the issue where putting in the subnet ID prevents the Control Plane from being distributed across Availability Zones.

**Comment by detiber** [comment]
> > We'll need to make sure to do some extra validation and guard rails to make sure that we don't match multiple subnets, but seems reasonable for byo uses
> 
> Want to make sure to explicitly state that since `AWSMachineTemplate` is leveraged in `KubeadmControlPlane` this would _resolve_ the issue where putting in the subnet ID prevents the Control Plane from being distributed across Availability Zones.

Ah, good point. It would definitely have to make sure that the combination of the provided filter and the AZ returns a singular result.
