### ISSUE TITLE
Change default branch to "main"

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1782]
Once the community agrees on the naming, we need to change our default development branch to `main`, and check that any tools or references to it are changed as well.

This includes the container image tag used in development.

/kind cleanup
/wg naming
/milestone Next

**Comment by randomvariable** [comment]
Let's do this. We have instructions here https://www.kubernetes.dev/resources/rename/

**Comment by sedefsavas** [comment]
This is done.
/close
