### ISSUE TITLE
EKS self managed node group support

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1784]
/kind feature

**Describe the solution you'd like**
When creating an EKS cluster i want to provision a "self managed node group"  that uses an EC2 instance for worker nodes. Will need to use the boostrap data from #1779.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by rudoi** [comment]
Could this and #1785 be solved by implementing MachinePool providers (maybe even #1786 if we're willing to flex the definition of "machine pool")? 

"AWSMachinePool", for example, could map to an AutoScalingGroup
"AWSManagedMachinePool" (or even just "AWSManagedNodeGroup", names are hard) could map to a Managed Node Group.

I've worked very little with Fargate profiles so I'm not quite sure how that would go at present.

**Comment by randomvariable** [comment]
@mytunguyen is there anything left to do on this given the bootstrap provider being added?
