### ISSUE TITLE
EKS Fargate profiles support

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1786]
/kind feature

**Describe the solution you'd like**
When creating a EKS cluster i want the option to be able to use fargate for the workloads. Adding support for [fargate profiles](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html) would be needed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by michaelbeaumont** [comment]
Mapping this to `MachinePool` feels like a little bit of a mismatch given that we don't have `version`, `replicas`, `bootstrap`, etc. We have `Node`s but we don't really have `spec.replicas`. Do we think this is important?

**Comment by richardcase** [comment]
> Mapping this to `MachinePool` feels like a little bit of a mismatch given that we don't have `version`, `replicas`, `bootstrap`, etc. We have `Node`s but we don't really have `spec.replicas`. Do we think this is important?

As this doesn't really match well to upstream CAPI kinds I wonder if we just create an `AWSFargateProfile` kind with associated controller? And maybe it just cares about its matching `AWSManagedControlPlane`. WDYT?

**Comment by richardcase** [comment]
@michaelbeaumont @randomvariable  - i think we should probably capture the decision on how we implement this in an ADR
