### ISSUE TITLE
Flaky tests resulting from linter timeouts

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api-provider-aws#1795]
/kind bug

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1793/pull-cluster-api-provider-aws-test/1280582665275183106
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1789/pull-cluster-api-provider-aws-test/1280438464378048512
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1798/pull-cluster-api-provider-aws-test/1280629722539102208

**Comment by randomvariable** [comment]
Prow has also been super slow of late, probably due to code freeze.

**Comment by benmoss** [comment]
Yeah, I think this might just be because of slow prow machines

**Comment by benmoss** [comment]
Seeing a bunch of `Entrypoint received interrupt: terminated` errors as well today

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1798/pull-cluster-api-provider-aws-test/1280628086131396613

**Comment by randomvariable** [comment]
Those interrupts happen when you push commits or force push.

**Comment by randomvariable** [comment]
Thinking it might be resource limits, maybe golangci is intermittently exhausting memory?
