### ISSUE TITLE
Re-enable multi-AZ e2e testing

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1806]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
With #1803 and #1805 merged, should be possible to re-enable multi-AZ in e2e testing.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by gab-satchi** [comment]
Closing as the new e2e tests use multi-Az by default. 

/close
