### ISSUE TITLE
Remove create-*-cluster Makefile tasks

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1826]
The Makefile has some old tasks related to old CI jobs and testing behaviours

`create-workload-cluster`,
`create-cluster`
`delete-workload-cluster`
`delete-cluster`
`kind-reset`

Tilt is the more widely used development practice, and these tasks have gone stale, not kept up to date, and importantly don't use clusterctl.

Does anyone rely on them, or can they be deleted?

**Comment by detiber** [comment]
+1 from me for removing them

**Comment by ncdc** [comment]
@rudoi any objections?

**Comment by rudoi** [comment]
@ncdc None, thanks for checking! Full steam ahead.
