### ISSUE TITLE
Create template flavours to support EKS control plane

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1828]
/kind feature

**Describe the solution you'd like**
It would be good to introduce [flavours](https://cluster-api.sigs.k8s.io/clusterctl/commands/config-cluster.html#flavors) with the introduction of EKS support so that users can create different luster configurations

When using clusterctl 

```bash
clusterctl config cluster my-cluster --kubernetes-version v1.16.3 --flavor managed > my-cluster.yaml
```

This would then generate the definitions for EKS using `AWSManagedCluster, AWSManagedControlPlane` etc

**Anything else you would like to add:**
[CAPZ have done this](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/templates/flavors) to help with AKS support.

**Comment by michaelbeaumont** [comment]
One little conflict here, `--kubernetes-version` requires a semver version `X.Y.Z` (for AKS, kubeadm, etc) whereas EKS wants `X.Y`.

**Comment by richardcase** [comment]
> One little conflict here, `--kubernetes-version` requires a semver version `X.Y.Z` (for AKS, kubeadm, etc) whereas EKS wants `X.Y`.

Good point @michaelbeaumont. Does clusterctl enforce semver on the version?

**Comment by michaelbeaumont** [comment]
Yes `clusterctl` validates it

**Comment by michaelbeaumont** [comment]
(Temporary) solution: ignore the patch version in the EKS control plane controller.

**Comment by richardcase** [comment]
@michaelbeaumont - am i right in thinking this has been complete with the change in name of the template file and also the patching the version number in the defaulting webhook?

**Comment by richardcase** [comment]
So:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/exp/api/v1alpha3/awsmanagedcontrolplane_webhook.go#L194
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/templates/cluster-template-managed.yaml

**Comment by michaelbeaumont** [comment]
Exactly, for example the command at [Create a EKS cluster](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/eks.md#creating-a-eks-cluster) is supported now.

**Comment by richardcase** [comment]
@randomvariable @rudoi - we can probably close this issue based on the ^^^^^^^^

**Comment by randomvariable** [comment]
I think maybe the bits for the worker nodes need to be added? Defer to @rudoi on this.

**Comment by randomvariable** [comment]
See you opened the issue for that.

Retitled and

/close
