### ISSUE TITLE
Support spreading AWSMachines across multiple subnets per availability zone

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1829]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

https://github.com/kubernetes-sigs/cluster-api/issues/3358 looks to spread MachineSet-owned Machines across available FailureDomains. This will work fine with CAPA in scenarios where there's only one subnet per availability zone. CAPA does not understand how to spread EC2 instances across subnets today.

In order to use MachineDeployments with multiple subnets per AZ, you must create a MachineDeployment and AWSMachineTemplate per subnet, specifying the subnet ID explicitly in the AWSMachineTemplate. 

It's unclear to me the best way to teach CAPA how to spread these EC2 instances out. State would need to be stored on the current distribution of AWSMachines per subnet, or we'd need to store enough state to be able to do some kind of round robin thing.

**Comment by detiber** [comment]
If we wanted a relatively naive implementation, we could pick a random value from the available subnets for a given failure domain, possibly with a fallback in the event that there is a failure related to not being able to allocate an IP in the chosen subnet.

**Comment by randomvariable** [comment]
Superseded by https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2924
