### ISSUE TITLE
cloud-init v20.2-45-g5f7825e2-0ubuntu1~18.04.1 never runs /etc/secret-userdata.txt

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1839]
/kind bug

**What steps did you take and what happened:**
Build OSS CAPA AMI Ubuntu 1804 using image builder for Kubernetes v1.18.3
If you're in US-East-1, here's an AMI: `ami-0e1906e4df51041c4`

Run through quickstart guide for CAPA.
Run 
clusterctl config cluster manager --kubernetes-version 1.18.3 > tmp.yaml
Add 
```
      ami:
        id: ami-0e1906e4df51041c4
```
To all of the `AWSMachineTemplate`

Deploy cluster.  cloud-init fails on first control plane, nothing happens after that.

Check: `/etc/secret-userdata.txt` *does* exist.
Check: `/var/lib/cloud/instance/user-data.txt` *does* reference that file.
Check: cloud-init *did* run twice (it was restarted from the unitial script)
FAIL: `/var/lib/cloud/instance/user-data.txt.i` *does not* resolve `/etc/secret-userdata.txt` into it.

**What did you expect to happen:**
Second run of cloud-init should properly resolve the secret-userdata and execute it properly.

**Anything else you would like to add:**
This makes me :sob: how long it took to figure out this was what was happening.

**Environment:**

- Cluster-api-provider-aws version: `us.gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller:v0.5.5-rc.0`
- Kubernetes version: (use `kubectl version`): Image is v1.18.3
- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by voor** [comment]
Taking `ami-04d57e17c284ca940` right now and updating just cloud-init and seeing if this also happens.

**Comment by voor** [comment]
`ami-0d01a41f15f1933f0` is an updated capa-ami-ubuntu-18.04-1.18.2-00 where cloud-init package has been updated.

Just make sure you're using 1.18.2 instead of 1.18.3 for this one.

```
clusterctl config cluster manager --kubernetes-version 1.18.2 > tmp.yaml
```

Same issue.

**Comment by voor** [comment]
Upstream Ubuntu bug https://bugs.launchpad.net/cloud-init/+bug/1888822

**Comment by detiber** [comment]
It looks like previously when we did a `systemctl cloud-init restart` in the boothook script it was causing cloud-init (version 19.4-33) to re-run the `consume_data` step, with the latest version (20.2-45).

I still need to do a bit more digging, just wanted to share my current progress (and give myself a starting point when I pick this back up)

**Comment by voor** [comment]
Is there a subset of folders that could be removed/destroyed that would cause cloud-init to run that step again?

**Comment by detiber** [comment]
> Is there a subset of folders that could be removed/destroyed that would cause cloud-init to run that step again?

Not sure yet, I haven't had a chance to continue digging yet, might be next week before I get a chance to continue looking into it if someone doesn't figure it out before then.

**Comment by voor** [comment]
Downgrading to `/usr/bin/cloud-init 18.2` did *not* solve the problem, looks like there's a more complicated grouping of stuff at play here. :sob:

**Comment by detiber** [comment]
Triaged the issue and summarized in https://bugs.launchpad.net/cloud-init/+bug/1888822/comments/5

We are hitting a bug in newer versions of cloud-init that is incorrectly resetting the content type of our boot hook from text/cloud-boothook to text/x-shellscript when processing the userdata resulting in the boothook not being recognized during execution.

We can work around this by forcing image-builder to downgrade cloud-init to version 19.4.33, but this will also need a fix in cloud-init itself to fully resolve the issue.

**Comment by voor** [comment]
Update from cloud-init team, tl;dr they concur and it's a critical regression.
https://bugs.launchpad.net/cloud-init/+bug/1888822

**Comment by voor** [comment]
https://github.com/canonical/cloud-init/pull/511

**Comment by OddBloke** [comment]
Hey folks, while we're working on landing and releasing the cloud-init fix: if you add `#cloud-boothook` as the first line of your boothook then it will be correctly detected as a boothook by cloud-init (both before the breaking change landed, currently, and once we land the fix). As a workaround, this may be preferable to downgrading cloud-init in images.

**Comment by ncdc** [comment]
@voor do you have time to test the workaround?

**Comment by randomvariable** [comment]
Trying the workaround bit
