### ISSUE TITLE
Instances should be tagged with their Machine name

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api-provider-aws#1840]
/kind feature

**Describe the solution you'd like**
Right now VMs in AWS are named for their `AWSMachine` object, which has a different name than the corresponding `Machine` object. It would be really useful if at least there was a tag on the VM with the `Machine` name so that it I don't have to do an extra lookup to find which `Machine` it corresponds to.

**Comment by detiber** [comment]
One caveat here, we already have quite a few tags that would conflict across namespaces, it might be good to make sure that if/when we introduce any new ones that they include the namespace in addition to the name to avoid potential conflicts from the same management cluster (not sure we should try to solve issues related to separate management clusters conflicting on naming).

**Comment by benmoss** [comment]
I agree, something like the Kubernetes `NamespacedName` could be used
