### ISSUE TITLE
:bug: Encrypted instances fail with very little feedback

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#1842]
/kind bug

**What steps did you take and what happened:**
Leverage an encrypted AMI that is encrypted with a KMS key that is not available to the `controllers.cluster-api-provider-aws.sigs.k8s.io` role

**What did you expect to happen:**
Something about `controllers.cluster-api-provider-aws.sigs.k8s.io` not having permissions to launch an EC2 instance with the given KMS key, or instance failed to create because of KMS related issue, _something_ other than a complete blackbox of:
```
I0726 22:56:18.697198       1 awsmachine_controller.go:368] controllers/AWSMachine "msg"="Error state detected, skipping reconciliation" "awsCluster"="registry" "awsMachine"="registry-control-plane-ql6wx" "cluster"="registry" "machine"="registry-control-plane-pl6dv" "namespace"="default" 
```

**Anything else you would like to add:**
Issue is solved by allowing use of key to the correct IAM role.

**Environment:**

- Cluster-api-provider-aws version: `v0.5.4`
- Kubernetes version: (use `kubectl version`): `1.18.3`
- OS (e.g. from `/etc/os-release`): Ubuntu AMI

**Comment by randomvariable** [comment]
How are you able to determine that was the issue yourself? I think the problem here is that the EC2 call will fire the KMS request async. Unless there's a proper way to introspect the issue, not sure what can be done.

**Comment by voor** [comment]
> How are you able to determine that was the issue yourself?
Tears, alcohol, and time.

If it does happen again, I can try to see if there's an EC2 query that might respond with something.  The VM basically just crashes out.
