### ISSUE TITLE
Move to a CNCF-owned AWS account for project-owned AMIs

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1861]
/kind feature

**Describe the solution you'd like**
We are currently publishing CAPA AMIs to a VMware-owned AWS account. This account is the hard-coded default account to use when looking up AMIs (this is overridable). It would be nice if we could transition the AMIs to a CNCF-owned AWS account.

**Anything else you would like to add:**
Bonus points if we can automate, via Prow and image-builder, publishing new AMIs when new Kubernetes versions are released.

cc @detiber @randomvariable

**Comment by randomvariable** [comment]
We should open an issue in github.com/kubernetes/k8s.io i think?

**Comment by ncdc** [comment]
We probably need multiple issues. Is k8s.io the right repo, or maybe test-infra?

**Comment by detiber** [comment]
k8s.io is where the tooling is going to live, since this account will be used for a purpose other than "testing", I think it is likely an appropriate place for the discussion, though it may also involve a discussion with sig-release

**Comment by ncdc** [comment]
👍 I will file in k8s.io and cross link

**Comment by ncdc** [comment]
https://github.com/kubernetes/k8s.io/issues/1116

**Comment by sedefsavas** [comment]
I started a document to brainstorm the next steps of moving the images and automating the build/publish process.

https://docs.google.com/document/d/142YzzRj2H_OWEUE03Vrw3D-XpDCWM8RviFGHT5-RBxo/edit?usp=sharing

I will bring this up during Sept 21 CAPA meeting.

cc @randomvariable @detiber @ncdc

**Comment by randomvariable** [comment]
I've two drive by comments, but will do a full read tomorrow.
