### ISSUE TITLE
Unable to create management cluster TKG on AWS EC2

### ISSUE THREAD

**Issue by sudinar** [kubernetes-sigs/cluster-api-provider-aws#1862]
‼ [0806 02:33:31.78466]: init.go:464] Failure while deploying management cluster, Here are some steps to investigate the cause:
‼ [0806 02:33:31.78481]: init.go:465] Debug:
‼ [0806 02:33:31.78484]: init.go:466] kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_N37NRVa2
‼ [0806 02:33:31.78491]: init.go:467] kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_N37NRVa2
‼ [0806 02:33:31.78494]: init.go:470] To clean up the deployment and kind cluster:
‼ [0806 02:33:31.78500]: init.go:476] kubectl delete cluster.cluster.x-k8s.io/aws-mgmt -n tkg-system --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_N37NRVa2
‼ [0806 02:33:31.78503]: init.go:477] docker rm -v tkg-kind-bslm7lfum25ogfkvsc10-control-plane -f
✘ [0806 02:33:31.78509]: init.go:111] unable to set up management cluster, : unable to wait for cluster and get the cluster kubeconfig: error waiting for cluster to be provisioned (this may take a few minutes): timed out waiting for cluster creation to complete: [cluster control plane is still being initialized, cluster infrastructure is still being provisioned]
---------------------------------------------------------------------------------------------------------------------------------------
ubuntu@ip-172-31-91-220:~$ kubectl get po,deploy,cluster,kubeadmcontrolplane,machine,machinedeployment -A --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_N37NRVa2
NAMESPACE                           NAME                                                                      READY   STATUS    RESTARTS   AGE
capa-system                         pod/capa-controller-manager-86cbf677bc-k62s8                              2/2     Running   0          34m
capi-kubeadm-bootstrap-system       pod/capi-kubeadm-bootstrap-controller-manager-6857dfc668-qtmfh            2/2     Running   0          34m
capi-kubeadm-control-plane-system   pod/capi-kubeadm-control-plane-controller-manager-85f4885cf5-85qcl        2/2     Running   0          34m
capi-system                         pod/capi-controller-manager-5df8c8fb59-xsx78                              2/2     Running   0          35m
capi-webhook-system                 pod/capa-controller-manager-555b87ddbd-w26w8                              2/2     Running   0          34m
capi-webhook-system                 pod/capi-controller-manager-7d8d9b87b8-b5pdh                              2/2     Running   0          35m
capi-webhook-system                 pod/capi-kubeadm-bootstrap-controller-manager-dff99d987-m5s66             2/2     Running   0          34m
capi-webhook-system                 pod/capi-kubeadm-control-plane-controller-manager-6cc995dd6c-bgf24        2/2     Running   0          34m
cert-manager                        pod/cert-manager-b56b4dc78-hcs6g                                          1/1     Running   0          35m
cert-manager                        pod/cert-manager-cainjector-6b54f84d85-th7mr                              1/1     Running   0          35m
cert-manager                        pod/cert-manager-webhook-6fbc6d7449-xtzdd                                 1/1     Running   1          35m
kube-system                         pod/coredns-dbbffcb66-8pgt2                                               1/1     Running   0          36m
kube-system                         pod/coredns-dbbffcb66-qkps8                                               1/1     Running   0          36m
kube-system                         pod/etcd-tkg-kind-bslm7lfum25ogfkvsc10-control-plane                      1/1     Running   0          36m
kube-system                         pod/kindnet-9lffp                                                         1/1     Running   0          36m
kube-system                         pod/kube-apiserver-tkg-kind-bslm7lfum25ogfkvsc10-control-plane            1/1     Running   0          36m
kube-system                         pod/kube-controller-manager-tkg-kind-bslm7lfum25ogfkvsc10-control-plane   1/1     Running   0          36m
kube-system                         pod/kube-proxy-cqflb                                                      1/1     Running   0          36m
kube-system                         pod/kube-scheduler-tkg-kind-bslm7lfum25ogfkvsc10-control-plane            1/1     Running   0          36m
local-path-storage                  pod/local-path-provisioner-774f7f8fdb-ctc2n                               1/1     Running   0          36m

NAMESPACE                           NAME                                                            READY   UP-TO-DATE   AVAILABLE   AGE
capa-system                         deployment.apps/capa-controller-manager                         1/1     1            1           34m
capi-kubeadm-bootstrap-system       deployment.apps/capi-kubeadm-bootstrap-controller-manager       1/1     1            1           34m
capi-kubeadm-control-plane-system   deployment.apps/capi-kubeadm-control-plane-controller-manager   1/1     1            1           34m
capi-system                         deployment.apps/capi-controller-manager                         1/1     1            1           35m
capi-webhook-system                 deployment.apps/capa-controller-manager                         1/1     1            1           34m
capi-webhook-system                 deployment.apps/capi-controller-manager                         1/1     1            1           35m
capi-webhook-system                 deployment.apps/capi-kubeadm-bootstrap-controller-manager       1/1     1            1           34m
capi-webhook-system                 deployment.apps/capi-kubeadm-control-plane-controller-manager   1/1     1            1           34m
cert-manager                        deployment.apps/cert-manager                                    1/1     1            1           35m
cert-manager                        deployment.apps/cert-manager-cainjector                         1/1     1            1           35m
cert-manager                        deployment.apps/cert-manager-webhook                            1/1     1            1           35m
kube-system                         deployment.apps/coredns                                         2/2     2            2           37m
local-path-storage                  deployment.apps/local-path-provisioner                          1/1     1            1           37m

NAMESPACE    NAME                                PHASE
tkg-system   cluster.cluster.x-k8s.io/aws-mgmt   Provisioning

NAMESPACE    NAME                                                                       READY   INITIALIZED   REPLICAS   READY REPLICAS   UPDATED REPLICAS   UNAVAILABLE REPLICAS
tkg-system   kubeadmcontrolplane.controlplane.cluster.x-k8s.io/aws-mgmt-control-plane

NAMESPACE    NAME                                                     PROVIDERID   PHASE
tkg-system   machine.cluster.x-k8s.io/aws-mgmt-md-0-9b96856c9-c6277                Pending

NAMESPACE    NAME                                               PHASE       REPLICAS   AVAILABLE   READY
tkg-system   machinedeployment.cluster.x-k8s.io/aws-mgmt-md-0   ScalingUp   1   
ubuntu@ip-172-31-91-220:~$ kubectl logs deployment.apps/<deployment-name> -n <deployment-namespace> manager --kubeconfig /home/ubuntu/.kube-tkg/tmp/config_N37NRVa2
-bash: deployment-name: No such file or directory
ubuntu@ip-172-31-91-220:~$

**Comment by randomvariable** [comment]
Hello,

We unfortunately can't provide support for products using Cluster API Provider AWS without logs for Cluster API Provider AWS.

Can you contact VMware support who can assist?
