### ISSUE TITLE
AWSManagedControlPlane controller should set up aws-auth ConfigMap automatically

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1870]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

By default, the only IAM entity that has access to an EKS cluster is the entity that created it. Users must create an `aws-auth` ConfigMap specifying additional mappings. See: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

Additional mappings must also be added for instance roles on EC2 instances looking to join the cluster as Nodes. 

It would be great if:
1. this ConfigMap were created for me automatically
2. I could specify in the `spec` of AWSManagedControlPlane an IAM role to be added to the cluster as an admin
3. I could specify in the `spec` of AWSManagedControlPlane an InstanceRole to be added to the cluster as a node

cc @richardcase @mytunguyen

**Comment by richardcase** [comment]
I wonder if this will help out in this area: https://gitlab.com/polarsquad/eks-auth-sync
