### ISSUE TITLE
Create default EKS IAM Role using clusterawsadm

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1877]
/kind feature

**Describe the solution you'd like**
It would help users if a default IAM role was created for EKS. This could then be used in the EKS control plane if no role was specified and if the EKSEnableIAM flag is false (i.e. not specified). It feels like this could be done using clusterawsadm.

**Anything else you would like to add:**
The default role should have a tag that denotes it as the default EKS role. This would then enable customers to create their own role with the tag and this be used instead.

We should also allow specifying addition polices when creating the role 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
/close 

Fixed in #1879

**Comment by randomvariable** [comment]
/reopen
misread this.
