### ISSUE TITLE
Document how to get onto instances

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#188]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Had completely forgotten what the default user for SSH 
was on Ubuntu 18.04, which we also haven't stated is the default OS choice.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chuckha** [comment]
related to #341
