### ISSUE TITLE
Set kube reserved across EKS and EC2 node types

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1885]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The Amazon EKS AMI includes a script to set kube-reserved values based on instance type at: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh 

This could potentially be handled consistently by CAP*

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
More likely we want CAPA to explicitly set this, especially as we also need this info for scale from zero in Cluster Autoscaler.

**Comment by randomvariable** [comment]
Relates to Cluster Autoscaler conversations, including CAPI meeting of 2021/10/03. Could be a future integration point between CAPI and CA where CAP* providers automatically provide the hints.

cc @elmiko

**Comment by elmiko** [comment]
thanks for the cc @randomvariable , i just want to make sure i understand the script. this is setting the size based on the instance, but is it also subtracting the overhead needed for the kubernetes bits? (i read through the script, but it wasn't quite clear to me)

**Comment by sedefsavas** [comment]
Closing in favor of Cluster API Informing kube-reserved and system-reserved kubernetes-sigs/cluster-api#5392
