### ISSUE TITLE
Spot Instance interruption notice support

### ISSUE THREAD

**Issue by Promaethius** [kubernetes-sigs/cluster-api-provider-aws#1899]
/kind feature

**Describe the solution you'd like**
Spot instance support has come in with #1868 however when a spot instance terminates, it drops the workload without notice.
Augment the spot instance support with interruption notice polling. When an instance receives the normal 2 minute notice, attempt to drain it using the same lifecycle process that the provider uses when scaling down a pool.

**Anything else you would like to add:**
https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#spot-instance-event-types

**Environment:**

- Cluster-api-provider-aws version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by rudoi** [comment]
I'm interested in the end product here, but curious about some of the effects of adding this polling into CAPA:
- does this mean we have to reconcile AWSMachines on an interval shorter than 2m?
- what impact would this have on our current EC2 request load? 

I'm curious if perhaps we could do some kind of integration with https://github.com/aws/aws-node-termination-handler? This is a DaemonSet that polls the metadata API, which does not count against EC2 request rate limits. 

Node Termination Handler minimally will cordon a Node and apply some labels to it. I wonder if there's some kind of configurable lifecycle mechanism we could use in CAPI to detect certain labels on Nodes. I do have certain feelings about CAPI knowing about an AWS-specific Node label though... 🤔

**Comment by randomvariable** [comment]
I think integration with the node termination handler would be better. If anything, trying to cut down the amount of polling of EC2 APIs.

We also have https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1871

**Comment by ncdc** [comment]
See https://github.com/kubernetes-sigs/cluster-api/pull/3528

**Comment by randomvariable** [comment]
Upstream PR https://github.com/kubernetes-sigs/cluster-api/pull/3668 has discussion on how we can do this in CAPI such  that nothing needs to be done here.

**Comment by ncdc** [comment]
Further discussions in https://github.com/kubernetes-sigs/cluster-api/pull/3668 resulted in https://github.com/kubernetes-sigs/cluster-api/issues/3504 and https://github.com/kubernetes-sigs/cluster-api/pull/3817. The requirement for CAPA is to add AWSMachine.status.interruptible (bool), and set it to true when AWSMachine.spec.spotMarketOptions is non-nil.
