### ISSUE TITLE
Persist default subnets early

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1906]
/kind feature

**Describe the solution you'd like**
When there are no subnets specified and we use the default subnet logic [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/network/subnets.go#L71) we should persist the subnet specs as soon as possible, especially before creating them. This will be helpful if there is an transient error part way thorough creating the subnets.

We should think about exiting early from the reconciliation loop after we have determined the subnets for the VPC but before actually creating them and force a requeue (i.e. `reconcile.Result{Requeue: true}`). This will persist the definitions and on the next reconciliation loop the subnets will be created from the definition.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 0.5.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by gab-satchi** [comment]
Hey @richardcase, we do set the subnets in a defer [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/network/subnets.go#L51) which should get called unless the function panics somehow. Are you seeing cases where a reconciliation happens and the subnets aren't getting persisted?

**Comment by richardcase** [comment]
@gab-satchi - it was an edge case where defer wasn't called, basically if there was a crash of some sort.
