### ISSUE TITLE
Improve clusterawsadm UX

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#191]
/kind feature
/good-first-issue

**Describe the solution you'd like**

The `clusterawsadm` command has some terrible UX:

e.g. you need to provide an account ID to this command.

``` bash
clusterawsadm alpha bootstrap generate-cloudformation
Error: accepts 1 arg(s), received 0
Usage:
clusterawsadm alpha bootstrap generate-cloudformation [flags]

Flags:
-h, --help   help for generate-cloudformation

accepts 1 arg(s), received 0

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
```
But it doesn't tell you what the argument is supposed to be.
Neither does it check that it's an account id.

It also reuses the glog tooling from the controllers, which is not
best for human readability, as in this example where no credentials
are present for CloudFormation to use.

``` bash
-> clusterawsadm alpha bootstrap create-stack
ERROR: logging before flag.Parse: E1008 16:38:12.671749    9045 bootstrap.go:82] unable to get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

This could be much improved, with the logging prefix removed, 
and errors handled gracefully with meaningful errors for
end users.

**Comment by xmudrii** [comment]
I want to take on the issue in the morning if that is okay and not late. :slightly_smiling_face:

/assign

**Comment by xmudrii** [comment]
Created PR #244 which should fix the issue
