### ISSUE TITLE
VPN Gateway, DXG attachment, and vgw routes

### ISSUE THREAD

**Issue by moensch** [kubernetes-sigs/cluster-api-provider-aws#1923]
/kind feature
/area vpc

**Describe the solution you'd like**
Original slack thread: https://kubernetes.slack.com/archives/CD6U2V71N/p1599005692025400

All clusters we make are "internal only" and the VPCs are connected to a Direct Connect Gateway (DXG) via a VPN Gateway (VGW). We currently maintain a CAPA fork to handle VGW creation, attachment to DXG, and addition of extra entries to the route table, using the VGW as a target.

With the full understanding that supporting a larger selection of network topologies is on the books (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1484), and also a potential move to ACK (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1818), I am wondering if the community would be interested in a contribution of this code to upstream regardless.

**Anything else you would like to add:**
I foresee the following changes to the Spec.

`VPCSpec` will probably need a whole new struct for `VPNGatewaySpec` for the following:
* Some flag indicating `create: true`, to tell CAPA to make one
* Store the VGW ID, will be set by the controller after creation
* ASN

The `SubnetSpec` will have to accept a list of `vpnRoutes`

I do not believe CAPA should be responsible for creating the DXG or accepting the VIFs, and instead allow the user to pass in a reference to an existing one. As such we would extend the `NetworkSpec` to hold a `DXGSpec` that would provide information to find/filter for the DXG to know which one to attach to.

**Environment:**

- Cluster-api-provider-aws version: v0.5.5
- Kubernetes version: (use `kubectl version`): n/a

**Comment by randomvariable** [comment]
Thanks for creating the issue.

As mentioned in Slack, let's table this for the 21 Sep meeting. Will add to the agenda.
