### ISSUE TITLE
Remove criticality from code paths using APIs not available as VPC endpoints

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1935]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

If operating in an AWS account without internet connectivity, access to AWS APIs may only be available via VPC endpoints in some environments.

In this scenario, some operations fail, e.g. cluster deletes do not succeed because ELBs cannot be listed via the Resource Tagging API, which is not endpoint enabled.

**What did you expect to happen:**
Cluster creates, scales, and deletes work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Review code for using VPC endpoint APIs and provide workaround where needed.

**Environment:**

- Cluster-api-provider-aws version: 0.5.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/help

**Comment by randomvariable** [comment]
We should at least document the instances the cases where various APIs may not be available. What a mess...

**Comment by gab-satchi** [comment]
I'll take a stab at it. Haven't worked with PrivateLink before so I'll look for a way to manually test it first

/assign
/lifecycle active

**Comment by ncdc** [comment]
@gab-satchi thanks! We should also try to add an e2e test for this (CAPA setup without an internet gateway).

**Comment by randomvariable** [comment]
@ncdc should go in a separate package. at most we can add an e2e test for someone to run, but can't run it in CI as we need connectivity from Prow.
