### ISSUE TITLE
e2e tests for AWSMachinePools

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1940]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add e2e tests for AWSMachinePools

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
this will help https://github.com/kubernetes-sigs/cluster-api/pull/3506
