### ISSUE TITLE
Document procedure for updating CAPA controller manager credentials

### ISSUE THREAD

**Issue by scottslowe** [kubernetes-sigs/cluster-api-provider-aws#1946]
/kind bug

**What steps did you take and what happened:**
I had to update/cycle my AWS credentials. I then needed to update the credentials being used by CAPA, but could not find any documentation on how to do so.

**What did you expect to happen:**
I expected to find documentation on how to update/edit/change the credentials that CAPA uses to interact with AWS.

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-aws version: 0.5.5 (but probably applies to any version)
- Kubernetes version: (use `kubectl version`): 1.18.2 (but probably applies to any supported version)
- OS (e.g. from `/etc/os-release`): Fedora 32 (client-side), Ubuntu 18.04 (server-side) (probably applies to any supported OS)

**Comment by scottslowe** [comment]
I have worked out the procedure for changing the credentials used by the CAPA controller manager and I will work on a PR to add this information to the documentation.

**Comment by randomvariable** [comment]
Thanks Scott!
/assign @scottslowe 
/lifecycle active
