### ISSUE TITLE
Node EC2 Instance isn't available via SSM

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1955]
/kind bug

**What steps did you take and what happened:**
Created a kind management cluster, init with the aws, eks-boostrap providers then created a cluster using the `eks` template flavor. Then tried to connect to the created EC2 instance for the node using the [SSM notes in the docs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/accessing-instances.md#accessing-nodes-via-aws-session-manager) and via the AWS managament console.

![image](https://user-images.githubusercontent.com/198425/93628714-ec419b80-f9de-11ea-94d2-d2b6e0e67878.png)

![image](https://user-images.githubusercontent.com/198425/93628795-12673b80-f9df-11ea-8f6a-dd76d4f81192.png)

![image](https://user-images.githubusercontent.com/198425/93631982-74766f80-f9e4-11ea-8951-b3950fd39ef8.png)

**What did you expect to happen:**

I would expect to be able to access the node instance

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
pro-tip

/lifecycle frozen

**Comment by randomvariable** [comment]
@richardcase PTAL and see if you want to do it for v0.7.0 or v0.7.x and change milestone appropriately.

**Comment by YanzhaoLi** [comment]
I hit the same issue.   I didn't use EKS but just follow the get-started guide: https://cluster-api-aws.sigs.k8s.io/getting-started.html
