### ISSUE TITLE
Creating EKS cluster failed

### ISSUE THREAD

**Issue by lxlxok** [kubernetes-sigs/cluster-api-provider-aws#1959]
/kind bug

Failed to create a EKS cluster by following the [doc](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/eks.md#creating-a-eks-cluster) 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```
$ clusterctl config cluster capi-eks-quickstart --flavour eks --kubernetes-version v1.17.3 --control-plane-machine-count=3 --worker-machine-count=3 > capi-eks-quickstart.yaml

Error: unknown flag: --flavour
```

```
$ clusterctl config cluster capi-eks-quickstart --flavor eks --kubernetes-version v1.17.3 --control-plane-machine-count=3 --worker-machine-count=3 > capi-eks-quickstart.yaml
Error: failed to read "cluster-template-eks.yaml" from provider's repository "infrastructure-aws": failed to download files from GitHub release v0.6.0: failed to get file "cluster-template-eks.yaml" from "v0.6.0" release
```

**What did you expect to happen:**

The command successfully generate capi-eks-quickstart.yaml without returning error

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is a doc issue, I fixed it in #1960

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
Thanks @lxlxok. A typo on my part!

The flavor name will be changing to `eks` from the 0.6.1 release
