### ISSUE TITLE
Holding issue for followups on MachinePool

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1968]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Making a note of non-critical issues so we can get #1860 in

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
From @richardcase : Add support for DefaultCooldown

**Comment by randomvariable** [comment]
Add io2 as acceptable EBS volume type.

**Comment by randomvariable** [comment]
Review cluster pause attributes

**Comment by richardcase** [comment]
- Add comment/validation to VersionNumber in AWSLauncgTemplate
- Check whether additional SG is needed for bastion access to the node - [see discussion]( https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1860#discussion_r496555444_)

**Comment by randomvariable** [comment]
Check if tags are being used and remove from exp api if unneeded.

**Comment by randomvariable** [comment]
Created separate issues for all of these, so can now.

/close
