### ISSUE TITLE
Add EKS Control Plane Provider to clusterctl

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1970]
**User Story**

As a user/operator] I would like clusterctl to support the EKS control plane provider so that i can `init` a cluster with the required providers to create EKS clusters

**Detailed Description**

Initially the EKS control plane was included in the main CAPA controller.  However, this has now been split out into its own controller. See https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1945

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by ncdc** [comment]
Transferred!
