### ISSUE TITLE
Update EKS docs after 0.6.1 release

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1971]
/kind feature

**Describe the solution you'd like**
The docs that relate to EKS need updating after the 0.6.1 release so they are inline. For instance, the flavor for use with EKS has changed names from `managed` to `eks`. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.6.0

**Comment by randomvariable** [comment]
Was thinking about this.

What I can do is update the current release and point at a specific commit, or even the v0.6.0 version of the docs.

I think it'd be better to update the docs ahead of time, so that all the docs are correct for the version tag.

**Comment by richardcase** [comment]
Sounds like a plan. Will do this after #1962 ...unless its picked up before then

**Comment by randomvariable** [comment]
Updated v0.6.0 to point exactly at v0.6.0 docs
