### ISSUE TITLE
clusterawsadm bootstrap create-cloudformation-stack fails on multiple regions

### ISSUE THREAD

**Issue by fyangd** [kubernetes-sigs/cluster-api-provider-aws#1977]
/kind bug

**What steps did you take and what happened:**
1. bootstrap a cloudformation stack in one region

2. try to bootstrap a cloudformation stack in a different region, results in the following failures:
```
export AWS_REGION=us-east-1
clusterawsadm bootstrap iam create-cloudformation-stack
Attempting to create AWS CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
Error: failed to create AWS CloudFormation stack: ResourceNotReady: failed waiting for successful resource state
Error: failed to create AWS CloudFormation stack: ResourceNotReady: failed waiting for successful resource state
```

Looking at the events, it show that it attempts to recreate global resources like IAM role.
```
2020-09-25 18:09:53 UTC-0700	AWSIAMRoleNodes	CREATE_FAILED	Resource creation cancelled
2020-09-25 18:09:52 UTC-0700	AWSIAMRoleControllers	CREATE_FAILED	controllers.cluster-api-provider-aws.sigs.k8s.io already exists
2020-09-25 18:09:52 UTC-0700	AWSIAMRoleControlPlane	CREATE_FAILED	control-plane.cluster-api-provider-aws.sigs.k8s.io already exists
```

**What did you expect to happen:**
An idempotent operation that either creates a new non-conflicting cloudformationstack or let user know to reuse the existing one in the other region (if that's possible).

**Anything else you would like to add:**
n/a

**Environment:**

- Cluster-api-provider-aws version: clusterawsadm version
```
clusterawsadm version: &version.Info{Major:"0", Minor:"5", GitVersion:"v0.5.5", GitCommit:"e46ab9168c3f97612202fe08c45c58538b0fefb0", GitTreeState:"clean", BuildDate:"2020-08-05T15:25:36Z", GoVersion:"go1.13.8", AwsSdkVersion:"v1.33.3", Compiler:"gc", Platform:"darwin/amd64"}
```
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by randomvariable** [comment]
> An idempotent operation that either creates a new non-conflicting cloudformationstack
The IAM resources are global.

> let user know to reuse the existing one in the other region (if that's possible).
This requires enumerating all of the regions. Could potentially be done, but lot of possible edge cases - not all regions are available, regions may be disabled etc...

**Comment by fyangd** [comment]
Thanks for responding, @randomvariable.  This may not be a bug with `clusterawsadm` bootstrap operation per se, but more to enable creation of `capa` clusters in multiple regions.

Based on my current understanding, since the CloudFormation stacks are regional, this would mean a new bootstrap CloudFormation stack must be created in the new region.   However, since `clusterawsadm` recreates the global IAM resources, this means the `bootstrap` operation cannot be used in the new region.  Is this correct?

If so, then what would be the user workflow to create a bootstrap CloudFormation stack in a new region if they want to deploy a `CAPA` cluster?  Or is this not supported at all?

**Comment by randomvariable** [comment]
> Thanks for responding, @randomvariable. This may not be a bug with clusterawsadm bootstrap operation per se, but more to enable creation of capa clusters in multiple regions.

Nope. Since IAM resources are global, you do not need the cloudformation stack run for every single region. It only has to be run once per account. Users should choose a "management" region where the CloudFormation is updated, and that stack sets global resources.

**Comment by fyangd** [comment]
Okay got it.  I didn't realize that the bootstrap cf stack only creates global IAM resources.  I thought it creates some regions specific resources as well.  This is good to know.  

I don't know if my feature requests to 'let user know to use an existing one in a different region" still stands.  If not, feel free to close this bug.

**Comment by jayunit100** [comment]
sounds like some kinda doc additions we can make here to clarify the way cloud formation stacks work (And dont work) when dealing w/ different regions
