### ISSUE TITLE
Support Flatcar linux for nodes

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1979]
/kind feature

**Describe the solution you'd like**
I would like to be able to use Flatcar linux for the control plane and worker nodes with CAPA.

**Anything else you would like to add:**
Documentation for running flatcar on ec2 is [here](https://docs.flatcar-linux.org/os/booting-on-ec2/). There are existing AMIs that can be used but we'd need to think about the ignition and kubeadm config.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
See also https://github.com/kubernetes-sigs/image-builder/pull/248 and https://github.com/kubernetes-sigs/cluster-api/pull/3437

**Comment by vbatts** [comment]
Having a provider like CAPA would be a good use case to test the WIP Ignition bootstrap provider in kubernetes-sigs/cluster-api#3437

**Comment by invidian** [comment]
See https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1875#issuecomment-779839267 for some progress update.

**Comment by invidian** [comment]
Created #2271 with initial implementation to resolve this and possibly #1875.

**Comment by invidian** [comment]
Should this be moved to v0.7.0 milestone the same as #2271 ?

**Comment by randomvariable** [comment]
Yup, thx.

/milestone v0.7.0

**Comment by invidian** [comment]
/remove-lifecycle stale

We're doing a good progress on https://github.com/kubernetes-sigs/cluster-api/pull/4172, we recently added missing e2e tests, a feature gate and documentation.

BTW, as CABPK decided that Ignition support will be behind a feature gate for the time being, how does it affect this PR? Can we enable the feature gate for e2e tests?

**Comment by sedefsavas** [comment]
Adding ignition support directly to the API that uses an experimental feature in the core cluster-api repository may not be the best option. We should consider feature-gating it in this repository as well.
> Can we enable the feature gate for e2e tests?

yes, we do it for other experimental feats: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/06e02b2d242d0496d0b0855d00d88b7f51b7e277/test/e2e/data/e2e_conf.yaml#L150

**Comment by invidian** [comment]
>Adding ignition support directly to the API that uses an experimental feature in the core cluster-api repository may not be the best option. We should consider feature-gating it in this repository as well.

We will do it, thanks for the advice, it make sense :+1: CC @surajssd

**Comment by invidian** [comment]
CABPK PR kubernetes-sigs/cluster-api#4172 has been merged and will be part of v1.1 release, so we're getting closer getting this resolved :tada:

**Comment by invidian** [comment]
/remove-lifecycle stale

This is still in progress.
