### ISSUE TITLE
AWSMachinePool should accept io2 EBS volume type

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1984]
/kind bug
/help
/good-first-issue

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
AWSMachinePoool has validation on EBS volume types. This should include io2.

**What did you expect to happen:**
Can use io2 volume type

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by arghya88** [comment]
@randomvariable so it just matter of adding it in `kubebuilder:validation` ?

**Comment by randomvariable** [comment]
Yup
