### ISSUE TITLE
Connectivity between bastions and AWSMachinePool nodes may not work

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1985]
/kind bug
/help

Breaking out of #1968

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

A check may need to be added to ec2.GetCoreNodeSecurityGroups to ensure that when running in EKS, the bastion security group gets added.

```
if scope.IsEKSManaged() {
   sgRoles = append(sgRoles, infrav1.SecurityGroupEKSNodeAdditional)
}
```

**What did you expect to happen:**
Can connect from bastion to machine pool instance.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by felipeweb** [comment]
The same problem occurs on AWSManagedMachinePool https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2231

Launch template logic needs some refactor to able use with managed machine pool. This PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2055 add the ability to refer launch template inside AWSManagedMachinePool, but as @michaelbeaumont said here https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2055#issuecomment-766361699 may we need to build new AMIs for EKS
