### ISSUE TITLE
Verify pause attributes are respected in AWSMachinePool

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1989]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Broken out of #1968 

Ensure that AWSMachinePool controller respects pause attributes as per CAPI spec.

**What did you expect to happen:**
Can use `clusterctl move` successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Haven't tested but at the very least we should add `ClusterUnpaused` watch to AWSMachinePool as it is not watching Clusters.

/assign
