### ISSUE TITLE
Default remote access security groups/bastion host for AWSManagedMachinePool

### ISSUE THREAD

**Issue by michaelbeaumont** [kubernetes-sigs/cluster-api-provider-aws#1990]
/kind feature
/kind cleanup
```
// SourceSecurityGroups specifies which security groups are allowed access
// An empty array opens port 22 to the public internet
```

This feels like a very dangerous default to me.

Appreciate thats the [default behavior of the SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#RemoteAccessConfig) but feels like we could protect the user a bit better. 

Perhaps for a follow up issue?

_Originally posted by @richardcase in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1916#discussion_r496694858_

### Bastion
Ideas:

* If `remoteAccess` specified without `SSHKeyName`, take the SSH key from the control plane spec.
* Add the `SecurityGroupEKSNodeAdditional` to `sourceSecurityGroups`

**Comment by randomvariable** [comment]
only comment is yowch
