### ISSUE TITLE
Remove hard-coded Calico install

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#200]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As per the [feature model](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/proposal/features.md#out-of-scope), the provider
is meant to be CNI agnostic - or more specifically agnostic of anything
that can be applied as a manifest.

#170 added a Calico install directly into the bootstrap, but
it may be possible to provide as an addons.yaml.

Calico also requires an explicit pod CIDR range, leading us to encode
the CIDR range in kubeadm init (#196).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
The calico manifest application should happen either through cluster addons or through the cluster actuator.

/kind bug
/priority critical-urgent

**Comment by randomvariable** [comment]
/lifecycle active
/assign

Supporting PR in https://github.com/kubernetes-sigs/cluster-api/pull/550

**Comment by randomvariable** [comment]
pre-req has been merged. bootstrap script in machine actuator needs updating and then tested with an appropriate addons.yaml
