### ISSUE TITLE
Remove unused allow additional roles feature flag related code

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2001]
/kind feature
/kind cleanup
/area provider/eks
/help
/good-first-issue

**Describe the solution you'd like**
In the main.go of the core manager there is code to get the value of the EKSAllowAddRoles feature flag. This doesn't appear to be used in this manager anymore and can be removed:

```go
allowAddRoles := feature.Gates.Enabled(feature.EKSAllowAddRoles)
```

Along with any related setting of this in the manager.yaml:

```yaml
 - "--feature-gates=EKS=${EXP_EKS:=false},EKSEnableIAM=${EXP_EKS_IAM:=false},EKSAllowAddRoles=${EXP_EKS_ADD_ROLES:=false}"
```

**Anything else you would like to add:**
This needs to be done post #1916 merging

**Environment:**

- Cluster-api-provider-aws version: 0.6.1

**Comment by Evalle** [comment]
I think I can help with this 
/assign
Will wait for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1916 to be merged

**Comment by Evalle** [comment]
@richardcase Hey Richard. I can see `allowAddRoles` in:
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/main.go#L165
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controlplane/eks/main.go#L143
Should I delete it in both locations? Thanks!

**Comment by richardcase** [comment]
@Evalle - thanks for working on this. It needs removing only from [https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/main.go#L165](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/main.go#L165) with is for the main manager.

The functionality that `EKSAllowAddRoles` relates to was refactored from the main manager to the controlplane.

Additionally the `EKSAllowAddRoles` flag is specified in the [config of the main manager](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/master/config) and this will need removing as well. (there is a separate confog for the control plane where it is used).

**Comment by Evalle** [comment]
Thanks a lot for the nice explanation!
