### ISSUE TITLE
Better AWS credentials management post-pivot

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#201]
/kind feature

**Describe the solution you'd like**

As part of the bootstrap, users need to provide AWS credentials
in the provider components manifest so that the controllers
can spin up AWS infrastructure from minikube.

It then pivots the manifests to the new cluster, however,
`clusterawsadm` creates an IAM role and instance profile
for this purpose, so some way of removing the env vars
for the controllers post install is needed. Could be done as:

* End-user documentation on editing the deployment
or
* Get the deployer to patch the provider components 
or
* Make it a clusterawsadm command

We should also support session tokens during bootstrap, e.g.
someone is assuming role to deploy the cluster, or is otherwise
using a temporary session.

**Comment by detiber** [comment]
Upstream cluster-api issue: https://github.com/kubernetes-sigs/cluster-api/issues/556

**Comment by randomvariable** [comment]
This is more or less resolved by moving away from the idea of pivoting by default, which has been done in the quick start.

/close
