### ISSUE TITLE
AWSMachinePool does not work in combination with cluster-autoscaler

### ISSUE THREAD

**Issue by dthorsen** [kubernetes-sigs/cluster-api-provider-aws#2022]
/kind bug

**What steps did you take and what happened:**

- Create a workload cluster with the experimental EKS Control Plane
- Create a MachinePool without specifying replicas and create associated AWSMachinePool resources.
- Install cluster-autoscaler and configure it to autoscale the autoscaling group managed by the AWSMachinePool
- Create a deployment that will trigger cluster-autoscaler to scale up the autoscaling group.

This caused the AWSMachinePool controller and the cluster-autoscaler to both attempt to manage DesiredInstances. The result being the DesiredInstances value on the ASG was alternating between the value cluster-autoscaler computed as needed and the value of `replicas: 1` coming from the defaulted value on the MachinePool object.

**What did you expect to happen:**
cluster-autoscaler should manage the `DesiredInstances` of the autoscaling group and the AWSMachinePool controller should ignore changes to the `replicas` and `DesiredInstances` fields.

**Anything else you would like to add:**
Even though `replicas` is an optional field on the MachinePool resource, it defaults to 1, so leaving the value unspecified is insufficient to prevent the AWSMachinePool controller from attempting to managed the DesiredInstance count.

**Environment:**

- Cluster-api-provider-aws version: Commit: 3338cd4
- Kubernetes version: (use `kubectl version`): v.1.17.9
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Comment by randomvariable** [comment]
I'm not sure this is a bug actually, there's going to be a clash of behaviour here. 

I think you'll want to use the Cluster API variant of Cluster Autoscaler? @benmoss is more knowledgeable in this area.

**Comment by dthorsen** [comment]
@randomvariable There is indeed a clash of behavior. I listed it as a bug because it failed to operate in the manner we originally designed due to the fact that the MachinePool replicas can't really be nil. The original thought being, if you don't set replicas at all, then CAPA won't manage replicas/DesiredInstances. If you want CAPA to manage them, then you set replicas. That seemed like a sensible interface.

At the moment there are no Machine or AWSMachine objects created from a MachinePool. Only Node objects. For the time being for our use cases, we planned to use CAPA to create the ASG's and let cluster-autoscaler manage scaling. It enables us to take advantage of cluster-autoscaler's full feature set today including things like scale to and from 0. I think a field in the spec would be a good idea to make this behavior configurable for the user. I am not certain it should be a deprecated field. It is hard to imagine all the possible use cases around autoscaling groups and where the replica count may be best controlled. I have been told also that cluster-autoscaler is frequently forked and customized for special use cases. I think flexibility in the interface could be valuable for the foreseeable future.

**Comment by randomvariable** [comment]
Interesting data point for @elmiko too here.

**Comment by elmiko** [comment]
thanks for the ping @randomvariable , an interesting issue for sure.

i agree with @randomvariable , there is a clash happening between the MachinePool and the way the cluster-autoscaler is attempting to scale. i don't know the MachinePool mechanics very well, but from the cluster-autoscaler side the capi provider attempts to manipulate the MachineSet and MachineDeployment replicas when it wants to scale. if these replica counts are disjointed from the MachinePool then i could envision some unexpected behavior.

**Comment by dthorsen** [comment]
That is correct @elmiko, this behavior is observed when operating cluster-autoscaler with the AWS provider, not the CAPI provider. In our local installation we have worked around this for now by simply telling CAPA not to react to replicas as long as replicas is set to 1. This allows cluster-autoscaler to work, so if we had a field in the AWSMachinePool spec to more properly ignore replicas, that would allow cluster-autoscaler with AWS provider to just work as it would with any other ASG.

**Comment by elmiko** [comment]
that makes sense @dthorsen, seems like this is really a feature request to add something that will ignore the replicas in this type of situation.

**Comment by benmoss** [comment]
I don't really understand this, why does the AWSMachinePool controller keep changing `DesiredInstances`? It's not clear this is an autoscaler bug, seems more appropriate to file it against CAPA.

**Comment by dthorsen** [comment]
@benmoss This bug is filed against CAPA, not cluster-autoscaler. 

@elmiko I am OK with changing it to a CAPA feature request instead of a CAPA bug if that is based on the context provided. I only listed it as bug because it did not behave as we initially designed it.

**Comment by benmoss** [comment]
Hah, my mistake 😸

**Comment by dthorsen** [comment]
I propose that we add an optional field to the AWSMachinePool spec called `ignoreReplicas` which defaults to `false`. The reconciliation logic will use this field to ignore the MachinePool replicas field and to always omit `DesiredInstances` field in any requests to the AWS AutoScalingGroup API.

@MarcusNoble @randomvariable Does this sound like an acceptable solution?

**Comment by MarcusNoble** [comment]
Sounds good to me. Just not 100% sure on the naming. `replicas` makes me think about kubernetes resources rather than ASG instances. How about something like `ignoreDesiredSize` ?

**Comment by dthorsen** [comment]
@MarcusNoble Hmm, technically we are ignoring both when this is set. From cluster-api user's perspective, if they update `replicas` on the MachinePool Kubernetes resource, the controller will do nothing if this field is set.

**Comment by MarcusNoble** [comment]
That is a good point. The name makes sense then.

The alternative is to handle an unset `replicas` value as meaning ignore, rather than setting a new property.

**Comment by dthorsen** [comment]
That was the original intent, but the code doesn't work as intended because replicas will never be nil (also incidentally why I originally opened this issue as a bug). It will be defaulted to a value of 1 if omitted. It also occurred to me that using replicas to indicate "don't reconcile this value" is a pretty fragile indicator. If cluster-autoscaler has scaled up the pool to say, 100 instances, and someone comes back and misunderstands how it works and sets replicas to 120, AWSMachinePool will suddenly begin reconciling replicas and scale up to 120 instances. Then cluster-autoscaler will try to scale down, and we are back into a thrashing scenario. I think based on this feedback I am going to start on a PR to implement a proper ignoreReplicas spec field.

**Comment by dthorsen** [comment]
@MarcusNoble @randomvariable I am finally getting back to this work. Sorry for the delay. After I observed the following behavior in our clusters, I realized the poor UX of totally ignoring the replicas field:
```
$ kubectl get machinepool
NAMESPACE         NAME                                                     REPLICAS   PHASE         VERSION
test-cluster      test-cluster-nodes-a                                     10         ScalingDown   v1.17.12
```
The MachinePool controller thinks this pool is always "scaling down" because the `replicas` field in the spec is set to 1 on the MachinePool, but the replicas field on the status has a value of 10. I am leaning toward making this field called something more like `externallyManagedReplicaCount`, and enhance the logic to have the AWSMachinePool reconciliation loop update the MachinePool .spec.replicas field too in order to make the UX a bit more sane. 

An alternative approach I think would be some change to the MachinePool spec that allows delegation of replica control to the infrastructure provider at the CAPI level instead of doing this at the infrastructure level. I'd like to hear your input as to which approach would make more sense.

**Comment by MarcusNoble** [comment]
Where's the value of 10 coming from on the status? Is that the current number of ASG instances?

**Comment by randomvariable** [comment]
@dthorsen you might want to chat to @devigned and @CecileRobertMichon , as there's similar discussion there, and we are likely to change MachinePools in v1alpha4. See https://github.com/kubernetes-sigs/cluster-api/issues/4063

**Comment by devigned** [comment]
How would `nil` replicas work with K8s version upgrades? In https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/819 we are planning on enabling MaxUnavailable and MaxSurge for safe rolling upgrade scenaios. These scenarios both implicitly require an understanding of the desired number of replicas. Seems like externalizing management of replica count would impair other behaviors or at a minimum require some coordination for other behaviors. Would it not make more sense to inform CA that the infra is managed by a CAPI and to manipulate replica counts via CAPI `MachinePool`?

**Comment by dthorsen** [comment]
Thank you @randomvariable.

@devigned replicas is not nil, it is not allowed to be nil as it will default to 1. The conversation going on in kubernetes-sigs/cluster-api#4063 is interesting. I'll chime in a bit in that thread as well. My goal was to push more of the instance management logic into the underlying Cloud Provider. Be able to utilize things like Instance Refresh, and Managed Node Groups, and enable cluster-autoscaler to use the AWS provider.

**Comment by randomvariable** [comment]
@dthorsen from the discussion in Slack, I think in your fork you have the API change in CAPI rather than CAPA. Can you open up an issue there? We can continue with this one for tracking...

**Comment by dthorsen** [comment]
@randomvariable The field is set in CAPI, but the implementation is delegated to the providers. So I will have a PR to both CAPI and CAPA when I'm done. I'm starting on this now.

**Comment by dthorsen** [comment]
> How would `nil` replicas work with K8s version upgrades? In [kubernetes-sigs/cluster-api-provider-azure#819](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/819) we are planning on enabling MaxUnavailable and MaxSurge for safe rolling upgrade scenaios. These scenarios both implicitly require an understanding of the desired number of replicas. Seems like externalizing management of replica count would impair other behaviors or at a minimum require some coordination for other behaviors. Would it not make more sense to inform CA that the infra is managed by a CAPI and to manipulate replica counts via CAPI `MachinePool`?

@devigned In the case of something like Azure Managed Machine Pools, I think the upgrade has to be handled by the cloud provider anyway. For the unmanaged AzureMachinePools, I am not sure yet. AWS has a concept of Instance Refresh we use to rotate the instances at the cloud provider level, so it is not an issue there. Does VMSS have a similar API?

**Comment by devigned** [comment]
> @devigned In the case of something like Azure Managed Machine Pools, I think the upgrade has to be handled by the cloud provider anyway. For the unmanaged AzureMachinePools, I am not sure yet. AWS has a concept of Instance Refresh we use to rotate the instances at the cloud provider level, so it is not an issue there. Does VMSS have a similar API?

For AMMP, that would be an update to AKS and then it would handled there. AKS also has the min / max settings for autoscaling, and that should soon be configurable on the AMMP. 

As for AMP, replicas `nil` kind of makes sense when using CA to manage pools directly through the cloud's API rather than through CAPI. However, some of the work going on in the [MachinePoolMachines proposal](https://docs.google.com/document/d/1y40ayUDX9myNPHvotnlWCvysDb81BhU_MQ7G9_yqK0A) would allow CA to treat MDs and MPs in a similar manor and then mutate the machines and replicas through CAPI, which seems preferable than directly using the cloud APIs.

**Comment by dthorsen** [comment]
In the implementation in our fork of CAPI/CAPA, we have used the `externallyManagedReplicaCount` field on the MachinePool to reverse the flow of reconciliation. The infrastructure provider updates the `spec.replicas` and relevant status fields on the MachinePool every reconciliation loop. So the replicas are not nil, in fact if I recall correctly it isn't possible to have replicas be nil. If it is set to nil, it effectively defaults to `1`.

I think you are correct that having the node pool scaler drive replicas through CAPI is more appealing for certain use cases, once the implementation is available and production-ready. It is worth noting that the `externallyManagedReplicaCount` feature is just an alternate (optional) configuration and permits additional flexibility with regard to node pool scalers, leaving this preference up to the cluster operator. The `externallyManagedReplicaCount` MachinePool feature does not prevent the features being planned in the MachinePoolMachines proposal from proceeding. The features are actually complementary, because having MachinePoolMachines will still be useful in the `externallyManagedReplicaCount` case for things like MachineHealthChecks.

**Comment by elmiko** [comment]
not sure if this will satisfy this issue, but i did see that @mboersma put up this wip pr to the autoscaler, https://github.com/kubernetes/autoscaler/pull/4676

i'm excited to see the progress here =)


/remove-lifecycle stale

**Comment by elmiko** [comment]
> This is exciting to see but unfortunately doesn't cover all use cases. Our use case for example is to have cluster-autoscaler running in the workload clusters and operate as normal (without any knowledge it's CAPA) to remove the load and single point of failure that having a single cluster-autoscaler on the management cluster would have.

in that case though, what is the integration between the cluster api MachinePool object and the cluster autoscaler? does the MachinePool just need to be updated about what has happened in the workload cluster or is there another concern i'm missing?

**Comment by AverageMarcus** [comment]
Ideally, this approach: https://github.com/kubernetes-sigs/cluster-api/pull/5685

Allowing something other than cluster-api to handle the desired replicas while still having it control the min/max of a pool.

**Comment by AustinSiu** [comment]
Hi all, I just wanted to ask what was the latest status of this issue? It looks like there are at least a few possibly related PRs in progress.

**Comment by AverageMarcus** [comment]
There's been a lot of progress on handling this via an annotation on the MachinePool:

* CAPI PR - https://github.com/kubernetes-sigs/cluster-api/pull/7107/files
* CAPA WiP PR - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683
* CAPZ merged PR - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2444

It looks like that is the direction this implementation is going. @dthorsen do you see any issues with the annotation-based approaches being worked on? Wondering if we consider closing this issue and PRs in favour of those.

**Comment by dthorsen** [comment]
@AverageMarcus I think the annotation-based approach will be sufficient for this use-case. This issue is still valid until the annotation-based solution PR's are merged so I'd recommend leaving this open and linking it to the relevant PR's.

**Comment by Skarlso** [comment]
I have to read this whole discussion, but is it possible that we just disable certain AWS ASG processes with this PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3741? 

It would allow to cluster-autoscaler just do its thing?

**Comment by dthorsen** [comment]
@AverageMarcus I propose we leave this issue open until the required annotation PRs are merged. I have closed my other PR: kubernetes-sigs/cluster-api#5685
