### ISSUE TITLE
AWSMachinePool - Subnets aren't fetched using filter

### ISSUE THREAD

**Issue by MarcusNoble** [kubernetes-sigs/cluster-api-provider-aws#2047]
/kind bug

**What steps did you take and what happened:**
When using `AWSMachinePool` you're required to specify the `Subnets` property in the spec otherwise the ASG fails to create. This value is typed as `infrav1.AWSResourceReference` which provides the ability to specify using IDs, ARNs or Filters but the `AWSMachinePool` only uses ID for subnets.

**What did you expect to happen:**
The `Filters` (or `ARN`) are also valid options to provide and cluster-api will look up the appropriate subnets.

_Alternatively..._ it would be good is `Subnets` was optional and if not provided it defaults to the private subnets associated with the control plane.

**Anything else you would like to add:**
Relevant code block: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f6a97de9ba98338e58bf1afafb71ece60db5b394/pkg/cloud/services/autoscaling/autoscalinggroup.go#L143-L146

**Environment:**

- Cluster-api-provider-aws version: 0.6.1
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): N/a

**Comment by richardcase** [comment]
I agree, if no subnets are supplied it should fall back to the subnets on the **AWSCluster** or **AWSManagedControlPlane**

**Comment by MarcusNoble** [comment]
/close 

Closing as covered by #2087 and the alternative fallback implemented in #2051
