### ISSUE TITLE
Support using IAM for Service Accounts on the management cluster components

### ISSUE THREAD

**Issue by MarcusNoble** [kubernetes-sigs/cluster-api-provider-aws#2053]
/kind feature

**Describe the solution you'd like**
Add the ability to make use of [IAM for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) as an alternative to providing credentials (Access key and secret from the `AWS_B64ENCODED_CREDENTIALS` env var) for the management components to make use of.

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-aws version: 0.6.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
This is something that @michaelbeaumont  and me discussed previously....this would be really good to add.

**Comment by michaelbeaumont** [comment]
There was also [a short discussion with @randomvariable](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1916#discussion_r494905820) in the AWSManagedMachinePool PR.
