### ISSUE TITLE
AWSManagedMachinePool - Launch Template support

### ISSUE THREAD

**Issue by michaelbeaumont** [kubernetes-sigs/cluster-api-provider-aws#2055]
/kind feature

**Describe the solution you'd like**
The managed EKS nodegroups backing AWSManagedMachinePool [support launch templates](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/). This functionality was put on hold until both the `AWSMachinePools` and `AWSManagedMachinePools` support was merged.

**Anything else you would like to add:**
Discussed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1916#issuecomment-700741381

**Comment by michaelbeaumont** [comment]
@richardcase @felipeweb Right now, `AWSMachinePool` supports setting a limited number of options for launch templates inline with the resource, most of which are covered by the `Nodegroup` API in the `AWSManagedMachinePool` case. I think it would make the most sense to only support referencing a launch template by ID with `AWSManagedMachinePool`. WDYT?

**Comment by felipeweb** [comment]
IMHO we need to be able to add the extra kubelet args passed in the EKSConfig object in the Launch template even if an Launch template ID is not passed to the mamagedmachinepool. The node-label argument must to be added https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b7294cef139c2642036592489e431b0fdf5bb59a/pkg/cloud/services/eks/nodegroup.go#L168 too and other fields we need to pass in userdata because nodegroup creation does not support passing those fields as parameter. here is an example how eksctl does this https://github.com/weaveworks/eksctl/blob/master/pkg/cfn/builder/managed_launch_template.go#L191-L193

**Comment by michaelbeaumont** [comment]
It's slightly more complicated I think, `eksctl` doesn't allow you to pass arbitrary kubelet args to a managed nodegroup.
The user data for managed nodegroups must follow the guidelines laid out [in the docs](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data) which prevent the userdata from calling the bootstrap directly, I believe, because the user data is merged _unless_ using a custom AMI.

**Comment by randomvariable** [comment]
@richardcase up to you where you want to do this.
I think one of us, me, @JoelSpeed or you were going to diff options with AWSMachine.

**Comment by richardcase** [comment]
Yeah we need to do the diff and come up with a solution that i think we should document via an ADR. I'm happy to do this diff before the next office hours.

**Comment by wmedlar** [comment]
Hi @richardcase ! Have there been any developments in the design for this?

**Comment by richardcase** [comment]
@wmedlar - there was a call a while back but i didn't go to it as i had a clash. @randomvariable @sedefsavas - was there any outcome of the call around launch templates?

**Comment by sedefsavas** [comment]
Folks in that meeting agreed on having a separate LaunchTemplate resource that can be used by different resources.

The meeting notes of that meeting are in our regular office hour notes, search for `Spot Instance Support Special Meeting
`
https://docs.google.com/document/d/1iW-kqcX-IhzVGFrRKTSPGBPOc-0aUvygOVoJ5ETfEZU/edit#

**Comment by richardcase** [comment]
Thanks @sedefsavas

**Comment by richardcase** [comment]
@JoelSpeed - are you working on this? Or would you be happy for me to pick this up and other issue related to launcg templates in CAPA?

**Comment by JoelSpeed** [comment]
I've not got any real bandwidth to work on this for at least a month, feel free to take over, let me know if I can help in any way with reviews etc

**Comment by richardcase** [comment]
> I've not got any real bandwidth to work on this for at least a month, feel free to take over, let me know if I can help in any way with reviews etc

Great, thanks @JoelSpeed ....will certainly take you up on a review :)

**Comment by randomvariable** [comment]
Is this still active?

**Comment by richardcase** [comment]
I'm going to introduce a new `AWSLaunchTemplate` kind with associated controller that will create launch templates and a reference to this can be used in `AWSManagedMachinePool`. Any objections / concerns?

**Comment by JoelSpeed** [comment]
Sounds good to me, let me know when you need review

**Comment by richardcase** [comment]
I need to make some small updates based on the feedback
