### ISSUE TITLE
[e2e] Add cluster-template-conformance-ci-artifacts.yaml to e2e_conf.yaml

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2061]
/kind bug

e2e conformance test is using `cluster-template-conformance-ci-artifacts.yaml` which is generated under `_artifacts/templates/`, but is not added to e2e_conf.yaml as sourcepath.

Related issue: https://github.com/kubernetes/kubernetes/issues/95730

**Comment by fabriziopandini** [comment]
If this file is generated before the e2e test run (e.g. by some script), you can add it to your e2e configuration
Otherwise, I see two options:
- generate the file under the repository/provider/version folder
- make the apply template file to read a file from a different location, which is currently supported by clusterctl, but not exposed by the current helper

**Comment by sedefsavas** [comment]
It is generated during e2e tests.
For the first option we may need to pass a path here https://github.com/kubernetes-sigs/cluster-api/blob/169440de58bb676909af1e400f8cede84d0120fb/test/framework/kubernetesversions/template.go#L59

**Comment by fabriziopandini** [comment]
I don't have a full picture of how this code works, but it looks like you can pass the path as artifact directory

**Comment by sedefsavas** [comment]
Yes, and artifacts path is an environment variable, so adding this path to the config.yaml as sourcePath is the problem.

**Comment by fabriziopandini** [comment]
If you pass the target path as a input for this func https://github.com/kubernetes-sigs/cluster-api/blob/169440de58bb676909af1e400f8cede84d0120fb/test/framework/kubernetesversions/template.go#L37 this will override the env variable. happy to zoom about this if you think it will help

**Comment by sedefsavas** [comment]
@fabriziopandini Opened a PR to show what I mean. Passing artifacts path but since that is a variable set in Makefile, cannot use it directly in e2e_conf.yaml, because we don't do variable parsing on the sourcePaths.

**Comment by fabriziopandini** [comment]
My idea was the other way around
To make `GenerateCIArtifactsInjectedTemplateForDebian`  to generate the template under  `_artifacts/repository/infrastructure-aws/v0.X.y/` by setting the artifacts path [here](
https://github.com/kubernetes-sigs/cluster-api/blob/169440de58bb676909af1e400f8cede84d0120fb/test/framework/kubernetesversions/template.go#L37)

**Comment by sedefsavas** [comment]
Solved by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2018
