### ISSUE TITLE
Provide a mechanism to add Kubernetes tags to BYO Subnets

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#2069]
/kind feature

**Describe the solution you'd like**
Adding in a cluster to an existing VPC through the BYO-VPC and BYO-Subnet leaves a major frustration point which is properly tagging the AWS subnets for the Kubernetes Cloud Controller Manager so that services can correctly find the private subnets or public subnets to apply load balancer listeners.  Provide some mechanism to add these tags to those subnets, even if they're BYO-VPC or BYO-Subnet.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
Bring your own was always explicitly "do not attempt to manage" so is out of scope I think for that. However, adoption could be a valid use case for #1484

**Comment by randomvariable** [comment]
/close

Rally in #1484
