### ISSUE TITLE
Upgrade go version to 1.15.3

### ISSUE THREAD

**Issue by arghya88** [kubernetes-sigs/cluster-api-provider-aws#2076]
/kind cleanup

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Current go version is 1.13. This should be upgraded to latest 1.15.3
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
We need to update controller runtime first, which depends on moving CAPI to v1alpha4. So assigning to v0.7.0

**Comment by randomvariable** [comment]
We're going to have to upgrade to v1.16 for v1alpha4, so will just close this.
