### ISSUE TITLE
Better handle cluster identification to take into account that clusters/machines are namespaced

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#208]
/kind bug

/priority important-soon

**Comment by chuckha** [comment]
cluster-api says cluster and machine must be in the same namespace and one cluster per namespace

**Comment by timothysc** [comment]
This cross-links with upstream conventions.  Please include me in these conversations.

**Comment by vincepri** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/issues/41

**Comment by detiber** [comment]
I'm not sure this issue is completely resolved...  What happens if a cluster with the same name is created in two different namespaces? I believe that they will try to reconcile the same resources based on the current tagging mechanism we have.

**Comment by vincepri** [comment]
I believe the cluster selection only happens within the same namespace https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L206-L209

**Comment by detiber** [comment]
Right, but I'm thinking about the underlying reconciliation with AWS resources
