### ISSUE TITLE
AWSResourceReference unimplemented logic

### ISSUE THREAD

**Issue by MarcusNoble** [kubernetes-sigs/cluster-api-provider-aws#2087]
Collating all instances of `AWSResourceReference` being used in the codebase without implementing all lookup logic (e.g. only using the `ID` property)

| Type | Property | References | ID | ARN | Filters |
| --- | --- | --- | --- | --- | --- |
| `AWSMachineSpec` | `AMI` | https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2e24bd127d875995ed13699966e60b9e12060cb2/pkg/cloud/services/ec2/instances.go#L132-L134 | ✅ | ❌ | ❌ |
| `AWSMachineSpec` | `AdditionalSecurityGroups` | https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2e24bd127d875995ed13699966e60b9e12060cb2/controllers/awsmachine_security_groups.go#L62-L64 | ✅ | ❌ | ❌ |
| `AWSMachineSpec` | `Subnet`| https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2e24bd127d875995ed13699966e60b9e12060cb2/pkg/cloud/services/ec2/instances.go#L261-L343 | ✅ | ❌ | ✅ |
| `AWSMachinePoolSpec` | `Subnets` | https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2e24bd127d875995ed13699966e60b9e12060cb2/pkg/cloud/services/autoscaling/autoscalinggroup.go#L144-L146 | ✅ | ❌ | ❌ |

**Comment by MarcusNoble** [comment]
It looks as though there aren't as many instances as first thought.

If ignoring test files and generated files `AWSResourceReference` is only made use of in 4 places.

All 4 make use of the `ID` property, one makes use of the `Filters` property and there are no instances where `ARN` is used.

**Comment by sedefsavas** [comment]
lifecycle/stale

**Comment by Ankitasw** [comment]
@sedefsavas @richardcase Just to clarify, here we need to implement lookup logic for fields which are of type  `AWSResourceReference` and using any of the properties(ID, Filters) from `AWSResourceReference` in the respective codes.

**Comment by shivi28** [comment]
Pasting slack discussion here for others reference:
Scope of this issue is 
```
if subnet id is there, do a lookup using that
if filter is there, do a lookup using that
If both are given then throw a validation error 
```
But currently in our code we are only doing lookup by IDs.

So a [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3255) is raised which will implement above logic for `AWSResourceReference` in `AWSMachinePool.Spec.Subnets` during ASG creation/updation.

/assign @shivi28

**Comment by Ankitasw** [comment]
> /assign @shivi28

I have [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2609) issue assigned to you which handles all the things mentioned above.
Do we still need this issue on your name?
