### ISSUE TITLE
instance type check for zone availability in AWS

### ISSUE THREAD

**Issue by asatish** [kubernetes-sigs/cluster-api-provider-aws#2106]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

 CAPA tries to place the control plane nodes in different availability zones for every node in the control plane pool. But, in AWS there are some instances which are not present in some availability zones, due to which the AWS SDK is returning an error. 

E1105 11:00:07.187357       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AWSMachine instance: failed to run instance: Unsupported: Your requested instance type (r6gd.large) is not supported in your requested Availability Zone (us-east-2a). Please retry your request by not specifying an Availability Zone or choosing us-east-2b, us-east-2c.\n\tstatus code: 400, request id: ffcec3c4-0248-41db-a3b6-efef54eb939e" "controller"="awsmachine" "name"="mukesh-aws-control-plane-vvncs" "namespace"="spektra-tenant2"

**What did you expect to happen:**

To fix this, ideally CAPA needs to place the node with consideration for the instance type availability in the zone.  

AWS documentation explaining the issue and how to identify and resolve it:
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-instance-type-not-supported-az-error/

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.5.5
- Kubernetes version: (use `kubectl version`): 18.8
- OS (e.g. from `/etc/os-release`): centos

**Comment by Promaethius** [comment]
Could you share the cluster YAML definition you are using in this particular setup?

**Comment by asatish** [comment]
For the YAML, I would suggest to use clusterctl, the important thing is to set the instance type as r6gd.large, control plane count as 3 and the region as us-east-2. 

export AWS_REGION=us-east-2
export AWS_SSH_KEY_NAME=default
export AWS_CONTROL_PLANE_MACHINE_TYPE=r6gd.large
export AWS_NODE_MACHINE_TYPE=r6gd.large

clusterctl config cluster capa-cluster \
  --kubernetes-version v1.18.8 \
  --control-plane-machine-count=3 \
  --worker-machine-count=1 \

**Comment by Promaethius** [comment]
Because this is a fringe case, I would encourage you to manually edit your resulting cluster definition and add the `failureDomain:` property to your control plane machine definitions. It allows you to specify the availability zone.

**Comment by asatish** [comment]
Sure, I can do this in the interim until this issue is fixed, but it would be good to fix this in CAPA itself. Not having the fix in CAPA means the user needs to find beforehand if the instance type is present in which zones in the region and if they are not available in all regions, they would need to use a different flavor for cluster template YAML to specify the failuredomain. Having CAPA place the control planes in different failure domains automatically is a nice thing..

**Comment by Promaethius** [comment]
/assign

I should make it clear that this isn't a bug. CAPA behaves as expected and
relays the error message and configuration issue back to the end user. AWS
allows this instance type only in a subset of availability zones while
CAPA's best practice programming attempts to spread it out over all
availablity zones. This is exactly why we have configuration for
machineTemplates. You're welcome to submit a MR with an availablity zone
lookup feature.
