### ISSUE TITLE
[e2e] Disable BootstrapUser from the IAM configuration in e2e tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2115]
v0.5.5 and later will, by default, remove the bootstrap user and group. Current e2e tests enable it: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e61516f73f0f1ca68d351124b3ab311842b15899/test/e2e/e2e_suite_test.go#L406

We should either remove this or also test the default behavior as described here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md

**Comment by randomvariable** [comment]
We do actually want to keep this because it's a good way of testing the permissions are sufficient.

**Comment by sedefsavas** [comment]
Got it, thanks. Closing this issue.
