### ISSUE TITLE
Allow to decide the maximum number of NAT gateways to create

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#2118]
/kind feature

**Describe the solution you'd like**
While creating a cluster I noticed that we're creating one NAT gateway for each subnet/availability zone. NAT gateways have a fixed per hour cost which might be expensive in small development environments.

It'd be great to provide more ways to customize the behavior that CAPA has when creating a cluster by providing a few options under the networking spec:

- Allow to specify the maximum amount of NAT gateways that we're able to create
- Allow to specify if we can route NAT gateways across subnets in availability zones; this has the downside that cross-AZ traffic is charged and it should be defaulted to false.
- Allow users to create public-only subnets

/cc @randomvariable @sedefsavas

**Comment by randomvariable** [comment]
v1alpha4 should address this, however, if you're going for a HA control plane, then you really should have one NAT gateway per AZ otherwise your failure domain might not be what's expected.

**Comment by vincepri** [comment]
> then you really should have one NAT gateway per AZ

That's fair, I was more hoping to get the option out there. If folks are testing out NAT gateways can be expensive to run

**Comment by randomvariable** [comment]
Going to fold into #1484
