### ISSUE TITLE
Retrieve kustomize release binary instead of building it

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2122]
cluster-api recently did this change: https://github.com/kubernetes-sigs/cluster-api/pull/3744.
To avoid any future dependency conflicts, we may want to apply this here as well.

**Comment by randomvariable** [comment]
I would say, it would be preferable to do it entirely within the Makefile rather than shelling out to a separate script. There's some examples already of this in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/hack/tools/Makefile#L125

**Comment by randomvariable** [comment]
I fixed the problem with building on MacOS, so don't think we need this anymore.

/close
