### ISSUE TITLE
Run e2e tests in parallel

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2131]
Our e2e tests takes too long.

As per @randomvariable's suggestion (https://kubernetes.slack.com/archives/CD6U2V71N/p1606757258017600), we can run tests in parallel (except VPC limit test).

**Comment by richardcase** [comment]
We will quickly run into EIP limits even with a small number of parallel tests.

**Comment by randomvariable** [comment]
Been thinking more about this, I think the urgency has increased as we keep adding HA clusters to the e2e without solving this.

Ideally we need something along the lines of the following:

- A cross process pool that can be shared across the ginkgo nodes. This is probably going to be file based (flock or sqlite3).
- Create pools for VPC, NAT and EC2 and other contended resources
- Each test declares what they're going to consume from those pools and subtract accordingly
- When a test completes, they "return" resources

- Separately, we need to eliminate changing the behaviour of a test based on changing the environment variable.
