### ISSUE TITLE
Add support for gp3 EBS volumes, and switch AMIs to gp3 by default

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2136]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

gp3 EBS volumes are cheaper and higher performing, so makes sense to now default to it.

A couple of tasks:

- Bump the AWS SDK for Go version to at least v1.35.37
- Allow gp3 in webhook validations
- Check gp3 support across regions - if it's everywhere then:
  - Update image builder to default to gp3 for all new AMIs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/help
/priority backlog

**Comment by randomvariable** [comment]
/hold

let's wait for the rest of re:invent announcements

**Comment by kkeshavamurthy** [comment]
Seems like gp3 volumes are available in all regions. [link](http://shepherd.run/namespace/tsm_system_tests/lock/d5746f75-233b-4aab-b8b6-43d284aed1a0/logs/)

> gp3 volumes are available in all AWS commercial and gov cloud regions.

**Comment by randomvariable** [comment]
Yup, gp3 volumes weren't available for root volumes when I filed this issue, but they've fixed it now.

I think https://github.com/kubernetes-sigs/image-builder/pull/452 fixes this, so 

/close

**Comment by randomvariable** [comment]
/open

We still need to add the validation allowance.
