### ISSUE TITLE
Make subnet field optional in AWSMachinePool to fallback to cluster subnets

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2137]
/kind bug

**What steps did you take and what happened:**
AWSMachinePool requires subnets (AWSMachinePool.spec.subnets) which is preventing the use of fallback logic implemented here: [#2051] and [#2095].

**What did you expect to happen:**
I expect AWSMachinePool to work without providing any subnets and use auto-created subnets attached to the AWSCluster.

This is API change but I suppose not breaking. We can do it in v0.7.0 too.

cc @MarcusNoble

**Comment by MarcusNoble** [comment]
@sedefsavas What error are you seeing here exactly? I've been able to create an AWSMachinePool without specifying subnets and it has correctly used the fallback logic.

Is this just an issue when running the tests? It looks like this: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2138/files#diff-9e1ddec7491885958965554ceab719f6fd0be3b168323d2e45392ec3dd36a3b6R103 would be causing problems as if no subnets are provided you're still creating an array with 1 empty item I think.

**Comment by sedefsavas** [comment]
@MarcusNoble you are right, since subnets type is list, OpenAPI does not enforce it to be required when optional field is not there (didn't realize that). Nonetheless your PR improves readability.

**Comment by sedefsavas** [comment]
Not a bug.
