### ISSUE TITLE
Add code coverage analysis as part of prow PR feedback

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2144]
Running unit tests with coverage in Prow gives useful insight which we can benefit to see which parts are missing coverage. E.g.: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#periodic-cluster-api-provider-azure-coverage&show-stale-tests=

Since there will be big restructuring in terms of networking for the upcoming v0.7.0 release, we don't need to invest immediately to make improvements in the coverage IMO but it would be good to see the coverage. 

We can either regular go test --coverage (e.g.,: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/b608470f59d54707fffed8c3112a47b201c4633f/Makefile#L160) or prow's coverage tool:
https://github.com/kubernetes/test-infra/blob/master/robots/coverage/docs/design.md

/priority backlog

**Comment by randomvariable** [comment]
Tried doing it in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1891 but couldn't get it to work

**Comment by sedefsavas** [comment]
Ah okay, I see that Azure also doesn't use that library and uses `go tool cover`

**Comment by randomvariable** [comment]
Cool, i think it was gopherage that was giving me problems.
