### ISSUE TITLE
Make controller IAM policies specific to each controller

### ISSUE THREAD

**Issue by MarcusNoble** [kubernetes-sigs/cluster-api-provider-aws#2146]
/kind feature

**Describe the solution you'd like**
Currently the controllers use a single IAM policy (`AWSIAMManagedPolicyControllers`) to cover all their required actions. It would be good to split these out into more specific policies to avoid giving unnecessary permissions. 

**Anything else you would like to add:**
This would be useful to be able to provide an IAM role for the controllers to use (making use of Kiam or IRSA) - some changes would need to be made to support using different roles.

It would be good to also have a policy that can be generated to create a role in another account that can be assumed when #1919 (multitenancy) is available.

**Comment by randomvariable** [comment]
Do we still want to do this given we merged the controllers together?
