### ISSUE TITLE
Properly handle deleting a cluster when machines exist

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#215]
/kind bug

Need to determine what the proper behavior here should be.
- Should deleting a cluster recursively delete all machinedeployments, machinesets, and machines in a cluster?
- Should deleting a cluster error or be blocked on existing machines?
- Should deleting a cluster that is hosting the cluster-api have any special behavior?

/priority important-soon

**Comment by phyber** [comment]
Thinking of this in terms of `rm` on a directory, I might have:

 - `rm cluster`: Error if cluster still contains things (like `rmdir` would if a directory contained stuff), otherwise remove the cluster.
 - `rm -r cluster`: Recursively delete the cluster. Delete the machines, then delete the cluster.
 - `rm -rf cluster`: Delete the cluster recursively and if it's a special cluster, try to delete it all anyway.

**Comment by vincepri** [comment]
Should we start setting ownerRef on Machines objects linking to the cluster? I'm not sure thought how it'd affect #214 and #215 and how it relates to it.

**Comment by detiber** [comment]
If we do set the `ownerRef`, then we should also set `foregroundDeletion` in the finalizers for the `Cluster` and set `ownerReference.blockOwnerDeletion=true` on the machines to ensure that cascading delete functions properly: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion

**Comment by vincepri** [comment]
I think that makes a lot of sense. That would solve #215. But how do you think it's going to work given #214?

**Comment by detiber** [comment]
@vincepri there is already a bit of support for #214 in `cluster-api` by preventing the deletion of a machine that is linked to the node that is running the controller. We would need to extend that support. The cascading deletion would block the cluster being deleted while a machine exists.

**Comment by vincepri** [comment]
* Forward deletion blocks the cluster deletion until machines are deleted .
* Machine running the controller can't be deleted.

Wouldn't those two conditions being true at the same time lead into a deadlock?

**Comment by detiber** [comment]
I was mistaken about the finalizer, but there is a field that needs to be set on the Machine* objects:

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion

Only objects that are set for `ownerReference.blockOwnerDeletion=true` will block the deletion of the owner object.
