### ISSUE TITLE
Security Groups on API Server Load Balancer are not reconciled properly

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#2156]
/kind bug

**What steps did you take and what happened:**

Add a new security group to an API Server load balancer.  

This causes CAPA to start throwing error messages that it's missing permissions for `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer`

**What did you expect to happen:**

Security group would be reconciled properly (added or removed accordingly)

**Anything else you would like to add:**

Adding `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer` resolves issue and reconciliation of the load balancers continues as expected.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
@voor which CAPA version are you using? 
     ` iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"` already has that:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d25c45090eab379b146b43e84d8b4ff24b8f58f9/cmd/clusterawsadm/cloudformation/bootstrap/cloud_provider_integration_control_plane.go#L67

**Comment by voor** [comment]
Yes, keen eye @sedefsavas unfortunately the API Server load balancer is reconciled by the controllers IAM Instance Profile and not the control-plane one.

**Comment by sedefsavas** [comment]
I see, where does the IAM Instance Profile is set to controllers, is it during `clusterctl move`?

**Comment by voor** [comment]
> I see, where does the IAM Instance Profile is set to controllers, is it during `clusterctl move`?

The controllers IAM Instance Profile is the role given to the pod running capa-controller-manager, wherever it may be.
For example, in our environment we apply:
```
spec:
  template:
    spec:
      iamInstanceProfile: controllers.cluster-api-provider-aws.sigs.k8s.io
```
To the `AWSMachineTemplate` for the management cluster's `MachineDeployment`, an alternative would be IRSA or KIAM to apply the role to the service account or pod directly.

**Comment by sedefsavas** [comment]
I see, so this is applied by the user to the AWSMachineTemplate after having a self-managed management cluster. I was not sure how this was added, thanks!

**Comment by voor** [comment]
/remove-lifecycle stale

Although it's worth noting that this bug can currently be leveraged to address a feature gap for security groups on load balancers.
