### ISSUE TITLE
Build new AMIs

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2160]
v1.19.5
v1.18.13
v1.18.11 --> see https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2109
v1.17.15

**Comment by randomvariable** [comment]
/remove-good-first-issue

only two people can do this.

**Comment by sedefsavas** [comment]
Thx @randomvariable , got confused for a minute.
