### ISSUE TITLE
Failure during v1.18.11 AMI build 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2165]
Still getting the same error I got in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2109 when creating AMIs for Kubernetes version v1.18.11.

```
    centos-7: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'kubelet-1.18.11-0' found available, installed or updated", "rc": 126, "results": ["No package matching 'kubelet-1.18.11-0' found available, installed or updated"]}
```
/assign

**Comment by randomvariable** [comment]
I'd check with SIG release about the location of the packages.

**Comment by randomvariable** [comment]
As far as I can see there's no 1.18.11 packages in https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages

**Comment by sedefsavas** [comment]
Yes, I only see 1.18.11 rc in kubelet repo.

**Comment by randomvariable** [comment]
Let's just skip over that release, since SIG Release didn't publish the artifacts. 1.18.12 and 1.18.13 seem available.

**Comment by sedefsavas** [comment]
Yes, asked in the slack: https://kubernetes.slack.com/archives/C2C40FMNF/p1607707230156600

We alreadyhave 1.18.12 and 1.18.13.

**Comment by sedefsavas** [comment]
Answer came:

1.18.11 is a no-op release due to some problems with GitHub. You can find more details here: https://groups.google.com/g/kubernetes-dev/c/nJix1xLQvZE

Should we add this to AMI doc or as release note?

**Comment by randomvariable** [comment]
Probably. I had no idea.

**Comment by randomvariable** [comment]
/close
busted release
