### ISSUE TITLE
Add conditions for EKS control plane and node upgrading

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2167]
/kind feature

**Describe the solution you'd like**
To provide feedback we should add consitions for when the control plane and nodes are 'upgrading'. 

Currently if i upgrade the version of the control plane it stays as ready and i have to query the AWS api to see that its upgrading.

**Comment by randomvariable** [comment]
I think we might get rid of phase in v1alpha4. Should use conditions as much as possible.

**Comment by richardcase** [comment]
Cool, i will reword.

**Comment by richardcase** [comment]
This was fixed as part of #2246, so closing
