### ISSUE TITLE
Not require DescribeNatGateways action when consuming AWS Infrastructure

### ISSUE THREAD

**Issue by lxlxok** [kubernetes-sigs/cluster-api-provider-aws#2169]
/kind feature

**Describe the solution you'd like**

An option to opt out the NAT gateway pre-requirement when consuming Existing AWS infrastructure [(doc)](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/book/src/topics/consuming-existing-aws-infrastructure.md#consuming-existing-aws-infrastructure)
 
NAT gateway is not needed when EKS cluster choose the private + public API endpoint networking mode [(link)](https://aws.amazon.com/blogs/containers/de-mystifying-cluster-networking-for-amazon-eks-worker-nodes/).

**Anything else you would like to add:**

Currently we have to grant CAPA the DescribeNatGateways action in its IAM Policy; without the action, the code will return an error.

Because`describeVpcSubnets()` will call `describeNatGatewaysBySubnet()`

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/bff3543f25f6316358e1e11f11492b594a94b168/pkg/cloud/services/network/subnets.go#L252-L255

and` reconcileSubnets()` will return error when it call `s.describeVpcSubnets()`
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/bff3543f25f6316358e1e11f11492b594a94b168/pkg/cloud/services/network/subnets.go#L46-L58

**Environment:**

- Cluster-api-provider-aws version: 0.6.1
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): N/a

**Comment by dlipovetsky** [comment]
This issue description is too broad.

NAT gateways are _not_ required. The documentation says this, as well (emphasis mine):
> A NAT gateway for each private subnet, along with associated Elastic IP addresses **(only needed if the nodes require access to the Internet, i.e. pulling public images)**

I use CAPA with existing infrastructure and my subnets do not have NAT gateways. It's clear to me, reading the code, that `describeNatGatewaysBySubnet` can return an empty slice without an error.

However, I still have to grant CAPA the `DescribeNatGateways` action in its IAM Policy; without the action, the code will return an error.

**Comment by lxlxok** [comment]
Thanks, @dlipovetsky, Adding the `DescribeNatGateways` action into IAM Policy sounds good. We can close this issue.

**Comment by dlipovetsky** [comment]
> Thanks, @dlipovetsky, Adding the `DescribeNatGateways` action into IAM Policy sounds good. We can close this issue.

Would you like to keep this issue open, but change its scope to _Not require DescribeNatGateways action when consuming AWS Infrastructure_?

**Comment by Ankitasw** [comment]
@sedefsavas do we still need to keep this issue?

**Comment by Ankitasw** [comment]
@sedefsavas do we still need to keep this issue open?

**Comment by sedefsavas** [comment]
To avoid making `DescribeNatGateways()` call, we need to add an API field (something like `isUsingNAT`) and get information, otherwise I don't see an easy way to detect if the existing infrastructure uses NatGateways or not.

BTW, we only make this call to fill out the ID field on the spec when VPC hence NAT gateways are externally managed, but it is still useful to fill out this info on `AWSCluster` resource.

Let's keep it open in case someone wants to make any further comments.

**Comment by Ankitasw** [comment]
@sedefsavas @richardcase can we close this issue, as we have not got any further response?

**Comment by richardcase** [comment]
@Ankitasw - now the lifecycle frozen is removed the usual lifecycle should apply and it will be closed after some inactivity. 

However, we appear to have  `ec2:DescribeNatGateways` so lets close.

@lxlxok @dlipovetsky - feel free to reopen if needed.

/close
