### ISSUE TITLE
Consume existing security group without cluster-name tag in EKS

### ISSUE THREAD

**Issue by lxlxok** [kubernetes-sigs/cluster-api-provider-aws#2170]
/kind feature

**Describe the solution you'd like**
Consuming existing security group without requiring cluster-name tag, so that different cluster can consuming same security group created before.

**Anything else you would like to add:**
Related code block in `reconcileSecurityGroups`
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/bff3543f25f6316358e1e11f11492b594a94b168/pkg/cloud/services/eks/securitygroup.go#L37-L44

**Environment:**

- Cluster-api-provider-aws version: 0.6.1
- Kubernetes version: (use `kubectl version`):  1.18
- OS (e.g. from `/etc/os-release`): N/a

**Comment by sedefsavas** [comment]
@lxlxok are you still working on this, or should it stay rotten?

**Comment by lxlxok** [comment]
Hi @sedefsavas, I am not working on this at the moment. Should we let it stay rotten or close it for now and reopen it in the future.
