### ISSUE TITLE
Tag resource if missing tags 

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes-sigs/cluster-api-provider-aws#218]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3f7039c7dc1bc458a3842bad742957b7f749e54c/docs/proposal/aws-resource-handling.md#resources-that-support-client-tokens-but-require-separate-tagging mentions that a resource not supporting tags on create missing tags, should be tagged on reconcile.

I don't think this is easily possible without requiring users to tag shared resources with `kubernetes.io/cluster/<name or id>=shared` before using them the cluster-api as otherwise its impossible to infer for root level resources whether the resource was created by cluster-api or is shared.

Requiring tagging itself might cause problems for resources, which can be shared by multiple clusters like a VPC as there is a tag limit of 50 per tags resource.

[kops](https://github.com/kubernetes/kops/blob/af4df08b694e2a1f8814a7b3649060477be67c86/docs/run_in_existing_vpc.md#running-in-a-shared-vpc) and [kubespray](https://github.com/kubernetes-incubator/kubespray/blob/e3d562bcdb0da3bc31c079907c9e04e0c1a43c68/docs/aws.md#aws) say they require explicit tagging of shared resources, but at least kops doesn't seem to enforce it.

A potential solution could be to required shared resources to be tagged with `kubernetes.io/cluster-api=shared`, which would be cluster agnostic and still deliver enough information whether cluster-api should manage the lifecycle of this resource or not.

Ported from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/66#discussion_r220473805

**Comment by chuckha** [comment]
related to #274
