### ISSUE TITLE
Log AWS service calls

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2181]
/kind feature
/help
/good-first-issue

**Describe the solution you'd like**
I would like the ability to log AWS service calls - see [this](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html).

This should be enabled for a specific log level or higher (and perhaps there are different levels for different AWS SDK log levels).

**Anything else you would like to add:**
This could potentially be done [when we create the clients](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e042503a799294e0002d64d057113cfb27f21121/pkg/cloud/scope/clients.go). 

**Environment:**

- Cluster-api-provider-aws version: 0.6.3

**Comment by randomvariable** [comment]
Looks interesting. Could also do it via adding handlers as we're doing for metrics.

**Comment by richardcase** [comment]
That would probably be better as we would have more control of the output into the logs

**Comment by shuheiktgw** [comment]
Hi, I'm new to contributing Kuberenetes but I'm eager to get involved with its development! May I take this issue if anyone else does?

**Comment by richardcase** [comment]
@shuheiktgw - that would be geat, thank you. If you need help reach out here on the slack channel. I will assign the issue to you but you can also assign issues yourself by commenting `/assign`. When you start work can you also comment `/lifecycle active`?  @randomvariable  also suggested that we could implement this via a [handler like we do for metrics](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7470b49be4c65865676d7833b37133d4da5a8f82/pkg/cloud/scope/clients.go#L53).....so there are 2 possible ways to do this.

/assign shuheiktgw

**Comment by shuheiktgw** [comment]
Thank you for your guidance @richardcase! I've started reading the code around it but still could not figure out the way to retrieve the current log levels... Would you have any recommendations on which part of the source code I should read? 🙇

**Comment by richardcase** [comment]
@shuheiktgw - thanks for the PR on this...i will take a look at this morning. Sorry for not getting back to you with the recommendations.

**Comment by shuheiktgw** [comment]
No worries! I made the PR draft since I'm still setting up my local development environment and haven't tested it, but I would really appreciate it if you would have a look!

**Comment by richardcase** [comment]
I just pined you in slack about the dev environment
