### ISSUE TITLE
Error when delete self hosted and eks cluster

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/cluster-api-provider-aws#2195]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

E0107 20:57:36.319989       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting security groups for AWSCluster default/undistro-quickstart: failed to delete security group \"sg-09d3723fc49768432\": DependencyViolation: resource sg-09d3723fc49768432 has a dependent object\n\tstatus code: 400, request id: 25281f88-0aeb-4a29-8346-8bb3f301af37" "controller"="awscluster" "name"="undistro-quickstart" "namespace"="default"
**What did you expect to happen:**
Delete the cluster

**Environment:**

- Cluster-api-provider-aws version: v0.6.3
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T10:37:08Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): 
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by felipeweb** [comment]
it seems machine pool is not deleting resource

**Comment by richardcase** [comment]
@felipeweb  - just to confirm this is a EKS based cluster (i.e. using AWSManagedCluster/AWSManagedControlPlane)? Are you using AWSMachinePool or AWSManagedMachinePool?

There was a recent fix for deletion in #2176 that covers both versions of the machine pool.

**Comment by felipeweb** [comment]
@richardcase yes I'm using AWSManagedMachinePool

**Comment by richardcase** [comment]
Thanks @felipeweb, in that case it would be worth trying this agan when 0.6.4 is out with the #2176 fix in it.

**Comment by felipeweb** [comment]
fixed in v0.6.4
