### ISSUE TITLE
Tag Elastic IPs on creation

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2207]
/kind feature

**Describe the solution you'd like**
The AWS EC2 API has been updated, and Elastic IPs can now be tagged on creation.

SDK support came in [v1.36.13](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v13613-2020-12-21)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.6.3
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Madhur97** [comment]
Hello @randomvariable, I found Elastic IPs created by CAPA already have following tags
```
sigs.k8s.io/cluster-api-provider-aws/cluster/test	    owned
Name                                                 	    test-eip-apiserver
sigs.k8s.io/cluster-api-provider-aws/role	            apiserver
```
Do we still need to add any other tag in Elastic IPs?

**Comment by sedefsavas** [comment]
Yes, we add these tags after creating the Elastic IPs in a separate call.

Instead, newer AWS-SDK has the option to provide the tags during creation of EIPs.

In `AllocateAddress()` api call, tags can be specified with this field: `TagSpecifications []*TagSpecification` in `AllocateAddressInput` struct:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/72f4dad21a8e72e7642d3e8327d9e4bbe14a19af/pkg/cloud/services/network/eips.go#L58


When we use this, we can remove: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/72f4dad21a8e72e7642d3e8327d9e4bbe14a19af/pkg/cloud/services/network/eips.go#L69
