### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#221]
/kind feature
/important soon

Related to #216 

**Describe the solution you'd like**

We need integration tests as unit testing can only get us so
far with regards to AWS APIs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
closing in favor of #271
