### ISSUE TITLE
LDFLAGS are missing in cloudbuild

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2218]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

In cloudbuild, there isn't actually a git checkout, it's a copy of the code only. During build, we pass in LDFLAGS for version information that are computed with git. This errors in Make, and the LDFLAGS are blank, which means that version info doesn't make it into the binary.

**What did you expect to happen:**
Version info gets built.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
In the logs, it is actually doing a checkout but then it complains that it is `not a git repository`.

https://storage.googleapis.com/kubernetes-jenkins/logs/post-cluster-api-push-images/1352342470024761344/clone-log.txt
```
$ git checkout 23ab5630cef14e40ab4f5b6d770d85ba9ec15915
Note: switching to '23ab5630cef14e40ab4f5b6d770d85ba9ec15915'
```


We can calculate version by using GIT_TAG and PULL_BASE_REF passed to GCB.

Required fields: 
```
version.gitCommit=429af035457db8f4372210d17d566321c2263631 
version.gitMajor=0 
version.gitMinor=3 
version.gitVersion=v0.3.10-302-429af035457db8
version.gitReleaseCommit=af6630920560ca0e12179897b96d6ea8bd830b63
```

**Comment by randomvariable** [comment]
Yup. I have an intense dislike of Bash scripts though, so wouldn't mind transferring the version.sh script to Go. https://github.com/go-git/go-git also now exists with an Apache license, so we could use it.

**Comment by randomvariable** [comment]
Let's start switching over to mage https://github.com/magefile/mage

**Comment by sedefsavas** [comment]
@Jont828 feel free to assign yourself on this issue.

**Comment by Jont828** [comment]
I synced with @sbueringer today since I found the same issue in CAPZ. The issue is the `.git` folder doesn't get copied when we try to get the folder on gcloud. I opened a [PR on CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2068) with a simple fix to clone the `.git` folder. The version script is coming from [here](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh), and where it tries to save the values to a file and read them back, so maybe that approach could work.

/assign

**Comment by Jont828** [comment]
Opened this [PR](https://github.com/kubernetes/test-infra/pull/25251) to fix this in test-infra

**Comment by Ankitasw** [comment]
@Jont828 anything else to be done here or shall we close the issue?

**Comment by sbueringer** [comment]
I think it's fixed > https://storage.googleapis.com/kubernetes-jenkins/logs/post-cluster-api-provider-aws-push-images/1501302836586090496/artifacts/build.log (LDFLAGS are set)
