### ISSUE TITLE
For v1alpha4, encrypted value of Volume struct should be pointer

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2233]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
If you're using an encrypted EBS snapshot for the root volume AMI, you explicitly need to set

``` yaml
rootVolume:
  encrypted: true
```

You shouldn't need to do this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
@randomvariable 
What is the expected behaviour you had in mind? We still need to set the EncryptionKey to the `rootVolume`
