### ISSUE TITLE
[we need to check this] When AWSCluster reconciliation fails, the cluster status may missing

### ISSUE THREAD

**Issue by lsh0357** [kubernetes-sigs/cluster-api-provider-aws#2236]
I was facing the issue in other capi cloud provider that the infracluster status is missing when infracluster controller reconciliation fails, I'm wondering if you have the same issue at CAPA.
The cause is that the infracluster's `status.Ready` field is required.

1. During infracluster reconciliation, we use client.Get to get infraCluster to a infraCluster type variable, which will set status.Ready to be false by default since it's a boolean.
2. If the reconciliation failed, the cluster status.Ready is set to false, in other word, it doesn't change.
3. And then when we patch the status, capi patchHelper thinks the status.Ready doesn't change and doesn't include this field to the patch, because both the original got InfraCluster and the reconciled InfraCluster has the same value for status.Ready, which is false. Then when we patch the status, it checks against the InfraCluster CRD which said the field is required but it's not there, so the patch request got an error, which cause the infracluster status is missing.

**Comment by randomvariable** [comment]
Just checked from a failed e2e run that we do indeed have the conditions set at https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1933/pull-cluster-api-provider-aws-e2e/1356437037489590272/artifacts/clusters/bootstrap/resources/functional-tests-aqf9dk/AWSCluster/cluster-l9rzw7.yaml

**Comment by randomvariable** [comment]
/close

I think we know this works.
