### ISSUE TITLE
[e2e] Fix the EKS tests so we can enable the full suite

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2239]
/kind bug
/area provider/eks
/area testing

**Describe the solution you'd like**
We had to disable the upgrade e2e test on the EKS side as it introduced flakiness that was a blocker for new features being added. We need fix this and enable the upgrade tests so that we have greater confidence that nothing has broken.

**Environment:**

- Cluster-api-provider-aws version: 0.6.4

**Comment by randomvariable** [comment]
@richardcase can you add priority?
