### ISSUE TITLE
Unit tests should not need to call reconcile()

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2267]
In the unit tests that use testenv, instance creation should trigger reconciliation automatically and hence we don't need to trigger `reconcile()`.

For this, we need to add the reconciler by calling SetupWithManager() similar to: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/76ea0c9445caa2ecbdcf97a24dcaf0433a6f8139/exp/instancestate/awsinstancestate_controller_test.go#L87

/kind cleanup
/help
/good-first-issue

**Comment by Srikrishnabh** [comment]
@sedefsavas I would like to contribute. can you please guide me further.

**Comment by sedefsavas** [comment]
@Srikrishnabh 
Right now, we do not attach controllers to envtest manager in most suite_test.go where we setup the testing environment.
And hence when we create an object, its reconciler is not triggered and we trigger it by calling the function like here:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/5721067c87ec597c8b7816d9e79851ca6bad5129/controllers/awsmachine_controller_test.go#L187

If we start the controller by calling SetupWithManager(), then just creating an AWSMachine will trigger AWSMachine controller's reconcile(). There are similar example in core cluster-api repo as well:
https://github.com/kubernetes-sigs/cluster-api/blob/8d1396821ca9bdb46b4dc3b63344f72f934bf443/controllers/machine_controller_test.go#L152

Feel free to ping me on slack if you have questions.

**Comment by tech-geek29** [comment]
I think this issue can also be closed now. We already have desired changes in code base!

**Comment by sedefsavas** [comment]
Welcome to the community @mevech!
Feel free to reach out on slack channel if you have questions.

**Comment by agill17** [comment]
Trying to understand the scope of this issue.
Out of the all the _test.go files under controllers/ dir, it looks only `awscluster_controller_test.go` is the one that requires the adjustment after adding its reconciler to the testEnv manager. The other tests in controllers dir are using mocked interfaces / fake-mocked k8s client and not using testEnv client. 
OR
Is this issue to setup all reconcilers with testEnv.manager  and swap all fakeClients from tests to testEnv/envTest client ? Which may be a bigger change ( For example, in machine_controller_test resource names will have to be different for each test or else in tearDown we will have to waitTillDeleted before going to the next test case

**Comment by Ankitasw** [comment]
Hey @mevech are you still working on this issue?

**Comment by KushalBeniwal** [comment]
It looks like no-one is working on this issue.

/assign

**Comment by sedefsavas** [comment]
@Ankitasw IIRC there were some difficulties triggering reconcile method in the recent tests you added.
Is this still a good first issue?

**Comment by Ankitasw** [comment]
Good point @sedefsavas will drop good first issue for now and would see if it's still possible to do this.
/unassign @KushalBeniwal 
/remove-good-first-issue
