### ISSUE TITLE
AWSMachine cannot be removed if controller is installed with invalid credentials

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-aws#2270]
/kind bug

**What steps did you take and what happened:**
1. Install AWS provide with invalid credentials (malformed, revoked etc.)
2. Create a cluster
3. Delete a cluster

Controller gets stuck by calling `ec2svc.GetRunningInstanceByTags`, which fails because of wrong credentials. This make removal of `AWSMachine` object stuck.

Actually, the same happens for `AWSCluster`.

**What did you expect to happen:**
Controller should perhaps handle this case somehow.

**Environment:**

- Cluster-api-provider-aws version: fbf880963b07b2fc5f869faab0e0ab07aa06a729

**Comment by randomvariable** [comment]
There's not much we can do automatically if it's erroring whilst querying EC2.

Maybe we need to add  something to the docs. You can force remove the object by deleting the finalizer.

**Comment by invidian** [comment]
>Maybe we need to add something to the docs. You can force remove the object by deleting the finalizer.

Yes, thanks, I figured that out already :) Maybe before putting the finalizer there should be some safety check run to make sure credentials are correct?

**Comment by randomvariable** [comment]
Yup, we need to fix the state machine so it doesn't add the finalizer until just before the first write operation, which should be after the read operation.

**Comment by randomvariable** [comment]
Might have to sort out as part of other refactoring for v0.7.0 though.
