### ISSUE TITLE
Enable usage of GPU optimized AMIs for EKS

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2275]
/kind feature
/area provider/eks
/help

**Describe the solution you'd like**
When creating an EKS cluster i would like to indicate that the GPU optimized AMI be used. Currently we use `/aws/service/eks/optimized-ami/%s/amazon-linux-2/recommended/image_id` to lookup the [AMI in parameter store](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/ami.go#L232).

To lookup the GPU accelerated AMIs we need to use `/aws/service/eks/optimized-ami/%s/amazon-linux-2-gpu/recommended/image_id`

It would be good if there was an option to say u want this machinepool to use the GPU accelerated AMI and then look this up from SSM.

> Is the accelerated AMI even needed? And what about https://github.com/NVIDIA/gpu-operator

It is possible with the `AWSManagedMachinePool` using `amiType: "AL2_x86_64_GPU"` but not with AWSMachinePool or AWSMachine

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
How does this relate to the GPU template?

**Comment by richardcase** [comment]
> How does this relate to the GPU template?

This is for the **AWSMachine** and **AWSMachinePool** scenarios. The GPU template uses **AWSManagedMachinePool** which already exposes the ability to use the GPU optimized AMI.
