### ISSUE TITLE
Control Plane Load Balancer Attachments management from Machine

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes-sigs/cluster-api-provider-aws#2283]
/kind feature

**Describe the solution you'd like**

Currently, the `AWSCluster` resource allows specification of a single classic load balancer (in spec and status). This works well when the `AWSCluster` is being managed by the `AWSCluster` controller, however, with the introduction of the Externally Managed Cluster Infrastructure concept, this could present a limitation to external cluster infrastructure provisioners.

Other infrastructure provisioners may use other types of load balancers (eg Network Load Balancers) or may even use multiple load balancers (one for external traffic and one for internal traffic, for security reasons). With the current design of the `AWSCluster` resource, this cannot be supported by external provisioners who intend to use the AWSMachine controller to provision AWS infrastructure for Machines.

The following needs to be met to allow internal and external management of cluster infrastructure:
- The `AWSMachine` controller must assume the load balancer attachment for control plane machines is optional (perhaps this is also done by some other component)
- The `AWSMachine` controller should be able to attach multiple load balancers to a single machine
  - These load balancers may be of different types (eg Classic ELB and NLB)
- The AWSCluster resource should be extended to allow many (or no) load balancers
  - In Spec and Status, there should be lists of load balancers rather than a single instance as is today
  - This should also allow for multiple types of load balancers as per the provisioner requirements

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Danil-Grigorev** [comment]
cc @JoelSpeed Feel free to add details to this issue if I missed anything.

**Comment by alexander-demichev** [comment]
This suggestion seems useful

**Comment by johannesfrey** [comment]
Most certainly not all aspects of this issue are addressed by this, but there currently is movement in using NLBs instead of classic load balancers for control-plane machines: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3804

**Comment by JoelSpeed** [comment]
The multiple load balancers (internal vs external) element here still seems important, do we want to track this still?
