### ISSUE TITLE
ELB resource lacks a `Name` tag

### ISSUE THREAD

**Issue by fyangd** [kubernetes-sigs/cluster-api-provider-aws#2284]
/kind bug

**What steps did you take and what happened:**
When you create a CAPA cluster, the ELB resource created has the following tags:

```
ELB - dev-mgmt-aws-apiserver - [tag:sigs.k8s.io/cluster-api-provider-aws/cluster/dev-mgmt-aws: "owned", tag:sigs.k8s.io/cluster-api-provider-aws/role: "apiserver"] 
```

**What did you expect to happen:**
Just like all other types of resources created by CAPA, such as NAT Gateway or EC2 Instance, with a `tag:Name` property, such as:

```
 EC2NATGateway - nat-xxxxxxxx. - [tag:Name: "dev-mgmt-aws-nat", tag:sigs.k8s.io/cluster-api-provider-aws/cluster/dev-mgmt-aws: "owned", tag:sigs.k8s.io/cluster-api-provider-aws/role: "common"]
 ```

I expect ELB to have a `tag:Name` property.

**Environment:**

- Cluster-api-provider-aws version: v0.6.4
- Kubernetes version: (use `kubectl version`): v1.20.4
- OS (e.g. from `/etc/os-release`): n/a

**Comment by fyangd** [comment]
I believe this line here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/dafe0711b279a6c04735338f9ccffa392a6d0f36/pkg/cloud/services/elb/loadbalancer.go#L343 is missing the Name parameter.

**Comment by elfklx** [comment]
Thanks @sedefsavas for the prompt fix!

**Comment by fyangd** [comment]
Thanks @sedefsavas for the prompt fix!
