### ISSUE TITLE
Bastion information is not removed from status when bastion is disabled

### ISSUE THREAD

**Issue by JosephSalisbury** [kubernetes-sigs/cluster-api-provider-aws#2297]
/kind bug

**What steps did you take and what happened:**
- Create an `AWSCluster` (`infrastructure.cluster.x-k8s.io/v1alpha3`)
- Set `spec.bastion.enabled` to `true`
- Verify that EC2 instance has been created, and that `status.bastion` has been populated
- Set `spec.bastion.enabled` to `false`
- Verify that EC2 instance has been destroyed, and that `status.bastion` remains the same

**What did you expect to happen:**
I expected `status.bastion` to be cleaned up when the bastion has been removed. 

**Environment:**

- Cluster-api-provider-aws version: v0.6.4
- Kubernetes version: (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): N/A

**Comment by JosephSalisbury** [comment]
Happy to push a PR to fix this, if the proposed behaviour (disabling a bastion should lead to the bastion information being removed from `status`) works for folks.

**Comment by randomvariable** [comment]
That makes sense.

If you do start a PR on it, just do a 

`/lifecycle active`, and either Prow or me or another maintainer will mark it as such so that someone else doesn't also start a PR at the same time.
