### ISSUE TITLE
Use availabilityZones provided in AWSMachinePool when creating ASG

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2320]
/kind bug

**What steps did you take and what happened:**
AWSMachinePoolSpec `availabilityZones` field is not used during ASG creation: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/9a2cf01bb9f8145cfd885c487f8369aaebaabba3/pkg/cloud/services/autoscaling/autoscalinggroup.go#L199
Currently, we are just providing a list of subnets during ASG creation.
This is a follow up on https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2302
cc @richardcase 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
@sedefsavas - the `availabilityZones` from the[ AWSMachinePool should be used](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/scope/machinepool.go#L228) with the change from #2302.

**Comment by shivi28** [comment]
assign @shivi28
