### ISSUE TITLE
MachinePool kubeadm token expires and is not renewed on the ASG

### ISSUE THREAD

**Issue by paurosello** [kubernetes-sigs/cluster-api-provider-aws#2321]
/kind bug

**What steps did you take and what happened:**
- Installed controllers with EXP_MACHINE_POOL env enabled
- Create cluster with a MachinePool
- After the initial kubeadm join token expires, scale-up the machinepool
- The new nodes to not join the cluster as they are using an expired token

**What did you expect to happen:**
- Once the kubeadm token is refreshed, the user-data in the LaunchTemplate should get updated with the new token

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- Check additional information in https://kubernetes.slack.com/archives/CD6U2V71N/p1616059118005600 a possible solution is to create a new LaunchTemplateVersion with the new token, set it as default and delete the old version.

**Environment:**

- Cluster-api-provider-aws version: 0.6.4
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by dlipovetsky** [comment]
Just to add some detail: The EC2 instances are created, pass the EC2 status checks, but fail to join the cluster.

The kubeadm error can be found in `/var/log/cloud-init-output.log`, and looks like this:
```
[2021-03-22 21:06:36] [preflight] Running pre-flight checks
[2021-03-22 21:11:37] error execution phase preflight: couldn't validate the identity of the API Server: could not find a JWS signature in the cluster-info ConfigMap for token ID "gthjug"
[2021-03-22 21:11:37] To see the stack trace of this error execute with --v=5 or higher
```

**Comment by randomvariable** [comment]
CAPA needs to watch the bootstrap secret and revision the LaunchTemplate with the new userdata, and then delete the old revision.

**Comment by richardcase** [comment]
As this breaks machine pools it feels like we should try and get this fixed instead of waiting for 0.7.0?

Also, perhaps a stupid question, but can the token be stored externally perhaps in secrets manager and the bootstrap scipy retireve the token?

**Comment by dlipovetsky** [comment]
A separate issue worth noting: Refreshing the token does not guarantee that it is valid at the time it is used by kubelet.

For example:
- If the token is defined in a LaunchTemplate, then it is fixed at the time of the EC2 RunInstances API call.
- This token can expire in the time after the EC2 RunInstances API call, but before it is used by kubelet to register with the control plane.

**Comment by dlipovetsky** [comment]
> CAPA needs to watch the bootstrap secret

This is because the CABPK controller updates the bootstrap secret if it is owned by a MachinePool: 
https://github.com/kubernetes-sigs/cluster-api/pull/3940

**Comment by dlipovetsky** [comment]
> CAPA needs to watch the bootstrap secret

I think the AWSMachinePool controller can watch the `KubeadmConfig`. That gets updated whenever the MachinePool is scaled:

```
I0414 18:51:00.657442       1 kubeadmconfig_controller.go:492] controllers/KubeadmConfig "msg"="Creating BootstrapData for the worker node" "kind"="MachinePool" "kubeadmconfig"={"Namespace":"default","Name":"dlipovetsky-ssh-keys-mp-0"} "name"="dlipovetsky-ssh-keys-mp-0" "version"="32528"
I0414 18:51:00.665230       1 kubeadmconfig_controller.go:875] controllers/KubeadmConfig "msg"="bootstrap data secret for KubeadmConfig already exists, updating"  "KubeadmConfig"="dlipovetsky-ssh-keys-mp-0" "secret"="dlipovetsky-ssh-keys-mp-0"
```

**Comment by dlipovetsky** [comment]
> revision the LaunchTemplate with the new userdata, and then delete the old revision.

Fortunately, there is already [code that does this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/dbd3b700f7eebe53e0cb1b44df797b6201d9639a/exp/controllers/awsmachinepool_controller.go#L454).

I think we can change the [code that determines](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/458025d9e8783c29356586e06cc4f88c36ca755b/pkg/cloud/services/ec2/launchtemplate.go#L245L259) whether a new LaunchTemplate Version is needed. Namely, this logic: if the bootstrap data changes, then a new Version is needed.

**Comment by dntosas** [comment]
i think issue persists even with latest version of CAPI + CAPA, AWSMachinePool seems not an option to consider until goes stable 🤔
