### ISSUE TITLE
Generated code may go to `$GOPATH/src` instead of in repo

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api-provider-aws#2323]
/kind bug

**What steps did you take and what happened:**

Found in https://github.com/kubernetes-sigs/cluster-api/issues/4185

We [conversion-gen](https://pkg.go.dev/k8s.io/code-generator/cmd/conversion-gen) to generate some of the code. This command has an optional argument of `--output-base` that controls where the generated files are placed.

The default for this arg can vary. If `GOPATH` is set, then it will place files under `$GOPATH/src`. But if not set, it defaults to `./`, which is what we want to have the generated files within the repo.

The dependency on an environment variable is non-obvious and can cause stale files to be used if the user doesn't know about it. There also appears to be a difference whether running with the repo cloned within `$GOPATH/src` or elsehwere.

**What did you expect to happen:**

Files generated/over-written within the repo. In environment with GOPATH set, files were generated under `$GOPATH/src/api`.

**Comment by richardcase** [comment]
This would be great as historically the advice has been to clone into the GOPATH for thsi reason: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/book/src/development/development.md
