### ISSUE TITLE
Add expiration logic to the providers and sessions in the cache			

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2330]
Currently, we cache providers and sessions but we do not cleanup them from the cache.
It would be good to have a mechanism to define an expiration on them and remove them when expired.

```
var sessionCache sync.Map
var providerCache sync.Map
```

/milestone v0.7.x

**Comment by Ankitasw** [comment]
@sedefsavas just wanted to confirm before we start, we still need this right? is it done as part of any existing PR?

**Comment by Ankitasw** [comment]
@sedefsavas regarding time for expiration of cache, which component will decide that? Shall we hardcode it to some value?

**Comment by Ankitasw** [comment]
Rethinking: is this covered as part of API rate limiting?

**Comment by sedefsavas** [comment]
No, this is not related to SDK calls. 
We cache providers/sessions but do not clean them. For example, identities that are no longer in use will linger until CAPA controller is restarted.

**Comment by Ankitasw** [comment]
> No, this is not related to SDK calls.
We cache providers/sessions but do not clean them. For example, identities that are no longer in use will linger until CAPA controller is restarted.

Got it, so here comes the follow up question, regarding time for expiration of cache, which component will decide that? Shall we hardcode it to some value?
