### ISSUE TITLE
Implement the stage 2 namespace scoped principal types

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2336]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

In completion of the multi-tenancy work, implement the stage 2 namespace scoped resources

AWSRolePrincipal, AWSStaticPrincipal

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
While implementing stage 2, we will probably need to get the namespace automatically similar to this issue:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1208

**Comment by randomvariable** [comment]
No, it's a separate issue.
