### ISSUE TITLE
v1beta2 API Changes

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2355]
/kind refactor
/kind api-change
/area provider/eks
/priority important-soon
/milestone v0.7.0

**Describe the solution you'd like**
Refactor the API with the proposed changes for v1beta2/v1 including any field deprecations:

Changes:

- [ ] EKS changes (old doc: https://docs.google.com/document/d/1EeD2KjFfeKoD-o0LJTMMWh9GUy-15yG80S5Uoj7oKcA/edit)
- [ ] Remove `Equals` from `Tags`
- [ ] ARN field in AWSResourceReference.
- [ ] `AWSManagedMachinePool` field deprecations as a result of #3094 

**Environment:**

- Cluster-api-provider-aws version: 0.6.5

**Comment by richardcase** [comment]
As this requires a change in contract we will have to wait for the next API bump (i.e. v1alpha5)

/milestone Next
/priority important-longterm

**Comment by richardcase** [comment]
Changing this to be a general v1beta2/v1 API changes issue

**Comment by Ankitasw** [comment]
ARN field in `AWSResourceReference`.
(couldn't edit the PR description, not enough permissions)

**Comment by pydctw** [comment]
FailureDomain in `AWSMachine`.

From [CAPI book](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html?highlight=failuredomain#data-types)
> providers will be expected to remove the field in the next version that provides breaking API changes, favoring the value defined on Machine.Spec.FailureDomain instead.

**Comment by richardcase** [comment]
Refactor the `disableVPCCNI` on the managed control plane so that the disable and extra args are in a struct.

**Comment by richardcase** [comment]
Make sure we don't miss: #3526

**Comment by richardcase** [comment]
Change the addons override to default to overwrite: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3513#discussion_r920090162

**Comment by pydctw** [comment]
Add a required field to SubnetSpec to use as listMapKey in SSA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3528

**Comment by sedefsavas** [comment]
Remove `deviceName` from `rootVolume` in AWSMachinePool CR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3624

**Comment by sedefsavas** [comment]
NLB support: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3088
with uniques NLB names: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/969

**Comment by sedefsavas** [comment]
Internet-facing LB scheme clean up: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3673

**Comment by sedefsavas** [comment]
Move SSH key validation out of API types:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3720#discussion_r972086935

**Comment by sedefsavas** [comment]
This might need API change as well:
https://github.com/kubernetes-sigs/cluster-api/pull/6412
cc @dlipovetsky

**Comment by richardcase** [comment]
We need to review the items on this and see what we need to get in and what can be moved to v1beta3

**Comment by Ankitasw** [comment]
AWSManagedMachinePool field deprecations as a result of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3094 can be moved to next API version.
