### ISSUE TITLE
Implement externally managed infrastructure

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#2356]
/kind feature

**Describe the solution you'd like**
Implement externally managed infrastructure as in https://github.com/kubernetes-sigs/cluster-api/pull/4135

**Anything else you would like to add:**
Needs https://github.com/kubernetes-sigs/cluster-api/pull/4303

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
As usual @enxebre , do the `/lifecycle active` when you start. Might want to wait for #2121 to avoid rebasing hell.
