### ISSUE TITLE
After upgrading kubekins version, conformance tests are failing

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2363]
/kind bug

**What steps did you take and what happened:**
We recently updated the kubekins version for main e2e tests to have go v1.16 for v1alpha4: https://github.com/kubernetes/test-infra/pull/21872 

After this change, conformance tests started failing:
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#capa-conformance-k8s-main&show-stale-tests=

I could not detect any particular issue in the logs, ec2 is being created but then core cluster-api controller is having connection issue:

`E0421 01:27:37.444909       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"conformance-b6a23s/cluster-ctyucn\": Get https://cluster-ctyucn-apiserver-1137648371.us-west-2.elb.amazonaws.com:6443/api?timeout=10s: EOF" "controller"="clusterresourceset" "name"="cluster-ctyucn-crs-0" "namespace"="conformance-b6a23s"`

This may get fixed once we merge v1alpha4 types to main, but don't see why it is failing for v1alpha3 types.

cc @randomvariable

**Comment by randomvariable** [comment]
It's because we haven't updated to v1alpha4 yet, so go.sum is mismatched.

**Comment by randomvariable** [comment]
I think the best thing to do atm is remove CAPA main branch from SIG Release informing so it doesn't create noise for the release team. Once we have v1alpha4 types and the CR upgrade in place, we should add it back after we have clean CI signal for ourselves.

I've added that to https://github.com/kubernetes/test-infra/pull/21907

**Comment by jimmidyson** [comment]
I'd really like to understand the go 1.16 issue with older version of controller-runtime. Could someone please point me to an issue (can't find any in controller-runtime repo)?
