### ISSUE TITLE
AWSMachinePool needlessly updates the Launch Template when it first creates an ASG

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2367]
/kind bug

**What steps did you take and what happened:**
The AWSMachinePool creates a Launch Template when it first creates an ASG. The next requeue, it updates the Launch Template. Nothing appears different between the two versions, however.

**What did you expect to happen:**
To keep the first version.

**Anything else you would like to add:**
I suspect that the controller thinks the launch template needs updating, probably because some information wasn't stored into the AWSLaunchTemplate (embedded in the AWSMachinePool object).

See this log for some more information:
<details>
<pre>
I0422 19:06:57.080208       1 session.go:106] controllers/AWSMachinePool/identity "msg"="Creating an AWS Session" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:57.080242       1 session.go:261] controllers/AWSMachinePool/identity "msg"="Getting identity" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "identityKey"={"Namespace":"","Name":"default"} "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:57.081950       1 awsmachinepool_controller.go:208] controllers/AWSMachinePool "msg"="Reconciling AWSMachinePool" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:57.083057       1 awsmachinepool_controller.go:407] controllers/AWSMachinePool "msg"="checking for existing launch template" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:57.769238       1 ami.go:147] controllers/AWSMachinePool "msg"="Found and using an existing AMI" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "ami-id"="ami-09709369c53539cd8"
I0422 19:06:57.769270       1 awsmachinepool_controller.go:421] controllers/AWSMachinePool "msg"="no existing launch template found, creating" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:57.769285       1 launchtemplate.go:67] controllers/AWSMachinePool "msg"="Create a new launch template" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:58.155457       1 autoscalinggroup.go:122] controllers/AWSMachinePool "msg"="Looking for existing AutoScalingGroup by name" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:58.416172       1 awsmachinepool_controller.go:375] controllers/AWSMachinePool "msg"="Initializing ASG client" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:58.416274       1 recorder.go:52] controller-runtime/manager/events "msg"="Normal"  "message"="No Auto Scaling Groups with dlipovetsky-mp-0 found" "object"={"kind":"AWSMachinePool","namespace":"default","name":"dlipovetsky-mp-0","uid":"2f4f6422-dfca-4e1b-95e1-c636b6c35f34","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","resourceVersion":"117853"} "reason"="FailedDescribeInstances"
I0422 19:06:58.416287       1 awsmachinepool_controller.go:379] controllers/AWSMachinePool "msg"="Creating Autoscaling Group" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:58.416308       1 shared.go:98] controllers/AWSMachinePool "msg"="using all the private subnets from the control plane" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:58.416345       1 autoscalinggroup.go:183] controllers/AWSMachinePool "msg"="Running instance" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.822113       1 recorder.go:52] controller-runtime/manager/events "msg"="Normal"  "message"="Created new ASG: dlipovetsky-mp-0" "object"={"kind":"AWSMachinePool","namespace":"default","name":"dlipovetsky-mp-0","uid":"2f4f6422-dfca-4e1b-95e1-c636b6c35f34","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","resourceVersion":"117853"} "reason"="SuccessfulCreate"
I0422 19:06:59.929960       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="awsmachinepool" "name"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.930080       1 session.go:106] controllers/AWSMachinePool/identity "msg"="Creating an AWS Session" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.930109       1 session.go:261] controllers/AWSMachinePool/identity "msg"="Getting identity" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "identityKey"={"Namespace":"","Name":"default"} "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.930632       1 awsmachinepool_controller.go:208] controllers/AWSMachinePool "msg"="Reconciling AWSMachinePool" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.931048       1 awsmachinepool_controller.go:407] controllers/AWSMachinePool "msg"="checking for existing launch template" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:06:59.931068       1 launchtemplate.go:43] controllers/AWSMachinePool "msg"="Looking for existing LaunchTemplates" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:00.876238       1 ami.go:147] controllers/AWSMachinePool "msg"="Found and using an existing AMI" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "ami-id"="ami-09709369c53539cd8"
I0422 19:07:00.974961       1 awsmachinepool_controller.go:464] controllers/AWSMachinePool "msg"="creating new version for launch template" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "existing"={"name":"dlipovetsky-mp-0","iamInstanceProfile":"nodes.cluster-api-provider-aws.sigs.k8s.io","ami":{"id":"ami-09709369c53539cd8"},"instanceType":"t3.large","versionNumber":1,"additionalSecurityGroups":[{"id":"sg-07df65ca9283ffec2"},{"id":"sg-07e8a6e0101a56bf1"}]} "incoming"={"iamInstanceProfile":"nodes.cluster-api-provider-aws.sigs.k8s.io","ami":{},"instanceType":"t3.large","rootVolume":{"size":80}}
I0422 19:07:00.975003       1 launchtemplate.go:110] controllers/AWSMachinePool "msg"="creating new launch template version" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "machine-pool"="dlipovetsky-mp-0"
I0422 19:07:01.350641       1 awsmachinepool_controller.go:480] controllers/AWSMachinePool "msg"="starting instance refresh" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "number of instances"=1
I0422 19:07:01.560719       1 autoscalinggroup.go:122] controllers/AWSMachinePool "msg"="Looking for existing AutoScalingGroup by name" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:01.674113       1 awsmachinepool_controller.go:362] controllers/AWSMachinePool "msg"="updating AutoScalingGroup" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.077872       1 instances.go:654] controllers/AWSMachinePool "msg"="Attempting to update tags on resource" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "resource-id"="lt-0c8d67ad1bf3e0d9a"
I0422 19:07:03.077896       1 instances.go:658] controllers/AWSMachinePool "msg"="Attempting to create tags on resource" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "resource-id"="lt-0c8d67ad1bf3e0d9a"
I0422 19:07:03.307750       1 autoscalinggroup.go:466] controllers/AWSMachinePool "msg"="Attempting to update tags on resource" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "resource-id"="dlipovetsky-mp-0"
I0422 19:07:03.307802       1 autoscalinggroup.go:467] controllers/AWSMachinePool "msg"="updating tags on resource" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "create"={"expiration":"6h","owner":"dlipovetsky"} "remove"={} "resource-id"="dlipovetsky-mp-0"
I0422 19:07:03.307817       1 autoscalinggroup.go:471] controllers/AWSMachinePool "msg"="Attempting to create tags on resource" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "resource-id"="dlipovetsky-mp-0"
I0422 19:07:03.503022       1 recorder.go:52] controller-runtime/manager/events "msg"="Normal"  "message"="updated tags on resources" "object"={"kind":"AWSMachinePool","namespace":"default","name":"dlipovetsky-mp-0","uid":"2f4f6422-dfca-4e1b-95e1-c636b6c35f34","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","resourceVersion":"119384"} "reason"="UpdatedTags"
I0422 19:07:03.850356       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="awsmachinepool" "name"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.851486       1 session.go:106] controllers/AWSMachinePool/identity "msg"="Creating an AWS Session" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.852299       1 session.go:261] controllers/AWSMachinePool/identity "msg"="Getting identity" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "identityKey"={"Namespace":"","Name":"default"} "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.853682       1 awsmachinepool_controller.go:208] controllers/AWSMachinePool "msg"="Reconciling AWSMachinePool" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.854137       1 awsmachinepool_controller.go:407] controllers/AWSMachinePool "msg"="checking for existing launch template" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:03.854190       1 launchtemplate.go:43] controllers/AWSMachinePool "msg"="Looking for existing LaunchTemplates" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:04.817081       1 ami.go:147] controllers/AWSMachinePool "msg"="Found and using an existing AMI" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default" "ami-id"="ami-09709369c53539cd8"
I0422 19:07:04.817169       1 autoscalinggroup.go:122] controllers/AWSMachinePool "msg"="Looking for existing AutoScalingGroup by name" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:04.953639       1 awsmachinepool_controller.go:362] controllers/AWSMachinePool "msg"="updating AutoScalingGroup" "awsMachinePool"="dlipovetsky-mp-0" "cluster"="dlipovetsky" "machinePool"="dlipovetsky-mp-0" "namespace"="default"
I0422 19:07:06.923343       1 controller.go:281] controller-runtime/controller "msg"="Successfully Reconciled" "controller"="awsmachinepool" "name"="dlipovetsky-mp-0" "namespace"="default"
</pre>
</details>

**Environment:**

- Cluster-api-provider-aws version: v0.6.5
- Kubernetes version: (use `kubectl version`): v1.20.2
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
We have backlog

/priority backlog
