### ISSUE TITLE
AWSMachinePool controller should clean up unused Launch Template Versions

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2368]
/kind bug

**Describe the solution you'd like**
The AWSMachinePool controller creates new Launch Template Versions when the configuration changes, or the MachinePool is scaled. (See #2354). AWS imposes a limit on the number of Launch Template Versions:

> You are limited to creating 5,000 launch templates per Region and 10,000 versions per launch template.
> -- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#launch-template-restrictions

When this limit is reached, further updates are not possible, and therefore further configuration changes or scale operations would be blocked.

**Comment by dlipovetsky** [comment]
I'm worried that I did not raise this in the v0.6.6 release notes. I think that there's a new version created every time a new bootstrap token is created; assuming that's about every 10m, then a pool can operate for about 10m * 10,000 versions = 100,000m, or approximately 69 days, before its launch template reaches the maximum allowed versions.

**Comment by sedefsavas** [comment]
Would you like to address the cleanup in the v0.6.7 release?

I will add this as a warning to the v0.6.6 for new users.

**Comment by dlipovetsky** [comment]
> I will add this as a warning to the v0.6.6 for new users. (update: added)

Thank you, @sedefsavas!

> Would you like to address the cleanup in the v0.6.7 release?

I will try.
