### ISSUE TITLE
If an ASG EC2 instance is terminated by the user or AWS itself, it may not get a valid bootstrap token

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2369]
/kind bug

**What steps did you take and what happened:**
Let's say an EC2 Instance is part of an ASG managed by AWSMachinePool.  If the Instance is terminated by the user, or by AWS, ASG immediately replaces the instance.  The current Launch Template version may have an expired bootstrap token. Therefore machine will not join the cluster. (Also, the machine will pass the ASG health checks, and will not be terminated.)
 
Please see this [slack conversation](https://kubernetes.slack.com/archives/CD6U2V71N/p1619126084189100?thread_ts=1616059118.005600&cid=CD6U2V71N) for more details.

**What did you expect to happen:**
Not sure. Either prevent out-of-band replacement, or ensure that the token is valid.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v0.6.5

**Comment by dlipovetsky** [comment]
Here's the warning AWS Console shows when asking to terminate an instance that's part of an ASG:

![image](https://user-images.githubusercontent.com/3445370/115798496-ea511800-a3c5-11eb-92f1-736fa40a4637.png)

**Comment by dlipovetsky** [comment]
When I terminated the instance, I observed:
- The ASG service immediately replaces the instance
- The AWSMachinePool controller does not know about the change until the next time it reconciles the AWSMachinePool. In the meantime, the provider IDs are stale, as are the Node Refs.
- The Node becomes NotReady, but is eventually cleaned up by the cloud-controller-manager

**Comment by sedefsavas** [comment]
Is this issue solved by: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2401 ?

**Comment by dlipovetsky** [comment]
> Is this issue solved by: #2401 ?

Good point! I think you're right. With #2401, the latest version of the LaunchTemplate will have a valid bootstrap token.

**Comment by dntosas** [comment]
@dlipovetsky can you confirm this issue is resolved? i have the same problem with latest CAPI / CAPA versions

**Comment by sedefsavas** [comment]
@dntosas 
Could you describe the steps to reproduce?

cc @Ankitasw
