### ISSUE TITLE
Add tests for conversion webhooks

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2384]
We should add similar tests for conversion webhooks than [kubernetes-sigs/cluster-api#4417](https://github.com/kubernetes-sigs/cluster-api/pull/4417) to make sure that v1alpha3 --> v1alpha4 conversion actually works for each CRD.

/help
/good-first-issue

**Comment by mevech** [comment]
@sedefsavas this is no longer an open issue or? seems like the test already in place?

**Comment by sedefsavas** [comment]
You're right, we can close this issue.
