### ISSUE TITLE
Add v1alpha3 to v1alpha4 upgrade e2e test

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2388]
Add an e2e test for v1alpha3 to v1alpha4 upgrade similar to what core cluster-api is adding [here](https://github.com/kubernetes-sigs/cluster-api/pull/3708) and run a basic scale test to make sure it is functional.

https://github.com/kubernetes-sigs/cluster-api/pull/3708

/help
/good-first-issue
/milestone v0.7.x

**Comment by yuzhang17** [comment]
Could I work on this issue？ It may take more time because I'm a newcomer

**Comment by sedefsavas** [comment]
@yuzhang17 yes!

/assign @yuzhang17 

You can reach out to us in #cluster-api channel for help because this will be probably done by calling `[ClusterctlUpgradeSpec](https://github.com/kubernetes-sigs/cluster-api/pull/3708)`.

**Comment by yuzhang17** [comment]
Learning Ginkgo and Reading E2E code. Working in progress.

**Comment by sedefsavas** [comment]
Thanks for the heads up @yuzhang17 , no rush we are still at least a month from a v1alpha4 release.

**Comment by sedefsavas** [comment]
/hold
until https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2388 is merged for new cluster-api version.
