### ISSUE TITLE
Enhance v1alpha4 webhook validation checks

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2391]
We can improve validation checks for v1alpha4 types.

Possible improvements:
1. Check if selectors are parsable.
2. During update, check if fields (such as clusterName) that should stay the same is changed etc.

/good-first-issue
/priority backlog
/help
/milestone v0.7.x

**Comment by Ankitasw** [comment]
Hi Sedef, I am interested in picking this issue up, can you tell me a little more details about the validations? Where to handle the upgrade parts as I dont see any special handling in cluster_webhook for upgrade? And what do we imply by parsable here?

**Comment by sedefsavas** [comment]
Welcome to the community @Ankitasw!

This is more of an exploratory issue, looking at the webhook validation checks in cluster-api, if there are any missing checks such as checking immutability etc.

For the label selectors we have, we need to add this check:
https://github.com/kubernetes-sigs/cluster-api/blob/06f58a66353d5a22a2849f2f516ee71e4664c323/api/v1alpha4/machinehealthcheck_webhook.go#L105\

Another example, in the CRDs that has clusterName field, we need to add a check to make sure they are not changed:
https://github.com/kubernetes-sigs/cluster-api/pull/2463
