### ISSUE TITLE
Evaluate disabling AutoControllerIdentityCreator controller by default

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2397]
We added `AutoControllerIdentityCreator` controller as experiment to be backward compatible with v1alpha3 clusters that were created before multitenancy is supported. It creates `AWSClusterControllerIdentity` singleton that can be used by all namespaces.

With v0.7.0 release (v1alpha4), we should should consider disabling this controller and make users enable it if needed. 
But this requires v1alpha3 users to first upgrade CAPA controllers to a version > v0.6.5.

/milestone v0.7.0

**Comment by randomvariable** [comment]
@Madhur97 the issue is a discussion point. Don't open a PR until we've made a discussion.

If you're not working on this, remove yourself from assignment.
