### ISSUE TITLE
iamAuthenticatorConfig doesn't update the aws-auth configmap

### ISSUE THREAD

**Issue by ruzickap** [kubernetes-sigs/cluster-api-provider-aws#2409]
/kind bug

**What steps did you take and what happened:**
When I set the `iamAuthenticatorConfig`, like described in [EKS Console](https://cluster-api-aws.sigs.k8s.io/topics/eks/eks-console.html?highlight=iamAuthenticatorConfig#eks-console), the `aws-auth` ConfigMap is not updated.

I used the following `AWSManagedControlPlane` to create the EKS cluster:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: AWSManagedControlPlane
metadata:
  name: ${CLUSTER_NAME}1
  namespace: tenants
spec:
  associateOIDCProvider: true
  region: "${AWS_DEFAULT_REGION}"
  sshKeyName: "${AWS_SSH_KEY_NAME}"
  version: "v1.19.8"
  iamAuthenticatorConfig:
    mapRoles:
    - username: "admin"
      rolearn: "arn:aws:iam::7xxxxxxxxxx7:role/something"
      groups:
      - "system:masters"
```

When I created the cluster and checked the `aws-auth` it didn't contain the `mapRoles` value defined above:

```
$ kubectl get configmaps -n kube-system aws-auth -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::7xxxxxxxxxx7:role/eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-18T16:58:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "805"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 55144205-4086-406a-bb3f-c94064aadf20
```

This part was missing:

```yaml
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::7xxxxxxxxxx7:role/something
      username: admin
```

**Environment:**

- Cluster-api-provider-aws version: 0.3.16
- Kubernetes version: (use `kubectl version`): v1.19.8-eks-96780e
- OS (e.g. from `/etc/os-release`): AmazonLinux2

**Comment by sedefsavas** [comment]
cc @richardcase for triage

**Comment by richardcase** [comment]
Thanks @ruzickap & @sedefsavas. I'll take a look first thing in the morning and update.

/assign

**Comment by ruzickap** [comment]
I'm sorry, but it seems to be working fine.

I did the tests again and I got it working...

Closing...
