### ISSUE TITLE
Upgrade to kind v0.11.0

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2413]
Upgrade kind to v0.11.0 for less flakiness in e2e tests.

Corresponding cluster api issue: https://github.com/kubernetes-sigs/cluster-api/issues/4503

https://github.com/kubernetes-sigs/cluster-api/pull/4469

/milestone v0.7.0

**Comment by tech-geek29** [comment]
@sedefsavas When looking at [L1114](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/159c13f18ec81243b9f2f1ac700e41a144863b96/go.sum#L1114) & [L1115](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/159c13f18ec81243b9f2f1ac700e41a144863b96/go.sum#L1115), the kind is already v0.11.1 Isn't this upgraded already?
