### ISSUE TITLE
Enable additional linters

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2414]
Core cluster-api repo is enabling some additional linters, it'd be good for consistency to enable same linters.

https://github.com/kubernetes-sigs/cluster-api/issues/4622

/help
/good-first-issue
/milestone 0.7.x

**Comment by Evalle** [comment]
Hi @sedefsavas I can help with this. Any specific linters that you want to enable? 
Thanks!

**Comment by sedefsavas** [comment]
There are couple of PRs open in cluster-api. We can keep an eye on those: https://github.com/kubernetes-sigs/cluster-api/issues/4622 and enable same ones.

Some relevant ones:
https://github.com/kubernetes-sigs/cluster-api/pull/4649
https://github.com/kubernetes-sigs/cluster-api/pull/4657

/assign @Evalle

**Comment by sbueringer** [comment]
Just fyi. I try to keep an up-to-date list here: https://github.com/kubernetes-sigs/cluster-api/issues/4622 for further inspiration. In general it might also make sense to compare the currently active linters in CAPI vs CAPA.

**Comment by sedefsavas** [comment]
I created a new issue for enabling comment enforcement linter, as it will be big change.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2428
