### ISSUE TITLE
Apply clusterctl label to global identity resources 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2415]
For discovery of global identity resources during `clusterctl move`: 
https://github.com/kubernetes-sigs/cluster-api/pull/4628:
`Providers are required to apply the clusterctl.cluster.x-k8s.io/move-hierarchy label on the infrastructure cluster global identity CRDs.`

AWSClusterRoleIdentity, AWSClusterStaticIdentity, and AWSClusterControllerIdentity should have this label.

/milestone v0.7.0
/help
/good-first-issue

**Comment by sedefsavas** [comment]
@shivi28 Welcome to the community!

/hold 
until kubernetes-sigs/cluster-api#4628 is merged

@shivi28 let's wait until the implementation in cluster-api is completed. That PR is still a draft.

**Comment by sedefsavas** [comment]
@shivi28 that PR is merged, do you still want to work on this?

**Comment by shivi28** [comment]
Hey @sedefsavas, thanks for informing me. Yes, I want to work on this but I am currently working on other issues, until I unassign this task, so if anyone is interested can pick it.   

/unassign @shivi28

**Comment by shivi28** [comment]
Hey @sedefsavas do I also need to add this label in v1alpha3 api?

**Comment by sedefsavas** [comment]
No, just to v1alpha4, clusterctl only added [moving global resources ](https://github.com/kubernetes-sigs/cluster-api/pull/4628)support to v1alpha4.
