### ISSUE TITLE
v1alpha3 e2e conformance fails for k8s v1.22

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2419]
/kind bug

v1alpha3 e2e conformance is failing with the latest Kubernetes ci v1.22.0 release: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#capa-conformance-v1alpha3-k8s-master&show-stale-tests=

As the tests are passing for 1.21, this is not a release blocker.

**Comment by randomvariable** [comment]
Let's do a smoke test with v1.22 beta at least.

**Comment by sedefsavas** [comment]
Conformance tests with v1.22 for both v1alpha3 and 4 are passing.
