### ISSUE TITLE
Enforce comments on the codebase

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2428]
Enable linters for enforcing adding a comment to exported methods.

Relevant cluster-api PRs: 
https://github.com/kubernetes-sigs/cluster-api/pull/4631
https://github.com/kubernetes-sigs/cluster-api/pull/4669

/milestone Next
/priority backlog
/good-first-issue
/help

**Comment by Algebra8** [comment]
Hello 👋 

So it seems like kubernetes-sigs's `cluster-api` uses `golint`, so it should be as simple as adding that to `.golangci.yml`.

Should certain files, packages, or code also be excluded, e.g. `(func|type).*Fake.*`, `.*test/` etc? (examples taken from the issue posted).

**Comment by sedefsavas** [comment]
Hello @Algebra8!

Yes, wherever we don't need to add comments, we should exclude, e.g.,: *test, *fake, *mock, hack/.

After enabling this in golangci.yml, missing comments should be added as well, so expecting this to be a big PR.

**Comment by Algebra8** [comment]
Ah ok, thanks for the heads up! I will work on my fork and make a PR when I think it's ready. Just a heads up though, I am currently interviewing so I won't be able to put 100% of my time and get it done ASAP. Is that alright?

**Comment by sedefsavas** [comment]
Yes, we are 1 month away from the release. You can do a draft PR or WIP PR if you want feedback too.

/assign Algebra8

**Comment by Algebra8** [comment]
Great, thanks @sedefsavas !

**Comment by sedefsavas** [comment]
@mohsen-abbasi-shia Hi!
This issue was already assigned to @Algebra8, so unassigning you. We have other unassigned good-first-issues you can pick up.
/unassign @mohsen-abbasi-shia

**Comment by sedefsavas** [comment]
This is also relevant.
https://github.com/kubernetes-sigs/cluster-api/pull/4631

**Comment by Algebra8** [comment]
> This is also relevant.
> [kubernetes-sigs/cluster-api#4631](https://github.com/kubernetes-sigs/cluster-api/pull/4631)

@sedefsavas Thanks for the resource! I'll make sure to include `package X implements X` comment requirements as well.

PS I think I'll be submitting a draft soon because there are a few things I would appreciate feedback/clarity on. Will be submitting the draft soon.

**Comment by Algebra8** [comment]
Also, just a quick update: It seems like  https://github.com/kubernetes-sigs/cluster-api/commit/0fb33bc44d66a095ef5bffbc8aca7d056bc818e2 swapped using `golint` for `revive`. I believe this is because `golint` has been archived and [golangci-lint recommends swapping it with `revive`](https://golangci-lint.run/usage/linters/). So, I'll be using revive instead of golint as well, unless asked not to.

**Comment by Algebra8** [comment]
@sedefsavas 

Hope you're doing well. I have a few questions that I would appreciate feedback on [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2443#issuecomment-856258825).

I would appreciate if you could provide some feedback or point me in the direction of the whom I should be getting feedback from. 

Thanks!
