### ISSUE TITLE
CAPA make generate command generates new files in wrong directory

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#2441]
**What steps did you take and what happened:**
When we execute 'make generate' from the repo root directory , the generated code is created in a separate folder hierarchy with prefix sigs.k8s.io/cluster-api-provider-aws/ which creates nested directories inside the workspace leading to multiple files with same name but different directories.

**What did you expect to happen:**
The generated files should be updated in the correct directories of the repo.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
The easiest way to avoid this is to checkout the code to this location:
`$GOPATH/src/sigs.k8s.io/cluster-api-provider-aws`

Here is the slack [thread](https://kubernetes.slack.com/archives/CD6U2V71N/p1620841263252000)

**Comment by Ankitasw** [comment]
@sedefsavas  I did the checkout at same location, still facing the issue.

**Comment by sedefsavas** [comment]
I am unable to replicate the issue when checking out the repo under GOPATH. Maybe $GOPATH or some other environment variables are not set right.
/priority awaiting-more-evidence

**Comment by Ankitasw** [comment]
GOPATH is set correctly, may i know which other env variables shall I check?

**Comment by Ankitasw** [comment]
only the generated conversion files are getting created separately, rest all files are getting modified in correct places (eg. manifests, deepcopy-generate etc.)

**Comment by randomvariable** [comment]
I've been having the same issue, but it not consistently, despite having checked out to `$GOPATH/src/sigs.k8s.io/cluster-api-provider-aws`

**Comment by Ankitasw** [comment]
@sedefsavas : looks like $GOPATH issue, some issue with my local setup where sometimes GOPATH is getting populated as nil, closing the issue

**Comment by sedefsavas** [comment]
Solved in here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2485
