### ISSUE TITLE
Where do I get clusterawsadm?

### ISSUE THREAD

**Issue by webern** [kubernetes-sigs/cluster-api-provider-aws#2459]
/kind bug

**What steps did you take and what happened:**
I spent a non-trivial amount of time searching the internet for a distribution of a binary named `clusterawsadm`.

**What did you expect to happen:**
To find some information on where `clusterawsadm` is to be obtained.

**Anything else you would like to add:**
Please document how/where I should obtain and install `clusterawsadm`.
I apologize if it is somewhere obvious, but I could not find it. Am I supposed to build it from source?

Thanks.

**Environment:**

N/A

Edit: this was my starting point https://cluster-api.sigs.k8s.io/user/quick-start.html

This comment should tell the user where/how to get `clusterawsadm`.

```sh
# Create the base64 encoded credentials using clusterawsadm.
# This command uses your environment variables and encodes
# them in a value to be stored in a Kubernetes Secret.
export AWS_B64ENCODED_CREDENTIALS=$(clusterawsadm bootstrap credentials encode-as-profile)
```

**Comment by sedefsavas** [comment]
It is normally published with each release as artifacts, but latest release v0.6.6 is missing it. Thanks for letting us know. Just added those binaries: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.6.6 see under assets.

Each cloud provider has its own documentation: we have it documented in the [getting started](https://cluster-api-aws.sigs.k8s.io/getting-started.html) section:
`Download the latest binary of clusterawsadm from the AWS provider releases and make sure to place it in your path.
`

Also, for faster response, you can reach us in the #cluster-api-aws Kubernetes slack channel.

**Comment by webern** [comment]
Thank you for the quick response.
I did miss that sentence, and the missing binaries added to my confusion.

You might consider adding the link https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/latest and being more specific about what is meant by from the "AWS provider releases". For example:

> Download the latest binary of clusterawsadm from the AWS provider GitHub [release](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/latest) artifacts and make sure to place it in your path.

If you want to make that change you can leave this issue open to track it. Otherwise my issue is resolved.

**Comment by sedefsavas** [comment]
> You might consider adding the link https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/latest and being more specific about what "from the AWS provider releases" means. For example:

We already have that link there, but also added to our intro section to reduce confusion.
