### ISSUE TITLE
Update cluster-api e2e test package import in e2e tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2467]
Core cluster-api introduced a new module for test package. We should be importing that to use cluster-api e2e methods. 

We should be updating cluster-api version to include this change: https://github.com/kubernetes-sigs/cluster-api/pull/4713

> ## :warning: Go Module changes :warning:
> 
> - The `test` folder now ships with its own Go module `sigs.k8s.io/cluster-api/test`.
> - The module is going to be tagged and versioned as part of the release.
> - Folks importing the test e2e framework or the docker infrastructure provider need to import the new module.
>   - When imported, the test module version should always match the Cluster API one.
> 

/good-first-issue
/milestone v0.7.0
/help

**Comment by CecileRobertMichon** [comment]
@sedefsavas FYI I'm running into issues doing this in CAPZ

I have
```
	sigs.k8s.io/cluster-api v0.0.0-20210607195256-55f064d1b9fc
	sigs.k8s.io/cluster-api/test v0.0.0-20210607195256-55f064d1b9fc
```

getting
```
go mod tidy
go: sigs.k8s.io/cluster-api/test@v0.0.0-20210607195256-55f064d1b9fc requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
make: *** [modules] Error 1
```

**Comment by CecileRobertMichon** [comment]
Adding 

```
replace sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v0.0.0-20210607195256-55f064d1b9fc
```

(replace it with your own version of capi) in CAPZ/CAPA go.mod

fixes the issue, which was that the replace was only happening locally https://github.com/kubernetes-sigs/cluster-api/blob/55f064d1b9fcf3f0a7b1a32e43559bdff4d3c2cb/test/go.mod#L5

**Comment by shysank** [comment]
I was also doing this and tried by removing `sigs.k8s.io/cluster-api` and only adding `sigs.k8s.io/cluster-api/test`. . Then,`go mod tidy` automatically added `sigs.k8s.io/cluster-api v0.0.0-00010101000000-000000000000`. As @CecileRobertMichon suggested, then had to add the replace block. Looked something like this:
```
        sigs.k8s.io/cluster-api v0.0.0-00010101000000-000000000000
	sigs.k8s.io/cluster-api/test v0.0.0-20210607195256-55f064d1b9fc
	sigs.k8s.io/controller-runtime v0.9.0-beta.6
	sigs.k8s.io/kind v0.11.1
)

replace sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v0.0.0-20210607195256-55f064d1b9fc
```

**Comment by CecileRobertMichon** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/4765
