### ISSUE TITLE
Add shortnames to all resources

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2491]
We only have short names for a subset of the resources: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/search?l=YAML&q=shortNames

Add shortnames wherever applicable.

/priority backlog
/good-firts-issue
/milestone Next

**Comment by tech-geek29** [comment]
@sedefsavas what short name do you suggest for `kind: EKSConfig` and `kind: EKSConfigTemplate`
