### ISSUE TITLE
Generate CRDs with kubebuilder

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#252]
/kind feature

**Describe the solution you'd like**
Instead of copy/pasting CRDs from the gcp project we should generate them ourselves

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): @

**Comment by randomvariable** [comment]
Related to #253
