### ISSUE TITLE
AWSCluster `controlPlaneEndpoint.scheme` defaults - validation issue blocks editing neighbouring mutable fields

### ISSUE THREAD

**Issue by 0xVox** [kubernetes-sigs/cluster-api-provider-aws#2534]
/kind bug
Hey guys, not sure if this has been reported before or if it's expected behaviour, but I've found that the default value for 

**What steps did you take and what happened:**
`awscluster.spec.controlPlaneEndpoint.scheme` Is validated as `Internet-facing` but actual value set by applying an AWSCluster without `spec.controlPlaneEndpoint` is `internet-facing`. When you then set other `controlPlaneEndpoint` values, such as additional SG rules for the control plane load balancer, the object fails validation with the below error:

`The AWSCluster "capi-dev" is invalid: spec.controlPlaneLoadBalancer.scheme: Invalid value: "Internet-facing": field is immutable`

**What did you expect to happen:**
For the value to be set as the proper default `Internet-facing` when applying an AWSCluster without a controlPlaneLoadBalancer struct, and to be able to edit other keys under controlPlaneLoadBalancer that aren't immutable.

**Environment:**

- Cluster-api-provider-aws version: 9b294114b
- Kubernetes version: (use `kubectl version`): 1.21.0
- OS (e.g. from `/etc/os-release`): KIND - ubuntu 18.04

`awscluster.spec.controlPlaneEndpoint.scheme `

is set as:

```
awscluster_types.go:147:   // Scheme sets the scheme of the load balancer (defaults to Internet-facing)
awscluster_types.go:148:   // +kubebuilder:default=Internet-facing
awscluster_types.go:149:   // +kubebuilder:validation:Enum=Internet-facing;internal
```

Note the `Internet-facing` with capital `I`

But, when you create an AWSCluster without providing `controlPlaneLoadBalancer` - await creation, then:

```
k get awscluster -oyaml | grep scheme
scheme: internet-facing
```

Now, this value is immutable (Why?) - but if you then go and attempt to add any other options under controlPlaneEndpoint, such as an additional SG for the control plane lb, you are faced with the validation error mentioned above.

Additionally, creating an AWSCluster with the following:

```
  controlPlaneLoadBalancer:
    scheme: Internet-facing
```

Will begin to fail if CAPA is restarted with the following error: 

```
ELB names must be unique within a region: \"capi-dev-apiserver\" ELB already exists in this region with a different scheme \"internet-facing\"
```

**Comment by sedefsavas** [comment]
`awscluster.spec.controlPlaneEndpoint.scheme` field is an enum hence only allows two values: `Internet-facing` and `internal`.

What happens in this issue is that, initially controlPlaneEndpoint is left blank, and ELB scheme is defaulted to `Internet-facing` internally by CAPA controllers. When the user tried to fill `controlPlaneEndpoint` fields, eventhough the value is correct, the comparison happening in the webhook sees it as changed (initially empty, now `Internet-facing`).
Improved this webhook check for the v0.7.0 release which allows setting the scheme to `Internet-facing` if previously left empty.


```
k get awscluster -oyaml | grep scheme
scheme: internet-facing
```
The value seen here is coming from `Status` not `Spec`. That is the actual ELB scheme value, so does not need to match our enum values.

**Comment by 0xVox** [comment]
Hey @sedefsavas 

I pulled your PR, and now when I explicitly set `scheme: Internet-facing` in my spec, I am faced with this after creating the AWSCluster resource:

```"msg"="failed to reconcile load balancer" "error"="ELB names must be unique within a region: \"kf-dev-apiserver\" ELB already exists in this region with a different scheme \"internet-facing\""```

The LB successfully creates if I omit the scheme value and allow it to default.

**Comment by dkoshkin** [comment]
I am seeing the same issue when using a build that includes this fix and `AWSCluster` with `apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4`.

```
E0720 19:40:44.293811       1 controller.go:302] controller-runtime/manager/controller/awscluster "msg"="Reconciler error" "error"="ELB names must be unique within a region: \"nuhu1xmz89348e0fbsih0f4dayvk-k8s\" ELB already exists in this region with a different scheme \"internet-facing\"" "name"="test-1626795856" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
```

The only way I've found to get around this was also to remove the whole `controlPlaneLoadBalancer:` block, just removing `controlPlaneLoadBalancer.scheme:` resulted in the same error.

**Comment by dlipovetsky** [comment]
Based on the [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
), the acceptable values for ELB scheme are `internet-facing` or `internal`. Note that both values are _lowercase_.

<img src="https://user-images.githubusercontent.com/3445370/133307096-4848d595-d465-4862-a1d8-6cd5bb30fd82.png" width=50% height=50%>

The enum capitalizes the first letter, i.e., `Internet-facing`. The comparison between the desired scheme (`Internet-facing`) and the actual scheme (`internet-facing`) is always false:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/9bb81e375bf53f37e6adc633bf4145717621bd7c/pkg/cloud/services/elb/loadbalancer.go#L603

/assign
