### ISSUE TITLE
securityGroupOverrides - AWS Resources deleted on AWSCluster delete

### ISSUE THREAD

**Issue by 0xVox** [kubernetes-sigs/cluster-api-provider-aws#2548]
/kind bug

**What steps did you take and what happened:**

1. Create 5 security groups before your AWSCluster, set them to the AWSCluster.spec.networkSpec.securityGroupOverrides values
2. Create your AWSCluster, Await provisioning
3. Delete AWSCluster
4. Observe that on recreating from the same YAML, the previously created Security Group IDs cannot be found by CAPA - and in fact have been deleted from your AWS account.

**What did you expect to happen:**
I expect pre-existing infrastructure, not managed by AWSCluster, to be preserved when an AWSCluster is deleted.

**Environment:**

- Cluster-api-provider-aws version: Main 101938796a
- Kubernetes version: (use `kubectl version`): 1.21.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by richardcase** [comment]
Another issue related to securityGroupOverrides: #2466
