### ISSUE TITLE
ELBs should never be *recreated* in managed VPC mode

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2561]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

For some reason, yet to find a root cause, CAPA deleted an ELB for an existing cluster and recreated it. This is essentially unrecoverable when using ELBv1 since the ELB DNS name is randomly generated, which means certificates and endpoints change.

**What did you expect to happen:**
CAPA should never attempt to create an ELB twice for the same AWSCluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.6.3
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/priority critical-urgent

**Comment by randomvariable** [comment]
I suspect the answer is if we're not already, track the ELB ID in the spec, and if it ends up in a state where it attempts to delete or recreate the ELB, error out.

**Comment by sedefsavas** [comment]
We can close this issue in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2563
