### ISSUE TITLE
[e2e] Dump Kuberenetes Events

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2577]
/kind feature
/area testing
/help
/priority important-soon
/milestone v0.7.x

**Describe the solution you'd like**

During the execution of the e2e tests we should periodically extract the Kubernetes events and save them to the artefacts folder of the e2e test. This will aid in issue investigation.

**Anything else you would like to add:**

This is similar to how we dump machines at present: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/e2e/shared/suite.go#L220

**Environment:**

- Cluster-api-provider-aws version: 0.6.6

**Comment by randomvariable** [comment]
Is this ticket still valid, given this does actually happen if you use the CAPI e2e framework?

**Comment by richardcase** [comment]
No, i don't think it is.
