### ISSUE TITLE
🐛 EKSConfig controller doesn't update bootstrap secret data

### ISSUE THREAD

**Issue by trutx** [kubernetes-sigs/cluster-api-provider-aws#2578]
/kind bug

**What steps did you take and what happened:**

I have a running `EKSConfig`:

```sh
$ k get eksconfig -n rt2a rt2a-general-us-east-2a -o json | jq '.spec.kubeletExtraArgs'
{
  "image-gc-high-threshold": "50",
  "image-gc-low-threshold": "45",
  "minimum-container-ttl-duration": "1m",
  "node-labels": "infrastructureRef=rt2a-general-us-east-2a,infrastructureKind=machinepool,nr-ops.net/cf=machinepool"
}
```

The `EKSConfig` controller someday generated the corresponding data `Secret`:

```sh
$ k get secret -n rt2a rt2a-general-us-east-2a -o json | jq -r '.data.value' | base64 --decode
#!/bin/bash
/etc/eks/bootstrap.sh rt2a --kubelet-extra-args '--image-gc-high-threshold=50 --image-gc-low-threshold=45 --minimum-container-ttl-duration=1m --node-labels=infrastructureRef=rt2a-general-us-east-2a,infrastructureKind=machinepool,nr-ops.net/cf=machinepool'
```

Now I need to add a new `cpu-manager-policy` kubelet arg to my LaunchTemplates so newly created nodes get it. I modified the existing `EKSConfig`:

```sh
$ k patch eksconfig -n rt2a rt2a-general-us-east-2a --type json --patch '[{"op": "add", "path": "/spec/kubeletExtraArgs/cpu-manager-policy", "value":"static"}]'
eksconfig.bootstrap.cluster.x-k8s.io/rt2a-general-us-east-2a patched
$ k get eksconfig -n rt2a rt2a-general-us-east-2a -o json | jq '.spec.kubeletExtraArgs'
{
  "cpu-manager-policy": "static",
  "image-gc-high-threshold": "50",
  "image-gc-low-threshold": "45",
  "minimum-container-ttl-duration": "1m",
  "node-labels": "infrastructureRef=rt2a-general-us-east-2a,infrastructureKind=machinepool,nr-ops.net/cf=machinepool"
}
```

**What did you expect to happen:**

I expected the data `Secret` to be updated by the `EKSConfig` controller, but it wasn't. There is no update logic [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/bootstrap/eks/controllers/eksconfig_controller.go#L246-L283) so the `Secret` will never be updated unless manually deleted. This will in turn cause the LaunchTemplate to never be updated due to a userdata change [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/bootstrap/eks/controllers/eksconfig_controller.go#L246-L283) because `bootstrapDataHash` will never change unless the `Secret` is deleted.

**Anything else you would like to add:**

Incoming PR to fix it.

**Environment:**

- Cluster-api-provider-aws version: `v0.6.6`
- Kubernetes version: (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`):
```
# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by richardcase** [comment]
@trutx - thanks for raising this. Did you want to assign the issue to yourself?

**Comment by trutx** [comment]
Whatever works best for you. I have the PR ready, will push in short.
