### ISSUE TITLE
Support writing AWS cloud provider tags on pre-existing infrastructure

### ISSUE THREAD

**Issue by scottslowe** [kubernetes-sigs/cluster-api-provider-aws#2584]
**User Story**

As a user/operator I would like to be able to have CAPA write the necessary AWS tags required for proper AWS cloud provider operation onto pre-existing/pre-provisioned infrastructure, so that shared infrastructure can used to support multiple CAPI workload clusters.

**Detailed Description**

Currently, CAPA will write AWS cloud provider tags (`kubernetes.io/cluster/<name> = [owned | shared]`) onto AWS infrastructure it creates, but it will not write AWS cloud provider tags onto pre-existing/pre-provisioned AWS infrastructure. In such cases, the ability to support multiple workload clusters within a single set of shared AWS infrastructure is limited unless the names of the workload clusters are known or assigned in advance. When the names are known or assigned in advance, the appropriate tags can be added to the shared AWS infrastructure before the workload clusters are provisioned. When the names are *not* known or assigned in advance, then the tags must be managed separately and independently.

**Anything else you would like to add:**

Not that I can think of at this time.

/kind feature

**Comment by pydctw** [comment]
@scottslowe, which pre-existing AWS resources need these tags?
Is adding `kubernetes.io/cluster/<name> = shared` tag to subnets enough? Or are there other AWS resources that need the tags?

**Comment by scottslowe** [comment]
We need that tag on all subnets, yes, but we also need `kubernetes.io/role/internal-elb = 1` for private subnets and `kubernetes.io/role/elb = 1` for public subnets. We also need the `kubernetes.io/cluster/<name> = shared` tag on the VPC.

**Comment by scottslowe** [comment]
I saw that #2715 had been merged; I'm guessing this will hit the 0.7.1 release?

**Comment by pydctw** [comment]
I think so as 0.7.1 hasn't been released yet. cc @sedefsavas

**Comment by randomvariable** [comment]
Released in v0.7.1 and v1.0.0

/close
