### ISSUE TITLE
Add webhook health check

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-aws#2602]
/kind feature

**Describe the solution you'd like**
It would be nice if the controller health checks would use the readiness of the webhook server (instead of the no-op Ping).

For reference, the implementation in cluster-api: https://github.com/kubernetes-sigs/cluster-api/pull/4989

**Anything else you would like to add:**
This requires at least controller-runtime v0.9.3.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Webhook health check was removed due to a bug found which lead to tls handshake errors in #2629. Fix PR has been merged in controller-runtime, but we have to wait until the next controller-runtime release to integrate it.

xref:
* Slack discussion: https://kubernetes.slack.com/archives/CD6U2V71N/p1627643594012600
* bugfix PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1616

/reopen

**Comment by sbueringer** [comment]
fyi controller-runtime v0.9.6 has been released with a fix. So we should be good to go (I also verified it via the e2e tests of the cluster-api repo).

**Comment by geetikabatra** [comment]
@sbueringer Here is the PR that fixes this https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2685

**Comment by sbueringer** [comment]
Has been fixed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2685

/close
