### ISSUE TITLE
Don't attempt to recreate an ELB after the cluster has been provisioned

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2608]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

If a cluster was created at time X, and then the user deletes the ELB , CAPA will try to recreate the ELB, which will have a new DNS endpoint which will not work. There's not much point doing this, and CAPA also has issues updating the resource in Kubernetes because its own webhook rejects the update as immutable.

In this scenario, we should mark AWSCluster as failed, and inform the user the cluster is unrecoverable.

Long term, we should switch to using NLBs and a recoverable endpoint.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
The trick here is to figure out under what circumstances CAPA shouldn't recreate the ELB. Possibly once the CAPI Cluster endpoint is filled, because it's at this stage it becomes immutable?

**Comment by richardcase** [comment]
Block creation exactly like EC2 instance re-creation.

If we do the NLB work sooner then this issue will be rectified.

/milestone v1.x
/triage accepted
/priority important-soon

**Comment by Ankitasw** [comment]
@sedefsavas since you are working on NLB, is this needed?

> If we do the NLB work sooner then this issue will be rectified.

**Comment by richardcase** [comment]
My feeling is that if we change to use NLBs via #3088 then we probably don't need this? wdyt @sedefsavas ?

**Comment by sedefsavas** [comment]
Even if with NLB changes, we will only deprecate ELB, will not block their usage. Existing clusters will keep using ELB for a while so it is good to have.

**Comment by sedefsavas** [comment]
> The trick here is to figure out under what circumstances CAPA shouldn't recreate the ELB. Possibly once the CAPI Cluster endpoint is filled, because it's at this stage it becomes immutable?

How about this suggestion pointed above?

It is problematic to use the conditions for decisions that is set in the same controller.

**Comment by Ankitasw** [comment]
> How about this suggestion pointed above?

Just to clarify, does `CAPI Cluster endpoint` mean `clusterSpec.ControlPlaneEndpoint`?
