### ISSUE TITLE
awsmachinepool do not respect subnets filters

### ISSUE THREAD

**Issue by calvix** [kubernetes-sigs/cluster-api-provider-aws#2609]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`AWSMachinePool.Spec.Subnets` is type `[]AWSResourceReference` which allow AWS resource specification via:
* ID
* ARN
* Filters

But the implementation only considers IDs and ignores the rest.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/scope/machinepool.go#L224-L227

**What did you expect to happen:**
defined subnets filters are respected as it is implemented for MachineDeployment:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/ec2/instances.go#L293-L319

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.4.0
- Kubernetes version: (use `kubectl version`): any
- OS (e.g. from `/etc/os-release`): any

**Comment by randomvariable** [comment]
I'm already working on this one in fact. I'll be removing the unused fields until such a time they actually get implemented.

/lifecycle active
/assign

Part of #2087

**Comment by randomvariable** [comment]
basically, Subnets  --> []SubnetReference
[]SecurityGroups --> []SecurityGroupReference

and so forth.

Deleting AWSResourceReference from v1alpha4 so we don't end up doing this again :(

**Comment by calvix** [comment]
> 

> I'm already working on this one in fact. I'll be removing the unused fields until such a time they actually get implemented.
> 
> /lifecycle active
> /assign
> 
> Part of #2087

I actually have a prepared code to implement the lookup by filters, I would like to have the option there

**Comment by randomvariable** [comment]
@calvix sure, i can rebase over the top.

If you can, but not 100% necessary, can you convert AWSResourceReference into SubnetReference?

Also, this problem isn't just in AWSMachinePool but also AWSCluster so might be worth seeing if you can put it in both places.

**Comment by calvix** [comment]
jumping back on this, @randomvariable  where is type SubnetReference located? in which package?

**Comment by sedefsavas** [comment]
@calvix I `SubnetReference` would be a new struct which holds only the fields that is used (for instance if ARN is not used, it should not be there) but we can no longer do any changes in the api (AWSResourceRef to SubnetRef) until v1beta2 release, so that change has to wait for a bit.
We can proceed with implementing what is necessary to consider filters for AWSMachinePools.
