### ISSUE TITLE
Replace GNU Make with Go

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2610]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This project originally started using Bazel, but the complexity grew and as Go introduced build caching, we replaced with Make.
Unfortunately, the Makefile itself has become unwieldy, and not many folk either do or want to spend time writing M4, so we should look for a replacement. https://github.com/magefile/mage seems the most promising, allowing us to write the whole thing in Go.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

We should scope out requirements before ploughing through with this. Feel free to reach out on Slack at https://kubernetes.slack.com/archives/CD6U2V71N 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
@sedefsavas - we should probably discuss this one in office hours. I am not sure if there is any benefit moving away from a "standard"

**Comment by richardcase** [comment]
Discussed in the office hours call on 2022-01-10 and the consensus was that there should be significant improvments to switching to overcome the cost of switching from make to something else. We should improve the make experience and fix any issues that people have with it.

**Comment by sedefsavas** [comment]
We can create new issues if there are areas we should improve in the Makefile as this issue will not be closely relevant.
Closing the issue as per Richard's explanation.
