### ISSUE TITLE
Scale-in protection for node pools

### ISSUE THREAD

**Issue by kirek007** [kubernetes-sigs/cluster-api-provider-aws#2635]
/kind feature

**Describe the solution you'd like**
I would like to be able to create a node poole that will have a scale-in protection in auto scaling group. This would be needed to prevent unexpected or mistakenly scaled down groups/instances by unaware user. 

**Environment:**

- Cluster-api-provider-aws version: n/d
- Kubernetes version: (use `kubectl version`): n/d 
- OS (e.g. from `/etc/os-release`): n/d

**Comment by Jacobious52** [comment]
Would like to suggest this issue still be planned. Having the option to enable scale-in protection on the ASG is pretty important for some use cases
