### ISSUE TITLE
Invalid Parameter for SSM PutParameter in SC2S

### ISSUE THREAD

**Issue by erockwood** [kubernetes-sigs/cluster-api-provider-aws#2636]
The AWS API in some high side environments will reject setting DataType to "text" for "SecureString" parameter types. This request parameter is only valid when using the "String" type. 
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html#systemsmanager-PutParameter-request-DataType

The API behavior is inconsistent with GovCloud, where GovCloud will just ignore the request parameter.  
 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/0792c9704d6456de2a141ca653fc097a15c7aa12/pkg/cloud/services/ssm/secret.go#L97

CAPI version 0.3.14
CAPA version 0.6.4

Steps to Reproduce:
In high side environment use the AWS CLI to run:
aws ssm put-parameter --name "dataTypeText" --value "Anything" --type "SecureString" --data-type "text"

Create a new cluster with secureSecretsBackend set to ssm-parameter-store
Check CloudTrail logs

Error Code: OperationNotFound

**Comment by randomvariable** [comment]
Is SecureString not even supported with custom CMK?

**Comment by randomvariable** [comment]
Oh I see, we should be using SecureString, and it's text

**Comment by randomvariable** [comment]
@erockwood are you able to PR the change and test it? I don't have access to GovCloud as a non US citizen.

**Comment by erockwood** [comment]
@randomvariable the way it was explained to me the SecureString is always text so they reject the data type parameter even if it’s text. There is a possibility that AWS will relax their API, but it is probably better to just make this change.

I can PR and test, but it’ll take a while to go through the approval process on my end. It will either be next week or several weeks from now that I have results.

Thanks,
Ed

**Comment by randomvariable** [comment]
@erockwood Following up on this, I'm guessing approval has been difficult. We can pick this up if you want.

/lifecycle frozen
/priority important-soon
/milestone v1.1
