### ISSUE TITLE
Add nonRootVolumes support to AWSLaunchTemplates

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2654]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Similar to `AWSMachineSpec`, we should support `nonRootVolumes` in `AWSLaunchTemplates` as well.

/milestone v0.7.x
/priority backlog
/good-first-issue

**Comment by bishtsaurabh5** [comment]
Hello,
I am a beginner and I want to contribute to this issue, can you help me learning more about it and what needs to be done ?

**Comment by randomvariable** [comment]
@bishtsaurabh5 do you still want to work on this?

**Comment by sedefsavas** [comment]
/remove-lifecycle stale

@bishtsaurabh5 are you still working on this issue?

We already support nonRootVolumes in AWSMachine Spec
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/api/v1beta1/types.go#L187

We should add that field to AWSLaunchTemplates https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/8343acd0aff76aec600caeb26df71fab8c33d44a/exp/api/v1beta1/types.go#L58

And then the logic we have for that in AWSMachine controller should be implemented in AWSMachinePool controller and in AWSManagedMachinePool controller after [this PR ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3094)is merged.

**Comment by bishtsaurabh5** [comment]
@sedefsavas yes I am working on this . Thanks for your inputs :)
