### ISSUE TITLE
Remove eks controlplane and bootstrap providers from clusterctl

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2656]
/kind feature
/area provider/eks
/priority important-soon
/milestone v0.7.x

**Describe the solution you'd like**
As a result of the graduation of EKS (#2570) the controlplane and bootstrap providers have been removed and the controllers incorporated in the main infrastructure provider. As a result we need to remove the `aws-eks` controlplane and bootstrap providers from clusterctl (originally added in #1970).

**Anything else you would like to add:**

At the same time i will update the quick start docs to point to the CAPA docs that detail disabling EKS support.

**Comment by sedefsavas** [comment]
I reopened but @richardcase is this still TODO?

**Comment by richardcase** [comment]
It is needed still.  I need to update the docs url.

/triage accepted

**Comment by richardcase** [comment]
I'll reopen the PR and fix it up
