### ISSUE TITLE
 CredentialRequiresARNError

### ISSUE THREAD

**Issue by pieterv-icloud-com** [kubernetes-sigs/cluster-api-provider-aws#2668]
/kind bug

**What steps did you take and what happened:**
Following instructions here: https://cluster-api-aws.sigs.k8s.io/getting-started.html

**Initialization for common providers**

`./clusterawsadm bootstrap iam create-cloudformation-stack  --config eks.config`

Getting the following error:

```
Attempting to create AWS CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
--
Error: CredentialRequiresARNError: credential type credential_source requires role_arn, profile local
Error: CredentialRequiresARNError: credential type credential_source requires role_arn, profile local
```

**What did you expect to happen:**
 
 The command to succeed

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.6.8
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): ;inux

**Comment by richardcase** [comment]
@pieterv-icloud-com - what AWS environment variables did you have set when running this?

**Comment by richardcase** [comment]
Closing the issue as discussed in the refinement session.

/close

@pieterv-icloud-com - if you are still having issues with this please re-open.

**Comment by sedefsavas** [comment]
This issue tried to be closed above but somehow still open. Retrying to close it.
