### ISSUE TITLE
Session manager plugin installation is asked in every local e2e run

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#2674]
/kind bug

**What steps did you take and what happened:**
When executing the e2e run locally using `make test-e2e`, it always asks if we want to replace the session-manager-plugin or not, which is observed in mac OS and not in linux OS.

**What did you expect to happen:**
It should not ask everytime what we want to do with session-manager-plugin

**Anything else you would like to add:**
make -C hack/tools bin/session-manager-plugin
/Library/Developer/CommandLineTools/usr/bin/make share/ssm/sessionmanager-bundle.zip
make[2]: `share/ssm/sessionmanager-bundle.zip' is up to date.
cd bin && unzip -j ../share/ssm/sessionmanager-bundle.zip sessionmanager-bundle/bin/session-manager-plugin
Archive:  ../share/ssm/sessionmanager-bundle.zip
replace session-manager-plugin? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

**Environment:**

- Cluster-api-provider-aws version: v1alpha4 (v0.7)
- Kubernetes version: (use `kubectl version`):  v1.21.2
- OS (e.g. from `/etc/os-release`):  macOS Big Sur 11.5.2

**Comment by randomvariable** [comment]
thanks for filing. needs a macos person to test any fix (not me)

/priority important-longterm
