### ISSUE TITLE
Umbrella: Improved Testing

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#268]
/kind feature

- [ ] [Integration tests](#221)
- [ ] [Bazel support](#13)
- [ ] [automated publishing](#270)
- [ ] [pr-blocking integration tests](#271)
- [ ] [periodic e2e tests](#272)

**Comment by ncdc** [comment]
Let's close this as it inflates the outstanding issue count, and we have all the other individual issues that we'll need to address.
