### ISSUE TITLE
elasticloadbalancing:AddTags is duplicated in policy

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2683]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
We at least have `elasticloadbalancing:AddTags` as a duplicate entry in the actions in the policies that clusterawsadm generates, which wastes bytes. let's fix it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/area security
/priority backlog

**Comment by rayandas** [comment]
Hi @randomvariable if I can get some help and insight on the task, I would like to work on it.

**Comment by randomvariable** [comment]
Yes, that's correct.
