### ISSUE TITLE
CAPA lets you define an AWSMachine and AWSMachineTemplate without specifying an instance type and then it fails.

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2686]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Specify an AWSMachineTemplate without setting instanceType
CAPA will try to create a resultant AWSMachine and then error out with 

```
lastTransitionTime: "2021-08-19T18:02:16Z"
    message: "failed to create AWSMachine instance: failed to run instance: InvalidParameterValue:
```

**What did you expect to happen:**
Have the template and AWSMachine rejected by validating webhook

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.6.6
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
@fyangd if you're starting work on this, can you do a `/lifecycle active` , or unassign if you don't have time.

**Comment by fyangd** [comment]
> @fyangd if you're starting work on this, can you do a /lifecycle active , or unassign if you don't have time.

@randomvariable since this story is marked as urgent, let me unassign myself.  I'd be an interested observer for the time being.
