### ISSUE TITLE
PR Blocking test(s)

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#271]
/kind feature

create and wire up pr-blocking integration tests

/assign @liztio

**Comment by liztio** [comment]
what sort of things qualify as "integration tests" here? What's our test for completion?

**Comment by detiber** [comment]
@liztio ideally we'd do a live test where we actually exercise the creation of a cluster using cluster-api and perform a minimal smoke test that the cluster appears to be functional. I do not think that this needs to include the full clusterctl workflow, since that introduces additional cleanup/teardown issues and also drastically increases the test time.

**Comment by timothysc** [comment]
In an ideal world we would test the following on a per PR basis: 

- [MVP] Behavioral Tests 
    -  Infrastructure (vpc, etc) has been stood up according to the declarative spec 
        - Traffic inside of the vpc are routable 
        - Check the health of etcd 
        - At a minimum, we need verification of (quick-test)  

--- 

As a follow on we will open an issue to enumerate the future test blocking issues.
- [Future] Integration Tests 
   - Standup, and Teardown 
   - (TODO) Define the breakout here.
- [Future] All behavioral level conformance tests are run (sonobuoy)
- [Future] Traffic has been verified to (ingress is accessible)

**Comment by liztio** [comment]
update on this: we're blocked on better aws resource management, otherwise we'd run out of resources pretty much immediately in CI

current plan is to add AWS support to test-infra's existing resource manager, boskos

**Comment by ncdc** [comment]
@detiber please reassign to @akutz

**Comment by chuckha** [comment]
/close

we can iterate on existing tests now!
