### ISSUE TITLE
Confirm if main branch has all changes for v1alpha4 types

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2710]
Since we opened the main branch to v1alpha4, there are some additions to the document that summarizes v1alpha3 to v1alpha4 changes in core cluster-api.

We need to ensure that we still have all the changes listed there.
https://cluster-api.sigs.k8s.io/developer/providers/v1alpha3-to-v1alpha4.html

/priority-important-soon
/good-first-issue
/milestone v0.7.x

**Comment by randomvariable** [comment]
Should we add a checklist of tasks here, otherwise this issue seems a bit open ended and may not get closed?

**Comment by sayantani11** [comment]
@randomvariable I can make the checklist task if required
