### ISSUE TITLE
Documentation for GPU enabled cluster on AWS

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#2727]
/kind feature
/kind documentation

**Describe the solution you'd like**
Since the GPU support has been tested on CAPA clusters, we would like to add documentation for GPU enabled kubernetes cluster on AWS.

**Anything else you would like to add:**
Similar documentation in CAPZ: https://capz.sigs.k8s.io/topics/gpu.html

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shivi28** [comment]
As this issue is marked as good first issue, so un-assigning my name :) . Encouraging new contributors to pick this issue as it will be a good start.

**Comment by AvineshTripathi** [comment]
Can multiple people assign this ??

**Comment by Ankitasw** [comment]
@AvineshTripathi i don't think there is a need :) but feel free to choose from other good-first-issues

**Comment by richardcase** [comment]
@bishtsaurabh5 - are you still interested in working on this?

/milestone v1.x
/triage accepted
/priority important-soon

**Comment by bishtsaurabh5** [comment]
Yes @richardcase would be picking this up coming week

**Comment by bishtsaurabh5** [comment]
Removing assign right now as I currently do not have enough bandwidth to pick this up :)

**Comment by Ankitasw** [comment]
@AvineshTripathi this issue is still up for grab if you are looking out.
