### ISSUE TITLE
findSubnet function's logic is incorrect when subnet ID is specified

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#2732]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

findSubnet function's logic is incorrect when subnet ID is specified in AWSMachine's spec.  Current logic returns a subnet ID from a spec when failureDomain is not defined, which may not match any subnets provided in AWSCluster.

**What did you expect to happen:**
The function should find a matching subnet regardless of a failureDomain setting.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
Fixed in #2728 so:

/close

**Comment by sedefsavas** [comment]
Already fixed.
