### ISSUE TITLE
Use same golang version everywhere

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-aws#2736]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, golang version is maintained in multiple places like [versions.mk](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/versions.mk#L16), [Dockerfile](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/Dockerfile#L18)

This Issue to keep all the versions to one level to avoid golang version mismatch across different artifacts like controller, clusterawsadm

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
Hey @mkumatag ,
I know that dependabot updates the golang version automatically(once there is stable version available) in the dockerfile.
I see that other files which you have suggested like versions.mk, is changed manually in past.
@randomvariable / @sedefsavas do you want to add in more details here??
