### ISSUE TITLE
Review CAPA APIs to add omitempty only for optional fields

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#2747]
/kind feature

**Describe the solution you'd like**
**First Requirement:**
In CAPA APIs we have to review the type fields and mark optional fields with `omitempty` and remove from all other fields. 

**Second Requirement:**
Also by default all fields should be required and have `+kubebuilder:validation:Required` whereas the fields that we want to be optional should have `+optional` and `omitempty` tag.

**Anything else you would like to add:**

Related to #2740 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shivi28** [comment]
@randomvariable Do you have any thoughts to add more on this issue?

**Comment by randomvariable** [comment]
Only that we should add the required validation at the package level, and then make optional make sesne.

/priority important-soon

**Comment by shivi28** [comment]
Similar [issue](https://github.com/kubernetes-sigs/cluster-api/issues/5239) going on in CAPI, adding here for reference

**Comment by sedefsavas** [comment]
@shivi28 Let's close this issue as #2888 includes this one too.
