### ISSUE TITLE
multi-az deployment proposal

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#275]
/kind feature

The current deployment leverages a single AZ, but there is demand for a deployment that spans multiple AZs. This issue is for tracking the creation of a proposal for how the current implementation can be extended to support multi-az deployments.

/priority important-soon
/assign @randomvariable

**Comment by dlipovetsky** [comment]
> there is demand for a deployment that spans multiple AZs.

There are pitfalls to nodes spanning multiple AZs. Here is one that I believe is well known: EBS volumes do not span AZs, so a workload using storage backed directly by EBS cannot be moved to another AZ in case of an AZ outage. However, it is possible to use a separate cross-AZ replication mechanism on top of EBS.

I worry that end users will use multiple AZs without being aware of the pitfalls, or come to expect the AWS provider to protect them from the pitfalls.

**Comment by detiber** [comment]
Closing, was resolved by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1721
