### ISSUE TITLE
Support RoleAdditionalPolicies for ManagedMachinePool

### ISSUE THREAD

**Issue by abhinavnagaraj** [kubernetes-sigs/cluster-api-provider-aws#2750]
/kind feature

**Describe the solution you'd like**
Currently, `AWSManagedControlPlane` supports both,`roleName` and `roleAdditionalPolicies`.
`AWSManagedMachinePool` supports only `roleName`.

Just like in MCP, we need to allow `roleAdditionalPolicies` in `AWSManagedMachinePool`, to allow attaching additional policies applicable to the node group role.

**Comment by richardcase** [comment]
@abhinavnagaraj thats for woring on this and the PR. When you work on an issue can you assign it to yourself and set th elifecycle as active? This helps to stop anyone else doing a parallel development.

/assign abhinavnagaraj
/lifecycle active
