### ISSUE TITLE
Cannot delete AWSManagedControlPlane when using existing VPC

### ISSUE THREAD

**Issue by erkules** [kubernetes-sigs/cluster-api-provider-aws#2758]
/kind bug

Maybe interesting. I played  with machinepools. I'm in an environment you need to use an existing vpc. I forgot to set the vpc in machinepool. So the AWSManagedControlPlane could not be deployed. FunFact I was not able to delete the resource either:

`failed to delete vpc "": UnauthorizedOperation: You are not authorized to perform this operation.`

So deleting AWSManagedControlPlane failed because it was not able (missing rights anyway) to delete a non-existing vpc (as it was never be created (missing rights)). So it hangs.
I'm not sure if that;s AWS-specific or something that can be handled by the provider. 

**What steps did you take and what happened:**

Simplified I created a Cluster without having the rights to create an VPC.

**What did you expect to happen:**
As it was my mistake. I would have expected to delete the resource AWSManagedControlPlane.

**Environment:**

- Cluster-api-provider-aws version:  0.7.0

- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
- 
- OS (e.g. from `/etc/os-release`): 
Laptop or Host?

**Comment by Ankitasw** [comment]
@richardcase @sedefsavas since we are handling unmanaged VPC deletion [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/vpc.go#L205), so will it be enough to put a nil check for VPC ID and skip reconciliation before this condition?

**Comment by richardcase** [comment]
@Ankitasw - yes that seems reasonable as long as its before this check.

**Comment by Ankitasw** [comment]
@erkules I am trying to replicate this issue, so wanted to ask what do you mean by:

> I forgot to set the vpc in machinepool.

Do you mean you forgot to set it in `AWSManagedControlPlane` ? As we cannot set network specs in `MachinePool`.

**Comment by Ankitasw** [comment]
Also, if i try to specify a nil vpc in `AWSManagedControlPlane`, it still creates a new vpc for us.

**Comment by Ankitasw** [comment]
@erkules reminder for the clarification.
