### ISSUE TITLE
Umbrella: UX and "getting started" experience improvements

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#276]
/kind feature
/priority important-soon

The current getting started experience and general user UX is pretty hostile. 

- Help reduce user confusion between bootstrapping the cluster-api components, cluster creation, and pivoting.
- Ensure prerequisites are clear and fully defined
- Documentation around how to configure cluster/machines
- Explain how to scale a cluster
- etc...

/assign @detiber @randomvariable

**Comment by rdodev** [comment]
* CLIs:
  * There are several places where things can go sideways and the user has no idea where to start looking for errors. 
  * CLIs should try to provide feedback more actively
  * When not possible to provide real-time feedback, the CLIs should at the very least instruct the user for next steps/debugging (like `kubeadm reset` for isntance)
  * CLIs should be more verbose by default
* Documentation:
  * Troubleshooting guide
  * Implicit requirements:
     * registry with push permissions
     * image must be public (or else how to pass credentials inside DIND)
* Pre-flight checks:
  * For every action that has potentially bad non-recoverable states we should try to verify that all critical parts work.

**Comment by detiber** [comment]
+1 for github projects, I'd like to avoid overloading the use of milestones.

**Comment by chuckha** [comment]
Please break this down into smaller issues and close this issue when done

**Comment by randomvariable** [comment]
I think we should close this now that we have the quick start guide?
