### ISSUE TITLE
Generate manifests with kustomize

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#277]
/kind feature
/lifecycle active

**Describe the solution you'd like**
Ideally this repository should use kustomize to generate manifests and files.

**Anything else you would like to add:**
Getting started should also be updated

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
Closing since #286 has merged.
