### ISSUE TITLE
prebootstrapcommand in machinepool / managed machinepool

### ISSUE THREAD

**Issue by kholisrag** [kubernetes-sigs/cluster-api-provider-aws#2771]
/kind feature

**Describe the solution you'd like**
a `preBootstrapCommand` feature like that `eksctl` have, maybe both in unmanaged node / managed node. its greate feature for all of us I believe

**Anything else you would like to add:**
for our case, we need to mount the instance store of aws ec2 instance and be able to use it in hostPath of PersistentVolume

**Comment by randomvariable** [comment]
For EC2, you can do that already in KubeadmConfigTemplate and KubeadmControlPlane under preKubeadmCommands.

**Comment by petrukngantuk** [comment]
@randomvariable if we use eks and unmanaged node we can do that? can you elaborate more how to do it?

**Comment by randomvariable** [comment]
Sorry, I misread this. This is indeed a missing feature.

/priority critical-urgent

**Comment by richardcase** [comment]
Moving miletone

/milestone v1.2.0

**Comment by sedefsavas** [comment]
We may need to take this into account during Launch Templates design: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2771

**Comment by sedefsavas** [comment]
Since this is not only relevant to MachinePools, we need to come up with a generic solution for all Machines as @richardcase pointed.

This is blocking enabling clusterctl upgrade tests, which will help to catch conversion related issues, so adding release-blocking tag.

**Comment by cnmcavoy** [comment]
Interested in this functionality and trying to understand where it is at...given that #2854 was closed in preference to #2965 and neither addressed the missing bootstrapping features for this issue.

Is working on this issue blocked on #3024 being merged? What work remains before a PR could be submitted to add this functionality?

**Comment by Skarlso** [comment]
I believe this will be handled by #3757

**Comment by richardcase** [comment]
> I believe this will be handled by #3757

Yes it will. My change has stopped in favour of #3757
