### ISSUE TITLE
Bring your own control plane ELB

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2774]
/kind feature

**Describe the solution you'd like**
I am creating a CAPA cluster using [existing AWS infrastructure](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/55df68a6f34fcf0c01ffc08c02d077bf2e337fee/docs/book/src/topics/consuming-existing-aws-infrastructure.md). I have an existing ELB that I want CAPA to use.

**Anything else you would like to add:**
The ELB name is not part of the AWSCluster spec. The AWSCluster controller [derives the ELB name](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/9bb81e375bf53f37e6adc633bf4145717621bd7c/pkg/cloud/services/elb/loadbalancer.go#L307) from the cluster name.

It appears possible to make the ELB name part of the AWSCluster spec. The user can provide a value. If the user does not provide a value, CAPA will derive a value from the cluster name, as it does today, and write it to the spec. The AWSCluster validation webhook can ensure that the ELB name is written at most one time, [in the way it does for the controlPlaneEndpoint](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/55df68a6f34fcf0c01ffc08c02d077bf2e337fee/api/v1alpha4/awscluster_webhook.go#L105) field.

**Comment by shivi28** [comment]
Thanks @dlipovetsky for raising the detailed use case. 
We have one on-going proposal for[ Load balancer provider](https://github.com/kubernetes-sigs/cluster-api/pull/4389) and I will check if we can address this use case as part of that proposal.

**Comment by richardcase** [comment]
As there is a PR open:

/assign dlipovetsky 
/lifecycle active
