### ISSUE TITLE
v1beta1 Tracking Issue

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2778]
/kind feature

**Describe the solution you'd like**

* Bump API version to v1beta1 to match Cluster API Core

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Rough task list

1. [x] #2779 
  * Do immediately
1. [x] #2792
  * Do immediately
1. [x] #2780 
  * Depends on #2792
1. [x] #2781 
  * Depends on #2792
1. [ ] #2788 
  * Depends on #2780
1. [ ] #2793 
  * Depends on #2781
1. [x] #2783 
  * Do last

Related Issues:
* https://github.com/kubernetes-sigs/cluster-api/issues/5260
* https://github.com/kubernetes-sigs/cluster-api/issues/5262
* https://github.com/kubernetes-sigs/cluster-api/issues/5269
* https://github.com/kubernetes-sigs/cluster-api/issues/5277

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@randomvariable added one more [issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2788), could you please add it to the tracking list as well?

**Comment by sedefsavas** [comment]
/close
We will track the remaining issues in their own thread.
