### ISSUE TITLE
Bump controller runtime version to v0.10

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2779]
/kind feature
/area api
/priority important-soon

**Describe the solution you'd like**

For v1beta1, bump CR release to v0.10

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by shivi28** [comment]
@randomvariable, should we also upgrade the controller-tools to v0.7? If yes, Is it being addressed in this PR or should we create a separate issue for it?

**Comment by Ankitasw** [comment]
@shivi28 taken care of controller-tools as well
