### ISSUE TITLE
EC2 E2E test to upgrade v1alpha4 to v1beta1

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2793]
/kind feature

**Describe the solution you'd like**
Verify upgrades work

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Depends on #2781

**Comment by sedefsavas** [comment]
Fixed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2950
