### ISSUE TITLE
Allow customisation of node rules

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2798]
/kind feature

**Describe the solution you'd like**

One of the most common requests we have is to allow customisation of the node security group. In particular, users want to often change the SSH ingress rule when bastion is enabled or not, and either disable or change the node port ruleset.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.7.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/area api
/area networking
/priority important-soon
/milestone v0.8.0

**Comment by sedefsavas** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/392
