### ISSUE TITLE
Add defaulter & conversion for Internet-facing to internet-facing ELB scheme change

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2801]
/kind bug

**What steps did you take and what happened:**
We fixed an issue about ELB scheme enum values https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2768, but forgot to add the conversion for the clusters.

We should fix this before doing a release with #2768 fix in.
Also, we need to backport it to v1alpha3 too.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
cc @dilyevsky

**Comment by randomvariable** [comment]
I think we also need this in the defaulter so that it applies to existing v1alpha3 or existing v1alpha4 clusters.

**Comment by randomvariable** [comment]
Discussing with @sedefsavas , I think what we want is:

v1alpha3 --> v1alpha3 & v1alpha4 --> v1alpha4, default on Update to corrected value
v1alpha3 --> v1alpha4 , v1alpha3 --> v1beta1, v1alpha4 --> v1beta1, correct in conversion

We may also want to call this particular defaulter inside the controller, such that it allows the ELB to complete reconciliation. Calling patch will then update with the corrected value:

**Comment by sedefsavas** [comment]
Changes for the v1alpha4 release is described in the open PR: [see](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2807)


TODO:

**Changes to be added to the next v1alpha3 release:**
 No change in the API or webhooks, just use "Internet-facing" scheme and translate it to "internet-facing" internally in the controllers. This is enough to unblock existing users without any change to their objects.

**Changes to be added to the next v1beta1 release:**
`Internet-facing` to `internet-facing` modification will only happen in the conversion webhook and remove the logic that accepts `Internet-facing` scheme from the controllers. No need for defaulting.

**Comment by dlipovetsky** [comment]
Thanks for catching this @sedefsavas!

(I missed this issue because of a tag typo above :grimacing: )
