### ISSUE TITLE
Conformance tests failing for CAPA cluster

### ISSUE THREAD

**Issue by njuettner** [kubernetes-sigs/cluster-api-provider-aws#2817]
Hello 👋🏻 ,

I need some help understanding why conformance tests are failing when launching a default CAPA cluster (no EKS, using version **v1alpha3**) with Kubernetes version **1.19** using the **latest AWS CNI** for pod network communication.

I ran the tests several times to ensure this is not due flakiness.

When running sonobuoy (version **0.53.2**) using mode **certified-conformance** I always get the same failed tests:

```
Status: failed
Total: 5484
Passed: 300
Failed: 5
Skipped: 5179

Failed tests:
[sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance]
[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
[sig-network] Services should have session affinity work for NodePort service [LinuxOnly] [Conformance]
[sig-network] Services should be able to create a functioning NodePort service [Conformance]
[sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance]

Plugin: systemd-logs
Status: passed
Total: 4
Passed: 4
Failed: 0
Skipped: 
```

Did you faced that before? Any ideas why this is failing? How do you test currently, did you also run it?

**Comment by randomvariable** [comment]
This is a result of #2798 . The conformance tests want to use node ports that aren't open by default in the security group rules.

However, we have to find a balance - most customers/users I speak to currently balk at the existing open ports, which is why #2798  allows for its customisation. You can however make it work, by adjusting "cniIngressRules" and adding the used ports there.

**Comment by njuettner** [comment]
Thanks for you answer @randomvariable 🤗, could you elaborate a bit on how someone would do this right now? Do I need to wait for the customisation, will this also cherry-picked for `v1alpha3` or is this only for `v1alpha4?

**Comment by randomvariable** [comment]
Set CNIIngressRules on the awsCluster resource with the rules required. https://cluster-api-aws.sigs.k8s.io/crd/index.html#infrastructure.cluster.x-k8s.io/v1alpha4.CNIIngressRules 

These were introduced in v1alpha3, so you don't need #2798 .

I'm not sure exactly what you'll need - I think you need to add UDP 30000-65535, best to check the source code in the main kubernetes repo for what's required.

**Comment by njuettner** [comment]
@randomvariable once again thank you 👍🏻
