### ISSUE TITLE
Follow up on conversion-gen issues in Kubernetes 

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2826]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

During the implementation of #2820 , conversion-gen was unable to handle the case where EKS API types were importing types from `/api`. This led to "Duplicate Static Conversion" errors being reported, which if a developer tries to resolve by deleting one of the conversions leads to a `compilemissingerror`, and from this loop there is no seeming escape.

The end result of which was forking conversion-gen, and then disabling that check.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
I think we had something very similar with the internal types of the kubeadm bootstrap provider as the new v1beta1 package had a conflict with the internal v1beta1 package.

In that case the internal packages were renamed to `upstreamv1beta1`. But it sounds like that's not an option for CAPA.

(/cc @vincepri)

**Comment by Ankitasw** [comment]
@richardcase is this still needed? 
I don't see such issues now with API change.
