### ISSUE TITLE
When leader election is disabled controllers fail to start conversion webhooks when upgrading from v1alpha3 to v1beta1

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2834]
/kind bug
/kind release-blocking
/priority critical-urgent
/area api
/milestone v1.0.0

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Tracking issue for something we're debugging in https://kubernetes.slack.com/archives/C8TSNPY4T/p1633553853231000  as part of #2833 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@randomvariable Bug has been fixed in CR.

PR to pick up the fix in CAPI v1.0.x: https://github.com/kubernetes-sigs/cluster-api/pull/5632/files

not sure when it will land on CAPI main (https://github.com/kubernetes-sigs/cluster-api/issues/5576)
