### ISSUE TITLE
Tighten AutoScalingGroup lookups using tags

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2857]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The [autoscaling API now supports lookups by tag](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v1413-2021-10-14), so the AWS MachinePool controller could be made more robust by only matching tagged ASGs, using the same rules as the other services.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 1.0.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
/remove-lifecycle rotten

@shivi28 I see that there is an open PR for this.
What is the status there?
