### ISSUE TITLE
Panic in controller manager

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes-sigs/cluster-api-provider-aws#2859]
/kind bug

**What steps did you take and what happened:**
I was playing around to see what would happen if I created two EKS clusters with the same name in separate bootstrap clusters (which obviously doesn't work due to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/969). When creating the second cluster in the second bootstrap cluster, the CAPA controller manager panicked with the trace below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f82a1f]

goroutine 663 [running]:
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/awsnode.(*Service).deleteCNI(0xc001059980, 0x2b1aff8, 0xc000bc9410, 0xc00148be00, 0x4)
/workspace/pkg/cloud/services/awsnode/cni.go:189 +0x1df
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/awsnode.(*Service).ReconcileCNI(0xc001059980, 0x2b1aff8, 0xc000bc9410, 0x0, 0x0)
/workspace/pkg/cloud/services/awsnode/cni.go:48 +0x1e05
sigs.k8s.io/cluster-api-provider-aws/controlplane/eks/controllers.(*AWSManagedControlPlaneReconciler).reconcileNormal(0xc0006a12c0, 0x2b1aff8, 0xc000bc9410, 0xc0003fb260, 0xc000da6000, 0xc0009bf680, 0x2739176, 0x16)
/workspace/controlplane/eks/controllers/awsmanagedcontrolplane_controller.go:229 +0x7f6
sigs.k8s.io/cluster-api-provider-aws/controlplane/eks/controllers.(*AWSManagedControlPlaneReconciler).Reconcile(0xc0006a12c0, 0x2b1aff8, 0xc000bc9410, 0xc000a7a800, 0x7, 0xc000044300, 0x1c, 0xc000bc9400, 0x0, 0x0,...)
/workspace/controlplane/eks/controllers/awsmanagedcontrolplane_controller.go:186 +0x5ae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005360a0, 0x2b1af50, 0xc0008cfc00, 0x241a7c0, 0xc000bac700)
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005360a0, 0x2b1af50, 0xc0008cfc00, 0x280b800)
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000b80830, 0xc0005360a0, 0x2b1af50, 0xc0008cfc00)
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:210 +0x425
```

**What did you expect to happen:**
Not panic, but considering the linked issue, not successfully provision either...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.7.0
- Kubernetes version: (use `kubectl version`): v1.21.2
- OS (e.g. from `/etc/os-release`): manjaro

**Comment by joejulian** [comment]
I was seeing these panics as well, but I was not creating duplicate named clusters. The panic seems to come from the client being unset https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/awsnode/cni.go#L189.

This appears to me to be caused by an unchecked error occurred in NewService: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/awsnode/service.go#L50
