### ISSUE TITLE
Fix the `AWS.SimpleQueueService.NonExistentQueue` errors

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2912]
/kind bug
/help

**What steps did you take and what happened:**

When looking at the logs for e2e test runs, there are a lot of errors like this:

```bash
E1103 18:11:17.046414       1 controller.go:317] controller/awscluster "msg"="Reconciler error" "error"="AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.\n\tstatus code: 400, request id: 346776dc-e171-5851-b3a6-2f2032741436" "name"="cluster-mbp3le" "namespace"="functional-gpu-cluster-dock0l" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" 
```

[Source log file](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2871/pull-cluster-api-provider-aws-e2e/1455958494833283072/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-7bd56cd58-w68gp/manager.log)

This makes it harder to look for the real errors of failures with these log messages polluting the log.

**What did you expect to happen:**
I expect these errors not to be logged.....unless its  actually the issue.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@richardcase Does it look fine now? 
[Recent logs after the fix](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2976/pull-cluster-api-provider-aws-e2e/1461647520751947776/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-7bd56cd58-mtpk8/manager.log)

**Comment by richardcase** [comment]
@Ankitasw - the logs look a lot better :+1: I haven't looked at the PR yet....what was the problem?

**Comment by Ankitasw** [comment]
Whenever we are trying to fetch the queue URL, in awsinstancestate controller, I checked for this error to skip. Not sure if that's fine to skip or shall we still throw those error.
