### ISSUE TITLE
Change branch from master to main in few files

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-aws#2913]
/kind bug

**What steps did you take and what happened:**
The branch in capa has been renamed to main quite some time ago. As per https://cs.k8s.io/?q=cluster-api%2Fblob%2Fmaster&i=nope&files=&excludeFiles=&repos= there are still a few files in which the branch is still not changed from master.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
/assign
cc @richardcase @nader-ziada

**Comment by sayantani11** [comment]
cc @randomvariable @richardcase

**Comment by richardcase** [comment]
So just in comments but we should change these:

/triage accepted
/help
/good-first-issue
/priority backlog

**Comment by randomvariable** [comment]
Yup, this seems reasonable. We couldn't change those before because the Cluster API repo didn't switch over until relatively recently (in the last 2 months). We can definitely clean it up now.

**Comment by DiptoChakrabarty** [comment]
hey would like to take it up

**Comment by sayantani11** [comment]
@DiptoChakrabarty I already am assigned this if you see. Sorry but can you take another issue.
Thanks.
