### ISSUE TITLE
Creating a new ec2 instance for the same AWSMachine

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2915]
/kind bug

**What steps did you take and what happened:**

In a fully functional v1alpha3 cluster, while a healthy ec2 instance exists, a second instance is created by the AWSMachine controller for the same `AWSMachine` due to unknown reasons. 

During AWSMachine `reconcileNormal()`, we check if the instance exists; if not, a new instance is created: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/controllers/awsmachine_controller.go#L489
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/controllers/awsmachine_controller.go#L504-L505

In this particular case, providerID on the AWSMachine was set, hence findInstance() called InstanceIfExists() method:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/pkg/cloud/services/ec2/instances.go#L79

The only case where a new instance is created is when `InstanceIfExists()` returns nil instance and nil error.
InstanceIfExists() calls `DescribeInstances` and two things might have happened for returning nil instance and nil error.:
1) DescribeInstances() returned a 404 error for an existing ec2 instance
2) DescribeInstances() returned 0 instances for an existing ec2 instance

I could not pinpoint what caused this but we should not be creating a new ec2 instance when ProviderID is set in `AWSMachine`, as it does not propagate to `Machine` object. Remediation is either handled in KCP or with MHC.

**Comment by dlipovetsky** [comment]
Thanks for filing this! I have seen at least two internal reports of what appears to be this issue. The reports are for CAPA v0.7.0. If we can create a failing test for this issue, let's check if it also fails on the release-0.7 branch.

**Comment by dlipovetsky** [comment]
The EC2 API is eventually consistent: One server might fulfill the RunInstances API call. Later another server, without the latest information on the set of created instances, might fulfill the DescribeInstances call, and return no matching instances.

**Comment by dlipovetsky** [comment]
To address the issue of eventual consistency, we should make our RunInstances API calls idempotent.

We'll need to create a client token (64 character string), store it with the AWSMachine, and use that token every time we call RunInstances for that AWSMachine.

See https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html#run-instances-idempotency

**Comment by sedefsavas** [comment]
@dlipovetsky 
We wait until instances come up before proceeding (`WaitUntilInstanceRunningWithContext`), it should be enough time to propagate the info and be consistent about the existence of the instance.

In the issue I observed, instances did not spawned back to back. The first instance works for several months, and for some reason at a later point in time, `DescribeInstance()` returns `not found` error. That is when the next instance is created.

**Comment by dlipovetsky** [comment]
> In the issue I observed, instances did not spawned back to back. The first instance worked for several months, and for some reason at a later point in time, `DescribeInstance()` returned `not found` error. That is when the next instance is created.

Interesting! In this case, the AWSMachine has a ProviderID, and the DescribeInstance query returns a NotFound error.

That _should_ only happen if the instance has been deleted. While it is true that, for about an hour after the instance is deleted, its record should be found, eventually the record is removed.

> Recently terminated instances might appear in the returned results. This interval is usually less than one hour. -- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html 

Of course, we can file an issue with AWS, because the EC2 service returned a false record. But I don't see what more we could do.

**Comment by dlipovetsky** [comment]
We could tag every instance with a unique identifier derived from the AWSMachine. When we reconcile the AWSMachine, we look for all instances matching this unique identifier. If we find more than instance that matches, we raise a warning to the user by setting a Condition, and recording an Event.

While we _could_ use a heuristic to delete all but one matching instance, I think that could have unintended consequences. And I'd also like any user that sees that warning to report back to us, or perhaps directly file an issue with AWS.
