### ISSUE TITLE
EKS control plane failed to allocate ELB instance

### ISSUE THREAD

**Issue by 10hin** [kubernetes-sigs/cluster-api-provider-aws#2918]
/kind bug

**What steps did you take and what happened:**

I create a cluster with EKS control plane and managed machine pool according to document:
https://cluster-api-aws.sigs.k8s.io/topics/eks/creating-a-cluster.html
Then, create Service resource in the cluster with type=LoadBalancer.
But cloud-controller-manager failed to assign ELB instance to the Service resource.
By my investigation, this problem happen because CAPA put wrong tag to AWS Subnet. Details are following section.

**What did you expect to happen:**

Service resource get ELB instance assigned.

**Anything else you would like to add:**

When I found this problem, I made following resources in management cluster:
- kind: Cluster
  name: deathstar
  namespace: deathstarbench
- kind: AWSManagedControlPlane
  name: deathstar-control-plane
  namespace: deathstarbench
And EKS control plane named "deathstarbench_deathstar-control-plane".
Then, I think that Subnets created for the cluster should have tag with key "kubernetes.io/cluster/deathstarbench_deathstar-control-plane", but in actual, they have only tag with key "kubernetes.io/cluster/deathstar" (I create these with Cluster named "deathstar").
In addition, by putting desired tag key "kubernetes.io/cluster/deathstarbench_deathstar-control-plane", CCM succeed to assign ELB instance to Service.

**Environment:**

- Cluster-api-provider-aws version: v1.0.0
- Kubernetes version: (use `kubectl version`): v1.21.2
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
To investigate:

/assign

**Comment by 10hin** [comment]
At following line, reconciler creates subnet tag from s.scope.Name().
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/ba3fa47bf5d0019d035dde12916eb7057724424f/pkg/cloud/services/network/subnets.go#L421
this should be decided according to name specified to EKS cluster. For example, the value of field eksClusterName in AWSManagedControlPlaneSpec.

**Comment by pydctw** [comment]
Thanks for reporting the bug. When I added the tag to the subnets, I didn't realize EKSCluster has a name field that can be generated differently. This is a valid.
