### ISSUE TITLE
RFE: Modify Makefile to just call bazel

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#292]
**Describe the solution you'd like**
Modify the Makefile to reduce the number of targets and to have a .PHONY precondition, requiring that developer install bazel with a link to the simplified instructions.  

This is standard operating procedure, for many build systems as they migrate.  e.g. It's normal to add a `make deps` that outlines the dependencies needed.  

https://suva.sh/posts/well-documented-makefiles/
 

/kind feature
/assign @liztio 
/cc @randomvariable

**Comment by randomvariable** [comment]
i'm going to change #290 into tackling this as having a consistent Go toolchain is needed to be able to get consistent results with `go fmt` because parameter alignment preferences changed.
