### ISSUE TITLE
Move non-exposable code to internal

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2925]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by invidian** [comment]
/remove-lifecycle stale

This is a good practice and in context of #3282, it make more sense IMO.

**Comment by sedefsavas** [comment]
@invidian copying a comment I left to #3282:
> Given that most of CAPA code is designed for internal consumption, we can add a warning to the book stating that which parts of the code is safe to use.
clusterawsadm libraries are probably the only bits that we would want to expose.
Instead of moving everything to internal packages, how about we only document this fact and change apidiff to check only api packages?

WDYT?

**Comment by invidian** [comment]
I think it's worth moving, even for the sake of just following the best practices, as there might not actually be many users of this code in the wild. The change is small and takes a fixed cost (sed+ it's likely to make conflicts to existing PRs), as opposed to leaving it as it is, where it will eventually gather users and then either break their workflow when breaking changes are introduced or will block them from updating the dependencies (which might also bring security implications). Also in my opinion just having it documented is not strong enough barrier, as there is a saying that "nobody reads documentation". The change is also easy to revert if needed (if there is a reported demand) and then it can be done consciously with all implications (maintenance burden etc). It also feels to me like just using the right tool for the job, by leveraging Go mechanisms as opposed to just documentation.

**Comment by dlipovetsky** [comment]
+1 to @sedefsavas's [proposal](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2925#issuecomment-986628986), and to the [points](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2925#issuecomment-1063868612) @invidian makes above.

**Comment by sedefsavas** [comment]
/good-first-issue

as most of the code (other than the libraries in cmd folder) will go to internal.

**Comment by dlipovetsky** [comment]
From office hours today:
- The benefits are not clear. We have not had (as of today) had problems as the result of exporting code that should be internal.
- Some maintainers prefer to not move code to `internal`, because it complicated the code layout.
- Instead of moving code to `internal`, we can document that the project guarantees compatibility for APIs, but not the implementation.
