### ISSUE TITLE
[e2e] Enable out-of-tree cloud-provider and CSI in e2e tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2941]
Since we are getting close to the release where in-tree cloud providers are removed from Kubernetes repo, it would be good to enable out-of-tree cloud providers by default in all of our e2e tests.

This gets us closer to defaulting to out-of-tree cloud provider issue is: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/964

/area testing
/priority important-soon
/milestone v1.x
/triage accepted

**Comment by sedefsavas** [comment]
Also, we should bump their versions. We are using 1.20 CCM in our tests and an older version of CSI driver.

**Comment by sedefsavas** [comment]
Not really a good first issue, requires e2e experience.

**Comment by sedefsavas** [comment]
It is better to start doing this when Kubernetes v1.24 is out, by this way all tests could use >v1.22 version where CSIMigration is enabled by default.

**Comment by Ankitasw** [comment]
/reopen
in favor of https://github.com/kubernetes/enhancements/pull/3519/files
/triage accepted
/priority important-soon

**Comment by Ankitasw** [comment]
cc @richardcase
