### ISSUE TITLE
Add AWSClusterTemplate type for ClusterClass support

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2942]
/kind api-change

**Describe the solution you'd like**

Add a new CRD named AWSClusterTemplate. This is needed for ClusterClass.
In the short term this type will not be used outside of ClusterClass.

**Comment by sbueringer** [comment]
@sedefsavas I think this might already be implemented: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2575

**Comment by sedefsavas** [comment]
I was on vacation when it was merged :smile:, missed it. Thanks @sbueringer

**Comment by sbueringer** [comment]
@sedefsavas Some additional info. I have to wait until https://github.com/kubernetes-sigs/cluster-api/pull/5583 is merged in core CAPI, but apart from that I have a CAPA ClusterClass quickstart test working (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2945)
