### ISSUE TITLE
[e2e] EKS tests failing for 0.6

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2967]
/kind bug
/area provider/eks
/area testing
/priority critical-urgent

**What steps did you take and what happened:**
The EKS e2e tests are failing for the release-0.6 branch:

```
I1117 11:33:23.007393       1 session.go:106] controllers/AWSManagedControlPlane/identity "msg"="Creating an AWS Session" "cluster"="cluster-j9v6wm" "eksControlPlane"="cluster-j9v6wm-control-plane" "namespace"="eks-nodes-jmxtus" 
I1117 11:33:23.007816       1 session.go:261] controllers/AWSManagedControlPlane/identity "msg"="Getting identity" "cluster"="cluster-j9v6wm" "eksControlPlane"="cluster-j9v6wm-control-plane" "identityKey"={"Namespace":"","Name":"default"} "namespace"="eks-nodes-jmxtus" 
E1117 11:33:23.108508       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create scope: failed to create aws session: Failed to get providers for cluster: AWSClusterControllerIdentity.infrastructure.cluster.x-k8s.io \"default\" not found" "controller"="awsmanagedcontrolplane" "name"="cluster-j9v6wm-control-plane" "namespace"="eks-nodes-jmxtus"
```

I suspect they have been failing for some time. So we need to fix the tests before the next release of 0.6 and also we need to add periodic testing.

**What did you expect to happen:**
I expect the eks e2e tests to pass

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.6.9
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
With the deprecation of 0.6 imminent, should we fix this?

@sedefsavas - wdyt?

**Comment by sedefsavas** [comment]
I think providing a working migration path should be enough.

**Comment by sedefsavas** [comment]
We will no longer backport fixes etc so don't really need a signal IMO.
