### ISSUE TITLE
Remove requirement for GNU Make, envsubst & gettext for end-user experience

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#299]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Part of #276 

Having gettext, envsubst and GNU Make installed is unusual for end-user
software, and it's extra things that will need to be 
`brew/apt/dnf` installed, as Make in particular is not installed
by default on all systems.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by randomvariable** [comment]
some bits in #310

**Comment by randomvariable** [comment]
There's another side to this than #310 where we can use Bazel to generate up to date provider-components manifests that are also potentially release artifacts rather than getting the user to copy the repo.

Any kustomize/ksonnet/<favouriteyamlmodifier> steps can then be a function of end-user or higher-level tooling.

**Comment by randomvariable** [comment]
My plan for this is to take some of the e2e bazel tests and turn them into release artifacts - that we end up with a compiled tar/zip with a `provider-components.yaml` that we can upload as part of the github release.

**Comment by randomvariable** [comment]
/lifecycle active

Will merge #310 in

**Comment by timothysc** [comment]
@randomvariable are you going to have cycles to finish this off?

**Comment by randomvariable** [comment]
#580 removes make. `gettext` remains at present, to be sorted out in a follow up PR.

**Comment by ncdc** [comment]
I'd propose that this be considered for deferring to Next if it gets down to the wire for v1alpha1.

**Comment by randomvariable** [comment]
We got rid of make, which was the main thing.

Removing the use of gettext entirely will require changes to e2e, so if it's done now, will break #606, which will need rebasing and fixups

**Comment by vincepri** [comment]
I'm ok moving this onto Next. The linked PR's changes is heavyweight and we're very close to reaching release.

**Comment by detiber** [comment]
We've removed the need for make, so I'll close this PR. Further improvements to the getting started experience can be refined later.

/close
