### ISSUE TITLE
Reduce cyclomatic complexity

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2995]
We have high cyclomatic complexity which makes the codebase harder to navigate, maintain, and test.

`gocyclo` linter is enabled but the default is set to 30, which is quite high. We have several functions with >20 complexity. 

```
pkg/cloud/services/securitygroup/securitygroups.go:54:1: cyclomatic complexity 26 of func `(*Service).ReconcileSecurityGroups` is high (> 10) (gocyclo)

pkg/cloud/services/ec2/instances.go:260:1: cyclomatic complexity 28 of func `(*Service).findSubnet` is high (> 10) (gocyclo)
```
Initially, let's target to reduce complexity to ~10 by [Ref1]

- Divide longer functions into smaller ones.
- Use Decorator pattern [Ref2]
- Reduce if-else-switch statements
- Remove duplicated + obsolete code

[Ref1]: https://linearb.io/blog/reduce-cyclomatic-complexity/
[Ref2]: https://en.wikipedia.org/wiki/Decorator_pattern

**Comment by Ankitasw** [comment]
List of functions which require cyclomatic complexity to be >10 :

- **cmd/clusterawsadm/cmd/eks/addons/list_available.go:53**:1: cyclomatic complexity 14 of func `listAvailableAddons` is high (> 10) (gocyclo)
- **cmd/clusterawsadm/cmd/eks/addons/list_installed.go:53**:1: cyclomatic complexity 12 of func `listInstalledAddons` is high (> 10) (gocyclo)
- **pkg/eks/identityprovider/plan.go:50**:1: cyclomatic complexity 12 of func `(*plan).Create` is high (> 10) (gocyclo)
- - **cmd/clusterawsadm/api/bootstrap/v1beta1/defaults.go:50**:1: cyclomatic complexity 11 of func `SetDefaults_AWSIAMConfigurationSpec` is high (> 10) (gocyclo)
- **exp/api/v1beta1/awsfargateprofile_webhook.go:71**:1: cyclomatic complexity 11 of func `(*AWSFargateProfile).ValidateUpdate` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/iam/iam.go:207**:1: cyclomatic complexity 16 of func `(*IAMService).EnsureTagsAndPolicy` is high (> 10) (gocyclo)
- **pkg/cloud/services/awsnode/cni.go:43**:1: cyclomatic complexity 21 of func `(*Service).ReconcileCNI` is high (> 10) (gocyclo)
- **cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go:50**:1: cyclomatic complexity 11 of func `SetDefaults_AWSIAMConfigurationSpec` is high (> 10) (gocyclo)
- **bootstrap/eks/controllers/eksconfig_controller.go:64**:1: cyclomatic complexity 14 of func `(*EKSConfigReconciler).Reconcile` is high (> 10) (gocyclo)
- **bootstrap/eks/controllers/eksconfig_controller.go:143**:1: cyclomatic complexity 12 of func `(*EKSConfigReconciler).joinWorker` is high (> 10) (gocyclo)
- **api/v1alpha4/types.go:534**:1: cyclomatic complexity 12 of func `(*IngressRule).Equals` is high (> 10) (gocyclo)
- **controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go:111**:1: cyclomatic complexity 13 of func `(*AWSManagedControlPlane).ValidateUpdate` is high (> 10) (gocyclo)
- **api/v1beta1/awscluster_webhook.go:68**:1: cyclomatic complexity 24 of func `(*AWSCluster).ValidateUpdate` is high (> 10) (gocyclo)
- **api/v1beta1/network_types.go:474**:1: cyclomatic complexity 12 of func `(*IngressRule).Equals` is high (> 10) (gocyclo)
- **api/v1alpha3/types.go:520**:1: cyclomatic complexity 12 of func `(*IngressRule).Equals` is high (> 10) (gocyclo)
- **pkg/cloud/scope/session.go:247**:1: cyclomatic complexity 15 of func `buildProvidersForRef` is high (> 10) (gocyclo)
- **pkg/cloud/scope/session.go:106**:1: cyclomatic complexity 12 of func `sessionForClusterWithRegion` is high (> 10) (gocyclo)
- **exp/controlleridentitycreator/awscontrolleridentity_controller.go:51**:1: cyclomatic complexity 14 of func `(*AWSControllerIdentityReconciler).Reconcile` is high (> 10) (gocyclo)
- **pkg/cloud/endpoints/endpoints.go:60**:1: cyclomatic complexity 11 of func `ParseFlag` is high (> 10) (gocyclo)
- **pkg/cloud/services/instancestate/rule.go:36**:1: cyclomatic complexity 16 of func `(Service).reconcileRules` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/cluster.go:46**:1: cyclomatic complexity 17 of func `(*Service).reconcileCluster` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/nodegroup.go:414**:1: cyclomatic complexity 15 of func `(*NodegroupService).reconcileNodegroupConfig` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/nodegroup.go:181**:1: cyclomatic complexity 15 of func `(*NodegroupService).createNodegroup` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/nodegroup.go:526**:1: cyclomatic complexity 15 of func `(*NodegroupService).setStatus` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/roles.go:154**:1: cyclomatic complexity 13 of func `(*NodegroupService).reconcileNodegroupIAMRole` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/roles.go:55**:1: cyclomatic complexity 13 of func `(*Service).reconcileControlPlaneIAMRole` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/nodegroup.go:312**:1: cyclomatic complexity 13 of func `(*NodegroupService).reconcileNodegroupVersion` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/roles.go:272**:1: cyclomatic complexity 12 of func `(*FargateService).reconcileFargateIAMRole` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/nodegroup.go:471**:1: cyclomatic complexity 12 of func `(*NodegroupService).reconcileNodegroup` is high (> 10) (gocyclo)
- **pkg/cloud/services/eks/identity_provider.go:32**:1: cyclomatic complexity 11 of func `(*Service).reconcileIdentityProvider` is high (> 10) (gocyclo)
- **cmd/clusterawsadm/ami/list.go:41**:1: cyclomatic complexity 15 of func `List` is high (> 10) (gocyclo)
- **cmd/clusterawsadm/cloudformation/bootstrap/template.go:75**:1: cyclomatic complexity 14 of func `(Template).RenderCloudFormation` is high (> 10) (gocyclo)
- **controlplane/eks/controllers/awsmanagedcontrolplane_controller.go:114**:1: cyclomatic complexity 12 of func `(*AWSManagedControlPlaneReconciler).Reconcile` is high (> 10) (gocyclo)
- **test/e2e/shared/resource.go:110**:1: cyclomatic complexity 15 of func `(*TestResource).doesSatisfy` is high (> 10) (gocyclo)
- **test/e2e/shared/aws.go:262**:1: cyclomatic complexity 12 of func `ensureTestImageUploaded` is high (> 10) (gocyclo)
- **test/e2e/shared/resource.go:155**:1: cyclomatic complexity 11 of func `AcquireResources` is high (> 10) (gocyclo)
- **exp/controllers/awsmachinepool_controller.go:383**:1: cyclomatic complexity 25 of func `(*AWSMachinePoolReconciler).reconcileLaunchTemplate` is high (> 10) (gocyclo)
- **exp/controllers/awsmachinepool_controller.go:88**:1: cyclomatic complexity 15 of func `(*AWSMachinePoolReconciler).Reconcile` is high (> 10) (gocyclo)
- **exp/controllers/awsmachinepool_controller.go:192**:1: cyclomatic complexity 13 of func `(*AWSMachinePoolReconciler).reconcileNormal` is high (> 10) (gocyclo)
- **exp/controllers/awsmanagedmachinepool_controller.go:91**:1: cyclomatic complexity 13 of func `(*AWSManagedMachinePoolReconciler).Reconcile` is high (> 10) (gocyclo)
- **main.go:116**:1: cyclomatic complexity 30 of func `main` is high (> 10) (gocyclo)
- **main.go:293**:1: cyclomatic complexity 17 of func `enableGates` is high (> 10) (gocyclo)
- **pkg/cloud/services/securitygroup/securitygroups.go:55**:1: cyclomatic complexity 26 of func `(*Service).ReconcileSecurityGroups` is high (> 10) (gocyclo)
- **pkg/cloud/services/securitygroup/securitygroups.go:658**:1: cyclomatic complexity 11 of func `ingressRulesFromSDKType` is high (> 10) (gocyclo)
- **pkg/cloud/services/securitygroup/securitygroups.go:461**:1: cyclomatic complexity 11 of func `(*Service).getSecurityGroupIngressRules` is high (> 10) (gocyclo)
- **pkg/cloud/services/elb/loadbalancer.go:53**:1: cyclomatic complexity 19 of func `(*Service).ReconcileLoadbalancers` is high (> 10) (gocyclo)
- **pkg/cloud/services/elb/loadbalancer.go:678**:1: cyclomatic complexity 14 of func `(*Service).describeClassicELB` is high (> 10) (gocyclo)
- **pkg/cloud/services/elb/loadbalancer.go:417**:1: cyclomatic complexity 12 of func `(*Service).getAPIServerClassicELBSpec` is high (> 10) (gocyclo
- **pkg/cloud/services/elb/loadbalancer.go:266**:1: cyclomatic complexity 11 of func `(*Service).RegisterInstanceWithAPIServerELB` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/subnets.go:47**:1: cyclomatic complexity 26 of func `(*Service).reconcileSubnets` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/routetables.go:41**:1: cyclomatic complexity 23 of func `(*Service).reconcileRouteTables` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/network.go:73**:1: cyclomatic complexity 16 of func `(*Service).DeleteNetwork` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/natgateways.go:39**:1: cyclomatic complexity 15 of func `(*Service).reconcileNatGateways` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/vpc.go:109**:1: cyclomatic complexity 13 of func `(*Service).ensureManagedVPCAttributes` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/subnets.go:265**:1: cyclomatic complexity 12 of func `(*Service).describeVpcSubnets` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/vpc.go:43**:1: cyclomatic complexity 12 of func `(*Service).reconcileVPC` is high (> 10) (gocyclo)
- **pkg/cloud/services/network/natgateways.go:124**:1: cyclomatic complexity 11 of func `(*Service).deleteNatGateways` is high (> 10) (gocyclo)
- **controllers/awsmachine_controller.go:422**:1: cyclomatic complexity 29 of func `(*AWSMachineReconciler).reconcileNormal` is high (> 10) (gocyclo)
- **controllers/awsmachine_controller.go:275**:1: cyclomatic complexity 19 of func `(*AWSMachineReconciler).reconcileDelete` is high (> 10) (gocyclo)
- **controllers/awsmachine_controller.go:130**:1: cyclomatic complexity 16 of func `(*AWSMachineReconciler).Reconcile` is high (> 10) (gocyclo)
- **controllers/awscluster_controller.go:238**:1: cyclomatic complexity 13 of func `(*AWSClusterReconciler).reconcileNormal` is high (> 10) (gocyclo)
- **controllers/awscluster_controller.go:119**:1: cyclomatic complexity 12 of func `(*AWSClusterReconciler).Reconcile` is high (> 10) (gocyclo)
- **controllers/awsmachine_security_groups.go:80**:1: cyclomatic complexity 11 of func `(*AWSMachineReconciler).securityGroupsChanged` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/instances.go:113**:1: cyclomatic complexity 28 of func `(*Service).CreateInstance` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/instances.go:261**:1: cyclomatic complexity 28 of func `(*Service).findSubnet` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/ami.go:191**:1: cyclomatic complexity 18 of func `(*Service).defaultBastionAMILookup` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/instances.go:471**:1: cyclomatic complexity 17 of func `(*Service).runInstance` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/launchtemplate.go:399**:1: cyclomatic complexity 12 of func `(*Service).DiscoverLaunchTemplateAMI` is high (> 10) (gocyclo)
- **pkg/cloud/services/ec2/bastion.go:47**:1: cyclomatic complexity 11 of func `(*Service).ReconcileBastion` is high (> 10) (gocyclo)

**Comment by sedefsavas** [comment]
We should not focus on numbers but rather dividing the over-complicated methods into logical parts.
Copying @vincepri's comment on[ this PR](https://github.com/kubernetes-sigs/cluster-api/pull/6183#discussion_r812134821):
> reducing the number of if branches or lines of code in a particular function or method isn't a particularly useful target. We should always strive for readability and simplicity rather than refactoring based on a arbitrary number.
