### ISSUE TITLE
Rally on a spec.  

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#3]
The goal of this effort is to produce a spec to rally on with interested parties, then break down the work items in this repo.  

I'd suggest PR-ing a KEP to this repo that we can agree on.

**Comment by timothysc** [comment]
In conversing on a kickoff meeting we'll start with 2 docs to feed into a local spec that we can rally on. 
The recording is here - https://youtu.be/_ewtDZsDNjM 

1. ) History document to serve as lessons learned 
2.)  Enumerate options and taxonomy to allow for feeding of requirements.

**Comment by timothysc** [comment]
Per subproject discussion:  

@detiber will PR the doc + refs to this repo and we will start breaking down work items 

/assign @detiber

**Comment by detiber** [comment]
Closing since #26 has merged.
