### ISSUE TITLE
Find alternative to adding a prefix to the namespace resource in Kustomize

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#300]
/kind bug
Part of #276

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Running `kustomize` as part of `make manifests`

```
2018/10/23 15:45:24 Adding nameprefix to Namespace resource will be deprecated in next release.
echo "---" >> cmd/clusterctl/examples/aws/out/provider-components.yaml
```

A solution to having to apply the name prefix to the namespace resource should be found.

**What did you expect to happen:**
N/A

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
/close

This isn't longer necessary in Kustomize 2
