### ISSUE TITLE
AWSMachine controller tries to update some immutable fields

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3000]
/kind bug

**What steps did you take and what happened:**
During creation of a cluster, seeing a couple of updates coming to `AWSMachine` that is denied by the webhook. Can be observed in e2e tests too: [example](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1466421813729824768/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-7bd56cd58-v5bh9/manager.log). This issue is harmless, clusters are coming up successfully.

```
E1202 15:18:42.006500       1 controller.go:317] controller/awsmachine "msg"="Reconciler error" "error"="admission webhook \"validation.awsmachine.infrastructure.cluster.x-k8s.io\" denied the request: AWSMachine.infrastructure.cluster.x-k8s.io \"cluster-xkmw1x-md-h7kdf\" is invalid: spec: Forbidden: cannot be modified" "name"="cluster-xkmw1x-md-h7kdf" "namespace"="functional-gpu-cluster-guzgx3" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSMachine"
```

/triage accepted
/priority important-soon
/milestone v1.2.0

**What did you expect to happen:**
We should not update immutable fields.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by pydctw** [comment]
For the e2e test, there is a difference in rootVolume spec and the update is rejected as it is an immutable field.

oldAWSMachineSpec
```
  "rootVolume": {
    "size": 100,
    "type": "gp2"
  },
```

newAWSMachineSpec
```
  "rootVolume": {
    "deviceName": "/dev/sda1",
    "size": 100,
    "type": "gp2"
  },
```

Do we know where this update in rootVolume's deviceName can come from? Reading the code, the `rootVolume.deviceName` should be empty during creation and looks like sth is trying to update it after instance creation.

**Comment by pydctw** [comment]
This issue was observed fist in gpu e2e test because it is the only test using a template with rootVolume field but the same issue happens whenever AWSMachine spec has rootVolume field defined. Verified it by modifying templates for other e2e test.
