### ISSUE TITLE
Clarify git process (squash vs. history) for contributors

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#302]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
A number of PRs have had the "please squash commits" prior to merge.

There are differing opinions on whether that is a good thing or not, but it
should be clarified in CONTRIBUTING.md

**What did you expect to happen:**
CONTRIBUTING.md explains project preferences for squashing commits or not.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
I wanna add that so far, we've been squashing commits before merging as general rule of thumb, but open to different opinions/suggestions.

**Comment by vincepri** [comment]
Seems like, as pointed by @detiber, that PRs are automatically squashed upon merge https://github.com/kubernetes/test-infra/blob/2005cfe3b3f0148cfcfbb7272a9dee64e4a87211/prow/config.yaml#L418. I'll go ahead and close this for now, feel free to reopen if necessary.

/close

**Comment by randomvariable** [comment]
Ah, fair enough.
