### ISSUE TITLE
Sort out GCR repository for pre-CNCF owned releases

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#303]
/kind bug
/priority critical-urgent

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
CRD migration changed the GCR repo that images are pushed to along the lines of GCP,
but the repository does not exist.

We will not have proper GCR repositories which are owned by the CNCF within the 1.13 release cycle, so will need a temporary home for the images.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
There is now a gcr.io repo created using the currently referenced name in the Makefile. It is currently a Heptio owned repository, but we are happy to transfer to CNCF ownership once that is a possibility.
