### ISSUE TITLE
Panic in the conversion tests

### ISSUE THREAD

**Issue by jonathanbeber** [kubernetes-sigs/cluster-api-provider-aws#3032]
The conversion tests in [v1alpha4](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/bootstrap/eks/api/v1alpha4/conversion_test.go) and [v1alpha3](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/bootstrap/eks/api/v1alpha3) result in panics. The panic is being hidden by the tear down strategy in 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/84466f909f9e7eb0991dfcaf34499e04a4befdc7/bootstrap/eks/api/v1alpha3/webhook_suite_test.go#L38-L44

I discovered it while trying to copy the test strategy to #3009.

When the teardown strategy is ignored (i.e. comment the `TestMain` func) the panic occurs like can be seem in this [CI run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3009/pull-cluster-api-provider-aws-test/1470836438860828672).

**Comment by sedefsavas** [comment]
/triage accepted
/priority important-soon
/milestone v1.3.0

Thanks for debugging and finding this out. 

cc @richardcase this is why we were not catching last weeks conversion issues.

**Comment by sedefsavas** [comment]
Changing the priority as without this, our conversion test failures are not showing up in unit tests.

/priority critical-urgent

**Comment by pydctw** [comment]
The issue is fixed as part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3033
