### ISSUE TITLE
Refactor actuators around a context

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#305]
/kind feature

**Describe the solution you'd like**
In the current state of things, the machine and cluster actuator are structured in a way which effectively operates around either a cluster, a machine, or both. Longer term, we should think about refactoring the actuators so they instantiate throw-away objects from a context. During this refactor, a lot of business logic currently present under services/ec2 could potentially move up one level, keeping a clear separation between the ec2 layer and the actuator operations.

CC @detiber @ashish-amarnath @chuckha @randomvariable

**Comment by randomvariable** [comment]
Do you mean literally a context.Context, or something more typed? Worry with the former is losing some compile time checks. On the other hand, for decent structured logging, particularly when we consider multi-cluster, many-node, it'd be good to pass a context at least for logging.

I generally agree with separating the actual service calls and actuator operations in a refactor now that we've got to a working state.

**Comment by vincepri** [comment]
I was suggesting of something more typed, I don't think "context.Context" is useful in this context 😛
