### ISSUE TITLE
Unable to use API machinery conversion APIs for AWSMachineProviderStatus and AWSClusterProviderStatus

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api-provider-aws#306]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It should be possible to use api-machinery APIs to convert the status to RawExtentions
https://godoc.org/k8s.io/apimachinery/pkg/runtime#Convert_runtime_Object_To_runtime_RawExtension

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Using this API, fails to compile like:
```
cannot use status (type *AWSMachineProviderStatus) as type *runtime.Object in argument to runtime.Convert_runtime_Object_To_runtime_RawExtension
```
and
```
cannot use status (type *AWSClusterProviderStatus) as type *runtime.Object in argument to runtime.Convert_runtime_Object_To_runtime_RawExtension
```

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by timothysc** [comment]
Closing, this no longer applies.
