### ISSUE TITLE
AMIs with some versions (e.g., vx.x.0) not showing up on the AMI list 

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3061]
We have a lambda function that updates automatically the list of AMIs we list in the [docs](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis.html).

AMIs with Kubernetes v1.23.0 is released but not showing up on that list. We were not publishing AMIs with .0 patch releases before so probably the logic is not supporting it currently. This must be a very minor fix.

/assign @Ankitasw 

/kind documentation
/triage accepted
/priority backlog
/milestone Backlog

**Comment by Ankitasw** [comment]
@sedefsavas do we need to directly update the document or change the logic for AMI with x.x.0 release?
