### ISSUE TITLE
imageLookupFormat should support Kubernetes versions with build metadata, e.g. +fips

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-aws#3076]
/kind feature

**Describe the solution you'd like**

I'm trying to use `imageLookupFormat: my-ami-{{.BaseOS}}-fips-release-?{{.K8sVersion}}-*` with a custom AMIs and a Kubernetes version that has some build metadata `v1.21.8+fips.0`.
AWS AMIs do not support `+` in the name, and when we build our AMIs using Packer we use [clean_resource_name](https://www.packer.io/docs/templates/legacy_json_templates/engine#clean_resource_name) to format the name, which replaces unsupported characters with a `-`.

So the AMI name ends up being something like `my-ami-rhel-8.2-1.21.8-fips.0-1641416145` but the AMI that is being searched for is `my-ami-rhel-8.2-?1.21.8+fips.0-*` (note the `+` vs `-`)

The code that is handling [this is here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1a61dfc39649749b8b8dfad8334909a388d675a7/pkg/cloud/services/ec2/ami.go#L73-L77), but its only handling an optional `v` prefix and no other changes.

**Anything else you would like to add:**

Originally asked in Slack https://kubernetes.slack.com/archives/CD6U2V71N/p1641571157011400 and discussed 01/10/2022 CAPA meeting.

**Environment:**

- Cluster-api-provider-aws version: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.7.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
There is a change in the AMI name, search logic specifically needs to handle `+` to `-` conversion. 
 With a generic logic, not sure if this specific case can be solved. 

[Runtime-extensions proposal ](https://github.com/kubernetes-sigs/cluster-api/issues/5175)in cluster-api might be useful to solve this issue: an extension can generate a replaced regex and then that regex is used in CAPA AMI search.

**Comment by dlipovetsky** [comment]
For reference:
> Constraints: 3-128 alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_)
> -- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateImage.html
