### ISSUE TITLE
Conversion is not completely implemented for all API types

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-aws#3085]
/kind bug

Hey folks,
in core CAPI we have a tool called conversion-verifier which loops over all types and ensures the controller-runtime conversion interfaces are implemented correctly, i.e. it checks the types have the Hub / ConvertTo / ConvertFrom functions.

The results for CAPA are:
* type "infrastructure.cluster.x-k8s.io/AWSClusterTemplateList" in package "sigs.k8s.io/cluster-api-provider-aws/api/v1beta1" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/AWSClusterTemplateList" in package "sigs.k8s.io/cluster-api-provider-aws/api/v1alpha4" it's not convertible, missing ConvertFrom() and ConvertTo() methods

I think it would be great to:
* implement the missing methods
* integrate the conversion-verifier in CI

The conversion-verifier can be found here:
* Code: https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier
* Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

I can provide additional details if needed / if you want to implement this issue.

**Environment:**

- Cluster-api-provider-aws version: latest
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): -

**Comment by sedefsavas** [comment]
Thanks for the detailed explanation @sbueringer 

This is not critical as ClusterClass support is in v1beta1, but we need to fix it anyway.

/triage accepted
/priority important-soon
/milestone v1.3.0

**Comment by richardcase** [comment]
As discussed in the office hours i think you need to do this as well for AWSClusterTemplateList conversion:

* Create a new file `api/v1alpha4/awsclustertemplate_conversion.go` that contains something like this:

```go
func (r *AWSClusterTemplateList) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*infrav1.AWSClusterTemplateList)

	return autoConvert_v1beta1_AWSClusterTemplateList_To_v1alpha4_AWSClusterTemplateList(src, r, nil)

	return nil
}

func (r *AWSClusterTemplateList) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*infrav1.AWSClusterTemplateList)

	return autoConvert_v1alpha4_AWSClusterTemplateList_To_v1beta1_AWSClusterTemplateList(r, dst, nil)
}
```

Also make sure that the `/api/v1beta1/conversion.go` has the `Hub` function for `AWSClusterTemplateList`. 

You should then be able to run `make generate-go-apis` and then your new verify make target.
