### ISSUE TITLE
Use controller-runtime setup-envtest instead of fetch_ext_bins.sh

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-aws#3086]
/kind feature

Hey folks,

just wanted to make you aware of that there is a tool by controller-runtime which can be used to setup the controller-runtime envtest binaries (https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest).

It's already used in core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L437-L441

I think this could be a good first issue, if you want to adopt setup-envtest.

**Environment:**

- Cluster-api-provider-aws version: latest
- Kubernetes version: (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): -

**Comment by sedefsavas** [comment]
@Skarlso is there any update on this issue?

**Comment by Skarlso** [comment]
Uh so sorry got bogged down with fever and life. I'm gonna do this this week or weekend. 😔😊 Thanks for the ping!

**Comment by Skarlso** [comment]
yay, got covid, so was out with high fever for most of the week. :/

But hopefully I can pick this up today. :)

**Comment by sedefsavas** [comment]
Hope you are better. This is not urgent at all, take care.

**Comment by Skarlso** [comment]
Thanks, yeah it's better today. :)

**Comment by Skarlso** [comment]
@sbueringer Hi!

Are you sure that this is the right link? https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L437-L441

This is linking to a docker build make target... I think you meant to use 84-86 maybe? https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L81-L84

Or did this change since? I guess the Makefile was updated or stuff was moved, right?

**Comment by Skarlso** [comment]
ah you probably meant this part:

```Makefile
.PHONY: test
test: $(SETUP_ENVTEST) ## Run unit and integration tests
	KUBEBUILDER_ASSETS="$(KUBEBUILDER_ASSETS)" go test ./... $(TEST_ARGS)
```

**Comment by Skarlso** [comment]
Ah, yeah okay, I know what to do know. :)

**Comment by sbueringer** [comment]
@Skarlso Exactly. I should have used a link based on a commit :). Our Makefile changed quite a bit recently.

**Comment by Skarlso** [comment]
No worries. :) I found it in the end. :) Now I'm comparing if we do anything extra in `fetch_ext_bins.sh` or if this can just be a drop-in replacement. And I'm wondering where, or if, the cleanup should be called.

**Comment by sbueringer** [comment]
Looks like in CAPI we're not calling it at all. I guess so we "cache" between test runs

**Comment by Skarlso** [comment]
There were some interesting things here. Some deprecation, some function wasn't called at all too. ¯\\\_(ツ)\_/¯.

I hope my changes will work. :D I also had to add a `-count 1` so I force a re-run without using the cache. I thought everything is working until I realised that it's not running anything hahahaha.
