### ISSUE TITLE
Specifying KMS encryption results in envelope encryption being set, but controller is trying to back it out

### ISSUE THREAD

**Issue by rayterrill** [kubernetes-sigs/cluster-api-provider-aws#3092]
/kind bug

**What steps did you take and what happened:**
Built a new cluster with CAPA using KMS envelope encryption. Encryption was successfully enabled (checked via the aws console), but the controller is attempting to back that out per the console logs:
```
E0121 19:23:55.475711       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane default/rterrill-test-1: failed reconciling eks encryption config: failed to update the EKS control plane: disabling EKS encryption is not allowed after it has been enabled" "name"="rterrill-test-1" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane"
```

KMS config setting:
```
  encryptionConfig:
    provider: "arn:aws:kms:us-west-2:REDACTED:key/REDACTED"
    resources:
    - "secrets"
```
**What did you expect to happen:**
KMS encryption should be enabled and the controller should show success.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: cluster-api-aws-controller:v1.2.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
I will investigate this so:

/assign

**Comment by richardcase** [comment]
@rayterrill - with the key you are using do you have an alias for it that starts with [cluster-api-provider-aws-](https://cluster-api-aws.sigs.k8s.io/topics/eks/encryption.html) ?

**Comment by richardcase** [comment]
Great, i've managed to recreate the issue.
