### ISSUE TITLE
Include searchable severity level in log lines

### ISSUE THREAD

**Issue by lackhoa** [kubernetes-sigs/cluster-api-provider-aws#3101]
/kind feature

**Describe the solution you'd like**
Currently logs produced by the capa controller does not include an obvious "grep"-able severity level, which makes it hard to search for errors or warnings, for example
```
I0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"  
```

I suggest including a severity level in the log lines, such as this...
```
INFO I0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"  
```
... or this
```
INFO-0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"  
```

The above are just some ideas; the exact format can be something else.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v1.2

**Comment by Skarlso** [comment]
@lackhoa The log in the controller begins with a character that represents the log level.
`I -> INFO`
`D -> DEBUG`
`E -> ERROR`

grep for info:

```log
cat logs.txt|grep "^I"
I0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"
I0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"
I0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"
```

grep for errors:

```log
cat logs.txt|grep "^E"
E0122 00:41:32.797919       1 awsmachine_controller.go:461]  "msg"="Reconciling AWSMachine"
```

It think this works pretty well.

**Comment by lackhoa** [comment]
@Skarlso Nice idea but unfortunately if you use stern, the log isn't at the beginning anymore.
```
capa-controller-manager-6d956f866c-9qdj8 manager I0131 06:09:25.818603       1 identity_provider.go:32]  "msg"="reconciling oidc identity provider"  
```

**Comment by Skarlso** [comment]
The "problem" here is that we are using `logr` which is used by k8s. They have a different opinion on log levels based on numbers, which do make sense. Also, if I recall, stern is a defunct project, right? :) 

Further, it is still pretty much grep-able since `manager` is a constant ( the name of the container ). So you can grep `manager [I|E]`.

I'll look into providing a header, but the header then won't match the log level, right? Logr is configured through numbers which represent chattyness. But at what point to switch to debug and what point to switch to trace or whatever? There is really no correlation other than an arbitrary one.

**Comment by lackhoa** [comment]
@Skarlso I didn't know stern was a defunct project, but my point wasn't about stern. It was about how grepping based on line opening can fail when you integrate with other things.
> Further, it is still pretty much grep-able since manager is a constant
I guess everything is greppable if you put enough effort into it. I could also use awk to parse the log lines and then grep. But the point is that it should be easy, right?
I'd like to add another point is that `I0122` is kind of confusing to beginners. I for example have no idea what that means.

**Comment by Skarlso** [comment]
@lackhoa I get your point, and it's a valid one. We'll figure something out in the next community meeting as this affects the whole project ( so we are consistent over other controllers as well.

Maybe something like `level=INFO` in amongst the values of the logger. The header is sadly not changeable as it's set based on severity. You can disable it, but that's about it. :))

**Comment by sedefsavas** [comment]
Copying comment from #3152

> We should also consider adding JSON support during this refactoring, which is being discussed in CAPI:
> https://github.com/kubernetes-sigs/cluster-api/issues/5571#issuecomment-1034000389
>
