### ISSUE TITLE
AWSCluster additional tags accepts empty key tags

### ISSUE THREAD

**Issue by jonathanbeber** [kubernetes-sigs/cluster-api-provider-aws#3102]
/kind bug

**What steps did you take and what happened:**
Create an `AWSCluster` resource with an additional tag where the key is empty (don't ask me why I did this):

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSCluster
metadata:
  name: emptytag
  namespace: default
spec:
  additionalTags:
    owner: jbeber
    expiration: 1d
    "": ""
...
```

This leaves the capa controller failing to apply resources:

```log
E0124 1 awscluster_controller.go:209] controller/awscluster "msg"="failed to reconcile network" "error"="failed to create new vpc: failed to create vpc: InvalidParameter: Tag key must have a value\n\tstatus code: 400, request id: X" "cluster"="emptytag" "name"="emptytag" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" 
```

**What did you expect to happen:**

[AWS docs](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html) says that:

> The tag key must be a minimum of 1 and a maximum of 128 Unicode characters in UTF-8.

So I'd expect the CRD to not even support this case. i.e.: `// +kubebuilder:validation:MinLength:=1` and `// +kubebuilder:validation:MaxLength:=128` in  https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e07d4fdd5dd88319c370da692719d2c21960ec27/api/v1alpha4/tags.go#L29

**Anything else you would like to add:**
The cluster is also stuck to be deleted, since its API is never added.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jonathanbeber** [comment]
I'd like to work on that if possible!

**Comment by jonathanbeber** [comment]
From what I see there's no easy way to validate a key in a `map[]` with kubebuilder, because it just becomes an object to OpenAPI and is never validated. I tried something like:

```go
// Tags defines a map of tags.
type Tags map[TagKey]TagValue

// TagKey is the key of a tag for AWS resources.
// +kubebuilder:validation:MinLength:=1
// +kubebuilder:validation:MaxLength:=128
type TagKey string

// TagValue is the value of a tag for AWS resources.
// +kubebuilder:validation:MaxLength:=256
type TagValue string
```

but that results in changes just for the keys:

```diff
diff --git config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
index 21760175..eda8c392 100644
--- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
+++ config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
@@ -1075,6 +1075,8 @@ spec:
             properties:
               additionalTags:
                 additionalProperties:
+                  description: TagValue is the value of a tag for AWS resources.
+                  maxLength: 256
                   type: string
                 description: AdditionalTags is an optional set of tags to add to AWS
                   resources managed by the AWS provider, in addition to the ones added
```
and no change at all for the keys. 

From what I understood another option would be to change the type of `AdditionalTags` from `map[string]string` to a struct, such that we could have something like:

```go
// Tags defines a map of tags.
type Tags []Tag

// Tag is a tag for AWS resources.

type Tag struct {
  // +kubebuilder:validation:MinLength:=1
  // +kubebuilder:validation:MaxLength:=128
  Key string `json:"key"`
  // +kubebuilder:validation:MaxLength:=256
  Value string `json:"value"`
}
```

but that would change drastically the way we define them in the `AWSCluster` resource spec to terrible UI in my opinion:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSCluster
spec:
  additionalTags:
  - key: owner
    value: jbeber
  - key: foo
    value: bar
```

although it's closer to what we have in AWS cloudformation and CLI. 

Another option would be just to leave the CRD as it's and simple ignore such tags in the controller. We could log a warn message but do not fail the cluster creation.

**Comment by jonathanbeber** [comment]
I was pointed to [this part](https://github.com/kubernetes/community/blob/f8148d406c36cf46783f62a38bae40352b760d34/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) of the API conventions that suggests the use of a list of named subobjects instead of maps. Although the convention itself presents an exception to "pure maps"

> The only exceptions are pure maps in the API (currently, labels, selectors, annotations, data), as opposed to sets of subobjects.

**Comment by sedefsavas** [comment]
I think we can do validation similar to conditions in api machinery:  https://github.com/kubernetes/apimachinery/blob/7149480564b7d40046f19040efa20171b49059ae/pkg/apis/meta/v1/validation/validation.go#L213

Or more similar to tags, we can checkout how metadata.labels and annotations throw error.
Because when I try to update labels I see these errors which we would want: 
```
# * metadata.labels: Invalid value: "": name part must be non-empty
# * metadata.labels: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')

```

**Comment by sedefsavas** [comment]
> I was pointed to [this part](https://github.com/kubernetes/community/blob/f8148d406c36cf46783f62a38bae40352b760d34/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) of the API conventions that suggests the use of a list of named subobjects instead of maps. Although the convention itself presents an exception to "pure maps"
List of objects are suitable to use for tags but we need to wait for a major release to do this change as we may break workflows.
In the meantime, we could implement a workaround. WDYT?

**Comment by sbueringer** [comment]
I think using a string=>string map should be fine. Sounds to me like it's a very similar use case to annotations/labels.

I also think implementing the validation in the webhook instead of via OpenAPI schema is absolutely okay.

**Comment by jonathanbeber** [comment]
@sedefsavas I guess we can close this one? WDYT? 

As @sbueringer mentioned and we discussed in [slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1644347460545489) doesn't seem like CAPA/CAPI without webhooks is a reality, and I prefer the `map[string]string` better instead of a list of named subobjects for that, due to the similarity with annotations/labels.

I'd be happy to be in the next biweekly meeting to discuss it better if you think it's necessary.

**Comment by sedefsavas** [comment]
Yes, let's close this.
No need to make any API changes as AWS tags only have key-value fields, no benefit of making it a list as you solved the validation in webhook and it is merged.
