### ISSUE TITLE
unknown field "emeritus_maintainers" in the OWNERS file

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api-provider-aws#3104]
there is a [new tool](https://github.com/dims/maintainers) for parsing the kubernetes/community/sigs.yaml file and it reports an error in the OWNERS file in this repository:
> ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-aws/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"

**solution**

1) move the entries under `emeritus_maintainers` https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/OWNERS#L19-L24 to `emeritus_approvers`.

2) remove the `emeritus_maintainers` key.

**Comment by neolit123** [comment]
/kind bug
/good-first-issue
/help
(see instructions in the OP)

**Comment by Skarlso** [comment]
@neolit123 Hi. :)

How likely is this change going to break existing tooling which isn't updated yet to use this new tooling?

I wonder if there is a way of rather ignoring certain fields or having both in the file until such a time comes when only the new tooling is used?

**Comment by Skarlso** [comment]
Would have been helpful to include that it's the `export` command that fails... :)

**Comment by Skarlso** [comment]
I feel like this tool is too new to be taken seriously. It has zero tests, no validations, no guidelines, PR checks, releases or relevant information. How come this was picked up or why is it not under the kube-sigs project structure.

**Comment by Skarlso** [comment]
Sorry, I didn't mean to sound so pendantic. Just please help me understand the adoption process of a new tool in this ecosystem. 😊

**Comment by richardcase** [comment]
@Skarlso - when you make this change could you move the existing `emeritus_approvers` into the `emeritus_reviewers` list? And then change `emeritus_maintainers` to `emeritus_approvers`?

**Comment by Skarlso** [comment]
Yes, and thank you for the background and clarifications! :)

**Comment by neolit123** [comment]
It can take some time before a tool like that becomes stable. I think what
matters in this case is that there is no such field (_maintainers) defined
in the YAML spec of the bot that reads the owners files.

**Comment by Skarlso** [comment]
`emeritus_reviewers` -> is also an unknown field

**Comment by neolit123** [comment]
Related issue https://github.com/kubernetes/community/issues/6334

**Comment by Skarlso** [comment]
@neolit123 Oh thank you! So. Umm... what do we change `emeritus_reviewers` into?

**Comment by Skarlso** [comment]
Oh I see the attached doc to the issue. I'll read that and try to come with something with Richard.

**Comment by neolit123** [comment]
There is only an _approvers field. Leaving the decisions to the current
maintainers.

**Comment by richardcase** [comment]
@Skarlso - what do you think to this then:

- Remove `emeritus_approvers`
- Rename `emeritus_maintainers` to `emeritus_approvers`

I think we should still acknowledge emeritus reviewers/approvers in general. So how about we add a section in the README.md that under the `Our contributors` (before the image of all the contributors) where we add something like  `Thank you to all our contributores and a special thank you to our emetritus maintainer: XXXXX and emeritus reviewers?`

**Comment by Skarlso** [comment]
@richardcase Yep, sounds good to me.
