### ISSUE TITLE
AWSMachine and AWSMachineTemplate.Spec creation validation should be consistent

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3109]
/kind cleanup

Creation validation of MachineSpec should be consistent everywhere.
There is a bug https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3105 for example in AWSMachine validation which is fixed in AWSMachineTemplate:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2969152895a268fdaf022156e3b14777d9bcfd8f/api/v1beta1/awsmachine_webhook.go#L172
vs
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2969152895a268fdaf022156e3b14777d9bcfd8f/api/v1beta1/awsmachinetemplate_webhook.go#L75

`AWSMachineTemplate` is immutable so it should have its own validation webhook logic for update.
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by bisakhmondal** [comment]
Hi @sedefsavas, could you please share some details and context about what needs to be done? Thank you

**Comment by cnmcavoy** [comment]
I took a stab at this as part of #3728 but this part puzzles me:
> AWSMachineTemplate is immutable so it should have its own validation webhook logic for update.

Why does an immutable resource need onUpdate logic? The current logic https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/awsmachine_webhook.go#L116 enforces the immutability. Is this immutability incorrect? I'm a bit confused at what work remains.

**Comment by Ankitasw** [comment]
> Why does an immutable resource need onUpdate logic? 

To ensure immutability, we need webhook checks during update.

> The current logic https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/awsmachine_webhook.go#L116 enforces the immutability. Is this immutability incorrect? I'm a bit confused at what work remains.

AWSMachine and AWSMachineTemplate are two separate entities. The above mentioned check enforces immutability on AWSMachine, not on AWSMachineTemplate.
Hence, we require to check if both AWSMachine and AWSMachineTemplate checks are done similarly, in their respective create and update webhooks. That's the remaining part of work.

**Comment by cnmcavoy** [comment]
@Ankitasw thanks for clearing up my misunderstanding, I thought the scope was only the on update handler, but if I understand correctly now, both of the on update and on create handlers should be consistent, and presently they are not.
