### ISSUE TITLE
Support looking up EKS optimized image for ARM

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3121]
/kind bug

**What steps did you take and what happened:**
When creating an EKS based cluster if we don't specify any of the image properties we [look up the default EKS optimized  AMIs using SSM]. 

We only support looking up the base AL2 [EKS ami](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/pkg/cloud/services/ec2/ami.go#L59) and the [GPU optimized AMI](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/pkg/cloud/services/ec2/ami.go#L62).

To support looking up EKS optimized images for ARM we need to use the following format when querying SSM:

`/aws/service/eks/optimized-ami/%s/amazon-linux-2-arm64/recommended/image_id`

This will require that we know we are using ARM based instances when looking up the images.

**What did you expect to happen:**

I would expect to be able to use EKS optimized ARM images without having to explicitly specify the image to look up.
 
**Anything else you would like to add:**
Created as a result of a [discussion](https://kubernetes.slack.com/archives/CD6U2V71N/p1643608696167349) on the community slack.

**Environment:**

- Cluster-api-provider-aws version: 1.2.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by khoavo-hatch** [comment]
@richardcase Can you assign this to me? I will push a PR soon.

**Comment by khoavo-hatch** [comment]
/remove-lifecycle stale
#3208 is ready for review

**Comment by charlie-haley** [comment]
Hey 👋, I noticed that the original PR for this went stale, and we're currently needing this feature. So, I decided to open a PR and rebase the changes from the original PR, I'm happy to pick up this issue going forward!
