### ISSUE TITLE
Add conversion-verifier to CI

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3127]
Populating this issue from https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3085 to track conversion-verifier addition separately.

```
Integrate the conversion-verifier in CI.

The conversion-verifier can be found here:

Code: https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier
Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

```

/good-first-issue
/priority backlog

**Comment by RishiKumarRay** [comment]
Can you give Me any reference where i can read about this, i want to go for this issue

**Comment by sedefsavas** [comment]
Hi @RishiKumarRay 

We want to add this conversion verifier to our `verify` target in Makefile very similar to how it is implemented in core cluster-api Makefile:

> Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

@sbueringer what is the best way to use the conversion verifier code without copying?
 https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier

**Comment by sbueringer** [comment]
Every provider seems to do this slightly differently but for CAPA it should be ca.:
* Add `CONVERSION_VERIFIER` here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4274a5ab5c9dc391045840d6e45e17fe0cbab3dc/Makefile#L48
* Add `CONVERSION_VERIFIER` here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/cb0a385b53fd75327956834bed126edc67a7daa7/hack/tools/Makefile#L75-L77
    * ~ like this: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/hack/tools/Makefile#L88
* hack/tools/go.mod already contains `sigs.k8s.io/cluster-api/hack/tools` so that should be fine
* Add `verify-conversions` target like this: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L340-L342
* Make sure `verify` also runs `verify-conversions` (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4274a5ab5c9dc391045840d6e45e17fe0cbab3dc/Makefile#L589)

**Comment by zeborg** [comment]
Hi @sbueringer! I think I've got the idea here, and would like to make a PR for this issue soon if it's not assigned to anybody yet. Thanks!

**Comment by sedefsavas** [comment]
@RishiKumarRay, would you like to work on this issue? If so, I will assign it to you.

@zeborg, let's wait for the answer as they've already shown interest.

**Comment by RishiKumarRay** [comment]
@sbueringer thankyou for mentioning , please assign @zeborg since he has the idea and i haven't figured out this as i was busy with something else.

**Comment by sedefsavas** [comment]
Thanks for responding @RishiKumarRay.

@zeborg Feel free to assign yourself.

**Comment by zeborg** [comment]
Hey @sedefsavas, I've made some changes locally but I would like to know the appropriate way in which I could test them. Can you please tell me how I can verify if the changes would work properly once implemented in the repo?

I tried to run `make verify` on my local system, but it seems to throw the following error:
```logtalk
❯ make verify
rm ./hack/tools/bin/*.sh
rm: ./hack/tools/bin/*.sh: No such file or directory
make: [verify-boilerplate] Error 1 (ignored)
./hack/verify-boilerplate.sh

KUBE_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
dirname "${BASH_SOURCE[0]}"

boilerDir="${KUBE_ROOT}/hack/boilerplate"
boiler="${boilerDir}/boilerplate.py"

files_need_boilerplate=()
while IFS=$'\n' read -r line; do
  files_need_boilerplate+=( "$line" )
done < <("${boiler}" "$@")
"${boiler}" "$@"

# Run boilerplate check
if [[ ${#files_need_boilerplate[@]} -gt 0 ]]; then
  for file in "${files_need_boilerplate[@]}"; do
    echo "Boilerplate header is wrong for: ${file}" >&2
  done

  exit 1
fi
Boilerplate header is wrong for: /Users/abhinav/git-forks/capa/cmd/clusterawsadm/ami/helper_test.go
make: *** [verify-boilerplate] Error 1
```
which makes me think that either there must be some steps prior to executing this command that I'm missing out, or that it's only supposed to be executed in the pipeline.

Any help would be really appreciated, thanks!
