### ISSUE TITLE
e2e unmanaged suite failing because of ECR creation/lookup

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-aws#3132]
/kind bug

**What steps did you take and what happened:**
Test failed running `make test-e2e` when trying to recreate a "capa/up" ECR but then looking for "capa/update"

**What did you expect to happen:**
`make test-e2e` runs successfully if the ECR has previously been created.

**Anything else you would like to add:**
The tests seem fine when specifying the same ECR name. Perhaps I'm not getting ErrCodeRepositoryAlreadyExistsException back after trying to create an ECR with the same name as the existing name?

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 1.23.3
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.3

**Comment by sedefsavas** [comment]
Interesting, this should fail in the Prow if the error we are checking was wrong.
Regardless, the repo names should match.

As a side note, we still have work to do to clean up created ecr public repos in Boskos (see [issue](https://github.com/kubernetes-sigs/boskos/issues/110))
