### ISSUE TITLE
[UX] Clusterctl requires many params

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#314]
/kind feature

**Describe the solution you'd like**
This issue came up during a demo of cluster api in Kubernetes Meeting. Clusterctl requires a minimum of 3 files / parameters to function and it was suggested to maybe use a configuration file for it.

**Comment by randomvariable** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/716 went someway to removing the need for separate `--cluster` and `--machine` parameters. These could be consolidated into a single `--cluster` flag given that we would expect machine-only deployments to be done via `kubectl`

**Comment by chuckha** [comment]
/close

clusterctl is getting reworked
