### ISSUE TITLE
Add branch variable in v0.7 release makefile 

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#3148]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
During release we hardcoded `branch=main` in makefile, needs to update the makefile to get current branch name

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Merged.
