### ISSUE TITLE
Failing to build release-notes binary

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3153]
Looks like a version incompatibility issue.

```
➜  cluster-api-provider-aws git:(main) make release         
make -C hack/tools bin/release-notes
mkdir -p bin
go build -tags tools -o bin/release-notes k8s.io/release/cmd/release-notes
go: downloading cloud.google.com/go v0.99.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.12
go: downloading github.com/BurntSushi/toml v1.0.0
go: downloading golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
go: downloading golang.org/x/tools v0.1.9-0.20211228192929-ee1ca4ffc4da
go: downloading golang.org/x/crypto v0.0.0-20220112180741-5e0467b6c7ce
go: downloading golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2
go: downloading google.golang.org/api v0.63.0
go: downloading google.golang.org/grpc v1.43.0
# cloud.google.com/go/storage
/Users/ssavas/go/pkg/mod/cloud.google.com/go/storage@v1.16.1/storage.go:1416:53: o.GetCustomerEncryption().GetKeySha256 undefined (type *"google.golang.org/genproto/googleapis/storage/v2".Object_CustomerEncryption has no field or method GetKeySha256)
make[1]: *** [bin/release-notes] Error 2
make: *** [hack/tools/bin/release-notes] Error 2
```

/kind bug

**Comment by richardcase** [comment]
I've been wondering for a while if we should change to use the GH release notes generation instead.

**Comment by sedefsavas** [comment]
> I've been wondering for a while if we should change to use the GH release notes generation instead.

I am using GH release to double check we are not missing any changes. 
Only thing is it is missing categorization, we need to go over each of them to decide bug/cleanup etc. 
We can possibly do something similar to what [cluster-api has ](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/release)using GH release notes.

**Comment by richardcase** [comment]
> > I've been wondering for a while if we should change to use the GH release notes generation instead.
> 
> I am using GH release to double check we are not missing any changes. Only thing is it is missing categorization, we need to go over each of them to decide bug/cleanup etc. We can possibly do something similar to what [cluster-api has ](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/release)using GH release notes.

I have done this with a different project, we can probably get away without custom code. You can customize the GH release notes generation using a config file placed in `.github/release.yml`. [This](https://github.com/weaveworks/flintlock/blob/main/.github/release.yml) is an example. The configuration options can be found [here](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options).

I like with the GitHub release notes generation that it also highlights first time contributors. 

@sedefsavas - i will add it to the office hours call this evening.

@meghanajangi - if we change the focus of this to user the GitHub release notes generation is this still something you'd want to work on?

**Comment by meghanajangi** [comment]
> > > I've been wondering for a while if we should change to use the GH release notes generation instead.
> > 
> > 
> > I am using GH release to double check we are not missing any changes. Only thing is it is missing categorization, we need to go over each of them to decide bug/cleanup etc. We can possibly do something similar to what [cluster-api has ](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/release)using GH release notes.
> 
> I have done this with a different project, we can probably get away without custom code. You can customize the GH release notes generation using a config file placed in `.github/release.yml`. [This](https://github.com/weaveworks/flintlock/blob/main/.github/release.yml) is an example. The configuration options can be found [here](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options).
> 
> I like with the GitHub release notes generation that it also highlights first time contributors.
> 
> @sedefsavas - i will add it to the office hours call this evening.
> 
> @meghanajangi - if we change the focus of this to use the GitHub release notes generation is this still something you'd want to work on?
> 
> It would involve changing the makefile, adding release notes config file and updating document (and potentially something else).

Yes, I would like to work on it.

**Comment by richardcase** [comment]
Added #3170 with the details of implementing github release notes.

**Comment by sedefsavas** [comment]
Closing this issue as it will not be a problem once we move to GH release notes. #3170
