### ISSUE TITLE
Add apidiff to Makefile target

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3174]
There are a few Makefile targets that are used in other cluster api projects that will be great to add to CAPA. 

One of them is `apidiff` which diffs API changes on PRs.

Refer to [cluster-api](https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L309-L311)

**Comment by sedefsavas** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3169

**Comment by pydctw** [comment]
didn't see the other issue. Thanks!
