### ISSUE TITLE
Errors missed out due to wrong usage of error.Wrapf()

### ISSUE THREAD

**Issue by Madhur97** [kubernetes-sigs/cluster-api-provider-aws#3179]
/kind bug

**What steps did you take and what happened:**
While writing the tests for `pkg/cloud/services/natgateway` package, I encountered [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/natgateways.go#L290) line of code. Here the expectation was to return an error if `len(out.NatGateways)` is zero but actually it will return error as nil. This is because `error.Wrapf(err, args…)` returns nil if err is nil. 
Due to this bug, the method `WaitForWithRetryable()` will keep retrying and then `deleteNatGateway()` will timeout. 

On further investigation, I found similar instances in other places too.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/fargate.go#L107
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/nodegroup.go#L487

**What did you expect to happen:**
We should use wrap errors with error.Wrapf() only if error is non-nil.

**Comment by shivi28** [comment]
Thanks @Madhur97 for creating this issue.
This issue can be useful for new contributors, so IMO we can mark it as
/good-first-issue

**Comment by DiptoChakrabarty** [comment]
Hi I wanted to work on this just wondering if its okay to return a custom error (using something like fmt.Errorf) when err is nil (checked using if else in case of error)

/assign

**Comment by sedefsavas** [comment]
Hello @DiptoChakrabarty 
We can use this instead:
`errors.New("AWSClusterControllerIdentity is immutable")`

/triage accepted
