### ISSUE TITLE
Refactor the reconciler creation

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3181]
/kind feature
/priority backlog
/area testing
/triage accepted

**Describe the solution you'd like**
As part of reviewing #3073 there was a [suggestion](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3073#discussion_r801902690) that we change how we create instances of our reconcilers and how we inject mocked dependencies for testing purposes  so that we can remove utility functions like this:

```go
func (r *AWSClusterReconciler) getEC2Service(scope scope.EC2Scope) services.EC2MachineInterface {
	if r.ec2ServiceFactory != nil {
		return r.ec2ServiceFactory(scope)
	}
	return ec2.NewService(scope)
}
```

The suggestion was that we should handle this as part of creating an istnace if the reconcilers and the code inside them shouldn't be aware  / have any logic around creation of service clients. Something along the lines of this code (not tested / doesn't compile):

```go
type NewClusterReconcilerInput struct {
	Manager ctrl.Manager
	WatchFilterValue string
	Endpoints []scope.ServiceEndpoint
}

type NewClusterReconcilerServices struct {
	EC2ServiceFactory     func(scope.EC2Scope) services.EC2MachineInterface
	NetworkServiceFactory func(scope.ClusterScope) services.NetworkInterface
	ElbServiceFactory     func(scope.ELBScope) services.ELBInterface
	SecurityGroupFactory  func(scope.ClusterScope) services.SecurityGroupInterface
}

func NewClusterReconciler(input NewClusterReconcilerInput) reconcile.Reconciler {
	return &awsClusterReconciler{
		Client:           input.Manager.GetClient(),
		Recorder:         input.Manager.GetEventRecorderFor("awscluster-controller"),
		Endpoints:        input.Endpoints,
		WatchFilterValue: input.WatchFilterValue,

		ec2ServiceFactory: ec2.NewService,
		elbServiceFactory: elb.NewService,
		networkServiceFactory: network.NewService,
		securityGroupFactory: securitygroup.NewService,
	}
}

func NewClusterReconcilerWithServices(input NewClusterReconcilerInput, svcs NewClusterReconcilerServices ) reconcile.Reconciler {
	return &awsClusterReconciler{
		Client:           input.Manager.GetClient(),
		Recorder:         input.Manager.GetEventRecorderFor("awscluster-controller"),
		Endpoints:        input.Endpoints,
		WatchFilterValue: input.WatchFilterValue,

		ec2ServiceFactory: svcs.EC2ServiceFactory,
		elbServiceFactory: svcs.ElbServiceFactory,
		networkServiceFactory: svcs.NetworkServiceFactory,
		securityGroupFactory: svcs.SecurityGroupFactory,
	}
}

// awsClusterReconciler reconciles a AwsCluster object.
type awsClusterReconciler struct {
	client.Client
	Recorder         record.EventRecorder
	Endpoints        []scope.ServiceEndpoint
	WatchFilterValue string

	ec2ServiceFactory     func(scope.EC2Scope) services.EC2MachineInterface
	networkServiceFactory func(scope.ClusterScope) services.NetworkInterface
	elbServiceFactory     func(scope.ELBScope) services.ELBInterface
	securityGroupFactory  func(scope.ClusterScope) services.SecurityGroupInterface
}
```

Or using functional options:

```go
type ReconcilerOption func(*AWSReconciler)

type EC2ServiceFactory func(scope.EC2Scope) services.EC2MachineInterface

func WithEC2ServiceFactory(fn EC2ServiceFactory) ReconcilerOption {
	return func(r *AWSReconciler) {
		r.EC2ServiceFactory  = fn
	}
}


func NewClusterReconciler(input NewClusterReconcilerInput, opt ...ReconcilerOption) reconcile.Reconciler {
	clusterReconciler := &awsClusterReconciler{
		Client:           input.Manager.GetClient(),
		Recorder:         input.Manager.GetEventRecorderFor("awscluster-controller"),
		Endpoints:        input.Endpoints,
		WatchFilterValue: input.WatchFilterValue,

		EC2ServiceFactory: ec2.NewService,
		ELBServiceFactory: elb.NewService,
		NetworkServiceFactory: network.NewService,
		SecurityGroupFactory: securitygroup.NewService,
	}

	for _, opt := range opt {
		opt(clusterReconciler)
	}

	return clusterReconciler
}
```

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@sedefsavas then shall we wait for this change to merge before merging/starting integration tests for AWSCluster and AWSMachine controllers?

**Comment by richardcase** [comment]
> @sedefsavas then shall we wait for this change to merge before merging/starting integration tests for AWSCluster and AWSMachine controllers?

If this will help with the integration tests then yes it may be worth waiting. But if not I can always refractor them, no problem

**Comment by sedefsavas** [comment]
No need to wait, we can rebase IMO.

**Comment by Ankitasw** [comment]
> No need to wait, we can refactor IMO.

Yes, what I meant was we first need this refactoring and then rebase changes in integration tests and we need these tests as soon as possible.
If @richardcase doesn't have any efforts as of now, I am happy to do it.

**Comment by richardcase** [comment]
I didn't get much further due to time constraints so:

/unassign

**Comment by richardcase** [comment]
@Ankitasw - is this something you'd still be interested in working on?

**Comment by Ankitasw** [comment]
@richardcase I can do it, if you have not started

**Comment by richardcase** [comment]
I prefer the functional options route and thats what i had made a start on. But whichever you feel is best

**Comment by Ankitasw** [comment]
I think functional options is better if we want to add more services later, in that way the implementation would be flexible and wont require huge changes everytime we add new service.

**Comment by Ankitasw** [comment]
@richardcase I have some questions regarding this implementation:

- As mentioned in example, `NewClusterReconciler` should be used while controller creation in main.go. If that is the case, what opts we will be passing from there? If we pass opts like `WithEC2ServiceFactory`, we would need scope there, but we wont have scope created by then.

**Comment by Ankitasw** [comment]
Update:
I got some idea after thinking out loud, maybe  I will try it once and raise a WIP PR to get your feedback.

**Comment by richardcase** [comment]
> Update: I got some idea after thinking out loud, maybe I will try it once and raise a WIP PR to get feedback.

Great :) The sample code i gave was just a brain dump....i never actually tested it. So i'm keen to see the idea you had :smile:
