### ISSUE TITLE
Modifying makefile in CAPA

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#3188]
/kind feature

**Describe the solution you'd like**

In CAPI repository I have seen they have listed the `makefile` commands in different section to make it more readable.

<img width="1494" alt="Screenshot 2022-02-10 at 5 06 46 PM" src="https://user-images.githubusercontent.com/15645218/153401947-ab6311b3-1823-46f5-9c44-d5725174ff4d.png">

We can do something similar to this in CAPA `makefile`.

**Comment by Ankitasw** [comment]
@shivi28 Can this qualify for good-first-issue ?
