### ISSUE TITLE
Version info/LDFLAGS is missing in postsubmit image push job

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-aws#3193]
/kind bug

**What steps did you take and what happened:**
In the [post-cluster-api-provider-aws-push-images](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-aws-push-images/1491605296307507200) job, the LDFLAGS are missing in the [build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/post-cluster-api-provider-aws-push-images/1491605296307507200/artifacts/build.log). 

The LDFLAGS are computed from `./hack/version.sh`, and it fails because the workspace directory does not have a `.git` folder and we get this error as a result.

```
make upload-staging-artifacts
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make[1]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make ARCH=amd64 docker-build
make[2]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Then, when we are running `docker build`, we can see that the `ldflags` are set to an empty string here

```
docker build --build-arg ARCH=amd64 --build-arg LDFLAGS="" . -t gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller-amd64:v20220210-v1.2.0-168-gd4e16e42
```

**Anything else you would like to add:**
This same issue appears to show up in CAPI and the other Cluster API providers too. I'm working on a [PR in CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2068) to try to fix this, and I'd be happy to work together since the same fix could be applied to all the CAP* repos.

**Environment:**

- Cluster-api-provider-aws version: Any
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
We are tracking this https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2218

Feel free to close this if you think that covers this issue.

**Comment by Jont828** [comment]
Yep sounds good. I'll reply in that thread in that case.
