### ISSUE TITLE
Makefile assume dep is installed via go toolchain

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#320]
/kind bug

**What steps did you take and what happened:**
`make vendor REVENDOR=yes` fails because I installed dep with homebrew

**What did you expect to happen:**
I expect `make vendor REVENDOR=yes` not care where dep is installed

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
#290 replaces all of this with Bazel supplying `dep`. @phyber tested this works on MacOS
