### ISSUE TITLE
pull-cluster-api-provider-aws-test check is failing in PRs

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#3204]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I am raising PR, `pull-cluster-api-provider-aws-test` check is failing.
Getting following logs
<img width="1451" alt="Screenshot 2022-02-11 at 4 46 54 PM" src="https://user-images.githubusercontent.com/15645218/153582500-102fb3b8-9b5d-4f34-a824-95317dd324ff.png">

**What did you expect to happen:**
`\test pull-cluster-api-provider-aws-test` should pass in PR.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
I will take a look
/assign

**Comment by Ankitasw** [comment]
I tried reproducing locally, but couldn't get the issue, so I have raised a PR with some modifications which might help resolve the flake. I will run the tests multiple times in PR to check if we still face the issue.

**Comment by sedefsavas** [comment]
Let's revert the PR that caused this issue to unblock other PRs.
