### ISSUE TITLE
Consider if to add --metrics-bind-addr=127.0.0.1:8080 in manager.yaml

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-aws#3225]
While working on https://github.com/kubernetes-sigs/cluster-api/pull/6117 we noticed that latest CAPA doesn't have "--metrics-bind-addr=127.0.0.1:8080" in your manager.yaml (see
https://cluster-api.sigs.k8s.io/developer/providers/v0.3-to-v0.4.html#required-kustomize-changes-to-have-a-single-manager-watching-all-namespaces-and-answer-to-webhook-calls).

Applying this change is not mandatory, but FYI deploying Prometheus in local dev env using the CAPI Tiltfile won't work without this change.

**Comment by sedefsavas** [comment]
Thanks @fabriziopandini 

We had this in v1alpha4, but not have it in v1beta1.

This is a simple change, we need to add this line:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/de756c7a98f9876c928e510deaf8ddae94d11ec9/config/manager/manager.yaml#L21

and this
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v0.7.3/config/rbac/auth_proxy_service.yaml

/good-first-issue
/triage-accepted
/priority backlog
/milestone v1.x

**Comment by Matheusafonsouza** [comment]
Can i be responsible for this one?
