### ISSUE TITLE
Add AWS Service functions to e2e test shared

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-aws#3235]
/kind feature

**Describe the solution you'd like**
Add some basic CRUD functions for VPCs, subnets, NatGW, IGW, route tables, routes and peering connections to be used by the e2e test suite for building out infrastructure prior to test.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Thanks @josh-ferrell, this is a great step to test different topologies.

We have a few of these under test/e2e/suites/unmanaged/helpers_test.go.
We can move them to a shared folder with the new ones as well.
