### ISSUE TITLE
AWSMachinePool minSize should be allowed to go to 0 

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-aws#3242]
/kind bug

**What steps did you take and what happened:**
I tried to set the AWSMachinePool minSize to 0 but this failed to apply

The current validation rule of [`AWSMachinePoolSpec.minSize`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/api/v1beta1/awsmachinepool_types.go#L45) specifies a validation rule of `Minimum=1`. 
An ASG does not have such a minimum and therefore allows setting minSize to zero. 

It might (depending on the implementation) also be important for the [autoscaler scale to zero proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210310-opt-in-autoscaling-from-zero.md), to have this validation corrected. 

**What did you expect to happen:**
Setting `minSize: 0` works and updates the autoscaling group accordingly.

**Anything else you would like to add:**
Happy to provide a PR for this, if that sounds like something you'd accept :) Not sure what kind of tests would be needed to do so - would need some guidance there. 

**Environment:**

- Cluster-api-provider-aws version: `v1.3.0`
- Kubernetes version: (use `kubectl version`): 1.23

**Comment by richardcase** [comment]
When doing this we should also update the e2e tests to test scale to 0.
