### ISSUE TITLE
Ability to add custom environment variables to the `aws-node` DaemonSet

### ISSUE THREAD

**Issue by charlie-haley** [kubernetes-sigs/cluster-api-provider-aws#3244]
/kind feature

**Describe the solution you'd like**
Ability to add custom environment variables to the `aws-node` DaemonSet, ideally through an existing CRD such as `AWSManagedControlPlane`

**Anything else you would like to add:**
I've recently needed to bump up the pod limits on our EKS clusters and as a result, needed to set `ENABLE_PREFIX_DELEGATION=true` on the `aws-node` DaemonSet - having the ability to modify the env vars on the DS would be very useful! 

Happy to raise a PR if this solution is accepted.

**Environment:**

- Cluster-api-provider-aws version: v1.3.0 
- Kubernetes version: (use `kubectl version`): v1.21.5
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Comment by richardcase** [comment]
Thanks @charlie-haley. I think this is a reasonable request and if you'd like to create a PR that would be fantastic....feel free to reach out here or in slack if you need any help.

/triage accepted
/priority important-longterm
/help

**Comment by richardcase** [comment]
I meant to say, feel free to assign the issue to yourself.

**Comment by charlie-haley** [comment]
Awesome, thanks @richardcase!

/assign @charlie-haley

**Comment by richardcase** [comment]
@charlie-haley - we have some existing code around aws-node...it may be worth looking at [this package](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/24e3ea2e372e5c6deff3c32bb6e72e4207f0f24a/pkg/cloud/services/awsnode).
