### ISSUE TITLE
Use AWSMachinePoolSpec Subnets.Filters field in fetching subnetIDs

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#3254]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

`AWSMachinePoolSpec` has a field `subnets` which is an array of subnet configurations and user can pass `subnetIDs` and `Filters` based on which we can fetch particular subnetIDs and create resources on them.
```
type AWSMAchinePoolSpec struct{
      ...
      ...
      Subnets []infrav1.AWSResourceReference `json:"subnets,omitempty"`
      ...
      ...
}

type AWSResourceReference struct {
	ID *string `json:"id,omitempty"`
	ARN *string `json:"arn,omitempty"`
	Filters []Filter `json:"filters,omitempty"`
}
```

So we should enable the code to use Filters field also in calculating the subnet. currently we are only using `ID`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

cc: @sedefsavas

**Comment by Ankitasw** [comment]
@sedefsavas Will this solve the problem mentioned in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2087 ?

**Comment by Ankitasw** [comment]
There is already an issue and PR for this https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2609.
@shivi28 we might want to close this issue and use original issue, and look for the discussions and existing [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2609).
