### ISSUE TITLE
Should we use ANDed or ORed approach in CRD fields

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/cluster-api-provider-aws#3268]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When we have multiple fields in any struct like AWSResourceReference, then should we use ANDed or ORed approach? 
Eg: In Kubernetes selectors, matchLabels and matchExpressions are ANDed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

cc: @sedefsavas

**Comment by shivi28** [comment]
Linking [thread discussion](https://kubernetes.slack.com/archives/C8TSNPY4T/p1646646144966339) for reference

**Comment by sedefsavas** [comment]
Is there any action items for this issue as per our discussion today in office hours? If not, can close the issue.

**Comment by sedefsavas** [comment]
/close

Since there is no general convention, we will make a decision on a case by case basis.
