### ISSUE TITLE
<clustername>-node security group contains a rule that overshadows <clustername>-lb security group rules

### ISSUE THREAD

**Issue by matlemb** [kubernetes-sigs/cluster-api-provider-aws#3271]
/kind bug

**What steps did you take and what happened:**
When deploying a kubernetes cluster on AWS with `capa-controller-manager` a security group `<clustername>-node` gets created which contains a [rule](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/40a8e0a70fffa69d165ddb8b47eed5368656804e/pkg/cloud/services/securitygroup/securitygroups.go#L520-L526) to allow access from `0.0.0.0/0` all node port services (`3000-32767`). This security group gets attached to all kubernetes nodes. The rule exists to support incoming traffic from ELBv1 (ELB Classic) Loadbalancers which do NAT the client connections and have a frontend security group in place to restrict access to the services.

However when using an NLB there is no frontend security group support on AWS. In this case filtering is implemented on the <clustername>-lb security group when using `svc.spec.loadBalancerSourceRanges`. The rules generated by `capa-controller-manager` do overshadow the rules implemented by the load balancer controllers to restrict acess to exposed services.

**What did you expect to happen:**
Have a startup flag for `capa-controller-manager` to disable the generation of inbound security rules for node port services.

**Anything else you would like to add:**
A startup of `capa-controller-manager` with eg. `--disable-elbclassic-inbound-rules` could simply disable [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/40a8e0a70fffa69d165ddb8b47eed5368656804e/pkg/cloud/services/securitygroup/securitygroups.go#L520-L526) code block. The issue would be solved and security group rules handling for services would be done just as expected through the load balancer controller.

**Environment:**

- Cluster-api-provider-aws version: 1.3
- Kubernetes version: (use `kubectl version`): 1.22.4
- OS (e.g. from `/etc/os-release`): VERSION="20.04.3 LTS (Focal Fossa)"

<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by matlemb** [comment]
I want to kindly ask if any further explanation or information is needed? Can i help you out on something?
<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by Ankitasw** [comment]
Hey @matlemb , I will try to replicate it locally and let you know if I need any more info.

**Comment by matlemb** [comment]
@Ankitasw Thank you very much for your feedback.

For every CIDR block item in svc.spec.loadBalancerSourceRanges a rule in the cluster-lb security group gets created with the source of the CIDR block and the port of the nodeport. This is the only needed rule if using NLB with client ip preservation on (no NAT mode like in classic ELB).

We already tested this locally (disabled the suggested code block) and exposed services through either cloud-controller-manager or aws-load-balancer-controller with an NLB which then works as expected.

If there is no option for the user to disable the node port services rule from capa the user is always restricted to only use load balancers which are backed by a front-end security group or having a big security risk.

**Comment by matlemb** [comment]
@Ankitasw Sorry, i forgot one more thing: The LB controller will additionally add rules for health checks of the Loadbalancer so the user doesn't have to think about this thing (usually the LB listener subnets is used as source).
<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by Ankitasw** [comment]
Thankyou @matlemb for the explanation.
We have an [issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3088) open to support NLB in CAPA going forward, so this issue would be valid wrt it.
@sedefsavas do we want to handle this issue now or shall we take it later with the NLB support? Please provide your feedback.

**Comment by matlemb** [comment]
@Ankitasw The [issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3088) is more about how the control-plane API is exposed (defaults to ELB) which is not affected by this current issue at all because the nodeport services rule (30000-32727) does not contain the port range of the control-plane API. So removing the node port services rules would still leave the control-plane API accessible.

I think we currently have support for NLB or all LBs which are supported by the loadbalancer controllers but we need to have configuration options for the default security group rules by capa so the users can secure their clusters properly.

<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by Ankitasw** [comment]
@matlemb Yes, you are aboslutely correct, we already have support for NLBs, the issue I mentioned is more about deprecating ELBs and using NLBs :) so sorry for the confusion.

**Comment by Ankitasw** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3314

**Comment by sedefsavas** [comment]
This is the same issue with https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3314

Modifying auto-created SGs are not supported, but a good workaround is providing your own node SG, see https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html#security-groups

When a node SG is provided, CAPA will not create the default one.
```
network:
    securityGroupOverrides:
      node: sg-04e870a3507a5ad2c5c8c3
```

Would that solve your issue @matlemb?

**Comment by matlemb** [comment]
@sedefsavas Thank you for your suggestion.

Indeed it would solve the creation of those `node port services rules` but then we would need to handle the creation of the group, the tags of the group and the needed default rules of the group (like node-to-node communication etc.) by ourself (another controller). I think there would be a lot burden to the user for just disabling the default rules of ELB classic loadbalancer  when going the bring your own security groups route.

**Comment by sedefsavas** [comment]
I agree, we will need to add modification to SGs, tracking here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/392

**Comment by Ankitasw** [comment]
Since we are tracking original issue [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/392), do we want to keep this issue open?
cc @sedefsavas @matlemb

**Comment by matlemb** [comment]
@Ankitasw Sorry for my late reply, From my understanding by reading through issue 392 and the mentioned issues (3341 for this case) it's okay for me to close this issue as we all have a common understanding what the problem is and how the solution in future should look like.

I just wanted so make everyone aware of the security concerns regarding 3341 when using NLBs.
<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by Ankitasw** [comment]
Thankyou @matlemb for raising the concern.
/close in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/392 and https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3341
