### ISSUE TITLE
pull-cluster-api-provider-aws-apidiff-main test is failing 

### ISSUE THREAD

**Issue by meghanajangi** [kubernetes-sigs/cluster-api-provider-aws#3272]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The prow job [pull-cluster-api-provider-aws-apidiff-main test is failing ](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-aws-apidiff-main)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Related to #3169 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/assign

**Comment by sedefsavas** [comment]
Issue is this target is not using PULL_BASE_SHA.

`hack/tools/bin/go-apidiff origin/main --print-compatible
`
