### ISSUE TITLE
clusterawsadm does not provision the controller role with ec2:AssociateVpcCidrBlock permission

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-aws#3273]
/kind bug

**What steps did you take and what happened:**
`clusterawsadm` does not provision the controller role with `ec2:AssociateVpcCidrBlock` permission, which is required when there is secondary cidr specified (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/secondarycidr.go#L55).

**What did you expect to happen:**
`clusterawsadm` should provision the controller role with both `ec2:AssociateVpcCidrBlock` and `ec2:DisassociateVpcCidrBlock` permissions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
/assign
Since facing this issue in [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3347) PR's E2E [test](url), will give a combined solution with this.

> E0324 19:54:51.448104       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile network for AWSManagedControlPlane eks-nodes-8muna9/cluster-k6q671-control-plane: UnauthorizedOperation: You are not authorized to perform this operation
