### ISSUE TITLE
Support multiple VPC secondary CIDRs in AWSMCP

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-aws#3275]
/kind feature

**Describe the solution you'd like**
Currently AWSMCP only allows one secondary CIDR (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go#L49). However we'd like to add support for multiple secondary CIDRs to create larger EKS clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardchen331** [comment]
I can see two options to support this:
1) Introduce a new field `SecondaryCidrBlocks` of type `[]string`, and deprecate the existing field `SecondaryCidrBlock`
2) Change the current field `SecondaryCidrBlock` from type `*string` to `[]string`
I prefer the first one. If anyone has thoughts/suggestions, please let me know :) Thanks!

**Comment by sedefsavas** [comment]
If we want to do this in the 1.x release, we should go with option to 2 as option 1 is breaking change.

One thing to decide, are we going to support deletion and addition to that list (like we do in tags, we keep things consistent, list of tags in the CAPA resource matches the list of tags in the AWS resource)?

cc @richardcase

**Comment by richardchen331** [comment]
Thanks for the feedback.

I think we can at least start with not allowing deletion/addition to that list, since the logic of that could be quite complex (e.g. what if user specified subnets/machine pools that uses a secondary CIDR).

**Comment by sedefsavas** [comment]
Sorry my numbering mixed up in my comment above, it is the other way around:

First option above is non-breaking and we should go with it.

**Comment by sedefsavas** [comment]
> Thanks for the feedback.
> 
> I think we can at least start with not allowing deletion/addition to that list, since the logic of that could be quite complex (e.g. what if user specified subnets/machine pools that uses a secondary CIDR).

I am okay with not allow any modification once SecondaryCIDRs are set initially.

**Comment by sedefsavas** [comment]
Rethinking, we definitely would want to support addition to the list considering that a general use case for this is running out of IPs in the current CIDR, so I'd expect users will not know if they want to add more CIDRs from the start.

**Comment by sedefsavas** [comment]
As a note: Multiple VPC CIDRs will affect both managed and unmanaged clusters, so the solution needs to be common.

**Comment by Skarlso** [comment]
The initial approach looks okay. One thing to note is to take care during reconciliation that we use cmd Equal and that only addition is supported. Deletaion is not allowed from either side. Incoming and the cluster config.

**Comment by mtougeron** [comment]
@Skarlso what about deletion from `secondaryCidrBlock` when moving for the first time to `secondaryCidrBlocks`? I would think that migration would be acceptable. Thoughts?

Assigning to myself to take on this work.

/assign @mtougeron

**Comment by Skarlso** [comment]
I suggest not allowing setting them both. When you do the migration part, meaning you create a new field, you need to set `secondaryCidrBlock` to optional anyways. So once someone deletes entries and sets an entry in `secondaryCidrBlocks` internally, it should use the same structure internally already.

**Comment by mtougeron** [comment]
Sorry I wasn't clear enough, that's essentially what I meant.

**Comment by Skarlso** [comment]
Ah ok cool. :) 👍

**Comment by richardcase** [comment]
Ideally we'd do this as part of a api version bump so that we can remove `secondaryCidrBlock` and convert to `secondaryCidrBlocks`. 

But as we are talking about changing how we represent/handle networking generally in CAPA we could go with the additional field  for the time being and have validation  added to the webhook where both can't be specified. 

We should also mark `secondaryCidrBlock` as deprecated and also add a log line if its set in the webhooks saying that its being deprecated in a future version and to consider using `secondaryCidrBlocks` instead.

**Comment by mtougeron** [comment]
FYI just so this doesn't go stale/rotten again, I'm still planning on addressing this
