### ISSUE TITLE
Only split SecondaryCidrBlock when there is no subnets specified in AWSMCP

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-aws#3276]
/kind bug

**What steps did you take and what happened:**
Currently when there's secondary CIDR block specified in AWSMCP, CAPA will automatically split the secondary CIDR into multiple subnets (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/subnets.go#L85-L110), even if the user manually specified subnets in AWSMCP. There is no way for the user to specify how the secondary CIDR could be used. 

**What did you expect to happen:**
CAPA should only split the secondary CIDR when user has not specified subnets.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
> CAPA should only split the secondary CIDR when user has not specified subnets.

In case where subnets are not specified, just using VPC CIDR block and dividing that into subnets could be an option, isn't it? So, we do not necessarily need to use Secondary CIDR block for Subnet CIDRs.

For instance, if we want to leave SecondaryCIDR block to pod networking only for AWS native CNI (as this is the initial reason they had in mind while supporting this [feat](https://github.com/aws/amazon-vpc-cni-k8s/issues/119)), do we still want to split this into subnets when subnets are not defined?

Don't have the full context of Secondary CIDR support, but if the main use case is for pod addressing, then we should avoid creating subnets out of Secondary CIDR block all together?

**Comment by richardchen331** [comment]
@sedefsavas IIUC, the largest primary CIDR block of a VPC allowed is /16 (https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html). In our use case, we'd like to create an EKS cluster with one subnet per AZ, and for each subnet, we need a /16 CIDR. AFAIK this could not be achieved without secondary CIDRs. Please let me know if you have other questions, happy to provide more context.
