### ISSUE TITLE
CAPA should disassociate secondary CIDR after subnets are deleted

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-aws#3277]
/kind bug

**What steps did you take and what happened:**
Currently CAPA disassociates secondary CIDR before subnets are deleted (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/network.go#L95), this won't work if there's still subnet in use.

**What did you expect to happen:**
CAPA should disassociate secondary CIDR after subnets are deleted

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
/triage accepted
/priority important-soon
/milestone v1.x

This bug shows the need to have an e2e test for SecondryCIDR support.

**Comment by Ankitasw** [comment]
> This bug shows the need to have an e2e test for SecondryCIDR support.

@sedefsavas would it be sufficient if we add secondary CIDR in one of the existing test case, or do we want a new E2E test case covering this?
