### ISSUE TITLE
[E2E] test to validate CAPA clusters in Internet restricted environments

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-aws#3296]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add an E2E test that will validate CAPA clusters can be created in private subnets pulling the necessary images from a privately hosted container registry with ECR private registry.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
/triage accepted
/priority important-longterm

Some PRs related to this are already in, would be good to link this issue to them to track the work that are in related to this.
