### ISSUE TITLE
Add repository layout to the book

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3297]
Similar to cluster-api https://github.com/kubernetes-sigs/cluster-api/pull/6282, would be good to add the layout to CAPA book too.

/good-first-issue
/triage accepted
/kind documentation
/priority backlog

**Comment by sedefsavas** [comment]
During last week's code walkthrough, we went over the repo structure, might be helpful for this issue:
https://www.youtube.com/watch?v=Y6kc7wmyElI&ab_channel=RichardCase

**Comment by VibhorChinda** [comment]
> During last week's code walkthrough, we went over the repo structure, might be helpful for this issue: https://www.youtube.com/watch?v=Y6kc7wmyElI&ab_channel=RichardCase

Thanks will have a look into this :)

**Comment by sedefsavas** [comment]
cc @Madhur97 created the layout for cluster api repo if you need help.
