### ISSUE TITLE
[machine actuator] Implement Update

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#33]

**Comment by phyber** [comment]
I'm starting to take a look at this. WIP PR coming soon.

**Comment by phyber** [comment]
Work on this happening in PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/91

**Comment by phyber** [comment]
Complete implementation of this also depends upon #94 and #95. #91 implements a naive `Update` that only updates object status.

**Comment by phyber** [comment]
Commenting to re-open this. Closed by mistake due to earlier PR comment.

Still to go here:
  - Update Tags
  - Update Security Groups
  - Error when trying to update immutable state
