### ISSUE TITLE
Add Codecov badge to CAPA repo

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#3304]
Codecov gives you a glance into the status of your project’s percentage of code coverage.

It would be good to see CAPA's code coverage on day-to-day basis since we have added a good amount of unit tests coverage recently. Based on the results we may do some more improvements. 
Also, keeping in mind that each new PR covers/tests the new code added.

Document to refer: https://docs.codecov.com/docs/quick-start

/area testing

**Comment by shivi28** [comment]
Let's keep it open @Ankitasw for the community. I will assign it later as per my bandwidth. Meanwhile if someone else wants to pick they can pick.

**Comment by Ankitasw** [comment]
Good call @shivi28 I thought you are already working on this some time back so thought of assigning you

**Comment by shivi28** [comment]
No I think there might be some confusion, I discussed to do this work for CAPA but did not start on this. 
But ya thanks for creating this issue for tracking and it would be good if we let the contributors to assign the issues by themselves as per their bandwidth.

**Comment by Ankitasw** [comment]
> Thanks for creating this issue for tracking and it would be good if we let the contributors to assign the issues by themselves as per their bandwidth.

I totally understand that, sorry for assigning it to you without asking you.
/good-first-issue

**Comment by zeborg** [comment]
Hey @Ankitasw, it seems like there's no prow job defined for test coverage in `test-infra` till now although we have a `ci-test-coverage.sh` script already present in the `scripts` directory.
Can you please confirm if that script is currently being used anywhere in any of the existing jobs _(prow or otherwise)_ or if we are yet to have it implemented?
Thanks!

**Comment by pydctw** [comment]
Similar to what I said in https://github.com/kubernetes-sigs/cluster-api/issues/6297#issuecomment-1065459656, I am not sure if we want to do it.

**Comment by Ankitasw** [comment]
Thanka @pydctw for feedback. If others in community feel the same, I am ok to close the discussion.

**Comment by zeborg** [comment]
Just for a follow-up on this issue, since the CAPI issue for codecov has been closed, should we proceed with doing the same for CAPA as well or should we wait for a final discussion in the upcoming office hours?

**Comment by Ankitasw** [comment]
@zeborg lets hold this till our next office hours.

**Comment by sedefsavas** [comment]
Closing this as per the discussions during the office hour. 

/close
