### ISSUE TITLE
generate provider command should not substitute variables when `--describe` is used

### ISSUE THREAD

**Issue by LucaLanziani** [kubernetes-sigs/cluster-api-provider-aws#3307]
/kind bug

**What steps did you take and what happened:**

Running the below command I got an error about variable substitution:

```bash
> clusterctl generate provider --infrastructure aws --describe
Error: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file
```

**What did you expect to happen:**

Following the clusterctl [documentation](https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html?highlight=--describe#how-can-i-known-which-variables-a-provider-requires) it looks like the command should skip the substitution and output the required variables:

```bash
> AWS_B64ENCODED_CREDENTIALS="This should not be needed" clusterctl generate provider --infrastructure aws --describe
Name:               aws
Type:               InfrastructureProvider
URL:                https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/
Version:            v1.3.0
File:               infrastructure-components.yaml
TargetNamespace:    capa-system
Variables:
  - AUTO_CONTROLLER_IDENTITY_CREATOR
  - AWS_B64ENCODED_CREDENTIALS
  - AWS_CONTROLLER_IAM_ROLE
  - CAPA_EKS
  - CAPA_EKS_ADD_ROLES
  - CAPA_EKS_IAM
  - CAPA_LOGLEVEL
  - EVENT_BRIDGE_INSTANCE_STATE
  - EXP_EKS_FARGATE
  - EXP_MACHINE_POOL
  - K8S_CP_LABEL
Images:
  - k8s.gcr.io/cluster-api-aws/cluster-api-aws-controller:v1.3.0

``` 

**Anything else you would like to add:**

I would be more than happy to open a PR myself if we think this is worth solving.

**Environment:**

- Cluster-api-provider-aws version: v1.3.0
- Kubernetes version: (use `kubectl version`): None 
- OS (e.g. from `/etc/os-release`):  Archlinux

**Comment by sedefsavas** [comment]
I also confirmed that this is a bug.

We should move the issue to cluster-api as the fix will go in there.

**Comment by sedefsavas** [comment]
I am unable to transfer it by using the transfer button on the right console.
Feel free to close this one and open a new one in cluster api repo.

**Comment by LucaLanziani** [comment]
Issue moved to cluster-api https://github.com/kubernetes-sigs/cluster-api/issues/6316, closing this.
