### ISSUE TITLE
Update ASG when AWSMachinePool subnets change

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3315]
We only use subnets fields in AWSMachinePool field during ASG creation and do not update Auto Scaling Group if subnets change.
UpdateASG() should return true if a change is detected in the subnets.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/6ab95625da2aabb209bc5744883eb4c009cc4fba/exp/controllers/awsmachinepool_controller.go#L534

ASG rollouts all machines and bring up new ones once updated with new `VPCZoneIdentifier`.

/kind feature
/priority important-longterm
/milestone v1.x

**Comment by sedefsavas** [comment]
We need to convert existing subnets in the ASG (`VPCZoneIdentifier`) to `AutoScalingGroup.Subnets` using SDKToAutoScalingGroup() method, it is missing right now.
VPCZoneIdentifier is a comma separated list.

**Comment by DiptoChakrabarty** [comment]
@sedefsavas  so in here https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/6ab95625da2aabb209bc5744883eb4c009cc4fba/exp/controllers/awsmachinepool_controller.go#L534
I create a `autoscaling.Group (from github.com/aws/aws-sdk-go/service/autoscaling)`  using the `*scope.MachinePoolScope` and fit that into SDKToAutoScalingGroup which returns a `expinfrav1.AutoScalingGroup` and compare it to `existingASG *expinfrav1.AutoScalingGroup (value entered in function originally)` 

Does this sound appropriate?

**Comment by sedefsavas** [comment]
SDKToAutoScalingGroup() should not need to be called from [awsmachinepool_controller.go](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/6ab95625da2aabb209bc5744883eb4c009cc4fba/exp/controllers/awsmachinepool_controller.go#L534)

**1) Changes that will be done in SDKToAutoScalingGroup() method:**
	
add 	Subnets field to the conversion:
```
	i := &expinfrav1.AutoScalingGroup{
		Subnets: create_slice_from_comma_separated_subnets(v.VPCZoneIdentifier)
	}
```
You can see how we generate VPCZoneIdentifier in runPool() method:    `aws.String(strings.Join(i.Subnets, ", ")),`

**2) In awsmachinepool_controller.go, just diff existingASG with `machinePoolScope.AWSMachinePool.Spec.Subnets`**

**Comment by DiptoChakrabarty** [comment]
@sedefsavas made a PR , just a bit confused on the comparison/diff checking between  `existingASG` and `machinePoolScope.AWSMachinePool.Spec.Subnets` , will follow up any changes requested. Thank you for all the help until now.

**Comment by Ankitasw** [comment]
/reopen

This issue has a corresponding PR open, if folks are interested to pick.

/unassign @DiptoChakrabarty
