### ISSUE TITLE
[E2E] Add tests for all the fields of type AWSResourceReference with filters as input

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#3348]
/area testing

**Describe the solution you'd like**
Since we now have lookup for the `AWSResourceReference` type fields with filters as well, it would be good to have E2E tests with those fields(currently `Subnet` and `AdditionalSecurityGroups` uses the same) having filters as input to test the lookup functionality.
We might also have to test `Subnet.ID` and `AdditionalSecurityGroups.ID` field input as well as it's not tested in our any of the E2E tests.
_Originally posted by @richardcase in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3257#issuecomment-1077646875_

**Comment by sedefsavas** [comment]
/triage accepted
/priority backlog
/milestone v1.x

I think we need to also start documenting or adding comments to the tests/manifests that we overload. Multiple functionality tested in a single test is a good idea, but would be good to keep track.
