### ISSUE TITLE
Should_successfully_reconcile_AWCluster_creation_with_unmanaged_VPC test is flaky

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-aws#3352]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created 2 PRs. Observed twice this test failing randomly: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3351/pull-cluster-api-provider-aws-test/1507369944281518080

**What did you expect to happen:**

All tests to pass.

**Comment by sedefsavas** [comment]
Tags need to be ordered in that test:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3351/pull-cluster-api-provider-aws-test/1507369944281518080/build-log.txt

/triage accepted
/priority important-soon
/milestone v1.4

cc @Ankitasw

**Comment by sedefsavas** [comment]
This still looks like an ordering problem:
```
              LoadBalancerNames: [""],
              Tags: [{
                  Key: "Name",
                  Value: "test-cluster-apiserver"
                },{
                  Key: "sigs.k8s.io/cluster-api-provider-aws/cluster/test-cluster",
                  Value: "owned"
                },{
                  Key: "sigs.k8s.io/cluster-api-provider-aws/role",
                  Value: "apiserver"
                }]
            } (*elb.AddTagsInput)
            Want: is equal to {
              LoadBalancerNames: [""],
              Tags: [{
                  Key: "sigs.k8s.io/cluster-api-provider-aws/cluster/test-cluster",
                  Value: "owned"
                },{
                  Key: "sigs.k8s.io/cluster-api-provider-aws/role",
                  Value: "apiserver"
                },{
                  Key: "Name",
                  Value: "test-cluster-apiserver"
                }]
```
