### ISSUE TITLE
[E2E] Merge external infrastructure, peered VPCs, internal ELB and private subnets test

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-aws#3360]
/kind feature

**Describe the solution you'd like**
Merge the external infrastructure, peered VPCs, internal ELB and private subnets test. This will help alleviate the VPC limit being reached.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by josh-ferrell** [comment]
This can be assigned to me

**Comment by sedefsavas** [comment]
You should be able to assign yourself.
Does /assign not work?

**Comment by josh-ferrell** [comment]
@sedefsavas Sorry about that
