### ISSUE TITLE
Validate and document EFS CSI driver support

### ISSUE THREAD

**Issue by Madhur97** [kubernetes-sigs/cluster-api-provider-aws#3384]
/kind feature

**Describe the solution you'd like**
Add [EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) to defaults addons manifest so that CAPA clusters running on AWS can manage the lifecycle of [Amazon EFS](https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html) file systems.

**Comment by Madhur97** [comment]
> We do not really manage LCM of addons like EFS drivers, the aim here is just to validate it works with CAPA clusters by adding an e2e test, am I right?

Yes, we will validate it with an E2E test.

**Comment by sedefsavas** [comment]
/reopen

I think we still need documentation for this @Madhur97.

**Comment by sedefsavas** [comment]
@Madhur97 are there any updates on this?
