### ISSUE TITLE
Makefile targets fails with setup-envtest not exist error

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3386]
On a clean checkout, I hit the following issue when I run several targets:

```
➜  cluster-api-provider-aws git:(b0388430)  make release-changelog  (or create-gh-release)
./hack/releasechangelog.sh -v v1.4.0 -pv v1.3.0 -gh hack/tools/bin/gh -ghorg kubernetes-sigs -ghrepo cluster-api-provider-aws -cimg gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller > out/CHANGELOG.md
bash: /Users/ssavas/dev/CAPA/v1.4.0/cluster-api-provider-aws/hack/tools/bin/setup-envtest-v0.0.0-20211110210527-619e6b92dab9: No such file or directory
```

Having setup-envtest is not a requirement for those targets so should not see this error.
This issue goes away after running make test as setup-envtest gets added to bin folder.

This bug is introduced with https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3362
/kind bug
/triage accepted
/priority important-soon

**Comment by sedefsavas** [comment]
cc @Skarlso

**Comment by Skarlso** [comment]
Huh. :O Oh dang, how the... I'll investigate ASAP.

Thank you for pinging.

**Comment by Skarlso** [comment]
Oh I see what's wrong. I'll do some shuffling, and then it should be okay. 🤞 :D
