### ISSUE TITLE
AWSMachine Reconciler fails with error "invalid secret backend" if insecureSkipSecretsManager: true with latest version 1.4.0

### ISSUE THREAD

**Issue by nehatomar12** [kubernetes-sigs/cluster-api-provider-aws#3402]
I am using version v1.4.0
I have `insecureSkipSecretsManager: true` in cloudInit

<img width="592" alt="Screenshot 2022-04-11 at 10 31 23 AM" src="https://user-images.githubusercontent.com/51879259/162668026-9bd8555e-64b4-4891-b952-1e2c66d2a823.png">

as this flag is set `secureSecretsBackend`  value is empty
due to which at the time of reconciliation [flow](https://github.com/platform9/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller.go#L576) when `deleteEncryptedBootstrapDataSecret` is called as [this](https://github.com/platform9/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller.go#L628) check is missing,
it goes to `getSecretService`, there we have a switch case for `SecureSecretsBackend`
as it is not set it is failing with `invalid secret backend `

```
if !machineScope.UseSecretsManager() {
		return nil
	}
```

Release 1.3 https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-1.3/controllers/awsmachine_controller.go#L579

Release 1.4 
https://github.com/platform9/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller.go#L628

is there any specific reason why we have removed this?

**Comment by sedefsavas** [comment]
Hi @nehatomar12, we had significant changes in v1.14.0 release to support[ ignition based bootstrapping](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271).

We are already tracking this issue here:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3394

and will make a release that will fix this soon.

**Comment by sedefsavas** [comment]
cc @invidian if you have time to review the fix for this to make sure ignition support is not affected: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3400

**Comment by sedefsavas** [comment]
/close 
in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3394

**Comment by nehatomar12** [comment]
@sedefsavas Thanks
is there any documentation regarding how can I configure AWS secret manager with CAPA?

when I am using `insecureSkipSecretsManager: false` default AWS secret manager is used, I am getting cloudinit boot issue
`Exception: [Errno 2] No such file or directory: '/etc/secret-userdata.txt' for url: file:///etc/secret-userdata.txt`

in the documentation, its is mentioned that this will be warning, [doc](https://cluster-api-aws.sigs.k8s.io/topics/userdata-privacy.html?highlight=Secret%20manegr#secrets-manager-console)

but my cloud-init always giving error for this file
