### ISSUE TITLE
AWSMachineTemplate with spot instance generate false error log

### ISSUE THREAD

**Issue by mloiseleur** [kubernetes-sigs/cluster-api-provider-aws#3404]
/kind bug

**What steps did you take and what happened:**
When I declare spotInstance on a new AWSMachineTemplate, like this:

```diff
--- a/clusters/infrastructure.cluster.x-k8s.io-v1beta1.AWSMachineTemplate-xxx-v1.yaml
+++ b/clusters/infrastructure.cluster.x-k8s.io-v1beta1.AWSMachineTemplate-xxx-v2.yaml
@@ -1,11 +1,13 @@
 apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
 kind: AWSMachineTemplate
 metadata:
-  name: xxx-v1
+  name: xxx-v2
   namespace: flux-system
 spec:
   template:
     spec:
       iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
       instanceType: xxx.medium
+      spotMarketOptions:
+        maxPrice: ""
       sshKeyName: xxx
```

Everything works fine. MachineDeployment using this template provision the new nodes, etc. They are seen by the management cluster and by the workload cluster. 

But it generates a false error log on capi-controller-manager :

```
E0411 12:54:02.362276       1 controller.go:317] controller/machine "msg"="Reconciler error" "error"="machines.cluster.x-k8s.io \"XXXX\" not found" "name"=XXXX" "namespace"="flux-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine"
```

Even though the nodes and the machines are here, consistent, up and running. 

**What did you expect to happen:**

I don't get a false error log message when I use spot instances.

**Anything else you would like to add:**

When I remove spotMarketOptions, I don't get this false error log.

**Environment:**

- Cluster-api version: 1.1.3 
- Cluster-api-provider-aws version: 1.4.0
- Kubernetes version: (use `kubectl version`): v1.22.6-eks-7d68063
- OS (e.g. from `/etc/os-release`): EKS

**Comment by Ankitasw** [comment]
Hey @mloiseleur, I don't think this is really an issue, cause while reconciling the machines, machine controller tries to fetch the machine object from etcd, and if it is not found, it is reconciled again. Till the machine is created, you'll see this error message, and it's not just with spot instances, even with on-demand instances, you'll see this error.

**Comment by mloiseleur** [comment]
Hey @Ankitasw :wave:,

The thing is, this error message is not until the machine is created. It never stops to fill the logs, even after the new nodes/machines are created, pods are moved on it and everything is stable.

**Comment by Ankitasw** [comment]
@mloiseleur please do not remove lifecycle-stale.
Is this issue still reproducible?

**Comment by Ankitasw** [comment]
@Madhur97 is there a chance you are still working on this? If not, please unassign yourself.

**Comment by mloiseleur** [comment]
@Ankitasw Yes, this issue is still reproducible.

**Comment by mloiseleur** [comment]
We are also seeing this error in (CAPI) metrics : `controller_runtime_reconcile_errors_total{controller="machine", namespace="capi-system}"`
It's still present in v2.0.2 of CAPA & v1.3.0 of CAPI

**Comment by Ankitasw** [comment]
We have spot instance tests running in our CI, which doesn't flood with this error, you could check out the logs [here](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1611234234561728512/artifacts/clusters/bootstrap/controllers/capi-controller-manager/capi-controller-manager-6c8d5c5b5c-9jmts/manager.log)

[Here](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1611234234561728512/artifacts/clusters/bootstrap/functional-test-spot-instances-ge5c6a-cluster-template.yaml) is the cluster template used. Could you please check if you are doing configurations differently?

**Comment by daveortiz-ctct** [comment]
We've run into the same issue, any idea when this might be prioritized?  I'd be happy to try and contribute a fix if nobody else has already.

**Comment by Ankitasw** [comment]
@daveortiz-ctct please go ahead and assign it to yourself if you are willing to contribute.

**Comment by mloiseleur** [comment]
We've not found any way to fix it but with 
1. Cluster API: `v1.4.1`
2. AWS Provider: `v2.0.2`

This issue has vanished.
