### ISSUE TITLE
Update the release changelog script to use arguments

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3405]
/kind refactor
/priority backlog
/triage accepted
/help
/good-first-issue

**Describe the solution you'd like**
Update the [releasechangelog.sh](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/hack/releasechangelog.sh) script to use arguments instead of relying on the right variables being set out side the script.

We need to ensure that any variable set from the arguments are local to the script and there is no interference from the variables set in the makefile.

The Makefile will also need to be updated to specify the arguments.

**Anything else you would like to add:**

This is a follow up from #3388 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
@rvacaru Hi. :)

Are you still looking into the regression thing? It's fine if there is just life and delays, that's understandable. Just reaching out for information. :)

/remove-lifecycle stale

**Comment by rvacaru** [comment]
@Skarlso I fixed the regression issue on the variables being overridden by the Makefile, the PR is ready to be reviewed and maybe more testing is needed, I tested as much as I could but I'd need some help, see https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3440#issuecomment-1354573179

**Comment by Skarlso** [comment]
Cool. I'll take a look when I can.
