### ISSUE TITLE
Deprecate `DisableVPCCNI` in `AWSManagedControlPlane`

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3410]
/kind feature
/area provider/eks
/priority important-longterm
/triage accepted
/help

**Describe the solution you'd like**
With #3374 we are introducing a new struct for settings that relate to the VPC CNI  (a.k.a aws-node). We should add a `Disable` field to this and start deprecation of `DisableVPCCNI`.

Any code that relies on `DisableVPCCNI` should be changed to use a field on the managed control plane scope that can internally get the values from `DisableVPCCNI` or `VPCCNI.Disable`.

We will also probably need to update the admission controller to:

- report that `DisableVPCCNI` is deprecated
- check if the values of `DisableVPCCNI` & `VPCCNI.Disable` are set to something different

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by charlie-haley** [comment]
I'm happy to take a look at this once #3374 has been merged into master

/assign @charlie-haley

**Comment by charlie-haley** [comment]
@richardcase do you also think it would make sense to do this https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3544 as part of the same PR?

**Comment by richardcase** [comment]
> @richardcase do you also think it would make sense to do this #3544 as part of the same PR?

I'd be tempted to do them as 2 separate PRs. Only because the e2e tests can take a while to get working. But if you want to do them as a single PR then thats good as well. 

It would be great to improve the e2e coverage on the EKS side, so if you are keen in this area and if would be useful i could do a a brain dump on developing e2e tests in CAPA.

**Comment by charlie-haley** [comment]
> > @richardcase do you also think it would make sense to do this #3544 as part of the same PR?
> 
> I'd be tempted to do them as 2 separate PRs. Only because the e2e tests can take a while to get working. But if you want to do them as a single PR then thats good as well.
> 
> It would be great to improve the e2e coverage on the EKS side, so if you are keen in this area and if would be useful i could do a a brain dump on developing e2e tests in CAPA.

Sounds good, I can take a look at the e2e tests once these API changes are in, I'll reach out when I start work on them, thanks!
