### ISSUE TITLE
Replace default userdata created with AWS secret manager with custom userdata

### ISSUE THREAD

**Issue by nehatomar12** [kubernetes-sigs/cluster-api-provider-aws#3422]
CAPA version v1.4.0
I want to use AWS secret manager as a backend, so I have set cloudInit to `secureSecretsBackend: secrets-manager`

when I create a workload cluster, by default there is some user data generated for the EC2 instance 
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="d18dac100908828cd37985bcca162963d3a8a84d0419e19aad5175df6964"

--d18dac100908828cd37985bcca162963d3a8a84d0419e19aad5175df6964
content-type: text/cloud-boothook

#cloud-boothook
#!/bin/bash
....
.....
SECRET_PREFIX="aws.cluster.x-k8s.io/e6b9d24a-e929-40dd-93f3-d24788b791ac-0"
CHUNKS="1"
FILE="/etc/secret-userdata.txt"
FINAL_INDEX=$((CHUNKS - 1))


content-type: text/x-include-url

file:///etc/secret-userdata.txt

--d18dac100908828cd37985bcca162963d3a8a84d0419e19aad5175df6964--
```

I am using custom kubeadm config, I have correct userdata  present `BootstrapConfig.Status.DataSecretName` `Machine.Spec.Bootstrap.DataSecretName`  `Machine.Spec.Bootstrap.DataSecretName` (without vendor-data)

is there a way I can overwrite the user data which is available in `Machine.Spec.Bootstrap.DataSecretName`(my custom data)
with the default one?

**Comment by sedefsavas** [comment]
You can use pre and post Kubeadm commands for adding additional logic to run on boot up. An example: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1515358559267721216/artifacts/templates/cluster-template-conformance-ci-artifacts.yaml

**Comment by Ankitasw** [comment]
@nehatomar12 is there any additional help required in this issue? Were you able to go forward with above suggestion?
