### ISSUE TITLE
[e2e] Rename Cluster names to match spec name

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3424]
Test templates do not reflect which test they are for: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1514452035578105856/artifacts/clusters/bootstrap/

We should use the spec name during cluster name generation similar to how [cluster api ](https://github.com/kubernetes-sigs/cluster-api/blob/61c9e2154106a49ea0d1be8cb48bea1d8391b965/test/e2e/quick_start.go#L94)does: 
`				ClusterName:              fmt.Sprintf("%s-%s", specName, util.RandomString(6)) 
`

/triage accepted
/priority backlog
/good-first-issue

**Comment by ydarb** [comment]
I'd like to give this a go.
/assign
