### ISSUE TITLE
CAPA cluster with private subnets only and a Transit Gateway as default route

### ISSUE THREAD

**Issue by mimmus** [kubernetes-sigs/cluster-api-provider-aws#3432]
/kind feature

We would like to create a cluster with:
-     already existing VPC and subnets on 3 AZs
-     only private subnets, with a Transit Gateway as default route (no NAT/Internet gw)
?
This is our current setup on AWS, as we deploy only internal services and we have a Direct Connect with on-premises resources.

**Comment by voor** [comment]
Hello, thank you for your post!  This setup is currently possible with Cluster API AWS.  Just populate the existing VPC ID in the `AWSCluster`, include the subnets you want to deploy machines into under the subnet section, and then specify the subnets that the control plane Load Balancer entries would need to go into.
