### ISSUE TITLE
Disable MachinePool ASG instance refresh

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-aws#3447]
/kind feature

**Describe the solution you'd like**
I'd like the ability to disable automatic instance refresh on a machinepool. Currently when one e.g. changes the AMI of a AWSMachinePool, an instance refresh is automatically started:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/awsmachinepool_controller.go#L480

**Anything else you would like to add:**
We have long running jobs on windows machines (boot up time takes a while and is expensive due to windows licensing). Ideally updating an AMI would not automatically refresh the instances but instead new instances come up with the new AMI while old instances are left as-is. In our use case they get shutdown after the job anyway, so with time a refresh is done without interrupting workloads. 

I'd be happy to collaborate on a PR for this. I'm not 100% which approach to take - there are `RefreshPreferences` with a `Strategy` (which currently only allows `Rolling`):
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e53fce703aaa8ffce6913cb96d24f1f37e355ef2/exp/api/v1beta1/awsmachinepool_types.go#L97

I could extend this to e.g. allow `Disable` as the Strategy, but then it wouldn't map 1:1 to the ASG refresh properties so I'm not sure if this is the best approach. 

**Environment:**

- Cluster-api-provider-aws version: 1.4.1
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): windows/linux hybrid

**Comment by Skarlso** [comment]
eh, I tried. :)

**Comment by Skarlso** [comment]
Hello @mweibel.

This is still a desired thing, right?

**Comment by mweibel** [comment]
hi @Skarlso 
yes :)

**Comment by harveyxia** [comment]
I am also interested in this feature—we want to use our own tooling for managing instance rotation for existing ASGs, and Cluster API for managing the lifecycle of the ASG itself.
