### ISSUE TITLE
Some log messages are misleading and probably need to be moved to a lower level

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#3454]
/kind bug

**What steps did you take and what happened:**
`awsmachine_controller.go:763]  "msg"="Deleting unneeded entry from AWS S3"  "secretPrefix"=""`
and
`awsmachine_controller.go:432]  "msg"="Reconciling AWSMachine"`

occur with great frequency in the logs, and neither provides much information or insight into what's going on.  Additionally, CAPA is not actually deleting anything from AWS S3, and so might lead to a misleading action that doesn't actually occur.

**What did you expect to happen:**

I believe we would be best served by moving these out of `INFO` and into debug.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: `v1.4.1`
- Kubernetes version: (use `kubectl version`): `v1.23.4`
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
Hey @voor, thanks for raising the issue.
Regarding the below log, we are actually deleting the bootstrap data related to ignition parameters from S3 bucket, while delete reconciliation of AWSMachine, hence the log.
 
> `awsmachine_controller.go:763] "msg"="Deleting unneeded entry from AWS S3" "secretPrefix"=""`

Also, regarding the below log, every time reconcile loop is triggered, it is logged by the awsmachine controller. AFAIK it's followed in other provider's as well.

> `awsmachine_controller.go:432] "msg"="Reconciling AWSMachine"`

**Comment by sedefsavas** [comment]
We should not log this unless ignition is used.
`awsmachine_controller.go:763] "msg"="Deleting unneeded entry from AWS S3" "secretPrefix"=""`

We can actually increase the log level of the recurring logs like `Reconciling AWSMachine` so that users will have an option to reduce verbosity.

/triage accepted
/good-first-issue
/kind clean-up

**Comment by voor** [comment]
@tasdikrahman were you still interested in working on this?

**Comment by tasdikrahman** [comment]
Hey sorry for the delay, I missed responding to this, will finish resolving the rest of the comments.
