### ISSUE TITLE
Unmanaged SecurityGroups should also get tagged for CCM

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-aws#3481]
/kind feature

**Describe the solution you'd like**
When using an unmanaged `SecurityGroup` for `[spec.network.securityGroupOverrides.lb](http://spec.network.securitygroupoverrides.lb/)` CAPA should tag it with `kubernetes.io/cluster/<cluster-name>` so that CCM can create ELBs for `LoadBalancer` `Services` without requiring users to tag the `SecurityGroup` themselves.

**Anything else you would like to add:**
When an instance has multiple SecurityGroups attached, CCM requires 1 of them to be tagged https://github.com/kubernetes/cloud-provider-aws/blob/8d2f0fd2b1b574bde3239a344bd0a9a4f244cdb0/pkg/providers/v1/aws.go#L4479-L4485

Currently managed `SecurityGroups` are already tagged with the required `kubernetes.io/cluster` tag. **Unmanaged** Subnets are also already tagged. It would not be a stretch for CAPA to also tag the SecurityGroup.

[Originally discussed in Slack.](https://kubernetes.slack.com/archives/CD6U2V71N/p1652814232505389)

**Environment:**

- Cluster-api-provider-aws version: 
[v1.4.1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v1.4.1)
- Kubernetes version: (use `kubectl version`): 
v1.22.8
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
As per the slack thread, we would be doing this in Next milestone, is it correct @sedefsavas ?

**Comment by dlipovetsky** [comment]
I'll pair on this with @dkoshkin.

/assign

**Comment by dlipovetsky** [comment]
@dkoshkin and I looked over this today. Here's the plan, roughly:

1. As part of the unmanaged infrastructure test, start exercising ELB creation (this is not done today).
1. As part of the unmanaged infrastructure test, provide an security group override for the loadbalancer subnet (by setting the `spec.network.securityGroupOverrides["lb"]` field on the AWSCluster resource).
    * We expect the test to fail at this point, because the CCM will return an error, because it can't choose from among the multiple security groups, since none of them has the required tags.
1. Tag user-provided security groups in https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/5f5e184dd31d94573a73f7f34271bfb5a1084ec0/pkg/cloud/services/securitygroup/securitygroups.go#L122-L134.
    * We expect the test to pass after this is implemented.

**Comment by dlipovetsky** [comment]
**Important**: As we agreed to in #3854. CAPA should  apply the CCM tag on cluster create, and remove it on cluster delete.
