### ISSUE TITLE
Spot Instance Support for AWSMachinePool

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3522]
/kind feature

**Describe the solution you'd like**
I would like to use spot instances with AWSMachinePool (which is backed by AWS AutoScalingGroup)/ MachinePool to reduce the operational cost of my workload clusters.

**Anything else you would like to add:**
AWSMachinePool can be used both for CAPA-managed and EKS clusters.

**Environment:**
- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by pydctw** [comment]
@Ankitasw

**Comment by Ankitasw** [comment]
@sedefsavas shall we close this issue, or wait for final changes with node draining?

**Comment by sedefsavas** [comment]
I think we can close this one, we are already tracking the draining here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2574
