### ISSUE TITLE
Enable CSI policy wont get csi policy attached with AWSIAMRoleControlPlane

### ISSUE THREAD

**Issue by jeffwubj** [kubernetes-sigs/cluster-api-provider-aws#3527]
/kind bug

**What steps did you take and what happened:**
I am writing some codes to create CloudFormation Stack with CSI policy enabled.
I have `template.Spec.ControlPlane.EnableCSIPolicy` set to `true` before call `template.RenderCloudFormation()` them create CloudFormation thru API.

**What did you expect to happen:**
Expect CSI policy is created and `AWSIAMRoleControlPlane` will use this policy, then EBS CSI could run with granted permissions.

**Anything else you would like to add:**
`AWSIAMRoleControlPlane` and CSI Policy is created in `CloudFormation Stack` while render the content, however, `AWSIAMRoleControlPlane` does not have CSI Policy attached.

According to https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/cmd/clusterawsadm/cloudformation/bootstrap/template.go#L128-L134
and 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/cmd/clusterawsadm/cloudformation/bootstrap/csi.go#L27-L30

Does it necessarily to change 2nd code piece to
```
if t.Spec.ControlPlane.EnableCSIPolicy {
		roles = append(roles, cloudformation.Ref(AWSIAMRoleControlPlane))
	}
```
to have role attached to the policy ? or maybe some of my understanding is not correct ?
Thanks

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
I replicated the issue, thanks for reporting.

/triage accepted
/priority important-soon
