### ISSUE TITLE
Upgrade to controller-tools v0.9.2

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3531]
Upgrade to controller-tools version that includes @chrischdi's PR that allows setting listMapKey, listType at both type and field level. Needed for using Server Side Apply with AWSCluster SubnetSpec.
* https://github.com/kubernetes-sigs/controller-tools/pull/692

Note: feel free to retitle with a correct controller-tools version when it is released.

**Comment by sedefsavas** [comment]
/triage accepted
/priority important-soon

We can bump this dependency during cluster-api 1.2.0 bump as SSA will go into that release.

**Comment by sedefsavas** [comment]
Related PR in cluster api: https://github.com/kubernetes-sigs/cluster-api/pull/6542

**Comment by pydctw** [comment]
It's done and now CAPA is using controller-tools v0.10.0
