### ISSUE TITLE
EKS control plane config update would fail if there are multiple updates issued at a time

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#3553]
/kind bug

**What steps did you take and what happened:**
Try updating EKS cluster's logging config and vpc config at a time. EKS doesn't allow multiple types of updates at once and this would fail
aws eks update-cluster-config --name <cluster-name> --resources-vpc-config '{"endpointPrivateAccess":true}'  --logging '{"clusterLogging":[{"types":["authenticator"],"enabled":true}]}'

An error occurred (InvalidParameterException) when calling the UpdateClusterConfig operation: Only one type of update can be allowed.

Current CAPA logic tries to reconcile on the complete updated spec:https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/44b51752125729b220e09cdc5698dabba2f22510/pkg/cloud/services/eks/cluster.go#L432

**What did you expect to happen:**
To update configs successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
I'll take a look at this:

/assign
/lifecycle active
