### ISSUE TITLE
:book: 404 links in Getting Started

### ISSUE THREAD

**Issue by oscr** [kubernetes-sigs/cluster-api-provider-aws#3575]
Hi,

There seems to be some dead links in the Getting Started docs: https://cluster-api-aws.sigs.k8s.io/getting-started.html

For example:
https://cluster-api-aws.sigs.k8s.io/reference/glossary.html#workload-cluster
https://cluster-api-aws.sigs.k8s.io/clusterctl/commands/generate-cluster.html

Are these maybe intended to reference the CAPI book?

**Comment by Mahesh1822** [comment]
I would like to work on this issue.

**Comment by Mahesh1822** [comment]
So looked into the issue. Few doc files are being shared between this and cluster-api repository. So links which are using relative path in those docs are not working. So i think we have separate those files.

**Comment by richardcase** [comment]
I think we should discuss this at the office hours.

**Comment by oscr** [comment]
Closing since it's superseded by #3589.
