### ISSUE TITLE
Broken links under EKS Addons and Multi-tenancy pages

### ISSUE THREAD

**Issue by bhegazy** [kubernetes-sigs/cluster-api-provider-aws#3614]
/kind documentation

While following the guide under [EKS Addons](https://cluster-api-aws.sigs.k8s.io/topics/eks/addons.html) and [Multi-tenancy](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html) I found some references to broken links which leads to `Document not found (404)`

Broken Links: 
- https://cluster-api-aws.sigs.k8s.io/templates/cluster-template-eks-managedmachinepool-vpccni.yaml
- https://cluster-api-aws.sigs.k8s.io/templates/
- https://cluster-api-aws.sigs.k8s.io/templates/cluster-template.yaml
- https://cluster-api-aws.sigs.k8s.io/templates/cluster-template-eks.yaml
- https://cluster-api.sigs.k8s.io/clusterctl/commands/config-cluster.html#flavors

Seems like the links should be pointed to GitHub folders instead.

**Comment by Skarlso** [comment]
Hi, we are also tracking these things globally here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3453

Because there are actually quite a lot of broken links in the guide. :)
