### ISSUE TITLE
Improve logging with following CAPI guideline

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3626]
There is a new logging guideline in CAPI and following this guideline and making logs consistent with CAPI will improve UX.

Guideline: https://github.com/kubernetes-sigs/cluster-api/pull/6969
 
and this is the CAPI implementation: https://github.com/kubernetes-sigs/cluster-api/pull/6150

/area ux
/triage accepted
/priority important-longterm
/help wanted

**Comment by Skarlso** [comment]
Oh, awesome. Can we close the rest of logging related issues then?

**Comment by sedefsavas** [comment]
We can close them if there is nothing additional to capture with those issues. Or consolidate additional improvements we want to see here.
