### ISSUE TITLE
Unlocking independent API version updates

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3628]
Up until now, CAPA was using the same API version with core Cluster API. 
I want to open up the discussion to change that and update CAPA API versions as needed. 

Some of the providers are already using their own versioning like Openstack and MicroVM and not matching with CAPI versioning. There is no blocker in the core cluster API to block this change. Plus, this makes our innovation/breaking change pace independent of another repo.

The main reason why we need this now is [ClusterClass support for CAPA-managed clusters](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3530), which requires a breaking change. 

Another reason why we need a new API version is ClusterClass support for EKS-managed clusters. 
Following the managed Kubernetes proposal https://github.com/kubernetes-sigs/cluster-api/pull/6988, we will need to make some CRD changes, possibly breaking.

Please comment if there are any concerns regarding this. I will also bring this up during Aug 8th community meeting.

**Comment by Ankitasw** [comment]
We have changed the API version to beta2, is this issue still needed?
cc @richardcase @Skarlso

**Comment by Skarlso** [comment]
Good point. I think this is "done" now.

**Comment by richardcase** [comment]
I agree @Ankitasw & @Skarlso, this is done:

/close
