### ISSUE TITLE
GPU e2e test fails

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3660]
Since yesterday, the GPU test is failing: 
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-e2e-main&show-stale-tests=

cc @Ankitasw 

/kind failing-test

**Comment by Ankitasw** [comment]
I will take a look
/assign

**Comment by sedefsavas** [comment]
Could this be related to: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3459?

**Comment by Ankitasw** [comment]
> Could this be related to: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3459?

@sedefsavas looks like its related to this issue

**Comment by Ankitasw** [comment]
I tried updating the imagepull policy as always, but even that is not working, something else is wrong with nvidia-container-toolkit-daemonset

**Comment by Ankitasw** [comment]
Related to https://github.com/NVIDIA/gpu-operator/issues/153

**Comment by sedefsavas** [comment]
Great, wondering why it stopped working yesterday, the issue is old.

**Comment by Ankitasw** [comment]
Yes, looks like even the workaround suggested in above issue also doesn't work ☹️ I will see some other existing issues around this, or else will raise issue in gpu-operator to get support.

**Comment by Ankitasw** [comment]
Raised issue : https://github.com/NVIDIA/gpu-operator/issues/388

**Comment by Ankitasw** [comment]
We need to update the GPU operator version as they have deprecated use of some of cuda base images in the init containers, there is no way to override this base image version. Trying to test with latest GPU operator version locally, but facing some issues, will fix those and then raise a PR. Meanwhile the test would still fail .
