### ISSUE TITLE
Support autoscaling from zero

### ISSUE THREAD

**Issue by com6056** [kubernetes-sigs/cluster-api-provider-aws#3679]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Add support for autoscaling from zero defined in https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210310-opt-in-autoscaling-from-zero.md

Just implemented upstream in https://github.com/kubernetes/autoscaler/pull/4840

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
/triage accepted

I saw this and wanted to do it! :)

**Comment by Skarlso** [comment]
Ping @richardcase, @sedefsavas and @Ankitasw for second opinion. :)

**Comment by Skarlso** [comment]
Also, now I'm wondering, when and how do we usually do triage-es?

**Comment by Skarlso** [comment]
My understanding from reading this is as follows:

- Create a `Status` field in AWSMachineTemplate and reconcile it
- Based on those templates, create annotations on the machine deployment following the names outlined within
- ?
- Profit.

I'm not sure what else is required. Do we just have to add the annotations based on our spec fields and reconcile them back into the status field? Is that it? :)

**Comment by Skarlso** [comment]
And, ofc, preventing CAPA itself from creating a machine instance where it expects one to be, if these fields are defined.

**Comment by Skarlso** [comment]
Aha
```go
	infraref, found, err := unstructured.NestedStringMap(r.unstructured.Object, "spec", "template", "spec", "infrastructureRef")
```

**Comment by Skarlso** [comment]
Answer from cluster-api channel:

Yes, it's enough to define the status. 
Reference implementation can be found [here](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/pull/30).
