### ISSUE TITLE
Latest capa-ami-centos-7-1.22.13 doesn't come up due to containerd' bug

### ISSUE THREAD

**Issue by mimmus** [kubernetes-sigs/cluster-api-provider-aws#3687]
/kind bug

**What steps did you take and what happened:**
Trying to create a Kubernetes 1.22.13 cluster using CentOS7 AMI lookup fails because first control plane node never come up as it contains a bugged containerd release with this bug:
https://github.com/containerd/containerd/issues/5130

**What did you expect to happen:**
Instance should go in Ready state and installation proceed.

**Anything else you would like to add:**
Bug is confirmed by our vendor.

**Environment:**

- Cluster-api-provider-aws version: 1.1.3
- Kubernetes version: (use `kubectl version`): 1.22.13
- OS (e.g. from `/etc/os-release`): CentOS 7

**Comment by Ankitasw** [comment]
The new AMIs have been built with containerd version 1.6.6.
/close
