### ISSUE TITLE
LoadBalancer stuck in pending

### ISSUE THREAD

**Issue by unnimona** [kubernetes-sigs/cluster-api-provider-aws#3691]
i have observed external ip is not  issued instead in state of pending

helm install wordpress bitnami/wordpress --values=wordpress.yaml --namespace production --version 15.1.0
wordpress.yaml

wordpressUsername: admin
wordpressPassword: admin
wordpressEmail: contact@admin.com
wordpressFirstName: admin1
wordpressLastName: admin1
wordpressBlogName: admin1.com
ports:
  - port: 80
    targetPort: 8080
service:
  type: LoadBalancer

kubectl get svc --namespace production -w wordpress

AME        TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
wordpress   LoadBalancer   10.96.59.172   <pending>     80:31550/TCP,443:31954/TCP   44m

**Comment by Skarlso** [comment]
Try describing the loadbalancer resource to find out its external address. Or check on the AWS console.

**Comment by unnimona** [comment]
i could not find any errors
any commands to check with awscli?

**Comment by Skarlso** [comment]
Well, you can use [describe-load-balancer](https://docs.aws.amazon.com/cli/latest/reference/elb/describe-load-balancers.html) with the aws cli to get its status.

With kubectl you can only describe the service....
