### ISSUE TITLE
Deletion stuck when instance is terminated and ack in status but creds are invalid

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#3694]
/kind bug

**What steps did you take and what happened:**
- Instance gets terminated in AWS (and so reflected in .instanceState).
- Break creds.
- Delete awsMachine.
- Deletion is stuck on invalid creds.

**What did you expect to happen:**
Would it be reasonable to let reconcileDelete infer .instanceState before querying the cloud provider and let it go through https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a87fc104303fab3a7ce0004f62126ff91da09096/controllers/awsmachine_controller.go#L302
effectively letting the CR to be removed when instanceState=terminated?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
This is similar to #2606
