### ISSUE TITLE
Documentation issue: invalid combination of new api version and old configuration in the AWSClusterStaticIdentity example

### ISSUE THREAD

**Issue by mihalycsokas** [kubernetes-sigs/cluster-api-provider-aws#3717]
/kind bug

**What steps did you take and what happened:**
I created the secret then tried to create the AWSClusterStaticIdentity according to the [official documentation](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html#awsclusterstaticidentity), [in the source ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/docs/book/src/topics/multitenancy.md?plain=1#L83)but  it failed with the following error message:
~~~
error validating data: ValidationError(AWSClusterStaticIdentity.spec.secretRef): 
invalid type for io.x-k8s.cluster.infrastructure.v1beta1.AWSClusterStaticIdentity.spec.secretRef: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
~~~

**What did you expect to happen:**
I expect the documentation contains an example which works with the stated api version (v1beta1).

**Anything else you would like to add:**
I checked the corresponding [CRD ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml) and I found the expected type of the secretRef is string rather than map for the api version v1beta1.

**Environment:**

- Cluster-api-provider-aws version: v1.5.0
- Kubernetes version: (use `kubectl version`):  v1.22.1
- OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.4 LTS

**Comment by Skarlso** [comment]
Oh! Nice catch.

In the code:

```go
	SecretRef string `json:"secretRef"`
```

For v1beta1... We'll have to fix that. Thanks!

/triage accepted

**Comment by Skarlso** [comment]
Ahh. Actually, that was an intentional change. Because we are now only reading secrets from the controller namespace.

Which just means we have to update the Example in the doc. :))

**Comment by Skarlso** [comment]
bummer. :)

**Comment by mihalycsokas** [comment]
Thank you for the fast response.
