### ISSUE TITLE
Optional NAT Gateway creation for private networks

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/cluster-api-provider-aws#3721]
/kind feature

**Describe the solution you'd like**
The ability to skip the creation of a NAT Gateway when using CAPI-managed VPC but with [fully private networking](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3711).

This wouldn't need to be explicitly set and could instead be based on the presence of public subnets existing. 
Only private subnets = no NAT Gateway.

**Anything else you would like to add:**

Related / subtask of: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3711

Looks like it'd be a breaking change based on existing logic in place: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/pkg/cloud/services/network/natgateways.go#L56-L65

**Comment by richardcase** [comment]
@Skarlso

**Comment by Skarlso** [comment]
/remove-lifecycle stale

I'll get to this eventually..
