### ISSUE TITLE
Disable VPC CNI Not Cleaning Up Everything

### ISSUE THREAD

**Issue by luthermonson** [kubernetes-sigs/cluster-api-provider-aws#3729]
/kind bug

**What steps did you take and what happened:**
Disabling VPC CNI is not deleting everything that is pre-installed. Currently it only deletes the `aws-node` DaemonSet and there is still a service account, cluster role and cluster role binding left behind.
1. Disable VPC CNI
2. Install VPC CNI Helm Chart by hand

The first time you install the chart you get...
```
[29] failed to reconcile charts []string{"/packs/cni-aws-vpc-custom/cni-aws-vpc-custom-155c84d68191/charts/aws-vpc-cni-1.1.17.tgz"}: unable to install chart /packs/cni-aws-vpc-custom/cni-aws-vpc-custom-155c84d68191/charts/aws-vpc-cni-1.1.17.tgz: Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "aws-node" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cni-aws-vpc-custom-aws-vpc-cni"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system" : exit status 1
```

If you delete the `aws-node` service account it'll complain about the Cluster Role, you delete that then it complains about the the Cluster Role Binding. You delete that and you can install the helm chart successfully.

**What did you expect to happen:**
disable vpc cni would clean up everything.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I'm gonna PR a fix, just wanted to document this if anyone runs across the helm chart errors

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
I... don't think CAPA is the one creating those. That's part of the addon creation phase. We don't tag those, so we don't know what is being created and what is not.

We could add a hardcoded remove service thing, but we have no way of tracking it properly.

DeleteAddon also only deletes the IAM role that is associated with the addon. That MIGHT work. We need to test that.

I defer to others if they have any better ideas about this. :)

**Comment by luthermonson** [comment]
im like 99% sure the VPC CNI and the 4 resources (ds/sa/cr/crb) are auto installed with any EKS cluster on boot and this CAPA code was added to help people install calico or something. we are trying to use it to reinstall the vpc cni helm chart to get more features more easily.

**Comment by Skarlso** [comment]
Hmm, if you start out without specifying the cni addon, does it still install stuff for it? I think it shouldn't do anything then.

**Comment by luthermonson** [comment]
https://gyazo.com/298e01a5de488210659d9f6ed0c65f52

there is no option in the UI to not install the addon, i thought it wasn't possible to even do. can you not install it via the api? I've never tried

**Comment by Skarlso** [comment]
If you create a capa cluster without explicitly defining addons, it will not create addons and EKS shouldn't create all the stuff that it does.

**Comment by luthermonson** [comment]
so based upon what im reading... 

```
If you created a 1.18 or later cluster using the AWS Management Console, then Amazon EKS installed the plugin for you as an Amazon EKS add-on. If you created a 1.17 or earlier cluster using any tool, or you created a 1.18 or later cluster using any tool other than the AWS Management Console, then Amazon EKS installed the plugin as a self-managed add-on for you.
```

you're right but that's not what im seeing in reality as we tested building with no addons and we still got the aws-node ds... im kinda confused and looking further

**Comment by luthermonson** [comment]
fyi for most of this it's coming from this: https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni#adopting-the-existing-aws-node-resources-in-an-eks-cluster

**Comment by luthermonson** [comment]
after some considerable testing i can't seem to get it to not install the vpc cni. every time i make a managed cluster via capa it is kubectl applying a manifest that looks like this one: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml

i find the ds/sa/crd/cr/crb when doing something as basic as this:
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-dev
  namespace: default
spec:
  region: us-east-2
  sshKeyName: devcluster
  version: v1.23.7
```
and this doc https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/19b6440b86aba5803d82f805b0b8fd49a372a662/controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go#L167

is sort of foreshadowing this... im going to stick to my suggestion that we add the deleting of the crd/sa/cr/crb if disableVPCCNI is true. In addition if you install the vpc cni helm chart it will reinstall all these things and capa will reconcile again and delete it so I'd like to propse we also check if the managed-by:Helm annotation is not there before we run the deletes.

**Comment by Skarlso** [comment]
I'm sort of on the fence with this one. The problem here is that we have no idea what to delete. We can hardcode it, but there is no guarantee that will be enough / will work.

We can add that, but I fear that it just adds confusion.

Ah, also, I just thought about another problem. CAPA doesn't make those. This means if you remove CNI from your cluster, and you decide to include it after a while, it won't work because the cluster role and binding and the service account will be missing. To put it differently, if you disable CNI you won't be able to enable it again. And this can disrupt some flows, like testing out a CNI plugin but then reverting back to aws-cni.

**Comment by luthermonson** [comment]
```I'm sort of on the fence with this one. The problem here is that we have no idea what to delete. We can hardcode it, but there is no guarantee that will be enough / will work.```

because there's no disable vpc cni in eks to do it for you and all docs point you to deleting these pieces by hand and installing your own cni... that's currently the best effort anyone can do so we might as well codify it to make people's lives easier.

we believe know exactly what to delete, it's right there in the manifest i linked and the helm chart docs shows you the pieces to "adopt", the list of these things are public as far as I'm concerned. it's all documented that the expectation is the vpc cni is burnt to the ground when you set disableVPCCNI to true. i feel the opposite than you on the confusion, not everything is cleaned up when that's your expectations. Read here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/93897be636031fac812765d95a018fe61dbd689f/docs/book/src/topics/eks/pod-networking.md#using-an-alternative-cni

i dont think im on the fence any more on this, we should delete the sa/crd/cr/crb in addition to the ds. i'm going to make a PR and we can continue talking about it there after we've seen the code.

**Comment by Skarlso** [comment]
Sure, and what about the second concern of not being able to enable the addon any longer?

**Comment by luthermonson** [comment]
disableVPCCNI and the addon named "vpc-cni" are mutually exclusive https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/06da7fc1fb1081308d2bc3edbd4e0403e96421ae/controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go#L368-L379

you would have to turn disableVPCCNI to false and include the addon in the list and the reconciler will add it to the eks cluster. the addon installer should take care of itself and add the CR/CRBs again... testing that theory, booting another test cluster right now.

weirdly enough if you boot an eks cluster from capa we get the defualt vpc cni, coredns and kube-proxy addons and none of them are installable via the UI... it's entirely possible that if you fail to specify addons when you create the cluster you can never modify them later. i dont have time to look at that right now but food for thought and maybe I could write that up in another issue one day.

**Comment by luthermonson** [comment]
confirmed... if you set disableVPCCNI to true it will delete everything. you edit the managedcontrolplane and set to false it will error out in ReconcileCNI because aws-node does not exist and it can't continue. edit managedcontrolplane and add the vpc-cni addon. it will reconcile again and installing the addon and all pieces are there (ds/sa/cr/crb) and it installs successfully and ReconcileCNI will continue on happily.coming to full reconciliation and a happy controller.

**Comment by luthermonson** [comment]
> Hmm, if you start out without specifying the cni addon, does it still install stuff for it? I think it shouldn't do anything then.

im testing this scenario... im pretty sure if you make a cluster with no addons and then try to add them after it will add defaults to coredns, vpc-cni and kube-proxy and you'll not be able to add them through the addons api in managedcontrolplane without first deleting all the pre-installed pieces yourself by hand. this could be fixed by adding safe deletes to those three addons if they weren't set so a user would get a proper installation if they go back and add it.

**Comment by luthermonson** [comment]
ok so the above.... is wrong but i dont know why because i got this screen shot from yesterday

<img width="1345" alt="image (24)" src="https://user-images.githubusercontent.com/1616909/190013446-08fcf113-f5fe-456d-86d3-b3c6a7b3d922.png">

but today it worked fine. im super confused... i did an addon from the UI and the capa api and no errors or problems after booting a managed cluster with no addons.

**Comment by Skarlso** [comment]
Cool, thanks for going the extra mile to figure this out! :)
