### ISSUE TITLE
Add Bazel BUILD verify script during CI

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#376]
/kind feature

**Describe the solution you'd like**:
Currently, we check in all BUILD files, which might get out of sync if they don't get updated before merging a PR or if they are modified manually. The upstream Kubernetes repository, uses this https://github.com/kubernetes/kubernetes/blob/master/hack/verify-bazel.sh to make sure Bazel is always in a correct state.

Thanks to @liztio and @timothysc for pointing this out.

**Comment by chuckha** [comment]
This should be part of CI so that PRs can't merge if BUILD files are out of sync

/priority important-longterm
