### ISSUE TITLE
Resources should define a `.status.observedGeneration` field, and controllers should update its value

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#3778]
/kind feature

**Describe the solution you'd like**
I update the `.spec` of a custom resource whose `.status` is written by a CAPA controller. For example, the `AWSManagedControlPlane` resource.

I expect the controller to set the `.status.observedGeneration` field when the controller reconciles the resource.

I need to compare `.status.observedGeneration` with `.metadata.generation` to know whether the `.status` reflects the current, or an outdated `.spec`.

**Anything else you would like to add:**
The `EKSConfig` resource [defines](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/ad99a1d982c9e938ac22905926a5f7c82e1603d6/bootstrap/eks/api/v1beta2/eksconfig_types.go#L81-L83) a `status.observedGeneration`, and the EKSConfig controller [sets](https://github.com/kubernetes-sigs/cluster-api-provider-aws//blob/ad99a1d982c9e938ac22905926a5f7c82e1603d6/bootstrap/eks/controllers/eksconfig_controller.go#L131) the field. No other CAPA resource does.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
/triage accepted

Under what circumstances are these fields checked? Before applying an update, for example?

**Comment by Skarlso** [comment]
Gotcha, thanks. That's a good example. :)

**Comment by dlipovetsky** [comment]
Counter-argument to my proposal: Instead of defining `.status.observedGeneration` field on the resource, each Condition should define an `observedGeneration` field. This field is part of the [Conditions schema](https://github.com/kubernetes/kubernetes/pull/90454) _recommended_ by Kubernetes core.

However, Cluster API core defines its own Conditions schema. CAPA, and other infrastructure providers, re-use the Cluster API core Conditions schema. The Cluster API Conditions schema does not have the `observedGeneration` field, as explained this [CAEP PR comment](https://github.com/kubernetes-sigs/cluster-api/pull/3017/files#r424582627).
