### ISSUE TITLE
Help: how is cluster created on EC2 instances

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-sigs/cluster-api-provider-aws#3806]
I can find how cluster is created with EKS, but not for EC2

In AWSClusterReconciler.Reconcile I can see AWSCluster being patched, but not sure how k8s cluster is created base on it.

Appreciate if anyone can help

**Comment by Skarlso** [comment]
Hello. :)

Look for unmanaged clusters. I will write a bit more once I wake up. 

It's basically using kubeadm to set things up. There are some sample yamls in the e2e folder that you can take a look at. Look for anything that doesn't have `managed` in the name.

**Comment by hzxuzhonghu** [comment]
Thanks for your clarification, will find that

**Comment by hzxuzhonghu** [comment]
Nope， thanks
