### ISSUE TITLE
EC2 ENIs are not being tagged

### ISSUE THREAD

**Issue by steve-fraser** [kubernetes-sigs/cluster-api-provider-aws#3839]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Create a MachineDeplyoment with the following AWSMachineTemplate

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: example
spec:
  template:
    spec:
      additionalTags:
        creator: test@test.com
      instanceType: t3.medium
      sshKeyName: ""
**What did you expect to happen:**

I expect the ENIs to be tagged with the additionalTags value

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v1.5.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
/triage accept
/assign

This is kind of important so resources can be created within an environment that applies control policies in the AWS account.

**Comment by Skarlso** [comment]
AARGH. This is almost impossible to do nicely. :(

ENIs are created outside of CAPA by all sorts of things like EKS, the LB, EC2 instances, the VPC... etc.

We would have to list all resources, describe each of them, go through all the enis, and tag them accordingly.

There is no single interface for these things. And then we get into the problem of managed, unmanaged ENIs and what to tag and what not to tag. And now I remember that `eksctl` had similar problems. Let me rummage around the issues.

**Comment by Skarlso** [comment]
I could maybe add one thing. ENIs created by aws-cni.
