### ISSUE TITLE
[e2e] EKS e2e tests need to be stabilised

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3873]
/kind bug
/area deflake
/area testing
/priority critical-urgent
/triage accepted

**What steps did you take and what happened:**

The periodic EKS e2e tests have been very flakey recently (see [testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-eks-e2e-main)). This is impacting our confidence in doing releases and that we aren't regressing functionality.

**What did you expect to happen:**

As a project we need our e2e tests to be less flakey.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
I feel testgrid looks good now, do we need to do any more changes here?

**Comment by Skarlso** [comment]
It looks okay now... Maybe this is okay. :D

**Comment by richardcase** [comment]
Ok, lets close 👍 

/close
