### ISSUE TITLE
SubnetSpec 'ID' must not be required field

### ISSUE THREAD

**Issue by joeunlog** [kubernetes-sigs/cluster-api-provider-aws#3883]
/kind feature

**Describe the solution you'd like**
SubnetSpec 'ID' must not be required field

**Anything else you would like to add:**
I tested creating aws managed control plane with configuring specific subnet cidr.
When I tested it 21 days ago, it worked fine.
And today, I tested same thing but it require subnet's ID, so test was failed.
I found pull request about this, and realize that subnet id is no longer omitempty.
[pull/3748](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3748)
Subnet id must be required only when using '[Bring Your Own AWS Infrastructure](https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html#bring-your-own-aws-infrastructure)'

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
This was introduced as part of new [SSA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3530) feature, which cannot be changed back. Please refer [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3748/files#r980991455).
