### ISSUE TITLE
Avoid downtime when migrating HA clusters from in-tree ccm to out-of-tree ccm

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes-sigs/cluster-api-provider-aws#3885]
**What did you expect to happen:**
To avoid controller-manager downtime, the [Leader Migration](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/#background) provides a mechanism by community in which HA clusters can safely migrate "cloud-specific" controllers between the old versioned kube-controller-manager and the new versioned cloud-controller-manager while upgrading the replicated control plane. To support Leader Migration, changes need to be made both before and after upgrade in Kubernetes clusters. 
We need also to check controller-manager downtime of HA clusters in our e2e test.

**Comment by dlipovetsky** [comment]
Related to #2941 and #964

**Comment by wangyuan0916** [comment]
[This documentation](https://cloud-provider-aws.sigs.k8s.io/getting_started/#upgrading-an-existing-cluster) tells us how to migrate existing clusters from in-tree CPI to out-of-tree CPI.  There're two scenarios.
1. HA clusters: Leader Migration should be enabled to support migration from the controllers in the kube controller manager to their counterparts in the cloud controller manager. That is, no controller should be running as a leader simultaneously in both controller managers. 
2. No HA clusters: Kube-controller-manager should be shut down and flags in control-plane changed then controller-manager started. In this way, downtime exists.
