### ISSUE TITLE
Make `clusterawsadm` installable via homebrew

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3908]
/kind feature
/area clusterawsadm
/priority important-longterm
/triage accepted
/help

**Describe the solution you'd like**

I would like to be able to use Homebrew to install clusterawsadm:

```shell
brew install clusterawsadm
```

This should support both MacOS and Linux.

**Anything else you would like to add:**

Its possible to install clusterctl via homebrew.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/117383

**Comment by Ankitasw** [comment]
/close

As PR is merged.
