### ISSUE TITLE
Having machinepool annotation to set externally managed request to be added to 1.x.x release

### ISSUE THREAD

**Issue by tasdikrahman** [kubernetes-sigs/cluster-api-provider-aws#3918]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

For making use of CAPI's https://github.com/kubernetes-sigs/cluster-api/pull/7107, of machinepool annotation for externally managed autoscaler, we were wondering if there are plans of adding the CAPA PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683/, in one of the releases for 1.x.x, as the same has been added for all the v2.x.x releases. Thanks for the help. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
Hi @tasdikrahman  This is already present in v2.0.x. Wouldn't it be possible for you to add upgrade to v2.0.2?

**Comment by tasdikrahman** [comment]
Hello @Ankitasw , thanks for the update, was wondering if I could open up a PR to backport this to CAPA 1.x.x.

**Comment by tasdikrahman** [comment]
Hello @Ankitasw , I added this PR here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4171 to address this issue. Thank you

**Comment by tasdikrahman** [comment]
closing this as we have backported this to https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v1.5.5
