### ISSUE TITLE
CAPA is modifiying tags of user owned VPCs, resulting into reconilcation loops

### ISSUE THREAD

**Issue by project0** [kubernetes-sigs/cluster-api-provider-aws#3919]
/kind bug

**What steps did you take and what happened:**
Creating a new cluster with custom vpc (and ipv6 enabled).
We deploy our VPC via terraform and it should be used my multiple clusters, each cluster has its own dedicated subnets. 
However, we see that capa is modifying existing tags (and even removes some) from the several vpc resources, even if its not meant to be managed at all by capa like the `Egress Only Internet Gateway`. 

Even worse, it also ends up in reconciliation loops as it reads (preview tags) and updates the tags all the time.

**What did you expect to happen:**
Do not touch resources what are not part of its business.

**Anything else you would like to add:**

![Screenshot 2022-12-06 at 16-07-59 run-niZ3DRMr54ndv1wo Runs networking-aws-eu-west-2 Traefik Terraform Cloud](https://user-images.githubusercontent.com/2286479/205949142-19df51ff-95ea-4ac4-8014-833c167c6990.png)

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`):  1.24.7
- OS (e.g. from `/etc/os-release`):

**Comment by project0** [comment]
I would also prefer cluster api would just consume provided VPC and not modifying it. There are good reasons some parts are managed outside of the cluster (like shared vpc for example). I dont see why it needs for example to know about the internet gateway or why it has to update tags at all.

**Comment by Ankitasw** [comment]
Related to #3692

**Comment by project0** [comment]
I dont know how can i fix this, it keeps in a reconciliation loop and the it looks like it removes and adds this property: `egressOnlyInternetGatewayId: eigw-xxx`

**Comment by project0** [comment]
It also keeps updating `sigs.k8s.io/cluster-api-provider-aws/cluster/clustername` tag on the egress only igw even if i set it manually to shared.

**Comment by Skarlso** [comment]
We will "fix" this by removing messing with the tags completely on unmanaged infra. :)

**Comment by Ankitasw** [comment]
Subset of #3948

**Comment by project0** [comment]
@Skarlso sounds good to me, i do not see a reason why CAPA should modify tags/resources for not owned resources at all.

**Comment by Skarlso** [comment]
@project0 eh, it's had its reasons. For example, ease of usage for once. It was a convenience for users not having to deal with all the messy tags that are required to be present. I think this will increase the burden on users, but such is life. 🤷
