### ISSUE TITLE
Misformatted events emitted: FailedAuthorizeSecurityGroupIngressRules and SuccessfulAuthorizeSecurityGroupIngressRules

### ISSUE THREAD

**Issue by erwinvaneyk** [kubernetes-sigs/cluster-api-provider-aws#3942]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
There is a minor issue with the message the following events create:
* SuccessfulAuthorizeSecurityGroupIngressRules
* FailedAuthorizeSecurityGroupIngressRules

They contain a `%v` which marshals the entire IngressRules object into the message. Making them unreadable:

```
2m53s       Normal    SuccessfulAuthorizeSecurityGroupIngressRules   awscluster/my-cluster                                  Authorized security group ingress rules [{bgp (calico) tcp 179 179 [] [sg-00000000000 sg-00000000000]} {IP-in-IP (calico) 4 -1 65535 [] [sg-00000000000 sg-00000000000]} {calico typha (pf9) tcp 5473 5473 [] [sg-00000000000 sg-00000000000]} {Kubernetes API tcp 6443 6443 [] [sg-00000000000 sg-00000000000 sg-00000000000]} {etcd tcp 2379 2379 [] [sg-00000000000]} {etcd peer tcp 2380 2380 [] [sg-00000000000]}] for SecurityGroup "sg-00000000000"
```
(redacted the identifiers)

**What did you expect to happen:**
Human-readable event messages

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v1.5.0 (issue present in main too)
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
/triage accepted

Thanks for spotting this. :)

**Comment by Skarlso** [comment]
I see what the problem is. The `String` method `IngressRule` has a pointer receiver and that's supposed to be a Value receiver. That's why `String()` isn't called in the formatter. :)
