### ISSUE TITLE
Proposal: Tagging of unmanaged network items should not be done by CAPA

### ISSUE THREAD

**Issue by Skarlso** [kubernetes-sigs/cluster-api-provider-aws#3948]
/kind feature

**Describe the solution you'd like**

At the moment, CAPA manages tags on unmanaged network items. This should be avoided. They cause several issues when they aren't removed, and they cause several problems when they are added to the wrong subnet, or many cases when security groups can't be deleted, etc.

Cleaning them up is a pain, and we don't want to end up causing a potential disaster when we delete the wrong tag.

I propose that we shouldn't manage tags on unmanaged items. This is partially already being done, but some tags are added nevertheless. These should be documented and left up to the user to do.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
Following issues has been reported for this problem:
#3947 
#3919 
#3692

**Comment by Skarlso** [comment]
Ah thanks for tagging them! <3

**Comment by Ankitasw** [comment]
> I propose that we shouldn't manage tags on unmanaged items. This is partially already being done, but some tags are added nevertheless. These should be documented and left up to the user to do.

I think this is what the intent was initially when we started supporting [BYO infra](https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html#tagging-aws-resources). 

> When consuming existing AWS infrastructure, the Cluster API AWS provider does not require any tags to be present. The absence of the tags on an AWS resource indicates to Cluster API that it should not modify the resource or attempt to manage the lifecycle of the resource.

So I am +1 for this proposal.
