### ISSUE TITLE
test

### ISSUE THREAD

**Issue by geosaja** [kubernetes-sigs/cluster-api-provider-aws#396]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
Closing since this issue does not contain anything other than template content. Please update and re-open if your issue still persists.

/close
