### ISSUE TITLE
Clusterctl move stucks after migration at OIDC provider

### ISSUE THREAD

**Issue by project0** [kubernetes-sigs/cluster-api-provider-aws#3972]
/kind bug

**What steps did you take and what happened:**

- create two management cluster with CAPI/CAPA
- create a workload cluster with `AWSManagedControlPlane (v1beta2)`
- use clusterctl move to migrate workload cluster

When using `clusterctl move` on clusters with enabled `associateOIDCProvider: true` the OIDC provider cannot be adopted anymore. 
I had to delete the identity provider manually and let the capa controller re-create it to fix it.

```
I0110 16:28:19.289830       1 logger.go:68] "Reconciling EKS OIDC Provider" cluster-name=0xc0007c3300
E0110 16:28:20.396962       1 controller.go:326] "Reconciler error" err=<
	failed to reconcile control plane for AWSManagedControlPlane default/t00-euc1-eks-rh-cp: failed reconciling OIDC provider for cluster: failed to create OIDC provider: error creating provider: EntityAlreadyExists: Provider with url https://oidc.eks.eu-central-1.amazonaws.com/id/C5E4BEAA7CA5AF038A8CA37B42560F80 already exists.
		status code: 409, request id: 937d1a9b-a8a7-47b3-a006-fff3f010e550
 > controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" aWSManagedControlPlane="default/t00-euc1-eks-rh-cp" namespace="default" name="t00-euc1-eks-rh-cp" reconcileID=afd5887d-2714-4f71-a292-86e4da782ceb
```

**What did you expect to happen:**
No error after migrating clusters, adopting the previous created OIDC without human intervention

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`): not relevant

**Comment by Skarlso** [comment]
There was an issue dealing with this already, but I can't find it right now. I will dig it up later. I don't remember what the resolution to that was. I think there was also a PR involved in that.
