### ISSUE TITLE
Support for IMDSv2

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#3974]
/kind feature

**Describe the solution you'd like**
E.g. API know to require IMDSv2. and pass through InstanceMetadataOptionsRequest.HttpTokens

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-8

http://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by JoelSpeed** [comment]
This looks like it could be related to/duplicate https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3744

**Comment by enxebre** [comment]
closing in favour of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3744
