### ISSUE TITLE
CAPA should autodiscover unmanaged LB subnets to enable multi-AZ control planes

### ISSUE THREAD

**Issue by thefirstofthe300** [kubernetes-sigs/cluster-api-provider-aws#3980]
/kind feature

CAPA allows users to BYO infrastructure, including ELBs. The algorithm used to select which AZ should be used by control planes appears to be as follows:

1. Fetch the subnet information from the AWSCluster spec and filter it for all of the private subnets
2. Compare the AZs in which the API server ELB lives to the subnet AZs
3. Every match is then marked in the AWSCluster status as a failureDomain capable of housing a control plane, i.e.
```
failureDomain:
    az-name:
        controlPlane: true
```

The above is deduced from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c0bd2df52fb82e02bd293e3d705b4f363ff20941/controllers/awscluster_controller.go#L343-L355

The subnet spec in the AWSClusterSpec allows the user to set the `isPublic` and `availabilityZone` fields; however, there is no place to specify the AZs in which the ELB lives. Instead, that is autodiscovered.

The algorithm for determining what AZs in which the ELB lives is as follows:

1. Fetch the spec from the NetworkSpec.APIServerELB
2. Use the named stored in the spec to describe the ELB
3. Check if the ELB is managed by CAPA
    1. If the ELB is managed, discover the AZs used by the ELB and copy that information into NetworkStatus
    2. If the ELB is unmanaged, continue

The above was ascertained from the following places:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7549bed37fb8c59c51c7f014a541df11e4585bc1/pkg/cloud/services/elb/loadbalancer.go#L402-L465
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7549bed37fb8c59c51c7f014a541df11e4585bc1/pkg/cloud/services/elb/loadbalancer.go#L446-L448

In essence, I think there's a bit of a bug here. My naive reading of the code seems to indicate that [these three lines](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7549bed37fb8c59c51c7f014a541df11e4585bc1/pkg/cloud/services/elb/loadbalancer.go#L446-L448) should live on line 463. Since the NetworkStatus block already handles an empty array just fine, the only possible states for the APIServerELB's AZ array should be containing a list of AZs or empty so I don't see this change introducing any bugs. In fact, it almost looks like this was the actual intended behavior.

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): v1.25.4

**Comment by AverageMarcus** [comment]
Just to clarify, you can specify where the ELB ends up, it's just fairly limited right now. See https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3979

/ok-to-test

**Comment by thefirstofthe300** [comment]
Correct. You can specify where the ELB ends up and get failure domains properly set if you haven't brought your own load balancer. 

This feature/bug is about BYO infrastructure. CAPA doesn't detect the AZs of the LB. If you add the tag to tell CAPA that the LB is managed by CAPA, the AZs are populated properly, but you also have the problem of two separate tools are likely trying to manage the same LB as in my case (Terraform and CAPA).
