### ISSUE TITLE
GC_WORKLOAD variable is missing in e2e conf to support gc test cases

### ISSUE THREAD

**Issue by wyike** [kubernetes-sigs/cluster-api-provider-aws#3998]
/kind bug

**What steps did you take and what happened:**
gc testcases will apply some workloads for the testing. It will read the yaml from GC_WORKLOAD variable. We should provide the variables in e2e conf, otherwise the testcases would fail with exception.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dlipovetsky** [comment]
Should also go to release-1.5 branch.

/kind backport

**Comment by wyike** [comment]
Haven't backport to release-1.5 branch. I will do in following up PR.
