### ISSUE TITLE
[cluster actuator] Reconcile Internet Gateway

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#40]
The MVP requires that the VPC created be configured with an Internet Gateway. 

Outstanding question: Should this step be skipped if the user provides an existing VPC through the ProviderConfig?

**Comment by vincepri** [comment]
Closing see https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/47#issuecomment-422564463
