### ISSUE TITLE
 Updating exising AWS cluster with AdditonalTags, the tags are not applied to VPC object

### ISSUE THREAD

**Issue by wyike** [kubernetes-sigs/cluster-api-provider-aws#4031]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1.I have an existing awscluster
2.I edit the awscluster and add additionalTags under the spec.
3. The tags are applied to all other aws resources including subnets, lb, nat gateway etc. while not for VPC.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/vpc.go#L47-L80 CAPA doesn't have tags reconcile for existing managed VPC.

**What did you expect to happen:**
I expect VPC can have  those additonalTags reflected after awscluster updated

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
/triage accepted
/priority important-soon

I think #4030 should solve this.

**Comment by Skarlso** [comment]
Yep, this is the issue I was waiting for to be created for that PR, hehe. :) Thanks @wyike.
