### ISSUE TITLE
in multitenancy occasion,AWSClusterStaticIdentity should be in tenant-owned namespace rather than manager namespaces

### ISSUE THREAD

**Issue by worstkid92** [kubernetes-sigs/cluster-api-provider-aws#4034]
/kind feature

buildAWSClusterStaticIdentity

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
currently,function buildAWSClusterStaticIdentity
`func buildAWSClusterStaticIdentity(ctx context.Context, identityObjectKey client.ObjectKey, k8sClient client.Client, clusterScoper cloud.ClusterScoper) (*identity.AWSStaticPrincipalTypeProvider, error) {
	staticPrincipal := &infrav1.AWSClusterStaticIdentity{}
	err := k8sClient.Get(ctx, identityObjectKey, staticPrincipal)
	if err != nil {
		return nil, err
	}
	secret := &corev1.Secret{}
	err = k8sClient.Get(ctx, client.ObjectKey{Name: staticPrincipal.Spec.SecretRef, Namespace: system.GetManagerNamespace()}, secret)
	if err != nil {
		return nil, err
	}
`
In this code,namespace is system.GetManagerNamespace().
also.
`type AWSClusterIdentitySpec struct {
    AllowedNamespaces *AllowedNamespaces `json:"allowedNamespaces"`
}
`
this struct has already defined namespaces but it seems this field is not used.
I think it is better in  multitenancy occasions,each tenant owns a namespace,and our controller has access to this tenant-owned namespace to find secret and some other resources. We use namespaces to do logical separation for tenant's rersource. The old act is an secret 'ultra vires' actually ,I think.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dlipovetsky** [comment]
@worstkid92 I don't completely underestand the request here. Before going into the implementation, could you describe the feature from the point of view of an end user?

/triage needs-information
