### ISSUE TITLE
Unable to use AWSClusterRoleIdentity for Cross Account Cluster Creation

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes-sigs/cluster-api-provider-aws#4046]
/kind bug

**What steps did you take and what happened:**
I'm attempting to create a managed EKS cluster from CAPA running in one account into another account.  I'm attempting to use ACRI as per https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html?highlight=AWSClu#awsclusterroleidentity .  However the existing management IAM policy for the CAPA controller does not have an sts:AssumeRole permission so it is unable to assume the role created in the other account which contains a trust relationship to allow the source role to assume it.

**What did you expect to happen:**
Ability to create EKS clusters cross account using ACRI

**Anything else you would like to add:**
Would assume this permission should be available here https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/93100739e18e8f28e8d1b7836d2a2331bc9751e2/cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go. However, no where in here is sts:AssumeRole.

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@ryan-dyer-sp we already have this defined in our [doc](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html?highlight=assume%20role#necessary-permissions-for-assuming-a-role) as a requisite step to be done.
Since this is applicable only for above mentioned use-case, please consider doing this manual step.

**Comment by ryan-dyer-sp** [comment]
@Ankitasw You have a tool which will create the role/policies necessary for CAPI to do all the things, except this one thing which is documented.  I dont understand the rationale behind documenting it and not adding the policy to the tool.

**Comment by ryan-dyer-sp** [comment]
Understood.  IMO adding that permission isnt a security issue as any role to be assumed would have to also allow/trust the assumer role.

If the concern is supplying that as a permission, is it possible to add it behind a flag? IDK the code well enough to answer this.  If it is and this is desired instead of making it a default permission, can someone point me to an example and I'll update my PR accordingly.

**Comment by Skarlso** [comment]
It's a security decision. Cross account access MUST be a choice. The tool will not do this.

**Comment by ryan-dyer-sp** [comment]
@Skarlso So does this mean if its put behind a flag, its okay?  Or that under no circumstances will the maintainers allow AssumeRole ?  When i proposed this PR and issue to @richardcase in slack he didnt seem to have an issue with it.

I'm perfectly happy submitting a PR which allows the policy behind a flag.  What would you suggest as the flag name? Should it just be a generic iam policy addition or something more targetted to this use case as proposed in my original PR?

**Comment by Skarlso** [comment]
Oh, I wasn't against it, I just said why it didn't do that to begin with. :D

**Comment by ryan-dyer-sp** [comment]
I have created new PR which enables the policy via optional parameter.  As its my first PR, please provide any guidance for things that may need to be additionally done (documentation updates, etc.).  Thanks!

**Comment by richardcase** [comment]
I don't have a strong opinion personally on this being a permission a user has to enable. But we do have a precedent in this area with things like IAM roles per cluster / adding additional iam roles. And as @Skarlso @Ankitasw think it should be optional, then I would defer to them.  And @Skarlso makes a good point in that this was a conscious decision not to include the permission by default.
