### ISSUE TITLE
controller shouldn't manipulate default SG when using Shared VPC

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#4075]
/kind bug

**What steps did you take and what happened:**
Running with externally managed infrastructure and trying to setup a shared VPC, the machine controller fails we access denied to the VPC default security group via `GetInstanceSecurityGroups`.
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html

**What did you expect to happen:**
Relax management of VPC default SG.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
/triage accepted

@enxebre this is still a problem, right?
