### ISSUE TITLE
Add version subcommands to clusterawsadm and clusterctl binaries

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#409]
/kind feature

**Describe the solution you'd like**
Currently there is no way to know if the versions of clusterctl or clusterawsadm used are what you expect them to be (or to compare the version installed to the versions released). There should be a version subcommand for each binary to output the version.

**Comment by vincepri** [comment]
What about using something like the git tag or commit (short version) as an exported variable? Not sure if that can be done through bazel, but that'd be neat.
