### ISSUE TITLE
[E2E] EventBridge feature to be enabled in one of the tests

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#4090]
/kind support
/kind failing-test
/kind flake 

**What steps did you take and what happened:**
In few of the test runs, EventBridge fails to create the rules in the eventbus. Refer [here](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-clusterclass/1627529141182009344/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-5dc575594d-dt72t/manager.log) for details. 
This brings us to the conclusion that EventBridge feature should be enabled only for one of the tests, such that all the tests wont be affected.

**What did you expect to happen:**
EventBridge feature is disabled in E2E tests. As part of this issue, we should reimagine a new/existing E2E to test EventBridge functionality such that other tests won't get affected by it.

**Comment by Ankitasw** [comment]
@richardcase I think enabling the feature gate for only one of the tests is not possible as the feature gates are initialized in the main.go itself.

**Comment by richardcase** [comment]
@Ankitasw - we'd have to do it as a separate test suite with its own e2e config. Seems like a bit of pain thinking about it ;) We can just fix the issue and globally enable.....wdyt?

**Comment by Ankitasw** [comment]
Sounds good to me 😅
