### ISSUE TITLE
Feature Request: clusterawsadm resource clean

### ISSUE THREAD

**Issue by luthermonson** [kubernetes-sigs/cluster-api-provider-aws#4108]
/kind feature

As someone who has now cleaned up a lot after CAPA lately I'd like to propose a set of cleanup tooling to the cli. Due to many catastrophic failures during development, most of which prompted me to wipe the management cluster, I have started over and had to clean sweep my AWS account due to account limitations (eips/vpcs) and cost.

Leaving some notes for things I do know from cleaning up from a working cluster all the way down to a clean account...

1) terminate the instantes
2) delete the load balancer
3) clean up the nat gateways
4) release eips
5) delete everything inside the s3 bucket
6) delete the s3 bucket
7) delete the vpc

I propose we add a `clusterawsadm resource clean` which works like list but will work to complete removal of all resources listed and only exit when this has been completed so you can set and forget your cleanup and speedup your dev lifecycle. This will also tie in nicely with `clusterawsadm bootstrap iam delete-cloudformation-stack`.

**Comment by hackeramitkumar** [comment]
You are right. I have also felt lot of trouble regarding it. It will be good if we are implementing it.
