### ISSUE TITLE
Cleanup: Move off k8s.io/utils/pointer package

### ISSUE THREAD

**Issue by luthermonson** [kubernetes-sigs/cluster-api-provider-aws#4119]
/kind cleanup

k8s.io/utils/pointer is a fine enough package, but we have tons of references to the now deprecated `<type>Ptr`. Since we should update these anyways at some point I would like to suggest we just move to entirely using the AWS package `github.com/aws/aws-sdk-go/aws` which does the same thing since we already use it for all the AWS SDK calls. This is a pretty easy PR which I will do, just looking for buy in from maintainers.

**Comment by Ankitasw** [comment]
/close

in favor of #4121
