### ISSUE TITLE
Update deployed k8s version to v1.13

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#412]
/kind feature
/priority important-soon

**Describe the solution you'd like**

Currently we are deploying v1.12 clusters, for kubeadm HA support we will need a min. version of v1.13.

Fix for this will require the following:

- Update the image building tooling for any v1.13 related changes
- Build new images for v1.13 and update the documentation for the newly built images
- Update kubeadm configs to use the v1beta1 structs rather than v1alpha3 structs
- Update examples to reference 1.13 instead of 1.12

**Comment by chuckha** [comment]
/remove-lifecycle active

The rest of this is blocked on 1.13 being released.
