### ISSUE TITLE
AWSManagedMachinePool does not work in combination with cluster-autoscaler

### ISSUE THREAD

**Issue by ionutbalutoiu** [kubernetes-sigs/cluster-api-provider-aws#4134]
/kind bug

**What steps did you take and what happened:**

The use case is similar with the one described in issue https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2022. The only differences being:
* Usage of `AWSManagedMachinePool` resource instead of `AWSMachinePool` resource.
* The `MachinePool` resource is annotated with `cluster.x-k8s.io/replicas-managed-by: "external-autoscaler"` as described [here](https://cluster-api-aws.sigs.k8s.io/topics/machinepools.html#autoscaling) (because I'm using `AWS` autoscaler provider).

**What did you expect to happen:**

cluster-autoscaler should manage the `DesiredInstances` of the autoscaling group and the `AWSManagedMachinePool` controller should ignore changes to the `replicas` and `DesiredInstances`.

The `AWSManagedMachinePool` controller should respect the annotation for externally managed autoscaler.

**Anything else you would like to add:**

This issue is already fixed with `AWSMachinePool` controller via PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683. 

All we need to do is to make sure that the `AWSManagedMachinePool` controller respects the annotation for externally managed autoscaler.
At the moment, there is no knowledge of the new annotation in the `AWSManagedMachinePool` controller.

In my scenario (using `v2.0.2` release), the autoscaler would adjust the `DesiredInstances` of the autoscaling group, and this  code path would cause the `AWSManagedMachinePool` controller to override those changes:

 * https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28bc9b8756d6d7f73038604038ddb3ccf4b22396/exp/controllers/awsmanagedmachinepool_controller.go#L237
 * https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28bc9b8756d6d7f73038604038ddb3ccf4b22396/pkg/cloud/services/eks/eks.go#L108
 * https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28bc9b8756d6d7f73038604038ddb3ccf4b22396/pkg/cloud/services/eks/nodegroup.go#L542
 * https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28bc9b8756d6d7f73038604038ddb3ccf4b22396/pkg/cloud/services/eks/nodegroup.go#L469-L473
 
In my opinion, all we need to do, is to incorporate this change from the `AWSMachinePool` controller:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28bc9b8756d6d7f73038604038ddb3ccf4b22396/exp/controllers/awsmachinepool_controller.go#L277-L288

That would allow the `AWSManagedMachinePool` controller to respect the annotation for externally managed autoscaler.

**Environment:**

- Cluster-api-provider-aws version: `v2.0.2`
- Kubernetes version: (use `kubectl version`): `v1.24.8`
- OS (e.g. from `/etc/os-release`): [Amazon EKS optimized Amazon Linux](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) 1.24

**Comment by Skarlso** [comment]
Hi @ionutbalutoiu.

Do you happened to have a test setup available for me to play with? ( By that I mean some cluster specs :) ).

**Comment by Skarlso** [comment]
Lovely. Thanks.
