### ISSUE TITLE
kubeadm cluster pod networking fails because of incorrect node security group

### ISSUE THREAD

**Issue by wilderk** [kubernetes-sigs/cluster-api-provider-aws#4136]
/kind bug

**What steps did you take and what happened:**
I followed the cluster api [quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html) to create an aws kubeadm cluster.
```
# init the bootstrap cluster with aws provider
clusterctl init --infrastructure aws:v2.0.2 -v5

# create a cluster config file
cat << EOF > clusterconfig-aws-kubeadm.yaml
# Required Variables
AWS_CONTROL_PLANE_MACHINE_TYPE: t2.xlarge
AWS_NODE_MACHINE_TYPE: t2.xlarge
AWS_REGION: us-east-2
AWS_SSH_KEY_NAME: wilder-capi-kubeadm
KUBERNETES_VERSION: v1.26.2
# Optional Variables
CONTROL_PLANE_MACHINE_COUNT: 1
WORKER_MACHINE_COUNT: 2
EOF

# generate the cluster config
clusterctl generate cluster wilder-capi-kubeadm --config clusterconfig-aws-kubeadm.yaml > wilder-capi-kubeadm.yaml

# create the infrastructure and workload cluster
kubectl apply -f wilder-capi-kubeadm.yaml

# wait for infrastructure and workload cluster to be provisioned
watch kubectl get cluster,kubeadmcontrolplane,machinedeployments,machine -A

# retrieve the kubeconfig for the workload cluster
clusterctl get kubeconfig wilder-capi-kubeadm > wilder-capi-kubeadm.kubeconfig

```
I attempted to install Calico CNI and it failed.
```
# in a separate terminal window
export KUBECONFIG=wilder-capi-kubeadm.kubeconfig
helm install calico projectcalico/tigera-operator --version v3.25.0 --namespace tigera-operator --create-namespace
```
Node security group blocked necessary communication
```
kubectl get events -n calico-system
3m5s        Warning   Unhealthy                pod/calico-node-gqb5p                           Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
```
I also tried other CNI plugins: WeaveNet, Cilium and they also failed to install.
As a test, from the AWS console I manually created a security group inbound rule to all protocols and all ports from the node security group source and then CNI installed successfully. This test security group rule opened all communication between the worker nodes. 
```
sgr-0e5bc8fc6a628bb41 | – | All traffic | All | All | sg-03e5224d2b3568cd7 / wilder-capi-kubeadm-node | test
```
I don't know exactly what specific inbound rule is needed.

**What did you expect to happen:**
I expected cluster-api-provider-aws to create a functional cluster with necessary security group to allow installation of CNI.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): v1.26.2 
- OS (e.g. from `/etc/os-release`): cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by Skarlso** [comment]
Hi. 

I don't see you using the kube config during your helm install call. Are you sure you are installing calico into your workload cluster?

**Comment by wilderk** [comment]
Retrieving the kubeconfig for the workload cluster was assumed. I will add it for completeness of the steps to reproduce.
