### ISSUE TITLE
Document manual steps for creating an HA cluster using clusterctl phases

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#414]
/kind feature

**Describe the solution you'd like**

Currently clusterctl only supports standing up a single control plane instance, as a workaround we should document the process for standing up an HA cluster leveraging clusterctl phases. Rough workflow would be something along the lines of:

- Stand up bootstrap cluster (create-bootstrap-cluster)
- Deploy cluster-api components to that cluster (apply-cluster-api-components)
- Create the shared cluster components (apply-cluster)
- Create initial control plane instance and wait for completion (apply-machines)
- Create the addon components (apply-addons)
- Create second control plane instance and wait for completion (apply-machines)
- Create third control plane instance and wait for completion (apply machines)
- Pivot the cluster-api components to the created cluster (pivot)
- Create additional worker nodes (apply-machines)

Depends on #413 
Depends on kubernetes-sigs/cluster-api#554

**Comment by chuckha** [comment]
leaving this here for reference https://gist.github.com/detiber/4ec73772f0618a40faad07c1abd06ab4

**Comment by ashish-amarnath** [comment]
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/545#discussion_r253503959
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/545#issuecomment-460456668
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/545#issuecomment-460677304

**Comment by chuckha** [comment]
/assign

going to try and finish this off today
