### ISSUE TITLE
Test CAPI with release 1.4 RC

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-aws#4146]
Release candidate for v1.4.0 release of CAPI is out: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0-rc.0

This issue is to track bumping the version of CAPI in CAPA and running all the tests with it to help validate the new release and ensure there are no regressions.

See [the Cluster-API book](https://main.cluster-api.sigs.k8s.io/developer/providers/v1.3-to-v1.4.html) for an overview of relevant changes between Cluster API v1.3 and v1.4 that may need changes in CAPA.

**Comment by Ankitasw** [comment]
@richardcase @Skarlso shall we just try it in a PR to see if it works fine, or do we merge PR and start using RC build, not very much caught up with the CAPI release system.
