### ISSUE TITLE
Binary for automating HA cluster creation

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#415]
/kind feature

**Describe the solution you'd like**

Automate the manual process that was defined for #414 

This can be built into clusterawsadm or provided as a separate binary.

/priority important-soon

**Comment by sfzylad** [comment]
I'm wondering how do we want to handle availibility zones in control plane definitions. Is it something we want to leave down to an user, just apply control plane machines blindly or discover subnets somehow and use them?

**Comment by detiber** [comment]
@sfzylad For now when we create a VPC for a user we are only creating a single private subnet in a single AZ. To support multi-AZ today would require the user to bring their own VPC/Subnets and manually override the region for each control plane Machine definition. We'd have to defer better multi-AZ support for post-v1alpha1 where we can address subnet management in a better way.
