### ISSUE TITLE
Validate MachineSets, MachineDeployments, and MachineClasses are functional

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#416]
/kind feature

**Describe the solution you'd like**

Currently we've only tested individual machine creation, we need to validate that MachineSets and MachineDeployments function as intended.

We should also update documentation to discuss scaling up/down of MachineSets and Machine Deployments, as well as updating the default examples to use a MachineDeployment for worker nodes.

**Comment by chuckha** [comment]
/lifecycle active

i will never get the syntax right

**Comment by chuckha** [comment]
We don't support MachineClass. This would require us to have an additional provider spec for machine class.

**Comment by chuckha** [comment]
Using https://gist.github.com/chuckha/a9e260c5e34b8de6063e9fdfe7e247cb to test the MachineDeployment, I believe it's working as expected.

The control plane is created and then the machine deployment is created. The correct number of replicas are created. When replicas are increased, the number of instances on AWS increases and when the number of replicas are decreased, the controller will delete the oldest nodes first. Nodes live in a queue of with the semantics of first-created-first-deleted (FIFO but create is insert and delete is dequeue)

I'll open a ticket for getting MachineClassProviderSpec up for the next milestone.

/close
