### ISSUE TITLE
Add Ignition certificate authority configuration support for Flatcar

### ISSUE THREAD

**Issue by thefirstofthe300** [kubernetes-sigs/cluster-api-provider-aws#4167]
/kind feature

First, a bit of back ground on my environment. I am attempting to build a cluster in an environment that is simulating a secret, i.e. air-gapped, AWS region. The particular solution used to perform this simulation uses DNS hijacking to man-in-the-middle all requests made to either a public domain or to the AWS APIs and log an assertion about whether the request made would be a valid request in the target region.

In the context of running Flatcar nodes, this behavior introduces a problem in that the current ignition configuration passed to each AWS instance's user data does not support [adding a `ignition.security.tls.certificateAuthorities`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/aa7d627ac2434b56314b36f4fcd74d980cf81173/controllers/awsmachine_controller.go#L736-L747) field to the JSON. Consequently, when Ignition attempts to fetch the rest of the configuration from S3, it fails due to the man-in-the-middle proxy's signing certificate not being in the trust store.

I attempted building my own Flatcar node using image-builder; however, since Ignition runs in initramfs, any changes made to the target file system are not actually reflected in the environment in which Ignition runs. A full Flatcar rebuild with the appropriate certs would be required to get this configuration working without making any changes to CAPA. The easier solution for end users would definitely be to allow users to specify a certificateAuthority Ignition can use to bootstrap the Flatcar node.

Currently, the only workaround I believe will work (although it is currently untested) is to use build an image with the signing cert installed to the root trust store from an OS with support for cloud-init since cloud-init is run after switch root and consequently has access to any certs installed during an image build.

**Comment by Skarlso** [comment]
So.. um... are you just asking us to add support for the possibility of making a MITM attack? :D

**Comment by thefirstofthe300** [comment]
> So.. um... are you just asking us to add support for the possibility of making a MITM attack? :D

Unfortunately, the reality of the modern enterprise and their security teams means that decryption proxies are not uncommon. Yes, it's technically a MITM attack; however, the assumption is that there are methods of adding the decryption proxy's certificate to the certificate stores to allow the configuration to work.
