### ISSUE TITLE
New Release plans

### ISSUE THREAD

**Issue by damdo** [kubernetes-sigs/cluster-api-provider-aws#4172]
/kind feature

Describe the solution you'd like:

I was wondering if there are any plans in regards to releasing a newer minor or patch release to cover [the bump in k8s dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/78877789bc4ab25912ae9383ad5cc2f291982270/go.mod#L32-L37), the use of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3920 and in general some vulnerable dependencies that have [already been bumped on main](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/78877789bc4ab25912ae9383ad5cc2f291982270/go.mod#L144) but are not yet present in a release.

Thanks!
cc. @Ankitasw @richardcase

**Comment by Skarlso** [comment]
Hello. Yes, there are. There are a number of items we are tracking for 2.1.0 which you can list here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.1.0

Other than that, we are discussing automation choices and options for releases here https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4091

And a discussion here https://github.com/kubernetes-sigs/cluster-api-provider-aws/discussions/3855

**Comment by damdo** [comment]
Thanks for the links @Skarlso will keep an eye on those.
Would the minor deps bumps grant a `v2.0.3` or are we going straight to `v2.1.0`?

**Comment by Skarlso** [comment]
Since the release process is manual ATM and it's rather tedious, we are going straight for 2.1.0. :)

**Comment by damdo** [comment]
Got it! Thanks for all the info, closing this :)
