### ISSUE TITLE
[cluster actuator] reconcile public subnet

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#42]
The MVP requires a public subnet for hosting a bastion host. This subnet should only be created if the user does not provide configuration to suggest that a public subnet already exists. What exactly that configuration looks like is TBD.

**Comment by vincepri** [comment]
Closing, see https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/47#issuecomment-422564463
