### ISSUE TITLE
No status for upgrade operation AWSManaged clusters

### ISSUE THREAD

**Issue by mjnovice** [kubernetes-sigs/cluster-api-provider-aws#4225]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I created a AWS Managed cluster, by updating the Kubernetes version and see that there is no field in the `status.Conditions` field which can indicate that the upgrade operation has completed.

**What did you expect to happen:**
A field/event indicating that the upgrade operation has succeeded.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`): 1.25
- OS (e.g. from `/etc/os-release`): macOS 13.3.1 (22E261)

**Comment by Skarlso** [comment]
There are no specific conditions because the conditions are the same for create and the upgrade flow. You just wait for the machine status to be Ready. What else would you require?

**Comment by mjnovice** [comment]
@Skarlso I have observed that sometimes even the `Ready` status doesn't get updated in the timestamp. 

```json
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  creationTimestamp: "2023-04-17T01:23:21Z"
  finalizers:
  - machinepool.cluster.x-k8s.io
  generation: 8
  labels:
    cluster.x-k8s.io/cluster-name: devmj-aws-upgrades-3
  name: devmj-aws-upgrades-3-private-0
  namespace: sfd-devmj-aws-upgrades-3
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: devmj-aws-upgrades-3
    uid: a9e1b96c-d772-4801-a158-0c03a0d165af
  resourceVersion: "11381465"
  uid: 0b3a98f4-51d4-4a2f-8103-d73c291422d2
spec:
  clusterName: devmj-aws-upgrades-3
  minReadySeconds: 0
  providerIDList:
  - aws:///us-east-1a/i-029fcd0a8774d597c
  - aws:///us-east-1a/i-05d580b9fdfbde76c
  - aws:///us-east-1b/i-0be54549f3eedd69b
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: devmj-aws-upgrades-3
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: devmj-aws-upgrades-3-private-0
        namespace: sfd-devmj-aws-upgrades-3
      version: v1.26.1
status:
  availableReplicas: 3
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2023-04-18T06:00:05Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-04-17T01:23:21Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2023-04-18T06:00:05Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2023-04-17T01:23:21Z"
    status: "True"
    type: ReplicasReady
  infrastructureReady: true
  nodeRefs:
  - name: ip-173-10-134-196.ec2.internal
    uid: c22673f2-d8cd-4c6c-a108-a9a2f56746bb
  - name: ip-173-10-173-49.ec2.internal
    uid: 56150429-883d-43d6-9357-b2ecca38932f
  - name: ip-173-10-239-68.ec2.internal
    uid: e48b607d-f8a2-440e-a7cd-b5008b0bfac1
  observedGeneration: 8
  phase: Running
  readyReplicas: 3
  replicas: 3
```

take for instance the above MachinePool spec. even when I updated the K8s version, the condition `Ready` did not update the status. 

Did you mean something else ? As I am not sure if I can access individual machines when using `AWSManagedClusters` ?

**Comment by Skarlso** [comment]
Check out how we do it in the E2E tests and what we are using for Wait conditions. I don't have a better answer. There is no separate condition for updates right now.
