### ISSUE TITLE
Support EKS Addons custom configuration

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes-sigs/cluster-api-provider-aws#4226]
/kind feature

**Describe the solution you'd like**
EKS addons now support custom configuration. ref: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks#CreateAddonInput 

**Anything else you would like to add:**
 For our use case, we need to modify env vars that are part of the VPC CNI in order to support eni/pod security groups.  

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
This will require changes to the api and then the procedures. For example: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/eks/addons/procedures.go#L146
