### ISSUE TITLE
add unit test for annotations.go

### ISSUE THREAD

**Issue by khareyash05** [kubernetes-sigs/cluster-api-provider-aws#4230]
/kind feature

**Describe the solution you'd like**
I would like to add unit tests for `pkg/annotations/annotation.go`

**Comment by Skarlso** [comment]
HI. :) 

Sure, go for it! 👍 :)

**Comment by khareyash05** [comment]
Do you want me to write tests using Ginkgo and Gomega @Skarlso ?

**Comment by khareyash05** [comment]
@Skarlso Kindly review the PR

**Comment by Skarlso** [comment]
Thank you for your contribution! :)
