### ISSUE TITLE
Support for external etcd

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#426]
/kind feature

**Describe the solution you'd like**
The current implementation plans for HA consist of deploying using a stacked etcd control plane using the `kubeadm join --experimental-controlplane` feature. There is also a need to eventually support HA clusters where etcd is hosted separately from the control plane.

To simplify the maintenance burden of this approach, we should rely on [etcdmgr](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0031-20181022-etcdadm.md) for managing the etcd components rather than rolling our own custom etcd management.

**Comment by ncdc** [comment]
@detiber should we transfer this to https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm?

**Comment by detiber** [comment]
Indeed, I'll transfer it now.

**Comment by detiber** [comment]
Or maybe not, it's not showing cluster-api-bootstrap-provider-kubeadm as a repo that I can transfer issues to.

**Comment by ncdc** [comment]
Maybe @chuckha can?

**Comment by ncdc** [comment]
I'm going to close this and open a new issue in the other repo.
/close
