### ISSUE TITLE
Umbrella: Exposing User Configuration

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#427]
/kind feature

**Describe the solution you'd like**
Currently we only expose very limited user configuration, which does not provide enough flexibility for most users.

- [ ] Expose kubeadm config #17 
- [ ] Expose common cluster infrastructure config #14

**Comment by chuckha** [comment]
There are several approaches that may need discussion.

## Exposing various fields
Exposing some of the fields of a kubeadm config through the cluster provider spec is one way to accomplish this.
### Advantages

Easy to understand, easy to implement, easy to add more, hides the kubeadm version as the kubeadm configuration version migrates from beta to stable.

### Disadvantages

Users will probably want to customize fields we don't expose. Kubeadm my change faster than we do which means users may want fields we don't even have access to. Tedious to add fields and reimplement a config file in our own spec that sort of mirrors the kubeadm config.

## Exposing an overridable config
This would expose a single field in our provider spec that would allow a user to embed their own kubeadm config.
### Advantages

This gives complete control to the user. Whatever they want, we add it to the user data and it gets run. No validation or anything.

### Disadvantages

This puts the onus on the user to write a perfect kubeadm configuration file. Probably not something many people actually want to do especially with the changing API (which will not be changing so much in future).

## Why not both?
Perhaps there is a middle ground where we allow some kind of configuration that merges with some defaults? I'm not entirely sure what this would look like yet from a provider spec perspective.
### Advantages
This would give the best of both worlds. Advanced users could override whatever they want and beginners could not override anything and still have a working default cluster.
### Disadvantages
This may be tricky to implement when merging hierarchies of maps

## Other?
There must be other strategies that I have missed. Please comment if you think of any you'd like to see discussed.

**Comment by vincepri** [comment]
Kubeadm reached [v1beta1](https://github.com/kubernetes/kubernetes/blob/v1.13.1/cmd/kubeadm/app/apis/kubeadm/v1beta1/types.go). I'd love to use those struct _in some ways_ (not necessarily through vendoring) and run validation/merging while exposing the whole configuration. 

The approach suggested has few pros/cons:
- 👍Highly customizable.
- 👍Uses strict typing.
- 👍Validation can be performed in the actuator and errors can be exposed as events.
- 👍Defaulting should be easy and straightforward.
- ⚠️Implementation might tie us up to a particular kubeadm config version.
- ⚠️Requires library to marshal into yaml in userdata.
- ⚠️Requires merging logic between default values and user configuration.

**Comment by timothysc** [comment]
Currently blocked on kubeadm 1.13 api absorption.

**Comment by vincepri** [comment]
Thanks for doing this @chuckha! 

I took a quick look and the concern I have here is related to all the constraints that are now part of the dep file. While this solves the immediate problem, it creates upgradability issues down the line. At the moment, we purely rely on upstream constraints and dependencies, which means we get newer k8s version when upstream updates its own dependencies. 

If we vendor kubeadm (k/k repo) and add constraints in our repository, we'll find ourselves in a situation where upgrading Kubernetes is going to be a much bigger deal with a lot more moving parts and a complicated dependency tree. For this reason, I'd like to instead follow another route for the time being (as suggested by @detiber in the community meeting) and copy the structs in.

I'd prefer to see the issue fixed upstream and kubeadm types to be moved out of k/k or kept in sync in an external repository.

**Comment by chuckha** [comment]
@vincepri I made some updates the Gopkg.toml file and you can see now that the constraints have been simplified back to just cluster-api but we've now also vendored in the kubeadm types. I think this is a nice trade off since we don't actually pull in that many more deps. The overhead for this is, imo, lower than copying the struct types.

As for moving the api versions out of k/k, considering dep will prune unused go packages and non-go files, I don't really see the problem with vendoring small packages such as kubeadm api types. What do you think the downsides of this are?

**Comment by chuckha** [comment]
Some more thoughts regarding the versioning concerns. Apologies for missing your point the first time around:

Versioning the types will not tie us too tightly kubernetes versions. 

If we vendor v1beta1 of the configurations then we're guaranteed it's viable for at least two releases. We may not immediately get all the new features that kubeadm exposes, but it will certainly work for this and the following two releases. 

Upgrading kubernetes will not be such a burden since we don't have to do it for each point release, just when the api gets deprecated or when new features get added that we want.

Does that address your concerns around versioning issues @vincepri?

**Comment by chuckha** [comment]
cc @timothysc @ncdc

**Comment by chuckha** [comment]
I was thinking a bit about how to handle upgrading kubeadm type versions over a long period of time. It's not very easy and would love to talk it out sometime. My current thinking:

Let’s say for a moment we vendor the kubeadm types in and reference them from probably AWSProviderClusterConfig. Once the next version of kubeadm types are created, say , `v1beta2`, then we have to support clusters in CAPA using both `v1beta1` and `v1beta2` which means the AWSProviderClusterConfig will have *both* kubeadm types embedded in it.

This is starting to sound like we'll definitely need a deprecation / version support policy.

**Comment by chuckha** [comment]
My current thinking here is to allow users to supply an init or join configuration that we will use with the exception of the infrastructure related fields. If they try to provide a piece of data we need to overwrite, we can warn them about that.
