### ISSUE TITLE
New Cluster can't sync the iam auth config -- looking for role which doesn't exist on the nodes.

### ISSUE THREAD

**Issue by empath-nirvana** [kubernetes-sigs/cluster-api-provider-aws#4271]
/kind bug

**What steps did you take and what happened:**
Provisioned a new cluster and aws machine pool using 
--feature-gates=EKS=true,EKSEnableIAM=true,EKSAllowAddRoles=false,EKSFargate=true,MachinePool=true,EventBridgeInstanceState=false,AutoControllerIdentityCreator=true,BootstrapFormatIgnition=false,ExternalResourceGC=false,AlternativeGCStrategy=false

the cluster is provisioned, the controller created the node pool, and provisioned the node, the node joined the cluster, but i get this error:

failed to reconcile aws-iam-authenticator config for AWSManagedControlPlane clusters/test-control-plane: failed to get ARN for role : unable to get role: NoSuchEntity: The role with name nodes.cluster-api-provider-aws.sigs.k8s.io cannot be found

I've looked at every spec for every cluster api object and that role name isn't anwhere in the spec or the status.

the only resource that lists a role at all is an awsmanagedmachinepool resource:

spec:
    amiType: AL2_x86_64
    capacityType: onDemand
    eksNodegroupName: clusters_test-pool-0
    roleName: capa_9dehreze3f3jnyncuqi3kvt41rd
    updateConfig:
      maxUnavailable: 1

And lastly, it _has_ updated the aws auth config map, but it's still throwing an error.

data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::redacted:role/capa_9dehreze3f3jnyncuqi3kvt41rd
      username: system:node:{{EC2PrivateDNSName}}

**What did you expect to happen:**
Expected it to sync

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v2.1.1
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`):

**Comment by Skarlso** [comment]
Apparently, this should have been fixed by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4011.

**Comment by faiq** [comment]
The relevant code is here https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/iamauth/reconcile.go#L107

The existing behavior before the PR was that this would role would be always be added to the iam authenticator config. The tests and previous users depended on this being there, so I decided not to break it.
