### ISSUE TITLE
Automate Amazon EBS CSI driver  deployment and configuration in EKS clusters

### ISSUE THREAD

**Issue by balti09** [kubernetes-sigs/cluster-api-provider-aws#4278]
/kind feature
/kind question

is there any method to configure automatically the Amazon EBS CSI driver  in eks clusters ?
the steps that they need to be automated : https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

**Comment by Skarlso** [comment]
As per the discussion here https://kubernetes.slack.com/archives/CD6U2V71N/p1684502305684799 this is a feature and not a bug.
