### ISSUE TITLE
Error updating AWSClsuter status with NLB target group

### ISSUE THREAD

**Issue by ttreptow** [kubernetes-sigs/cluster-api-provider-aws#4284]
/kind bug

**What steps did you take and what happened:**
Created an AWSCluster with `loadBalancerType: nlb`

The CAPA controller pod throws an error:

> E0522 15:05:01.995734       1 controller.go:329] "Reconciler error" err="AWSCluster.infrastructure.cluster.x-k8s.io \"blah\" is invalid: status.networkStatus.apiServerElb.elbListeners[0].targetGroup
.protocol: Unsupported value: \"TCP\": supported values: \"tcp\", \"tls\", \"upd\"" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster"

**What did you expect to happen:**

AWSCluster status is set correctly

**Anything else you would like to add:**

Looking at the code, the kubebuilder validation is set to
```
// +kubebuilder:validation:Enum=tcp;tls;upd
```
(Note all lowercase and misspelled "udp")

whereas `ELBProtocol` can be `TCP`, `SSL`, `HTTP`, `HTTPS`, `TLS`, `UDP`

I think the validation should either be removed (as with the `Listener` `Protocol` field
) or set to `TCP;TLS;UDP`

**Environment:**

- Cluster-api-provider-aws version: v2.1.1
- Kubernetes version: (use `kubectl version`): 1.26
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by Skarlso** [comment]
```
E0522 15:05:01.995734 1 controller.go:329] "Reconciler error" err="AWSCluster.infrastructure.cluster.x-k8s.io "blah" is invalid: status.networkStatus.apiServerElb.elbListeners[0].targetGroup
```

`blah`?????????

**Comment by ttreptow** [comment]
That was the name of the cluster that I redacted. 
The issue is with the field validation [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/8a2e6b72738aa92636176adaae85717071421584/api/v1beta2/network_types.go#L113), which doesn't match the actual values of `ELBProtocol`.
