### ISSUE TITLE
Migration to v2.1.2: failed to reconcile aws-iam-authenticator

### ISSUE THREAD

**Issue by darkweaver87** [kubernetes-sigs/cluster-api-provider-aws#4291]
/kind bug

**What steps did you take and what happened:**
After migrating our clusters from v2.0.2 to v2.1.2, capa controller fails to reconcile.

```
failed to reconcile aws-iam-authenticator config for AWSManagedControlPlane flux-system/xxxx-cp: failed to get ARN for role : unable to get role: NoSuchEntity: The role with name nodes.cluster-api-provider-aws.sigs.k8s.io cannot be found.
```

It seems to be broken by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4011 cc @faiq.

**What did you expect to happen:**
No changes and clusters are reconciled. This role was not mandatory and should be put as a default if none is provided ?

**Anything else you would like to add:**
Creating the missing role `nodes.cluster-api-provider-aws.sigs.k8s.io` fixes the issue.

**Environment:**

- Cluster-api-provider-aws version: v2.1.2
- Kubernetes version: (use `kubectl version`): v1.26.4-eks-0a21954
- OS (e.g. from `/etc/os-release`): 
```
# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by faiq** [comment]
This was also reported in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4271

I think it makes sense to remove the role and see if the e2e tests pass.

I wrote in the other PR:

> The existing behavior before the PR was that this would role would be always be added to the iam authenticator config. The tests and previous users depended on this being there, so I decided not to break it.

**Comment by faiq** [comment]
I pr'ed a potential fix for the issue :crossed_fingers: it works!

**Comment by darkweaver87** [comment]
Many thanks for your reply. Let's hope it works :crossed_fingers:
