### ISSUE TITLE
 Private only  subnets topology cannot get the information of EC2 instances from  EKS cluster

### ISSUE THREAD

**Issue by tingchienc** [kubernetes-sigs/cluster-api-provider-aws#4317]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I followed the instruction from https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html to use existing vpc to create EKS Clusters.
I used kind cluster based on the get started guide.
`clusterctl generate cluster capi-eks-quickstart --flavor eks --kubernetes-version v1.26.0 --worker-machine-count=2 > capi-eks-quickstart.yaml`
I used VPC that has two private subnets and route tables and I specified ids into the yaml file.

![Screenshot from 2023-06-07 10-47-21](https://github.com/kubernetes-sigs/cluster-api-provider-aws/assets/134561490/784eb8f0-94da-47b4-bab1-ce2f231ba8b6)

At the end, the EKS cluster and EC2 instances run but I cannot get the EC2 information by EKS cluster.
When typing `clusterctl get kubeconfig capi-eks-quickstart > capi-eks-quickstart.kubeconfig
kubectl get nodes --kubeconfig capi-eks-quickstart.kubeconfig 
`
It shows No resources found in default namespace.

`kubectl logs capa-controller-manager-5d487d7d68-nj46j -n capa-system`

![Screenshot from 2023-06-07 10-45-10](https://github.com/kubernetes-sigs/cluster-api-provider-aws/assets/134561490/542543fe-598d-401e-9f9a-263bfa91d1a0)

**What did you expect to happen:**
Shows something like here.

capi-quickstart-md-0-55x6t-5649968bd7-8tq9v   Ready    <none>          6m5s   v1.27.1
capi-quickstart-md-0-55x6t-5649968bd7-glnjd   Ready    <none>          6m9s   v1.27.1

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The cluster status looks weird.
It always stucks here.
![Screenshot from 2023-06-06 17-31-51](https://github.com/kubernetes-sigs/cluster-api-provider-aws/assets/134561490/1dcb3d7c-e525-497e-a1dc-404158d75de7)

I tried to create ec2 endpoints to help connects but it seems no help.

**Environment:**

- Cluster-api-provider-aws version: v1.42
- Kubernetes version: (use `kubectl version`): v1.26.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by dlipovetsky** [comment]
@tingchienc Sorry that you're having an issue creating a CAPA EKS cluster.

It's clear that you are unable to deploy the worker nodes, but I don't see a clear CAPA bug here.

We can help with questions around cluster creation in the #cluster-api-provider-aws channel in Kubernetes Slack, but GitHub issues are not the best place for that.
