### ISSUE TITLE
AMI_CUSTOM has no way for upgrading

### ISSUE THREAD

**Issue by mjnovice** [kubernetes-sigs/cluster-api-provider-aws#4327]
/kind bug

**What steps did you take and what happened:**
Create an `AWSManagedMachinePool` and the correspoding `MachinePool` with custom AMI, and then try to upgrade the AMI version from one to another (e.g 1.24 -> 1.25)

I keep getting the error. 
```
   message: |-
      failed to reconcile nodegroup version: failed to update EKS nodegroup: InvalidParameterException: Launch template details can't be null for Custom ami type node group
      {
        RespMetadata: {
          StatusCode: 400,
          RequestID: "7948195d-3912-4eb3-808a-5e55c2ea8038"
        },
        Message_: "Launch template details can't be null for Custom ami type node group"
      }
```

which is as mentioned here to https://repost.aws/knowledge-center/eks-managed-node-group-update 

It seems we need to pass both `AMIReleaseVersion` and the new LaunchTemplate for it to pass, currently there is no way to do so unfortunately, or atleast I cannot find one.

**What did you expect to happen:**
The MachinePool should have been upgraded to the desired version `1.24` 

I even tried changing the userdata used in the `MachinePool` via the secret used `.spec.template.spec.boostrap.dataSecretName`, but it seems https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v2.0.2/pkg/cloud/services/ec2/launchtemplate.go#L684 this is a known issue and we would want to fix it ? @dlipovetsky 🙏 Could you help tell, when is this scheduled for ?

**Anything else you would like to add:**
I tried checking if this got fixed in the latest version v2.1.x but seems this is an issue there as well.

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): v1.25
- OS (e.g. from `/etc/os-release`): Linux

**Comment by dlipovetsky** [comment]
/triage accepted

I'll take a closer look at the code, and the FIXME comment.

**Comment by fad3t** [comment]
Also interested in this.

I noticed that when I'm either updating the machine pool's k8s version or the AMI id in the launch template, a new version of the launch template gets created. The node group isn't updated automatically (it throws the error reported in this issue) but it's possible to manually update the version of the launch template and use the latest, which redeploys the node group using the updated version.
