### ISSUE TITLE
TagUnmanagedNetworkResources false still tags subnets for LoadBalancers

### ISSUE THREAD

**Issue by Jacobious52** [kubernetes-sigs/cluster-api-provider-aws#4340]
/kind bug

**What steps did you take and what happened:**

 With the feature gate `TagUnmanagedNetworkResources=false` CAPA still tags unmanaged subnets with `"kubernetes.io/role/internal-elb: 1"` and cluster name tag. 

**What did you expect to happen:**

When `TagUnmanagedNetworkResources=false` CAPA should not tag the subnets at all.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Due to business requirements, our control-plane / capa subnets can't be used for load balancing. Remove the tag ensures that aws-load-balancer-controller doesn't auto discover them when not wanted.

I'm raising a PR for this one, happy to assign to me.

**Environment:**

- Cluster-api-provider-aws version: `main`
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`): N/A

**Comment by Skarlso** [comment]
Nice catch. I thought we had them all. :)

/triage accepted

**Comment by Jacobious52** [comment]
> 1. The `cluster name tag` here means ` kubernetes.io/cluster/<cluster-name>:shared` tag, right?

Yes, that is the tag I meant 👍

> 2. For `kubernetes.io/role/internal-elb: 1` or `kubernetes.io/role/elb: 1` tag, does it do some harm if existing on the unmanaged subnets in your env? Because these tags are useful for creating LB service.

Yes, it does harm our env in the case we don't want LB services on the subnets attached to the control plane or managed by capa. We removed the tags after running the patch to resolve the issue of LBs landing on the wrong subnets.

**Comment by wyike** [comment]
> Yes, it does harm our env in the case we don't want LB services on the subnets attached to the control plane or managed by capa. We removed the tags after running the patch to resolve the issue of LBs landing on the wrong subnets.
Just curious, can your existing tags for the subnets be automatically removed after upgrade CAPA with this patch? I thought you have to manually removes them.
Because here https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/subnets.go#L140 and finally goes here:  https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/tags/tags.go#L117: the ec2client.CreateTags(createTagsInput) won't remove the existing tags on the subnet if they are not existing in createTagsInput from my testing.

**Comment by Jacobious52** [comment]
Not with this patch. I didn't want to implement logic to "reverse the bug" and have capa still modify subnet tags with `TagUnmanagedNetworkResources=false` even to remove them. So I guess this patch is forward-looking only and not backwards compatible. One has to manually remove the tags in this edge case.
