### ISSUE TITLE
Bump CAPI to v1.5.0

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#4390]
/kind feature
/help

**Describe the solution you'd like**
We want to bump CAPI to 1.5.0 (as soon as its released).

**Anything else you would like to add:**
We have an issue to bump to the RC: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4375

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
@furkatgofurov7 - just to confirm this is for the 1.5.0 release and not the rc

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 - just to confirm this is for the 1.5.0 release and not the rc

@richardcase sure, I can bump it to actual release once it is out too, for now opened https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4398 to bump it to rc.0
