### ISSUE TITLE
Publish clusteraswadm as clusterctl plugin

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#4391]
/kind feature
/help
/milestone v2.2.0

**Describe the solution you'd like**
With a recent change in CAPI (https://github.com/kubernetes-sigs/cluster-api/pull/8957) it's possible to create plugins for clusterctl (like you can do with kubectl).

We should publish `clusterawsadm` so it can be used as an plubin like this:

`clusterctl aws bootstrap iam create-cloudformation-stack`

**Anything else you would like to add:**

This means we need to publish a binary called `clusterctl-aws`

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
We can publish it on our GitHub release, and it can be downloaded and placed in a users' PATH.

**Comment by Ankitasw** [comment]
@richardcase we are already publishing clusterawsadm in our release binary, how do we publish it so that it can be used as plugin?
