### ISSUE TITLE
[cluster actuator] Reconcile routes for public subnet

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#44]
If the cluster actuator is managing a public subnet it should created the needed routes. The actuator *should not* manage routes if a user is specifying an existing public subnet should be used through config.

Depends on #42 
/kind feature
/priority important-soon

**Comment by vincepri** [comment]
Closing, see https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/47#issuecomment-422564463
