### ISSUE TITLE
ROSA: CAPA basic support

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api-provider-aws#4431]
/kind feature

**Describe the solution you'd like**
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4344 introduces a common ground for collaboration on ROSA CAPA and basic ability to spin up a new cluster.

This is an umbrella ticket to cover the following up work to support ROSA
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4430
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4429
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4428

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by enxebre** [comment]
cc @muraee

**Comment by muraee** [comment]
Create some more issues based on @richardcase suggestions/review

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4457
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4459
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4460
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4461
