### ISSUE TITLE
Feature request: disable EKS-provided CoreDNS deployment

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/cluster-api-provider-aws#4475]
/kind feature

**Describe the solution you'd like**
A spec field and controller support to disable/delete the EKS-provided CoreDNS deployment if another DNS provider is to be used/configured, similar to the disable flags provided for kubeProxy and vpcCni.

**Environment:**

- Cluster-api-provider-aws version: v2.2.1
- Kubernetes version: (use `kubectl version`): v1.26
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by dothinh316** [comment]
+1 to this feature request please

**Comment by dothinh316** [comment]
this thing will save lives. please re open
