### ISSUE TITLE
How to handle global roles and related stacks (possibly duplicated stacks)

### ISSUE THREAD

**Issue by vinibali** [kubernetes-sigs/cluster-api-provider-aws#4488]
/kind bug

**What steps did you take and what happened:**
* create stack1 in region1
* create stack1 in region2

**What did you expect to happen:**
* stack1 becomes available in both regions

**Anything else you would like to add:**
We end up having problems as the global roles were created with stack1 in region1. While creating stack1 in region2, the stack creation has failed, as the global roles are already available.
What would be a better way to check if stack1 is already available?
As we see clusterawsadm is not able to give back such values.

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): v1.26.8
- OS (e.g. from `/etc/os-release`): SLES 15

**Comment by vinibali** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3211
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1977

**Comment by Skarlso** [comment]
Why would you want to create the same stack in both regions? I would postfix it with the region name. This is not possible at the moment because of iam resources as you aptly found out already. 😊

**Comment by vinibali** [comment]
> Why would you want to create the same stack in both regions? I would postfix it with the region name. This is not possible at the moment because of iam resources as you aptly found out already. 😊

We execute a bootstrap
```
clusterawsadm bootstrap iam create-cloudformation-stack
```
because, there is no such information about if this has been run before, as clusterawsadm doesn't have a parameter to check if a bootstrap has been done previously.
