### ISSUE TITLE
Bump k8s dependency to 1.28

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-sigs/cluster-api-provider-aws#4505]
The k8s has evolved to 1.28, but here we still depend on 1.26.

Can we  upgrade

**Comment by vincepri** [comment]
We usually upgrade once Cluster API and Controller Runtime upgrades, there is no real need to update the clients immediately given that they'll still be working against a few skews.

Feel free to reopen if necessary.

/close

**Comment by hzxuzhonghu** [comment]
I see both cluster api and Controller Runtime bumps 

FYI 
https://github.com/kubernetes-sigs/cluster-api/blob/main/go.mod#L42C2-L42C26
https://github.com/kubernetes-sigs/controller-runtime/blob/main/go.mod#L26
