### ISSUE TITLE
Ability to spawn machines in an external vpc to the cluster vpc

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes-sigs/cluster-api-provider-aws#4540]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As a platform administrator that uses CAPA, I'd like to be able to define and declare a cluster that lives in VPC "foo" and spawn machines in subnets under that VPC, as well as spawn machines in a VPC "bar", which has it's own separate subnets. This is useful in cases where the subnet space of the cluster is limited, or in scenarios where the VPCs have differing network configurations with regards to internet access.

We can assume VPC "foo" and VPC "bar" have peering, a transit gateway, or some other way to crosstalk.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is currently not possible today, even if you specify an AWSMachine with a subnet in another VPC, using the existing `subnet` field, because the VPC ID is specified when filtering subnets.

**Environment:**

- Cluster-api-provider-aws version: 2.2.1
- Kubernetes version: (use `kubectl version`): 1.24.14
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.6 LTS

**Comment by Skarlso** [comment]
This is the main part here I think:

>We can assume VPC "foo" and VPC "bar" have peering, a transit gateway, or some other way to crosstalk.

Any documentation describing how to do this _MUST_ greatly emphasise that we will not make the VPCs able to talk to each other.

Also, I feel like this could be a major change in behaviour for other parts of CAPA and not just AWSMachnie, right?

**Comment by cnmcavoy** [comment]
I'll clarify the language for the fields to make that assumption clear. 

> Also, I feel like this could be a major change in behaviour for other parts of CAPA and not just AWSMachnie, right?

For AWSMachinePools, the placement of machines in an ASG is controlled by the `AWSMachinePool.spec.subnets` field, not the  the machine fields. So this change is only for MachineDeployments. Are there other components this change didn't take into consideration? We (Indeed) are still exploring this type of configuration as a possibility for new clusters, so I'd be interested in any considerations you are aware of.
