### ISSUE TITLE
Broken tests for unused import for cloud/services/{network,ec2} in v2.2.4

### ISSUE THREAD

**Issue by damdo** [kubernetes-sigs/cluster-api-provider-aws#4546]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I stood up envtest and ran `go test ./pkg/...` on `v2.2.4` and I got the following failures for:
```
# sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2 [sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2.test]
pkg/cloud/services/ec2/bastion_test.go:20:2: "context" imported and not used
FAIL    sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2 [build failed]

# sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network [sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network.test]
pkg/cloud/services/network/natgateways_test.go:20:2: "context" imported and not used
pkg/cloud/services/network/vpc_test.go:20:2: "context" imported and not used
FAIL    sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network [build failed]
```

**What did you expect to happen:**
No errors on tests

**Anything else you would like to add:**
It looks like [this commit](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4510/commits/43b06c8918b86e08819aec9fec8479aa68659111) on the [Bump CAPI to v1.5.0](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4510) PR, introduced unused imports of `"context"` in:
```
pkg/cloud/services/network/natgateways_test.go
pkg/cloud/services/network/vpc_test.go
pkg/cloud/services/ec2/bastion_test.go
```

That PR got then merged against main, and then got also backported to `release-2.2`, for which a `v2.2.4` got cut today.
At the moment, this is not a problem on `main` as a new PR got merged there which makes use of those previously unused contexts: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4490
Although this still remains an issue on `release-2.2` and on `v2.2.4`.

**Environment:**
- Cluster-api-provider-aws version:  `v2.2.4`
- Kubernetes version: (use `kubectl version`):  local envtest (v1.24`)
- OS (e.g. from `/etc/os-release`): -

**Comment by damdo** [comment]
A potential fix: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4547

**Comment by Skarlso** [comment]
If there was a fix in main that makes use of those context, wouldn't it be better to merge that fix back instead of removing the contexts?

**Comment by damdo** [comment]
Yes that's another option.
The PR that fixed it in main also contains other things, if we are happy to backport them, the yes, let's go with that.
Otherwise if we prefer only to fix it, we can go with the one I created.

**Comment by Skarlso** [comment]
How about the fix is to use the context instead of the whole PR being backported? Or using it involved adding a bunch more things?

**Comment by richardcase** [comment]
The PR checks on the release-2.2 aren't the same as on main....this is how this slipped through i guess. I will add the additional checks on the release-2.2 branch today.

@damdo thanks for picking this up and fixing 👍

**Comment by Skarlso** [comment]
👍

**Comment by richardcase** [comment]
Created the jobs: https://github.com/kubernetes/test-infra/pull/30966

Lets get the test-infra chanhe merged before this:

/hold

**Comment by damdo** [comment]
Closing this now that https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4547 merged.
