### ISSUE TITLE
Add the ability to add a secondary load balancer to the control plane

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#4554]
/kind feature
/assign
/priority important-soon

**Describe the solution you'd like**
In a lot of topologies, the control plane has a public and internal load balancer. Currently the AWSCluster CRD offers only ways to configure a single control plane.

Given the long term proposal for an AWSNetwork CRD to address the current shortcomings of AWSCluster, I'd like to propose to add a way to create and attach also a _secondary_ load balancer, configured by the user, and limited only to NLB or ALB (aka elbv2, not classic) load balancer types.

There are a few options we can consider, currently leaning towards the first one:

- [preferred] Add a `SecondaryControlPlaneLoadBalancer` field alongside the `ControlPlaneLoadBalancer` one and take into account of the new field and behavior in the current elb scopes and reconcilers.
  - This would be a backward compatible change.
  - The code changes should not be too invasive, and can be made in a next minor release.
  - Compatible with ClusterClass and SSA.
- Add a list of `AdditionalControlPlaneLoadBalancers` alongside the `ControlPlaneLoadBalancer`.
  - Requires a CRD breaking change to support SSA and ClusterClass if we want to reuse the struct in `ControlPlaneLoadBalancer`, given that the `name` is optional.
  - Unclear if more than two load balancers for the control plane is useful at all.
  - Handling a large number of load balancer and storing their information might be tricky.

cc @richardcase @JoelSpeed @nrb

**Comment by richardcase** [comment]
There have been a few asks related to this, tagging for future reference: #2849 and #1484
