### ISSUE TITLE
Allow load balancers of type NLB to add additional TCP listeners

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#4562]
/kind feature
/assign
/lifecycle active
/priority important-soon

**Describe the solution you'd like**
Currently it's not possible to add additional listeners and target groups for the load balancers created with CAPA. NLBs are easier to reason with, given that a TCP health check is easy to configure.

In the future, we might want to add ability to add different kinds of listeners, like http/https, etc; with proper certificate support.

**Comment by Skarlso** [comment]
You mean like this? https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3899

**Comment by vincepri** [comment]
TLS listeners are for later, I meant just add support for simple TCP to NLBs

**Comment by vincepri** [comment]
Something like:

```
// AdditionalListeners sets the additional listeners for the control plane load balancer.
	// This is only applicable to Network Load Balancer (NLB) types for the time being.
	// +optional
	AdditionalListeners []*AdditionalListenerSpec `json:"additionalListeners,omitempty"`
```
