### ISSUE TITLE
Request for `PodDisruptionBudget` and `PriorityClass` for CAPA components

### ISSUE THREAD

**Issue by esierra-stratio** [kubernetes-sigs/cluster-api-provider-aws#4628]
/kind feature

It would be nice to configure the components of CAPA with a `PriorityClass` and a `PodDisruptionBudget`. In my opinion, this addition is crucial considering the significance of these components in cluster administration. 
The `PriorityClass` would help emphasize their importance over other pods, while the `PodDisruptionBudget` would contribute to ensuring the high availability, stability, and resilience of these core components.

**Environment:**

- cluster-api-provider-aws version: From the current version onward and any potential future releases.
- Kubernetes version: N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by philjb** [comment]
I'm not sure the priority class can be sanely set in the manifests provided for CAPA. Classes are not standardized across the industry. So CAPA would have to provide its priority class spec and then that class might conflict or might not be as high as anticipated. It depends on the environment so much i think we should leave this to those running CAPA. I don't think system-critical priority class is appropriate. 

I support a PDB if CAPA specified more than one replica in the deployment by default, but with release 2.3.1 (and before i believe) - it deploys the CAPA controller as a singleton pod. A PDB doesn't help in this situation as the one pod has to be disrupted for rollouts and upgrades.

**Comment by philjb** [comment]
As I mentioned in [my earlier comment](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4628#issuecomment-1869760937), I believe the PDBs and PCs should be left to operators. We can make a recommendation on PCs and PDBs but to release with those set, we'll have to pick one configuration would be "one-size-fits-all" which would likely fit almost no one (except prototyping). I believe CAPA would be better served with an operational guide.

/close
