### ISSUE TITLE
AWSMachine controller leaks EC2 instances when specifying a Name tag in `additionalTags`

### ISSUE THREAD

**Issue by mjlshen** [kubernetes-sigs/cluster-api-provider-aws#4629]
/kind bug

**What steps did you take and what happened:**
After applying two `infrastructure.cluster.x-k8s.io/v1beta2` AWSMachines with the following additionalTags:

```yaml
spec:
  additionalTags:
    Name: sample-name-tag
```

124 EC2 instances were created in quick succession for these AWSMachines before `.spec.providerID` was populated. All of the EC2 instances (leaked and not-leaked) do have the tags `Name: sample-name-tag`

```
❯ k get awsmachine                                                  
NAME                                    CLUSTER                            STATE     READY   INSTANCEID                              MACHINE
sample-name-tag-251d8688-cjd7r   ${ID}   running   true    aws:///us-east-2a/i-019c51ee0ded3e51a   sample-name-tag-workers-55b788fd4dx5n4zb-kn2h6
sample-name-tag-251d8688-hwhb4   ${ID}   running   true    aws:///us-east-2a/i-0c9169fb1781d2a8e   sample-name-tag-workers-55b788fd4dx5n4zb-8brbs
```

**What did you expect to happen:**
One EC2 instance to be created per AWSMachine, with the tag `Name: sample-name-tag`

**Anything else you would like to add:**
I think this occurs because:

1. We try to find an instance during a normal reconcile loop - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/56c9a39dd834640ee4a027e679ad2a5757098dfd/controllers/awsmachine_controller.go#L483-L489 
2. We look for the instance with these tags, including the name of the AWSMachine https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/abd444c27083d5054c772c7bf5101266da10f76f/pkg/cloud/services/ec2/instances.go#L46-L53
3. If `instance == nil`, then a new EC2 instance is created https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/56c9a39dd834640ee4a027e679ad2a5757098dfd/controllers/awsmachine_controller.go#L517C29-L522 
4. However, this only happens when the instance cannot be found by tags (or an AWS not found/permission error). So the bug is with a change in v1beta2 to allow overwriting the `Name` tag: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta2/tags.go#L244-L264

vs v1beta1 https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/abd444c27083d5054c772c7bf5101266da10f76f/api/v1beta1/tags.go#L250-L269 where the AWSMachine's own `.metadata.name` had precedence

So I think we need to either not allow overwriting the `Name` tag or we need to be smarter about how we find the instance based off of tags. Even if we update the filtering logic to account for the additional Name tag, we don't want to find an instance that's already been claimed by another AWSMachine.

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): 
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6+f67aeb3
```
- OS (e.g. from `/etc/os-release`):

**Comment by mjlshen** [comment]
As for why `findInstance` even needs to be called - normally providerID is populated when an EC2 instance has been created at least once, however I noticed that this bug occurred in my case because CAPA did not have the ability to perform `ec2:CreateTags` on ENIs https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/abd444c27083d5054c772c7bf5101266da10f76f/pkg/cloud/services/ec2/instances.go#L272-L281 so the providerID was never returned and lost, resulting in `findInstance` needing to fallback to tag-based detection

**Comment by cnmcavoy** [comment]
I am surprised the AWSMachine controller uses `Name` as a key to look up AWS resources. I would have expected to fallback to a tag key CAPA explicitly controlled, e.g `sigs.k8s.io/cluster-api-provider-aws/aws-machine`.

**Comment by celebdor** [comment]
/retitle OCPBUGS-23174: AWSMachine controller leaks EC2 instances when specifying a Name tag in additionalTags

**Comment by celebdor** [comment]
sorry for the noise

**Comment by dlipovetsky** [comment]
From today's office hours: I wonder if can address this once and for all by using the _client token_ strategy described in https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html
