### ISSUE TITLE
upstream dependencies on kubernetes v1.13

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#467]
Issue to track blocking upstream issues

We need dependencies to use kubernetes version 1.13 (update later with reasons why)

https://github.com/kubernetes-sigs/controller-runtime/issues/275

**Comment by detiber** [comment]
/active

Initial controller-runtime PR: https://github.com/kubernetes-sigs/controller-runtime/pull/279
controller-tools and kubebuilder PRs will be handled as followups due to the chained dependencies

**Comment by detiber** [comment]
closing since we now vendor k8s v1.13
