### ISSUE TITLE
make manifests fails with aws_manager_image_patch.yaml: no such file or directory

### ISSUE THREAD

**Issue by babu-selector** [kubernetes-sigs/cluster-api-provider-aws#469]
/kind bug

sigs.k8s.io/cluster-api-provider-aws $ make manifests
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd
CRD files generated, files can be found under path /Users/babu-s2/go/src/sigs.k8s.io/cluster-api-provider-aws/config/crds.
kustomize build config/default/ > cmd/clusterctl/examples/aws/out/provider-components.yaml
Error: SliceFromPatches: open /Users/babu-s2/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/aws_manager_image_patch.yaml: no such file or directory

**What did you expect to happen:**
The startup guide steps are broken, not working as mentioned.

**Anything else you would like to add:**

 Workaround is to run ./generate-yaml.sh explicitly

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ashish-amarnath** [comment]
https://kubernetes.slack.com/archives/CD6U2V71N/p1547570376262000
The workaround was to run `make clean manifests`

**Comment by ashish-amarnath** [comment]
@rdodev Do you have anything more to add here?

**Comment by rdodev** [comment]
Sorry @ashish-amarnath didn't get notifications until now. Let me check it out.

**Comment by rdodev** [comment]
@babu-selector is right. I think the docs seems to be missing steps or provide incomplete info. Both the `make clean && make manifests` and then using Jason's gist helped for instructions not using minikube.

**Comment by chuckha** [comment]
This will be going away as we start merging in pieces of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/310. I'll track the work but I don't think this needs to be fixed independently of the Makefile changes

/lifecycle active

**Comment by randomvariable** [comment]
Fixed in #580 

Removed `aws_manager_image_patch.yaml` completely, so this issue will no longer apply.

/close
