### ISSUE TITLE
ROSA: Extend ROSAControlPlane API

### ISSUE THREAD

**Issue by muraee** [kubernetes-sigs/cluster-api-provider-aws#4737]
/kind feature

**Describe the solution you'd like**
`ROSAControlPlane` CRD should be extended to include the following fields:
- Autoscaling
- ComputeMachineType
- ServiceCIDR
- PodCIDR
- HostPrefix
- PrivateLink
- EtcdEncryption (bool) / EtcdEncryptionKMSKey
- Tags

ROSAControlePlaneController would need to be adjusted to reconcile these fields.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by stevekuznetsov** [comment]
- [ ] Autoscaling
- [ ] ComputeMachineType
- [ ] ServiceCIDR
- [ ] PodCIDR
- [ ] HostPrefix
- [x] PrivateLink https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4758
- [ ] EtcdEncryption (bool) / EtcdEncryptionKMSKey
- [ ] Tags
