### ISSUE TITLE
Makefile build fails in certain edge case

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#476]
/kind bug

**What steps did you take and what happened:**
Build the release binaries and then build the dev binaries and see what happens

from @detiber from #473 
> Just noticed the wildcard here, this will cause issues if someone has run the release-binaries target and cross compiled binaries for other targets.

**What did you expect to happen:**
installation to be successful and the correct platform/arch for the current host

**Comment by sfzylad** [comment]
I'd like to work on this issue, please.

**Comment by vincepri** [comment]
@sfzylad You can use `/lifecycle active` command on its own line to assign yourself this issue.

**Comment by sfzylad** [comment]
@vincepri Thanks for the hint 👍
