### ISSUE TITLE
Support for additionalControlPlaneIngressRules in AWSManagedControlPlane

### ISSUE THREAD

**Issue by fad3t** [kubernetes-sigs/cluster-api-provider-aws#4788]
/kind feature

**Describe the solution you'd like**
It would be great to have support for additional control plane ingress rules when using the AWS managed control plane.
Currently, the additional security group gets created but is empty, even if additional ingress rules are specified in the managed control plane specs.

**Environment:**
- Cluster-api-provider-aws version: current (v2.3.x)
- Kubernetes version: (use `kubectl version`): 1.28.3
- OS (e.g. from `/etc/os-release`): AL2

**Comment by alagukannan** [comment]
did this get merged?
