### ISSUE TITLE
[failing-test] periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/cluster-api-provider-aws#4858]
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-conformance-main-k8s-main

See https://github.com/kubernetes/kubernetes/issues/123663 for context.

**Comment by richardcase** [comment]
Tesgrid for this: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-conformance-main-k8s-main
