### ISSUE TITLE
[cluster actuator] Reconcile NAT Gateway

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#49]
The cluster actuator should create and manage NAT gateway configuration for actuator-managed private subnets. It should not create a NAT gateway for user-provided pre-existing private subnets that are provided through the ProviderConfig.

Depends on: #47, #38, #35 

/kind feature
/priority important-soon

**Comment by vincepri** [comment]
Closing, see https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/47#issuecomment-422564463.
