### ISSUE TITLE
Documentation of startup guide  doesn't reflect the current configuration process

### ISSUE THREAD

**Issue by bsingarayan** [kubernetes-sigs/cluster-api-provider-aws#490]
/kind bug

1. region is missing in the startup guide steps 

For example

aws ec2 create-key-pair --key-name cluster-api-provider-aws.sigs.k8s.io  | jq .KeyMaterial -r

fails as it misses the region, I just included below in the command to make it work

aws ec2 create-key-pair --key-name cluster-api-provider-aws.sigs.k8s.io --region us-east-1 | jq .KeyMaterial -r

2. As per the document, the below command doesn't work unless the non-IAM user configuration is set up.

export AWS_REGION=us-east-1
clusterawsadm alpha bootstrap create-stack

The document doesn't tell me clearly what commands are to be executed by IAM user and the rest by non-IAM user(owner)

Also, the documentation assumes the users of this page are experts on AWS account handling(like setting up keys, IAM users etc..). That shouldn't be the same IMHO.

**Please note: I am filing this bug out of frustration spending more than a week and still couldn't get the cluster up and running.**

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
/milestone v1alpha1
/assign @chuckha 
/kind documentation

Assigning you because I remember you were also tackling other docs issues
