### ISSUE TITLE
Include CA and service account keypairs in cluster spec.

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api-provider-aws#492]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Goal: Cluster operators should be able to supply cert material for CA and SA keypairs for the clusters that they create.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
As discussed here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/463#discussion_r246430304

Include CA and service account keypairs to be part of the cluster provider spec.
Actuator will then use the fields in the cluster provider spec to create the CA and SA keypairs for kubeadm to use.

cc @detiber @chuckha 

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
@ashish-amarnath can you update the issue description with a summary of the linked discussion? I'd be good for newcomers that don't have the full context.

**Comment by ashish-amarnath** [comment]
Missed this notif. @chuckha lmk if you need the context @vincepri wanted me to include.

**Comment by chuckha** [comment]
I think the @vincepri's point is to keep a record on this issue since we decided to break it out. Linking to the conversation is good, but it would be even better to have a summary of what was discussed and why we're breaking this work item out so that people don't actually have to read our thread unless they really want to.
