### ISSUE TITLE
UX: Provider Components manifest generation should use AWS credential provider chain

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#494]
/kind bug

Part of #276 

**What steps did you take and what happened:**
The process by which to generate the provider components manifest for clusterctl, currently `make manifests` should use the default AWS credential provider.

**What did you expect to happen:**
Credentials from ~/aws/config to be used for bootstrapping the cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

`clusterawsadm` is currently responsible for this part of the manifest generation

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
If anyone can find where this is in the Go SDK, please comment. https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/chain_provider.go#L61 is the closest I've got to, but still looks like I need to pass an array of providers.

**Comment by rdodev** [comment]
As per their documentation, this is the method to retrieve credential from the default chain: https://docs.aws.amazon.com/sdk-for-go/api/aws/defaults/#CredChain
