### ISSUE TITLE
IMDSv2 and default tags

### ISSUE THREAD

**Issue by gburke-ppb** [kubernetes-sigs/cluster-api-provider-aws#4995]
/kind bug

**What steps did you take and what happened:**
When creating an EKS Cluster the `AWSManagedMachinePool` is adding some default tags, `kubernetes.io/cluster/<cluster-name>`  being one.
We have an account setup to use IMDSv2, and our Security team won't allow us to use IMDSv1 on it.
One of the changes with IMDSv2 is the allowed characters in a tag name -- specifically `/` is no longer allowed (especially so with instance metadata tags enabled).

So we get this reconciler error:
```
E0530 11:10:10.864609       1 controller.go:329] "Reconciler error" err=<
    failed to reconcile machine pool for AWSManagedMachinePool my-cluster/my-cluster: failed to create nodegroup: failed to create nodegroup: InvalidRequestException: 'kubernetes.io/cluster/my-cluster' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index')
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      },
      Message_: "'kubernetes.io/cluster/my-cluster' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index')"
    }
 > controller="awsmanagedmachinepool" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSManagedMachinePool" AWSManagedMachinePool="my-cluster/my-cluster" namespace="my-cluster" name="my-cluster" reconcileID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
 ```
 
 I have tried adding
 ```
 ...
               forProvider:
                manifest:
                  apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
                  kind: AWSManagedMachinePool
                  ...
                  spec:
                    ...
                    awsLaunchTemplate:
                      ...
                      metadataOptions:
                        httpTokens: required
                        httpPutResponseHopLimit: 2
                        instanceMetadataTags: disabled
```
(as per [here](https://cluster-api-aws.sigs.k8s.io/topics/instance-metadata)) to no avail.

**What did you expect to happen:**
Certainly not this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v2.5.0
- Kubernetes version: (use `kubectl version`): 1.30
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

```
Installing Provider="cluster-api" Version="v1.7.2" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.7.2" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.7.2" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-aws" Version="v2.5.0" TargetNamespace="capa-system"
```

**Comment by gburke-ppb** [comment]
![image](https://github.com/kubernetes-sigs/cluster-api-provider-aws/assets/67321087/690efad2-b0fe-4e71-897c-b4f9bd27cc68)

Interestingly, with these settings everything works!

The main setting that causes us issues is the “Access to tags in metadata” – if this is `Enabled` then we can’t create a nodegroup because of the tags with a `/` in them.

**Comment by jwitko** [comment]
This is still a real and valid issue.
/reopen
