### ISSUE TITLE
Setting up test infra automation

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-aws#5]
Required mundge github 
bots 
talk with @spiffxp about where we are going to release artifacts
setup integration with testgrid 
talk with @roberthbailey about having a separate cluster-api specific suite. 
...

**Comment by chuckha** [comment]
So far there are already specific suites for each provider and cluster-api. 

Please see:

[cluster-api-provider-aws](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws) and [cluster-api](https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api)

**Comment by chuckha** [comment]
[mungegithub is deprecated](https://github.com/kubernetes/test-infra/tree/master/mungegithub#deprecation-warning) and we should be using prow plugins.

**Comment by detiber** [comment]
@timothysc release artifacts came up during the cluster-api meeting this week and currently the gcr.io/k8s-cluster-api bucket currently requires a Googler to push to, but @roberthbailey has offered to support pushing images until permissions can be granted to provider repo owners.

**Comment by chuckha** [comment]
I think this ticket is closed. @timothysc We have test infra now and we have release binaries figured out. Please open issues with more detail if more needs to be done. For example, what functionality does mungegithub provide that we don't have that we might want out of a prow plugin?

**Comment by timothysc** [comment]
Awesome, thx @chuckha @detiber !
