### ISSUE TITLE
Should InternalDNS names be lower-cased

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api-provider-aws#5049]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When using custom DHCP options for a VPC, with a custom hostname that contains capital letters, the Machine status will report the InternalDNS name using both the AWS and custom hostnames for the Machine.

The custom hostname is currently reported cased exactly as it is in the AWS DHCP options, however, if you are using the AWS EC2 metadata service to pull the hostname, and using that to set the hostname of your nodes using the `--hostname-override` flag, then while you are passing that value through, [kubelet](https://github.com/kubernetes/kubernetes/blob/2d4514e1690dc5babb144542da799f6b331afd1b/staging/src/k8s.io/component-helpers/node/util/hostname.go#L45) lower cases the string since Kube object names must be lower cased.

This creates an inconsistency between the node name being lower case and the Machine status showing a mixed case value.

**What did you expect to happen:**

DNS names are not case sensitive anyway, but I wondered, should CAPA be lower-casing InternalDNS names to be consistent?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This may well be a won't fix, but I wanted to see what others thought to the idea of blanket lower casing DNS names.

I've looked at how other providers might do this (Azure, GCP, vSphere), but, for them, the way the names and addresses come across is all sourced from Kube naming anyway, so there cannot be an discrepancy.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by JoelSpeed** [comment]
/remove-lifecycle stale

This is relevant still

**Comment by nrb** [comment]
I think this causes issues downstream of CAPA, so that even if our systems are working, anything else that relies on hostnames (for example, certificates) might fail if the casing aren't consistent.
