### ISSUE TITLE
switch to aws-sdk-go-v2 as v1 is going away

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api-provider-aws#5068]
Context: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
Migration guide: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

Basically maintenance mode on July 31, 2024 and reach end-of-support on July 31, 2025. The SDK will not 
receive API updates for new or existing services, or be updated to support new regions.

**Comment by mjlshen** [comment]
I would like to work on this if there are no objections

/assign

**Comment by richardcase** [comment]
We already an issue for this #2225.

@mjlshen - feel free to comment and  work on #2225 if you want.

**Comment by richardcase** [comment]
As this is a duplicate:

/close

**Comment by richardcase** [comment]
And thank you @dims for thinking of CAPA
