### ISSUE TITLE
EKS managed addon configuration changes are not flagged for reconciliation

### ISSUE THREAD

**Issue by d-g-town** [kubernetes-sigs/cluster-api-provider-aws#5086]
When reconciling EKS managed addons, CAPA does not check whether the configuration field has changed: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/28159461db6a61f0da6693ad6190eb4a0ac68e52/pkg/eks/addons/types.go#L38

**Comment by gutmensch** [comment]
Thanks @d-g-town for creating the issue, can confirm this for release 2.6.1. Changing configuration (e.g. adjusting resources in the csi plugin) does not yield a reconciling, only when combined with e.g. bumping the plugin version itself, then the configuration is update along with the plugin itself.
```
> kubectl get awsmanagedcontrolplane 87d4ab6a -n pre -o json | jq '.spec.addons'
[
  {
    "configuration": "{\"controller\":{\"resources\":{\"requests\":{\"cpu\":\"10m\",\"memory\":\"40Mi\"},\"limits\":{\"memory\":\"100Mi\"}}},\"node\":{\"resources\":{\"requests\":{\"cpu\":\"10m\",\"memory\":\"40Mi\"},\"limits\":{\"memory\":\"100Mi\"}}}}",
    "conflictResolution": "overwrite",
    "name": "aws-ebs-csi-driver",
    "version": "v1.36.0-eksbuild.1"
  },
  {
    "configuration": "{\"enableNetworkPolicy\":\"true\"}",
    "conflictResolution": "overwrite",
    "name": "vpc-cni",
    "version": "v1.18.5-eksbuild.1"
  }
]
```
