### ISSUE TITLE
New line required in error printing

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#511]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`clusterawsadm` should produce a line break between status and error message. e.g.

```
Attempting to create CloudFormation stack cluster-api-provider-aws-sigs-k8s-ioError: failed to create AWS CloudFormation stack: OptInRequired: The AWS Access Key Id needs a subscription for the service
        status code: 403, request id: <blah>
```

**What did you expect to happen:**

```
Attempting to create CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
<New line here>
Error: failed to create AWS CloudFormation stack: OptInRequired: The AWS Access Key Id needs a subscription for the service
        status code: 403, request id: <blah>
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
`Version Info: GitReleaseTag: "v1.0.0-alpha.3", MajorVersion: "1", MinorVersion:"0", GitReleaseCommit:"1d5a033234f40b", GitTreeState:"clean"`
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
@ishantanu we would most definitely welcome a PR for this issue if you would like to work on it.

**Comment by vincepri** [comment]
Of course! You can use `/lifecycle active` to take it :)

**Comment by detiber** [comment]
Assigning to myself for tracking, since we cannot assign to non-org members

/assign
