### ISSUE TITLE
Implement MachineClassProviderSpec

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#513]
/kind feature

**Describe the solution you'd like**
In order to make full use of the cluster-api APIs we will need to implement a MachineClass provider spec that can be used to specify machine types on AWS.

We may decided we don't need this part of cluster-api. If that is the case, close this issue.

**Anything else you would like to add:**
Please see https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machineclass_types.go#L33

**Environment:**

**Comment by detiber** [comment]
I don't think there is a requirement to implement any additional types for supporting MachineClass, I think the only thing that is needed is to extend the way that we are decoding the ProviderSpec to also support references to a MachineClass instead of just directly embedded values.

**Comment by detiber** [comment]
This ties into the work I'm doing around updating the pivoting logic for clusterctl

/assign
/lifecycle active
