### ISSUE TITLE
[e2e] Tests are failing on main

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#5165]
/kind bug

**What steps did you take and what happened:**

The e2e tests are failing on main before it gets to anything to do with the AMIs. Looking at the error its failing when running kustomize here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/e2e/shared/suite.go#L79

The error is:

```
Error: trouble configuring builtin PatchTransformer with config: `
patch: platform-kustomization.yaml
`: unable to parse SM or JSON patch from [platform-kustomization.yaml]
```

I created a PR (see #5164) to just run the e2e on main.

**What did you expect to happen:**

I'd expect the e2e to get past this point.

**Anything else you would like to add:**

I don't see what has changed in this area, the upstream function (see this: https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/kubernetesversions/template.go#L71) hasn't changed in years.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by damdo** [comment]
Likely due to: https://github.com/kubernetes-sigs/cluster-api/pull/10294

We'll need updating kustomize to v5
