### ISSUE TITLE
[aws] Idempotent create instance

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#53]
There was talk of tokens and tags and opinions and I'd like to capture those ideas here.

cc @kris-nova @csrwng

**Comment by csrwng** [comment]
For creating instances we can use client tokens to ensure uniqueness of the instance to create. Info here: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html
One option would be to use the machine UID as the token. Or if we want to not rely on a specific UID, we could generate a hash based on Name + Namespace.

**Comment by detiber** [comment]
Updating priority because I think we want to solve this before we get too far into the implementation

/priority important-soon

**Comment by detiber** [comment]
I think we also want to get general agreement into the contract we want to provide about idempotent creation and deletion of AWS resources to ensure that we are not leaving users with orphaned resources.

kops relies heavily on tags applied to created resources
kubicorn relies on storing the resource ids as part of the state and relies on deleting resources when failures are hit.

Some conditions we'll need to take into account:
- resource create succeeds, but subsequent tagging fails
- resource creates succeeds, but update of cluster/machine object fails
- attempting to delete resource fails after a successful create it but before recording/tagging it
- the controller/actuator dies after creating a resource but before tagging and or recording the resource

I don't think we'll be able to fully solve all of the potential problems, but we need to target a best effort and leave a clean logging/event trail for users to be able to manually resolve the cases we can't.
