### ISSUE TITLE
Tagging failures can result in orphaned resources

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#539]
/kind bug

**What steps did you take and what happened:**
Currently the code returns an error if tagging fails, causing resources being created, tags not being applied and internal status not being updated.  

**What did you expect to happen:**
Tagging should be warning users of failures without returning any errors preserving the internal status update.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by randomvariable** [comment]
In a follow up call with @ashish-amarnath, @detiber, and @chuckha on 2019/03/01, the consensus reached is that we should error on the failure of tagging, and return.

This wouldn't fix this issue, but make it a "wontfix".

The first step would be to update the [AWS resource handling](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/proposal/aws-resource-handling.md) doc with the pros and cons of different proposals, and how it particularly ties into #608 

We should also reconsider whether or not this is going to be addressed in v1alpha1.

**Comment by ncdc** [comment]
Going to remove milestone so we can re-triage
/milestone clear

**Comment by ncdc** [comment]
@randomvariable bumped the AWS SDK and there might be new features available for better retrying. Will investigate.

/assign @randomvariable 
/milestone v0.5.0
/unassign @detiber

**Comment by randomvariable** [comment]
Have had reports of issues with EC2 from 2019-10-24 onwards.
Specifically, the following types of resources intermittently fail a tagging operation with the following errors:
* Client.InvalidGroup.NotFound
* Client.InvalidRouteTableID.NotFound
* Client.InvalidInternetGatewayID.NotFound
* Client.InvalidSubnetID.NotFound

**Comment by detiber** [comment]
We could do some better guarding than we do today by generating an idempotency token for resources that do not support tagging on create, persisting that token to the api server (and ensuring success) prior to the creation of the aws resource.

I'm not sure every resource that we use that does not support tagging on create actually supports idempotency tokens, though.

**Comment by ncdc** [comment]
Do we think we'll have time to do anything about this for the upcoming release?

**Comment by ncdc** [comment]
Going to reevaluate for v1alpha4 planning.
/milestone Next

**Comment by randomvariable** [comment]
/lifecycle frozen

There's been some API improvements around supporting ClientTokens in the EC2 API, so will look at some easy wins.

Going to 
/assign

but if anyone else wants to pick this up, please say so until I actually mark it as actively being worked upon.

**Comment by randomvariable** [comment]
This is kind of solving itself. EC2 is slowly adding Tag on create, and we've been updating the code to do that as the API gets fixed.

/close
