### ISSUE TITLE
[aws] Test framework and implementation for AWS.

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#54]
In order to avoid having to manually build out fake interfaces for all AWS APIs we are interacting with we should look into leveraging some auto-generation or automation.

We can potentially leverage existing work from KOPS or openshift/cluster-operator here.

cc @csrwng 
/kind feature
/priority important-soon

**Comment by chuckha** [comment]
I'm hoping we're able to scope down the interfaces enough to make test mocking less onerous.

**Comment by vincepri** [comment]
@detiber @chuckha given that this is covered by gomock, is it ok to close?

**Comment by chuckha** [comment]
gomock gets the job done.
