### ISSUE TITLE
Unable to generate manifests via make

### ISSUE THREAD

**Issue by ishantanu** [kubernetes-sigs/cluster-api-provider-aws#540]
/kind bug

**What steps did you take and what happened:**
I was following this guide - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/getting-started.md.

Everything went well until this - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/getting-started.md#generating-cluster-manifests-and-example-cluster.

When I ran `make manifests`, these are the files it generated:

```
➜  cluster-api-provider-aws git:(master) ✗ make manifests

clusterawsadm alpha bootstrap generate-aws-default-profile > cmd/clusterctl/examples/aws/out/credentials
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd
CRD files generated, files can be found under path /Users/shantanudeshpande/cloudssky_contrib/src/sigs.k8s.io/cluster-api-provider-aws/config/crds.
kustomize build config/default/ > cmd/clusterctl/examples/aws/out/provider-components.yaml
2019/01/31 22:19:33 Adding nameprefix and namesuffix to Namespace resource will be deprecated in next release.
echo "---" >> cmd/clusterctl/examples/aws/out/provider-components.yaml
kustomize build vendor/sigs.k8s.io/cluster-api/config/default/ >> cmd/clusterctl/examples/aws/out/provider-components.yaml
2019/01/31 22:19:33 Adding nameprefix and namesuffix to Namespace resource will be deprecated in next release.

➜  cluster-api-provider-aws git:(master) ✗ ls cmd/clusterctl/examples/aws/out
aws_manager_image_patch.yaml cluster.yaml                 credentials                  provider-components.yaml
```

Whereas, as per docs this file `cmd/clusterctl/examples/aws/out/machine.yaml` should've also been generated (if I am following the docs correctly).

Also, these files are generated empty:
1. `cmd/clusterctl/examples/aws/out/aws_manager_image_patch.yaml`
2. `cmd/clusterctl/examples/aws/out/cluster.yaml`

**What did you expect to happen:**
`cmd/clusterctl/examples/aws/out/machine.yaml` to be generated while running `make manifests`.

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): `v1.12.0`
- OS (e.g. from `/etc/os-release`):  macOS Mojave

**Comment by chuckha** [comment]
@ishantanu did you use a release version of clusterawsadm or did you build it from master?

**Comment by chuckha** [comment]
`make manifests` depends on clusterawsadm. Right now we're in a weird state where our master branch is *very* different from our most recently released version. The released versions pretty much don't work anymore and should not be used. We are working on releasing a new version very soon but we are changing the versioning scheme and need to let the community know so it's taking a bit of time.

**Comment by chuckha** [comment]
I think the initial state was not completely clean (as in `make clean` was not run before `make manifests`).

I think the solution is to make the `.../out` target a phony target.
