### ISSUE TITLE
Alternatives to Kustomize and envsubst

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#549]
/kind feature

**Describe the solution you'd like**
In the current state, the manifest generation requires `kustomize` and `envsubst` to achieve the level of customization we need. This workflow has been working fine so far, but as user configuration grows the complexity of the adhoc bash script will grow as well. In the next iteration, we should think about an alternative solution which would better fit our use cases and requirements.

**Comment by randomvariable** [comment]
`kustomize` was removed from the user workflow, but envsubst remains. Tracking in existing issue #299

/close
