### ISSUE TITLE
Repeated error message with clusterawsadm

### ISSUE THREAD

**Issue by ishantanu** [kubernetes-sigs/cluster-api-provider-aws#550]
/kind bug

**What steps did you take and what happened:**
I was trying to create a cloudformation stack with `clusterawsadm`'s `create-stack` command at which point I stumbled upon the case where an error was displayed twice.

```
➜  cluster-api-provider-aws git:(master) ✗ clusterawsadm alpha bootstrap create-stack
Attempting to create CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
Error: failed to create AWS CloudFormation stack: AccessDenied: User: arn:aws:iam::XXXXXXXXXXXX:user/bootstrapper.cluster-api-provider-aws.sigs.k8s.io is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-east-2:XXXXXXXXXXXX:stack/cluster-api-provider-aws-sigs-k8s-io/*
	status code: 403, request id: cb7b5896-2958-11e9-92e4-d31491798876
Usage:
  clusterawsadm alpha bootstrap create-stack [flags]

Flags:
  -h, --help   help for create-stack

failed to create AWS CloudFormation stack: AccessDenied: User: arn:aws:iam::XXXXXXXXXXXX:user/bootstrapper.cluster-api-provider-aws.sigs.k8s.io is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-east-2:XXXXXXXXXXXX:stack/cluster-api-provider-aws-sigs-k8s-io/*
	status code: 403, request id: cb7b5896-2958-11e9-92e4-d31491798876
```

**What did you expect to happen:**
1. An error should be displayed only once. 
2. **If** folks are in favor of this: The `cmd.Help()` function should only be called when there is an error with the command (for example, incorrect flags being specified) instead of showing the `Usage:` instruction everytime there is any error.

**Anything else you would like to add:**
1. The error is intended and correct. It's just that it is displayed twice.
2. `clusterawsadm`'s binary was built by `make clusterawsadm` and a released binary was not used for this purpose.

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): `v1.12.0`
- OS (e.g. from `/etc/os-release`): macOS Mojave

**Comment by ishantanu** [comment]
@vincepri I wanted to work on this. In fact, I already started to look into this. I narrowed it down to the fact that these lines print the error twice:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a3f1aeaa6e782ddc2dc515bb9c259cd096a27a8b/cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go#L137-L139

And that the error originates from here:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a3f1aeaa6e782ddc2dc515bb9c259cd096a27a8b/pkg/cloud/aws/services/sts/identity.go#L30-L40.

But, I am a bit stuck in finding out the exact reason. Perhaps, I am missing some smaller detail?

**Comment by vincepri** [comment]
CC @randomvariable ^

**Comment by ashish-amarnath** [comment]
@ishantanu If you are looking for reasons why the `GetCallerIdentity` might be failing, then here's the aws doc https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html.

Also, the error you saw `Error: failed to create AWS CloudFormation stack:...` is coming from 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/services/cloudformation/cloudformation.go#L30-L39
Which is called from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go#L142

**Comment by ishantanu** [comment]
@ashish-amarnath Thanks for the pointers. I saw that changing 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/a3f1aeaa6e782ddc2dc515bb9c259cd096a27a8b/cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go#L137-L139 To
```
if stsErr != nil {
	fmt.Printf("Error: %v", stsErr)
	os.Exit(401)
}
``` resolves the issue of printing the error twice (not really sure if that's the right way). Same goes for condition where the error `failed to create AWS CloudFormation stack` is returned.

**Comment by chuckha** [comment]
We should reconsider our usage of `RunE` given this issue: https://github.com/spf13/cobra/issues/340 I think we don't need `RunE` or we need to silence the output.
