### ISSUE TITLE
Fix up namespaces for the providers

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#551]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The manifests should be cleaned up so components go into meaningful namespaces.
At a first pass, theses should be:

Upstream Cluster API components -> `cluster-api-system`
This provider's components -> `cluster-api-provider-aws-system`
The example cluster -> `default` 

The provider components manifest also includes a double declaration of a `system` namespace that the example cluster then ends up in. These can be removed if the cluster namespace is changed to default.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
The `default` namespace for the cluster and machine object does open the possibility of allowing a user coming in via rbac to then escalate privileges. we should document that production clusters should explicitly set a non-default namespace for cluster / machine objects.

**Comment by detiber** [comment]
Since there are still unresolved questions/concerns around the use of the `default` namespace, I'm removing `good-first-issue`

/remove good-first-issue

**Comment by ncdc** [comment]
@randomvariable is this still an issue? If so, what specifically needs to be addressed?

Any objection to deferring out of v1alpha1?

**Comment by randomvariable** [comment]
The namespace changes of the controllers are cosmetic, and can be punted.

Re: the namespace or the cluster - this was more a recording of a conversation from Slack where it was deemed to be an issue. I'm of the opinion that no change is required, as moving to default brings along security issues.

**Comment by randomvariable** [comment]
Additionally, we should check for a consistent naming standard across the providers.

Definitely punt to next.

**Comment by chuckha** [comment]
/close

we think this is fixed already
