### ISSUE TITLE
Extend kubeadm cloud-init module to support CLI arguments

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api-provider-aws#559]
/kind feature

**Describe the solution you'd like**
Follow-up from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/510/files#r254815203
Kubeadm cloud-init module should support the passing of CLI params to kubeadm operations.
cloud-init repo is at https://github.com/detiber/cloud-init/tree/cluster-api
kubeadm module in this repo is at https://github.com/detiber/cloud-init/blob/cluster-api/cloudinit/config/cc_kubeadm.py

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

cc @detiber

**Comment by ncdc** [comment]
Is this fundamental for v1alpha1 or could we defer it to Next?

**Comment by sfzylad** [comment]
I would say it's better to have than not to. Before swirtching to `cloud-init` we logged more while running `kubeadm`. Now we can't debug joining process as effectively as before.

**Comment by randomvariable** [comment]
@ncdc Not fundamental for v1alpha1. Defer to next as it was about supporting debugging.

**Comment by chuckha** [comment]
Sounds like we'll move back to bash for now, but we are concerned about the size of user data and where the bash will call kubeadm directly

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/849

**Comment by ncdc** [comment]
In v1alpha2, cloud-init bootstrapping is moving to a bootstrap provider. I believe we are trying to move away from a forked copy of cloud-init. If that's the case, closing this makes sense. Otherwise, we could transfer this to https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm. Thoughts?

**Comment by ncdc** [comment]
/close

Let me know if you think this needs to be reopened.
