### ISSUE TITLE
Kustomize 2.0+ not compatible with getting started guide

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#569]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Related to #549 - alternatives to kustomize/envsubst
Related to #276 - UX improvements.

**What did you expect to happen:**
Due to security concerns, the use of commands as a secret generator has been removed, but the current user workflow is reliant upon it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Workflow needs to be fixed to be compatible with Kustomize 2, ideally in a backwards compatible way.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
@randomvariable I don't think we need to enforce backwards compatibility. I'm good with making kustomize 2.x a requirement if we can get everything patched up to work.

**Comment by vincepri** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/issues/745

**Comment by randomvariable** [comment]
Yeah, not intending to. As far as the user-facing bits, they won't notice if we're still using an older kustomize inside bazel to generate bare manifests.
