### ISSUE TITLE
Better CA private key management

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#574]
/kind feature

**Describe the solution you'd like**
Currently we store the generated CA keys and ServiceAccount private key in the Cluster ProviderSpec, this is suboptimal from a security standpoint, but provides a better user experience to users by not requiring them to have some external form of orchestration to create a more secure secret and then link that into the creation of the Cluster object.

In order to provide a balance between the UX and security, instead of only allowing the sensitive key material to be specified using a text field, extending that field to also support one or more external sources for retrieving the key material (kubernetes secrets, AWS Secrets Manager, Hashicorp Vault, etc). There should also be an admission webhook that would migrate any user provided key material (through the text field) to a more secure location prior to allowing the request admission and being persisted to etcd.

/priority important-longterm
/milestone Next

**Comment by ashish-amarnath** [comment]
crumbs: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/492#issuecomment-454148926
