### ISSUE TITLE
gcr.io/cluster-api-aws-controller:latest does not reference latest release

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#593]
/kind bug

/milestone Next
/priority important-longterm

The :latest tag should always point to the latest release. alternatively, :latest should not exist at all.

**Comment by detiber** [comment]
We should probably define what we mean by latest, especially if we start looking at having different release streams (based on the vendored version of kubeadm). Ideally, I'd like for us to not even have a `latest` release outside of CI to avoid any confusion that `latest` means a particular release stream. If we do have a `latest`, then it should probably be built automatically on merges to master, but I would expect that to be pushed to a development repo and not the release repo...

**Comment by chuckha** [comment]
Deleting latest tag is definitely a valid solution to this issue!

**Comment by detiber** [comment]
Since the v0.1.0 release is finally complete, I finished up the tasks for that release by deleting all of the previous releases to avoid future confusion. As part of this I deleted the outdated image for the `latest` tag.
