### ISSUE TITLE
This is this a subproject of sig-cluster-lifecycle exclusively?

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes-sigs/cluster-api-provider-aws#6]
I presume subprojects may span multiple SIGs, and I think it'd make sense for this subproject to also be linked to sig-aws.

**Comment by timothysc** [comment]
It is from the beginning, and I've looped in the appropriate parties.  
/cc @d-nishi

**Comment by timothysc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/OWNERS_ALIASES#L26  

Closing this, as folks have looped in the appropriate lists since epoch.

**Comment by errordeveloper** [comment]
👍
