### ISSUE TITLE
Gazelle warning

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#601]
/kind bug

**What steps did you take and what happened:**
During any Bazel build there is a warning:

```
gazelle: open /Users/akutz/Projects/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/kubernetes/BUILD.bazel: no such file or directory
```

**Anything else you would like to add:**
https://github.com/kubernetes/kubernetes/blob/master/BUILD.bazel is a symlink...

**Environment:**

/milestone Next
/priority important-longterm
/help

**Comment by tahsinrahman** [comment]
adding ```# gazelle:exclude vendor/k8s.io/kubernetes``` in `BUILD.bazel` removes this warning, but i'm not sure if its the correct way to fix this
