### ISSUE TITLE
Restrict IAM policies further to only allow deletion (and possibly update) of resources

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#608]
/kind feature

**Describe the solution you'd like**
While we currently have our IAM policy scoped down with respect to Operations, we can further scope down the policy through the use of Conditions. In particular, we should scope down the Delete operations only to instances that are tagged with the tags we create. We should also investigate if we can further scope down other operations as well.

/priority important-soon
/milestone Next

**Comment by randomvariable** [comment]
Have opened https://github.com/kubernetes/cloud-provider-aws/issues/33 as the cloud provider itself needs better IAM policies to make this truly effective in some scenarios.

**Comment by randomvariable** [comment]
Loose consensus (n=2) is that for Cloud Provider AWS, will scope requests down to objects with the `k8s.io/cluster` tag.

Cloud Provider AWS does not currently set `k8s.io/cluster-provider-aws/managed=true`

**Comment by randomvariable** [comment]
/remove-lifecycle

I've done some initial feasibility investigations in #612, which should be used as a basis for further work, but will want to have e2e for scoping these down.

**Comment by ncdc** [comment]
Actually going to clear the milestone so we re-triage
/milestone clear

**Comment by randomvariable** [comment]
Interest has dropped off on this one.

/close
