### ISSUE TITLE
Need to set ProviderID on common Machine objects

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#610]
/kind bug

**What steps did you take and what happened:**
Deploy a machine using cluster-api-provider-aws, the machine Spec.ProviderID field will be empty

**What did you expect to happen:**
The Spec.ProviderID field should be set with a string in the same format as is populated by Spec.ProviderID on a Node object.

/priority important-longterm
/milestone v1alpha1

**Comment by vincepri** [comment]
@detiber Do you have an example for the string format?

**Comment by detiber** [comment]
https://github.com/kubernetes/kubernetes/blob/30ed3b41b7b080cf37639371726a445032d5ef29/pkg/cloudprovider/providers/aws/instances.go#L48-L53

**Comment by vincepri** [comment]
Could we copy the ProviderID from the Node object now that we're setting the reference?

**Comment by detiber** [comment]
@vincepri as long as we can query Node objects that belong to a remote k8s cluster, since the management cluster may not be local.

**Comment by ncdc** [comment]
Depends on https://github.com/kubernetes-sigs/cluster-api/issues/520

**Comment by ncdc** [comment]
We could consider bumping this to Next if it comes down to the wire - we don't lose any functionality if the data is not populated.
