### ISSUE TITLE
OpenAPI CRD docs

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#613]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The CRDs now have lots of metadata, but has also become less immediately human readable.

Would be nice to publish a formatted version of these somewhere.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
/remove-lifecycle rotten

This may have to wait until Structural Schemas are available, since currently the CRD definition only defines validations and not the actual properties of the CRD objects: https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
