### ISSUE TITLE
Update to Go 1.12

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#623]
/kind feature
/priority important-soon
/milestone next

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As per LWKD, Kubernetes master is now on Go 1.12, Cluster API and Cluster API AWS should be updated to match.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
PR #622 addresses this, but have run into issues documented on the PR.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chuckha** [comment]
is `go mod` implicit in this issue or is that separate?

**Comment by randomvariable** [comment]
`go mod` is separate though it is technically supported by the Go 1.12 compatible bazel rules.

**Comment by randomvariable** [comment]
Probably is worth looking at switching Gazelle out for Kazel though, as that's happened in k/k https://github.com/kubernetes/repo-infra/tree/master/kazel
