### ISSUE TITLE
AWS account using MFA does not work

### ISSUE THREAD

**Issue by lindicvmware** [kubernetes-sigs/cluster-api-provider-aws#653]
/kind bug

**What steps did you take and what happened:**
In the [getting start document ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/getting-started.md)
it says that we have to provide AWS region access key id access key. I think this assumes that we are not using MFA so we do not need to provide session key. When I use MFA and provide a session key the steps provided in the document will not work.

**Comment by randomvariable** [comment]
Which step fails?

Generating an access key pair for `bootstrapper.cluster-api-provider-aws.sigs.k8s.io` is actually optional, but is there to illustrate the common path.

`clusterawsadm` includes support for session tokens set as the `AWS_SESSION_TOKEN` environment variable, and should be ingested when you run `./aws/generate_yaml.sh` if you have previously used `aws-vault` or similar to gain a session token.

**Comment by randomvariable** [comment]
Revisiting this, the binaries published at https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.1.0 which date to Dec 2018 don't support session tokens, but this was later fixed in #518

**Comment by detiber** [comment]
We've updated the binaries attached to the v0.1.0 release. @lindicvmware can you please try again with the updated binaries?

**Comment by ashish-amarnath** [comment]
@lindicvmware  I am assuming you are referring to the [setting-up-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/getting-started.md#setting-up-aws) section of the Getting Started doc.

Can you please follow instructions https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/ to do this?

**Comment by detiber** [comment]
Using a session token should work today. My current workflow uses aws-vault and an account that is MFA-enabled.

**Comment by detiber** [comment]
I'm unable to replicate locally. If this problem still exits, please reopen this ticket with additional information.
