### ISSUE TITLE
Crash with Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#656]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I followed the https://gist.github.com/detiber/8f61767b6d39d65aceab89d5a92589c4 instruction and if I don't wait for VPC creation to finish before creation of any machine, it will crash the controller and controller is unable to recover from the state. 

**What did you expect to happen:**
Recover from crash

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Attach is the stack trace 
```I0227 00:17:46.374001       1 vpc.go:40] Reconciling VPC
E0227 00:17:46.377784       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:522
GOROOT/src/runtime/panic.go:513
GOROOT/src/runtime/panic.go:82
GOROOT/src/runtime/signal_unix.go:390
pkg/cloud/aws/actuators/machine/actuator.go:242
vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:148
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1250acd]

goroutine 156 [running]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x154a880, 0x281b890)
    GOROOT/src/runtime/panic.go:513 +0x1b9
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine.(*Actuator).Delete(0xc0004c3940, 0x194a300, 0xc0000460f0, 0xc0005c81a0, 0xc000336000, 0x0, 0x0)
    pkg/cloud/aws/actuators/machine/actuator.go:242 +0x24d
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine.(*ReconcileMachine).Reconcile(0xc0005df840, 0xc0004367c9, 0x7, 0xc0000451a0, 0x11, 0x282ff00, 0x0, 0x0, 0xc000660558)
    vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go:148 +0xb20
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00045e000, 0x0)
    vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x18f
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
    vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000484040)
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000484040, 0x3b9aca00, 0x0, 0x1, 0xc00052e120)
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000484040, 0x3b9aca00, 0xc00052e120)
    vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
    vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32a```

**Environment:**

- Cluster-api-provider-aws version: latest
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
`sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine.(*Actuator).Delete(0xc0004c3940, 0x194a300, 0xc0000460f0, 0xc0005c81a0, 0xc000336000, 0x0, 0x0)`

Seems like the failure is coming from a `Delete` call, which should have been fixed in #654

**Comment by vincepri** [comment]
Which version of cluster-api-provider-aws is being used? Latest master or released?

**Comment by Lokicity** [comment]
This is the top of my tree.

commit 60789ed2e2bd1aa66fd30348eec3bd39d7b66762 (HEAD -> master, origin/master, origin/HEAD)

**Comment by vincepri** [comment]
Got it! It seems there was a little more information in #657, which seems you're running a `Delete` call right after creation?

**Comment by Lokicity** [comment]
Yeah if it was not created successfully, I try running the delete call, but at that point the controller has already crashed thus deletion doesn't work either.

**Comment by vincepri** [comment]
I'd need to replicate the behavior, although I'm not sure how much it can be done. Each actuator call relies on state to be present and populated. In cases like these destroy/recreate is usually how I'd go about getting things back up. There was some talks about supporting rollback in the future, although I'm not sure if that's still on the table. 

I'll take a look and try to reproduce locally. 😄

**Comment by ashish-amarnath** [comment]
@Lokicity This is what I did in an attempt to repro:
```(bash)
$ kind create cluster --name=clusterapi
$ #Wait for kind cluster to be available
$ kc apply -f cmd/clusterctl/examples/aws/out/provider-components-dev.yaml
$ #Wait for the aws-provider-controller-manager-0 pod to start running
$ kc create -f cmd/clusterctl/examples/aws/out/cluster.yaml &
$ kc create -f cmd/clusterctl/examples/aws/out/machines.yaml &
$ kc delete -f cmd/clusterctl/examples/aws/out/machines.yaml &
```
I wasn't able to repro this crash. 
I ran this at commit [6ff9411](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/6ff9411c2828ef7e15d94f29b708b1467a6f1d00)

Also, the current master is at [78f45a1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/78f45a1d83efe1bcd28eb7cf24acfb74cf19c3f4)

There is a critical fix that you are missing at [60789ed](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/60789ed2e2bd1aa66fd30348eec3bd39d7b66762)

Can you please sync your fork and try again?

**Comment by ncdc** [comment]
@Lokicity could you please give us an update and let us know if Ashish's suggestions helped?

**Comment by DheerajSShetty** [comment]
I faced this issue when creating cluster failed in creating VPC, and on deleting the cluster. Thats when I hit the issue again.
kubectl logs -f  -n aws-provider-system aws-provider-controller-manager-0
I0319 20:52:21.339515       1 plugins.go:39] Registered cluster provisioner "aws"
I0319 20:52:21.341314       1 reflector.go:131] Starting reflector *v1alpha1.Cluster (10h0m0s) from pkg/cache/internal/informers_map.go:126
I0319 20:52:21.341350       1 reflector.go:169] Listing and watching *v1alpha1.Cluster from pkg/cache/internal/informers_map.go:126
I0319 20:52:21.430851       1 reflector.go:131] Starting reflector *v1alpha1.Machine (10h0m0s) from pkg/cache/internal/informers_map.go:126
I0319 20:52:21.430891       1 reflector.go:169] Listing and watching *v1alpha1.Machine from pkg/cache/internal/informers_map.go:126
I0319 20:52:21.540443       1 controller.go:89] Running reconcile Cluster for test1
I0319 20:52:21.540463       1 controller.go:112] reconciling cluster object test1 triggers delete.
I0319 20:52:21.540468       1 actuator.go:92] Deleting cluster test1.
I0319 20:52:21.541845       1 loadbalancer.go:85] Deleting load balancers
E0319 20:52:21.550232       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:522
GOROOT/src/runtime/panic.go:513
GOROOT/src/runtime/panic.go:82
GOROOT/src/runtime/signal_unix.go:390
pkg/cloud/aws/services/elb/loadbalancer.go:162
pkg/cloud/aws/services/elb/loadbalancer.go:88
pkg/cloud/aws/actuators/cluster/actuator.go:104
vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go:113
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1258033]

goroutine 142 [running]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x15b8560, 0x29418a0)
	GOROOT/src/runtime/panic.go:513 +0x1b9
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/elb.(*Service).getAPIServerClassicELBSpec(0xc00000c490, 0xc000693988)
	pkg/cloud/aws/services/elb/loadbalancer.go:162 +0x353
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/elb.(*Service).DeleteLoadbalancers(0xc00000c490, 0xc00000c490, 0xc0000984b0)
	pkg/cloud/aws/services/elb/loadbalancer.go:88 +0x84
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/cluster.(*Actuator).Delete(0xc000285b20, 0xc0003bc9c0, 0x0, 0x0)
	pkg/cloud/aws/actuators/cluster/actuator.go:104 +0x23b
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster.(*ReconcileCluster).Reconcile(0xc000581770, 0xc0000bd420, 0x7, 0xc0000bd410, 0x5, 0x2956180, 0xc0000a7040, 0xc0000cd588, 0x12fbb6d)
	vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go:113 +0x6a9
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002a61e0, 0x0)
	vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x18f
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00024c040)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00024c040, 0x3b9aca00, 0x0, 0x1, 0xc0000845a0)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00024c040, 0x3b9aca00, 0xc0000845a0)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start

**Comment by DheerajSShetty** [comment]
Once my VPC creation succeeded, deletion of cluster does not cause panic as there is a valid VPC to delete in the first place.
I tried the method mentioned by @Lokicity as well and coult not recreate the bug.

**Comment by vincepri** [comment]
@DheerajSShetty Do you have the error shown when the VP creation failed? I think this particular issue is part of rolling back resources on failure. We don't have support for rollback at this point unfortunately, but that's something we should open an issue for and track for later.

**Comment by DheerajSShetty** [comment]
We can open a new bug to track rollback issues. at least to avoid panics

**Comment by ncdc** [comment]
@vincepri @DheerajSShetty is the conclusion that the issue originally reported here is resolved, and we can close this?

**Comment by vincepri** [comment]
I think this can be closed. We should make sure to add a note in the release notes stating that rollbacks aren't supported.

**Comment by ncdc** [comment]
/close

@vincepri @DheerajSShetty could one of you please create the issue to track rollback issues, if needed?
