### ISSUE TITLE
Improve dep experience on slow networks

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#659]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The Makefile used to have the following to reduce the need for a full `dep ensure` run.
`@${DEP} status 2>&1 > /dev/null || make dep-install`

Unfortunately in at least some MacOS configurations, this did not have the expected effect, and was removed in #645. But it does have a serious usability impact on systems where it does work, particularly on slow networks.

Find a solution that works across desktops.

/milestone next
/priority important-longterm

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chuckha** [comment]
switching to go module makes this issue closed 

/close
