### ISSUE TITLE
Mismatched binaries in 0.1.0 release

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#660]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`./clusterawsadm-linux-amd64 version` using the release binary from https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.1.0 

Got 
```
Version Info: GitReleaseTag: "v1.0.0-alpha.4", MajorVersion: "1", MinorVersion:"0", GitReleaseCommit:"41f84093cfa905", GitTreeState:"dirty"
```

This has the side effect that clusterawsadm doesn't produce the credential's secret in a way that's consumable by the examples tar.

**What did you expect to happen:**
```
Version Info: GitReleaseTag: "v0.1.0", MajorVersion: "0", MinorVersion:"1", GitReleaseCommit:"d148b48"
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
/priority critical-urgent
/milestone v1alpha1

Either we kill this release or update the binaries properly?

**Comment by chuckha** [comment]
@detiber @randomvariable can one of you verify?

**Comment by detiber** [comment]
@chuckha The version output of the linux binaries looks good to me:

```sh
~💰 ~/Downloads/clusterctl-linux-amd64 version
Version Info: GitReleaseTag: "v0.1.0", MajorVersion: "0", MinorVersion:"1"
😄 Thu Mar 14 detiber@yeti 🏠
~💰 ~/Downloads/clusterawsadm-linux-amd64 version
Version Info: GitReleaseTag: "v0.1.0", MajorVersion: "0", MinorVersion:"1"
```

**Comment by chuckha** [comment]
awesome, thank you. I checked os x

/close
