### ISSUE TITLE
Do not use relative tags (:latest) in release YAML

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#661]
/kind bug
/priority critical-urgent

**What steps did you take and what happened:**
Release YAML should not have `:latest` hardcoded in the image tag. A release should always reference absolute tags (yes, I know docker tags that are not the SHA of the container image are mutable).

**Comment by detiber** [comment]
I think this will be less of an issue once we are vendoring a tag from cluster-api rather than vendoring a point in time version of the master branch.

That said, we should probably cut interim releases of cluster-api to avoid this issue all together.

**Comment by chuckha** [comment]
This isn't really an issue as pointed by Jason
