### ISSUE TITLE
Error reconciling cluster object; ailed to query ec2 for VPCs: NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api-provider-aws#663]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Followed the setup guide, tried creating a cluster in us-west-2.

Pulled latest code.

built clusterctl and clusterawsadm binary.

ran ./generate-yaml.sh

the provider-components.yaml has a secret appended and looks like this. I am not pasting the secret here.

apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: aws-provider-system
type: Opaque
date:
  credentials:=========

kubectl apply -f provider-components.yaml
kubectl apply -f cluster.yaml

the two pods that are running
aws-provider-system   aws-provider-controller-manager-0                             1/1       Running   0          14h
cluster-api-system    cluster-api-controller-manager-0                              1/1       Running   0          14h

aws-provider-controller-manager-0 logs show 
kubectl -n aws-provider-system logs -f aws-provider-controller-manager-0

I0314 03:08:00.336855       1 controller.go:89] Running reconcile Cluster for test1
I0314 03:08:00.336889       1 controller.go:127] reconciling cluster object test1 triggers idempotent reconcile.
I0314 03:08:00.336896       1 actuator.go:57] Reconciling cluster test1
I0314 03:08:00.337785       1 certificates.go:72] Reconciling certificates for cluster "test1"
I0314 03:08:00.337800       1 network.go:25] Reconciling network for cluster "test1"
I0314 03:08:00.337804       1 vpc.go:40] Reconciling VPC
E0314 03:08:20.743966       1 controller.go:134] Error reconciling cluster object test1; failed to reconcile network for cluster "test1": failed to describe VPCs: failed to query ec2 for VPCs: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
clusterawsadm version
Version Info: GitReleaseTag: "v0.1.0", MajorVersion: "0", MinorVersion:"1", GitReleaseCommit:"d148b486fa4e7f", GitTreeState:"dirty"

- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"archive", BuildDate:"2019-02-14T21:38:58Z", GoVersion:"go1.10.3", Compiler:"gc", 

Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

**Comment by DheerajSShetty** [comment]
@randomvariable CCing you.

**Comment by detiber** [comment]
@DheerajSShetty are you running from the release binaries/images or did you build from `master`? If built from `master` when were the images built? There was a change to the base image and a fix for updating the mount point shortly afterwards to re-align with the base image change here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/83f8bad0bd6430bd186fbbff934ef84cdea8d212

**Comment by DheerajSShetty** [comment]
Built from master. I built the image yesterday evening.

**Comment by randomvariable** [comment]
This is definitely a lack of credentials being present within kind.

@DheerajSShetty did you have AWS credentials set anywhere in your environment, either as environment variables or default profile at the time of running `./generate-yaml.sh`?

You can test this by running `aws sts get-caller-identity` just before `./generate-yaml.sh`.

Also, can you check the volume mount of the secret in the `provider-components.yaml`. If it is not also `manager-bootstrap-credentials`, delete all of those files and restart and see if it reoccurs.

**Comment by detiber** [comment]
After discussing a bit in Slack, we believe the issue comes down to using binaries/manifests generated from the `master` branch along with the images published as part of the v0.1.0 release. So there is a mismatch between the expected location of the aws credentials (image is pre-distroless change, and manifests are expecting the distroless-based image).

**Comment by DheerajSShetty** [comment]
I checked the volume mounted by the aws control manager for the credentials. The credentials matched. 

After discussing with @detiber we suspect the issue is with the image
  image: gcr.io/cluster-api-provider-aws/cluster-api-aws-controller:0.0.4

**Comment by randomvariable** [comment]
Makes sense.

**Comment by detiber** [comment]
@DheerajSShetty closing since I believe this is resolved now, please re-open if you are still having issues.
