### ISSUE TITLE
[aws] DHCP options & association

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#70]
Add code to create and associate dhcp options and association with our vpc

**Comment by chuckha** [comment]
assigning this to you since it fits into the vpc path you're working on. It might not even be necessary, so feel free to close if you don't think we need to do this.

**Comment by vincepri** [comment]
@chuckha As per our discussion this morning, moving this to be long term.

**Comment by timothysc** [comment]
Closing until we have a user request.

**Comment by enxebre** [comment]
fwiw at some point having DHCP options awareness and reflecting it on the machine.status addresses might come in handy for scenarios where users wanting to adopt pre-existing vpcs.

**Comment by detiber** [comment]
@enxebre can you create a new issue to track adding that information to the status?
