### ISSUE TITLE
Is Cluster API Provider AWS clashing with cloud provider code?

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#704]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Drawing https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/697#issuecomment-480075174 into it's own issue:

We're tagging that cluster-api-provider-aws is managing the resource (`sigs.k8s.io/cluster-api-provider-aws/managed=true`, and we are also tagging everything that is managed by the provider with the cluster ID (`kubernetes.io/cluster/blah=owned`, because we use it for reconciliation.

Unfortunately, the AWS cloud provider only checks for cluster ID `kubernetes.io/cluster/blah=owned`, and ends up mutating resources being managed by this provider.

**What did you expect to happen:**
> Give therefore to the emperor the things that are the emperor’s, and to God the things that are God’s

Substituting the AWS Cloud Provider for the emperor, and Cluster API for God.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by rudoi** [comment]
:+1: just for the "What did you expect to happen" block

**Comment by sethp-nr** [comment]
It sounded in #701 like there was enough work colliding here to put on the agenda for Monday's meeting, which sounds like a great time to discuss answers for this.
