### ISSUE TITLE
Node join configuration is empty

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#711]
/kind bug

**What steps did you take and what happened:**
Created a new cluster, the controlplane went up successfully, but nodes can't join. 

**What did you expect to happen:**
Node to join.

**Anything else you would like to add:**
SSH'd into the node and it seems that the join configuration si

```
---
apiVersion: kubeadm.k8s.io/v1beta1
caCertPath: ""
discovery:
  tlsBootstrapToken: ""
kind: JoinConfiguration
nodeRegistration: {}
```

**Environment:**

- Cluster-api-provider-aws version: latest master
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
@chuckha Do you mind taking a look at this? Tracing back the changes seems https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/707/files#diff-d847f3bba360ab8ef215b2d78a0034ddL174 was the latest one.

**Comment by chuckha** [comment]
@vincepri thanks for catching that. The full implementation has fixed it: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/709

**Comment by chuckha** [comment]
fixed
