### ISSUE TITLE
Followup from Logging as Dep PR

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#716]
This is a checklist of the more minor things to figure out after the major refactor

- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/714#discussion_r274951956
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/714#discussion_r274952021
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/714#discussion_r274953445

/assign
/lifecycle active
/priority backlog
/milestone Next

**Comment by detiber** [comment]
@chuckha is this issue still valid?

**Comment by chuckha** [comment]
/remove-lifecycle rotten

I'll look into these and see if they are still relevant.

**Comment by vincepri** [comment]
I think we solved this issue when we moved to Kubebuilder v2 and the new loggers

**Comment by chuckha** [comment]
two were invalid one was still a valid unhandled/unlogged error, I opened a PR to fix the unhandled error.
