### ISSUE TITLE
replace ClusterConfiguration with static pod manifest for kube-apiserver/controller-manager/scheduler ...

### ISSUE THREAD

**Issue by qingzhhu** [kubernetes-sigs/cluster-api-provider-aws#727]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
remove kubeadm join/kubeadm init happened at boot time.
instead just pass static pod manfiests for kube-apiserver/kube-controller-mannager/kubec-scheduler to the vm with pre-installed images.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
We plan to tackle this in kubeadm here https://github.com/kubernetes/kubeadm/issues/1379 and Cluster API should inherit the functionality as a result.
