### ISSUE TITLE
running ./aws/generate-yaml.sh in clusterctl examples references moved file

### ISSUE THREAD

**Issue by pickledrick** [kubernetes-sigs/cluster-api-provider-aws#758]
/kind bug

**What steps did you take and what happened:**
ran ./aws/generate-yaml.sh

saw

Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/cluster.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machines.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machines-ha.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machine-deployment.yaml
Done copying /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/addons.yaml
Generated credentials
cat: /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/provider-components-base.yaml: No such file or directory

**What did you expect to happen:**

Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/cluster.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machines.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machines-ha.yaml
Done generating /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/machine-deployment.yaml
Done copying /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/addons.yaml
Generated credentials
Done writing /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/provider-components.yaml
WARNING: /Users/$USER/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterctl/examples/aws/out/provider-components.yaml includes credentials

**Anything else you would like to add:**
I know this is small but helps with adoption if getting started things are easier

**Comment by detiber** [comment]
@pickledrick is this still an issue? I believe the missing file is generated by bazel and you should be able to run `make manifests` if trying to generate from the repo rather than the release artifacts.

**Comment by vikaschoudhary16** [comment]
`make manifests` also resulting in error:

```
(unset)
bazel build --workspace_status_command=./hack/print-workspace-status.sh //cmd/clusterawsadm 
ERROR: /root/.cache/bazel/_bazel_root/482d98cbd78a00cef9816d257dd620d9/external/bazel_skylib/lib/unittest.bzl:188:27: name 'analysis_test_transition' is not defined
ERROR: error loading package '': Extension 'lib/unittest.bzl' has errors
ERROR: error loading package '': Extension 'lib/unittest.bzl' has errors
INFO: Elapsed time: 0.058s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
make: *** [Makefile:190: clusterawsadm] Error 1
```

**Comment by ncdc** [comment]
In v0.4.x, we no longer have generate-yaml.sh.
/close
