### ISSUE TITLE
isNodeJoin should be thread safe

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api-provider-aws#763]
/kind feature

**Describe the solution you'd like**
`isNodeJoin` method in the machine actuator is not thread safe. It is possible for two machines to race to be the first controlplane machine and can result in 2 machines, incorrectly, trying to run `kubeadm init`. This can land the cluster in a bad state.

Also, kubedm, until `v1.15`, doesn't support parallel `init` and `join`.

For these reasons,  controlplane machines will have to be added one at a time

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Follow commentary here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/745#discussion_r280096104

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sethp-nr** [comment]
While the code is racy, it's currently run with a parallelism of 1, right? So until that changes, we won't see it?

**Comment by detiber** [comment]
@sethp-nr if using `clusterctl`, yes. If interacting with the api directly there are no assurances.
