### ISSUE TITLE
DNS lookups from worker nodes failing on CAPA cluster

### ISSUE THREAD

**Issue by ashoksekar07** [kubernetes-sigs/cluster-api-provider-aws#769]
/kind bug

I created a CAPA cluster with one control plane node and one worker node. I deployed a pod on  the cluster which ran on the worker node. This pod was not able to access the Core DNS service running inside the cluster. Core DNS and Calico pods were running fine. So, I checked the security groups on the control-plane node and opened the ingress rules to allow all traffic on all ports. As soon as I did this, the pod was able to resolve the DNS addresses.

So, I think there is an issue in CAPA where the security group inbound rules are not being correctly set. But this seems to be an intermittent issue because I created another cluster using CAPA which did not have this issue.

**Environment:**

- Cluster-api-provider-aws version: v0.2.0 
- Kubernetes version: (use `kubectl version`): 1.13.3 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2

**Comment by chuckha** [comment]
Looking into this

/assign @chuckha

**Comment by chuckha** [comment]
Interesting I have not been able to reproduce this using these steps:

I've been creating clusters and running a busybox:1.28 which gets scheduled on the worker node and then doing an `nslookup kubernetes.default` which resolves just fine.

I will try a few more things (like actually matching all versions you described 😂)

**Comment by chuckha** [comment]
This definitely is reproducible on v0.2.0

My guess to why this appeared intermittent for you: you modified the security group, deleted your *instances* and recreated the cluster that used the same instances you had modified. Is that plausible? I believe this is fixed in v0.2.1.

**Comment by chuckha** [comment]
The security group changed between v0.2.0 and v0.2.1. Please use v0.2.1. This commit is what fixed this particular bug:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/c694a556e993c243326d63e38f09ee167dfdd6b8
