### ISSUE TITLE
Rename build/amis to build/images

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-aws#778]
/kind feature

**Describe the solution you'd like**
Please consider renaming `build/amis` to `build/images`. The readme even refers to [_Building base **images**_](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/master/build/amis#building-base-images), and the directory structure change (and subsequent dependency changes) would result in a more portable solution for use with other providers.

**Anything else you would like to add:**
NA

**Environment:**
NA

**Comment by ncdc** [comment]
The image building is moving to a new repo, so we can close this.
/close
