### ISSUE TITLE
Metrics/Tracing

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#78]
Would be good to get at least metrics added early on. 

A cluster operator may want to metrics from the controllers available in their monitoring system of choice, e.g. Prometheus. I would be interested in metrics with regards to the creation, deletion, mutation and failure rates of AWS APIs, and the state of their objects at least to help diagnose when limits have been reached.

Specifically, adding https://opencensus.io/quickstart/go/metrics/ would do this in a vendor agnostic fashion and allow the choice of tracing / metrics system, incl. CloudWatch and AWS X-Ray.

**Comment by randomvariable** [comment]
if there's a strong preference for prometheus client_golang, also fine.

**Comment by vincepri** [comment]
We should have some umbrella issue to track this, not sure what the standards is across k8s components.

CC @detiber

**Comment by randomvariable** [comment]
Found them. https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md

https://docs.google.com/document/d/1U_h7osUDF6plKn_nkDF2Y-EjZA6BY8RR6LfTezrFBwM/edit?ts=5b926ad1 may also be useful.

**Comment by randomvariable** [comment]
From the new KEP, this seems to be important:

> Kubernetes also makes extensive use of a global metrics registry to register metrics to be exposed. Aside from general shortcomings of global variables, Kubernetes is seeing actual effects of this, causing a number of components to use `sync.Once` or other mechanisms to ensure to not panic, when registering metrics. Instead a metrics registry should be passed to each component in order to explicitly register metrics instead of through `init` methods or other global, non-obvious executions.

> While uncertain at this point, once cleaned up, this effort may put us a step closer to having stability guarantees for Kubernetes around metrics. Currently metrics are excluded from any kind of stability requirements.

**Comment by detiber** [comment]
@randomvariable I like this idea very much, should we also track this at the more generic cluster-api level as well?

**Comment by detiber** [comment]
@vincepri I think we can use this issue as the umbrella issue and spawn out more specific issues to address as identified.

**Comment by randomvariable** [comment]
On the last attempt at this, it seemed like one of the best ways for instrumenting AWS calls is to use the `WithContext` methods in the AWS SDK, and add a hook to get stats. It required opening up the HTTP requests to do well, so left it last time.

**Comment by randomvariable** [comment]
Will sync with SIG Instrumentation to get latest advice

**Comment by ncdc** [comment]
@randomvariable I assume you're not actively working on this?

**Comment by randomvariable** [comment]
Nope, would have lifecycled/active'd it if I were.

I didn't provide an update at the time because I think SIG Instrumentation was in the process of considering OpenCensus, which has been added to container runtime now.

**Comment by ncdc** [comment]
Do you still want to be assigned?

**Comment by randomvariable** [comment]
Sure. Now we're upgraded, this is implementable.
