### ISSUE TITLE
gomock is over prescriptive

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#784]
/kind feature

**Describe the solution you'd like**
the Gomock framework makes us mix implementation into the tests. For example, I don't care how many times some function was called in the implementation. I just care that the output looks like what I expect it to.

Gomock regularly gives me this error: `aborting test due to missing call(s)` and that is really unnecessary in most cases. Sometimes it's useful but I don't know why the default is always on.

**Comment by moshloop** [comment]
Could try a mock external ec2 api server: https://github.com/spulec/moto

**Comment by chuckha** [comment]
bigger fish to fry

/close
