### ISSUE TITLE
Resize machine deployment fails

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#787]
/kind bug

For the the current cluster, I tested with machinedeployment replica = 3, created the 3 workers. I then modify the deployment to replica = 2 and something strange happened: one of the worker nodes is terminated on AWS, however, it was brought back by CAPA and recreated again, I double check the machinedeployment and it has replica=2 set.  Error looks like the following:
```E0521 22:39:06.188942       1 machine_scope.go:179] [machine-actuator]/cluster.k8s.io/v1alpha1/79cb5d5abe1a6ce6a3bcb7e1e0a0fe687984dc7e/m42/m42-nodedeployment-m5.large-766fb7b887-z6mhs "msg"="failed to update machine status" "error"="Operation cannot be fulfilled on machines.cluster.k8s.io \"m42-nodedeployment-m5.large-766fb7b887-z6mhs\": the object has been modified; please apply your changes to the latest version and try again"```

My colleague Dheeraj also noticed some issue similar to machine deployment:
```I tried deleting a Machine-Deployment, the original machine deployment was deleted, but.. new machines belonging to that deployment was reconciled by CAPA… they would not have any Nodes attached, but a new machine object belonging to that MachineDeployment was created, and then it got deleted, but then another one with a different name belonging to same deployment was created```

**Comment by vincepri** [comment]
These are the logs when I tried to scale down a MachineDeployment

```
I0522 18:27:24.691652       1 controller.go:113] Reconciling Machine "sample-machinedeployment-85894485fb-bm5sj"
I0522 18:27:24.691740       1 controller.go:170] Reconciling machine "sample-machinedeployment-85894485fb-bm5sj" triggers delete
I0522 18:27:24.691797       1 actuator.go:263] [machine-actuator] "level"=0 "msg"="Deleting machine in cluster"  "cluster-name"="test1" "machine-name"="sample-machinedeployment-85894485fb-bm5sj" "machine-namespace"="default"
I0522 18:27:24.695377       1 instances.go:84] [machine-actuator]/cluster.k8s.io/v1alpha1/default/test1/sample-machinedeployment-85894485fb-bm5sj "level"=2 "msg"="Looking for instance by id"  "instance-id"="i-0603c57000bf49160"
I0522 18:27:24.840985       1 actuator.go:299] [machine-actuator] "level"=0 "msg"="Terminating machine"
I0522 18:27:24.841015       1 instances.go:316] [machine-actuator]/cluster.k8s.io/v1alpha1/default/test1/sample-machinedeployment-85894485fb-bm5sj "level"=2 "msg"="Attempting to terminate instance"  "instance-id"="i-0603c57000bf49160"
I0522 18:27:24.945068       1 instances.go:326] [machine-actuator]/cluster.k8s.io/v1alpha1/default/test1/sample-machinedeployment-85894485fb-bm5sj "level"=2 "msg"="Terminated instance"  "instance-id"="i-0603c57000bf49160"
E0522 18:27:25.015636       1 controller.go:192] Failed to remove finalizer from machine "sample-machinedeployment-85894485fb-bm5sj": Operation cannot be fulfilled on machines.cluster.k8s.io "sample-machinedeployment-85894485fb-bm5sj": the object has been modified; please apply your changes to the latest version and try again
I0522 18:27:26.015922       1 controller.go:113] Reconciling Machine "sample-machinedeployment-85894485fb-bm5sj"
I0522 18:27:26.015976       1 controller.go:170] Reconciling machine "sample-machinedeployment-85894485fb-bm5sj" triggers delete
I0522 18:27:26.016139       1 actuator.go:263] [machine-actuator] "level"=0 "msg"="Deleting machine in cluster"  "cluster-name"="test1" "machine-name"="sample-machinedeployment-85894485fb-bm5sj" "machine-namespace"="default"
I0522 18:27:26.019175       1 instances.go:84] [machine-actuator]/cluster.k8s.io/v1alpha1/default/test1/sample-machinedeployment-85894485fb-bm5sj "level"=2 "msg"="Looking for instance by id"  "instance-id"="i-0603c57000bf49160"
I0522 18:27:26.073527       1 instances.go:46] [machine-actuator]/cluster.k8s.io/v1alpha1/default/test1/sample-machinedeployment-85894485fb-bm5sj "level"=2 "msg"="Looking for existing machine instance by tags"
I0522 18:27:26.154922       1 actuator.go:285] [machine-actuator] "level"=3 "msg"="Instance is nil and therefore does not exist"
I0522 18:27:26.163655       1 controller.go:196] Machine "sample-machinedeployment-85894485fb-bm5sj" deletion successful
```

It does seem one iteration failed to remove the finalizer, which shouldn't happen. Other than that it seems that the deletion was successful.

**Comment by Lokicity** [comment]
I am able to reproduce the issue and here are more logs from CAPI

I0523 00:58:31.983725       1 controller.go:334] Too many replicas for cluster.k8s.io/v1alpha1, Kind=MachineSet b46ee553b2cc9ff639498178c1dddae0e28c9930/m1745-nodedeployment-m5.large-7dcb6c569, need 2, deleting 1
I0523 00:58:31.983810       1 controller.go:341] Found  delete policy
E0523 00:58:32.004068       1 controller.go:181] Failed to reconcile MachineDeployment "b46ee553b2cc9ff639498178c1dddae0e28c9930/m1745-nodedeployment-m5.large": Operation cannot be fulfilled on machinedeployments.cluster.k8s.io "m1745-nodedeployment-m5.large": the object has been modified; please apply your changes to the latest version and try again
I0523 00:58:32.096265       1 controller.go:309] Too few replicas for cluster.k8s.io/v1alpha1, Kind=MachineSet b46ee553b2cc9ff639498178c1dddae0e28c9930/m1745-nodedeployment-m5.large-6f7cdd795f, need 1, creating 1
I0523 00:58:32.096284       1 controller.go:315] Creating machine 1 of 1, ( spec.replicas(1) > currentMachineCount(0) )
E0523 00:58:33.609233       1 controller.go:116] Unable to retrieve Machine b46ee553b2cc9ff639498178c1dddae0e28c9930/m1745-nodedeployment-m5.large-7dcb6c569-q9qqh from store: Machine.cluster.k8s.io "m1745-nodedeployment-m5.large-7dcb6c569-q9qqh" not found

**Comment by Lokicity** [comment]
This is the updated machine deployment yaml

```
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cluster.k8s.io/v1alpha1","kind":"MachineDeployment","metadata":{"annotations":{"machinedeployment.clusters.k8s.io/revision":"1"},"creationTimestamp":"2019-05-22T23:19:39Z","finalizers":["foregroundDeletion"],"generation":2,"labels":{"cluster.k8s.io/cluster-name":"m1745"},"name":"m1745-nodedeployment-m5.large","namespace":"b46ee553b2cc9ff639498178c1dddae0e28c9930","ownerReferences":[{"apiVersion":"cluster.k8s.io/v1alpha1","blockOwnerDeletion":true,"kind":"Cluster","name":"m1745","uid":"70b4ead5-7ce7-11e9-9a98-02debd68392c"}],"resourceVersion":"595828","selfLink":"/apis/cluster.k8s.io/v1alpha1/namespaces/b46ee553b2cc9ff639498178c1dddae0e28c9930/machinedeployments/m1745-nodedeployment-m5.large","uid":"1292af8f-7ce8-11e9-9a98-02debd68392c"},"spec":{"minReadySeconds":0,"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":1,"selector":{"matchLabels":{"cluster.k8s.io/cluster-name":"m1745","set":"node"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"cluster.k8s.io/cluster-name":"m1745","set":"node"},"namespace":"b46ee553b2cc9ff639498178c1dddae0e28c9930"},"spec":{"metadata":{"creationTimestamp":null},"providerSpec":{"value":{"ami":{},"iamInstanceProfile":"nodes.cluster-api-provider-aws.sigs.k8s.io","instanceType":"m5.large","keyName":"gophoton-global-keypair","kubeadmConfiguration":{"init":{"localAPIEndpoint":{"advertiseAddress":"","bindPort":0},"nodeRegistration":{}},"join":{"caCertPath":"","discovery":{"tlsBootstrapToken":""},"nodeRegistration":{}}},"metadata":{"creationTimestamp":null}}},"versions":{"kubelet":"1.14.0"}}}},"status":{"observedGeneration":2,"replicas":3,"unavailableReplicas":3,"updatedReplicas":3}}
    machinedeployment.clusters.k8s.io/revision: "2"
  creationTimestamp: "2019-05-22T23:19:39Z"
  finalizers:
  - foregroundDeletion
  generation: 4
  labels:
    cluster.k8s.io/cluster-name: m1745
  name: m1745-nodedeployment-m5.large
  namespace: b46ee553b2cc9ff639498178c1dddae0e28c9930
  ownerReferences:
  - apiVersion: cluster.k8s.io/v1alpha1
    blockOwnerDeletion: true
    kind: Cluster
    name: m1745
    uid: 70b4ead5-7ce7-11e9-9a98-02debd68392c
  resourceVersion: "615930"
  selfLink: /apis/cluster.k8s.io/v1alpha1/namespaces/b46ee553b2cc9ff639498178c1dddae0e28c9930/machinedeployments/m1745-nodedeployment-m5.large
  uid: 1292af8f-7ce8-11e9-9a98-02debd68392c
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: m1745
      set: node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster.k8s.io/cluster-name: m1745
        set: node
      namespace: b46ee553b2cc9ff639498178c1dddae0e28c9930
    spec:
      metadata:
        creationTimestamp: null
      providerSpec:
        value:
          ami: {}
          iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
          instanceType: m5.large
          keyName: gophoton-global-keypair
          kubeadmConfiguration:
            init:
              localAPIEndpoint:
                advertiseAddress: ""
                bindPort: 0
              nodeRegistration: {}
            join:
              caCertPath: ""
              discovery:
                tlsBootstrapToken: ""
              nodeRegistration: {}
          metadata: {}
      versions:
        kubelet: 1.14.0
status:
  observedGeneration: 4
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 1
```

**Comment by Lokicity** [comment]
kubelet: 1.14.0
CAPA version:
```
Name:               aws-provider-controller-manager-0
Namespace:          b46ee553b2cc9ff639498178c1dddae0e28c9930
Priority:           0
PriorityClassName:  <none>
Node:               worker-7a45d5ce-7b49-11e9-8daf-02ed75df2286/10.1.159.137
Start Time:         Wed, 22 May 2019 16:14:59 -0700
Labels:             control-plane=controller-manager
                    controller-revision-hash=aws-provider-controller-manager-747ff65c4d
                    controller-tools.k8s.io=1.0
                    statefulset.kubernetes.io/pod-name=aws-provider-controller-manager-0
Annotations:        <none>
Status:             Running
IP:                 10.2.3.7
Controlled By:      StatefulSet/aws-provider-controller-manager
Containers:
  manager:
    Container ID:  docker://c545881bf81b634fb98ab17bc8ff90299deafb862ee4425ac4aa2de6a6637941
    Image:         gcr.io/cluster-api-provider-aws/cluster-api-aws-controller:v0.2.1
    Image ID:      docker-pullable://gcr.io/cluster-api-provider-aws/cluster-api-aws-controller@sha256:0c2807ce459a090ccd92ca0c89f35ac47fb6e839ce61ff9216c8bd1ce7957e21
```

**Comment by Lokicity** [comment]
Did more debugging with @vincepri  and it seems like somehow the operation triggered 2 machineset to be  created for the same machine deployment causing the issue.

**Comment by chuckha** [comment]
Interesting, I've not been able to reproduce this with the given versions. How are you editing the machine deployment? I was using `kubectl edit machinedeployment <name>`

**Comment by Lokicity** [comment]
I did `kubectl get -o yaml machinedeployment <name>` and `kubectl apply -f`.

**Comment by chuckha** [comment]
I noticed the containerID is using docker. This makes me think there may be a management cluster AND a kind(?) cluster both controlling the same machinedeployment. I could imagine this behavior if one of them had 2 replicas and the other had 3. Is this a possible scenario at all?

**Comment by chuckha** [comment]
I'd be interested to see your entire workflow (how you are creating a cluster from nothing)

**Comment by Lokicity** [comment]
Provided @chuckha a repro ENV and he was able to repro the issue as well. Also provided my entire workflow. Pending investigation.

**Comment by vincepri** [comment]
@chuckha If you're working on it, can you mark the issue as active?

/cc @liztio

**Comment by chuckha** [comment]
I was able to reproduce this issue by using a typed client to create a MachineDeployment and an undefined creationTimestamp in the providerspec metadata.

This reproduces regularly when you `kubectl get machinedeployments -o yaml > file.yaml`, edit the replicas from 3 to 2 (for example) and `kubectl apply -f file.yaml`. Jordan thinks it's because kubectl apply will remove the field (thus resulting in an empty object for the metadata) and the unstructured unstructured for CRD will let the null go in.

**Comment by chuckha** [comment]
Here is a gist containing a script to create a MachineDeployment using the AWS provider with a typed client: https://gist.github.com/chuckha/19628c3e42de3020299a7c3139d98bbd

as well as the yaml for the machine deployment before and after the kubectl apply is issued in addition to the machinesets before and after (there are two after and one before ⚠️ )

**Comment by chuckha** [comment]
/priority important-longterm
/remove-lifecycle active

We now know about this but there is an easy work around; ensure creation time is defined. The fix will be in upstream cluster-api and how machinedeployments detect the machinesets they are responsible for.

**Comment by vincepri** [comment]
This should be fixed upstream in https://github.com/kubernetes-sigs/cluster-api/pull/1054

**Comment by vincepri** [comment]
This is going to be fixed in v1alpha2.

@Lokicity Let me know if you need this to be patched in v1alpha1 as well, we can probably work to backport a fix.

**Comment by Lokicity** [comment]
We will port CAPI 0.1.6 and CAPA 0.3.4 later this week. It should be good. Thanks @vincepri

**Comment by ncdc** [comment]
@Lokicity is this still an issue for you?

**Comment by Lokicity** [comment]
@ncdc  This issue has been fixed. Closing the ticket. Thanks
