### ISSUE TITLE
AWS node came up however not joined to cluster if version differ.

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#792]
/kind bug

**What steps did you take and what happened:**
I have a set up with a cluster of 1 master node and 3 worker nodes in a machine deployment. The nodes are version 1.14.0.  I created another machine deployment with version 1.13.6 and the new node is created in AWS however unable to join

Attach is the cloud-init error:

```
[join] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.13" ConfigMap in the kube-system namespace
configmaps "kubelet-config-1.13" is forbidden: User "system:bootstrap:hpgtc2" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
Cloud-init v. 18.3-52-gc5f78957-1~bddeb~18.04.1 running 'modules:final' at Thu, 23 May 2019 18:06:55 +0000. Up 14.73 seconds.
2019-05-23 18:06:56,818 - cc_kubeadm.py[ERROR]: Failed to run kubeadm: Unexpected error while running command.
Command: ['/usr/bin/kubeadm', 'join', '--config', '/tmp/kubeadm-node.yaml']
Exit code: 1
Reason: -
```

**What did you expect to happen:**
The new machine deployment able to join the cluster successfully even with mismatch K8s version of the different machine deployment

**Anything else you would like to add:**
I can repro 100% times when the machine deployment using version 1.13.6 and not match with the master version 1.14.0. I recreated another machine deployment with version 1.14.0 and the new nodes are able to join

**Environment:**

- Cluster-api-provider-aws version: 
    Image:         gcr.io/cluster-api-provider-aws/cluster-api-aws-controller:v0.2.1
    Image ID:      docker-pullable://gcr.io/cluster-api-provider-aws/cluster-api-aws-controller@sha256:0c2807ce459a090ccd92ca0c89f35ac47fb6e839ce61ff9216c8bd1ce7957e21

- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- OS: CAPA running on photonOS

**Comment by vincepri** [comment]
/milestone Next
/priority important-longterm

I'm not sure if we support joining nodes on N-1 to a cluster running version N.

/cc @detiber @ncdc

**Comment by ncdc** [comment]
@neolit123 if we have a control plane running 1.14.x, should we be able to join a new 1.13.x node to it?

**Comment by neolit123** [comment]
the short answer is no.
i had a rant here but i omitted it.

**Comment by Lokicity** [comment]
Is there a way for me to figure out for a given control plane with version X, which sub versions of machine deployment for worker nodes are supported? I know it is based on kubeadm support. Is there a chart or something I can refer to?

**Comment by ncdc** [comment]
Given control plane version `v1.y.z`, you should be able to join worker nodes `v1.y.<anything>`. The `y` must remain constant.

Given control plane version `v1.y.z`, you should be able to join control plane nodes `v1.y.<anything>` and `v1.<y+1>.<anything>`. You may have to do a bit of hand-editing to do `y+1` but we've had success so far.

**Comment by Lokicity** [comment]
Closing. Current support is "Given control plane version v1.y.z, you should be able to join worker nodes v1.y.<anything>. The y must remain constant.". If ended up needing given control plane version 1.y.z, join worker 1.y+1.<anything>, will raise a feature request.
