### ISSUE TITLE
Implement usage of the container image promoter process

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#795]
/kind feature

**Describe the solution you'd like**
Releasing container images is a manual process today. It requires someone with access to `gcr.io/cluster-api-provider-aws/cluster-api-aws-controller` to push a new image after it is built.

The goal is to automate that process for k8s-sanctioned gcr.io repositories. Take a look here https://github.com/kubernetes-sigs/k8s-container-image-promoter to understand the container image promoter process. There may be some more context https://github.com/kubernetes/k8s.io/issues/158.

We release using the releaser tool found in cmd/release directory in this project. It should also push to the staging directory and at some point prow should promote from that staging directory to production.

**Anything else you would like to add:**
You will have to get added to some google group list, it should be in the documentation linked above.
There are many small pieces to figure out such as, is there a staging gcr.io bucket already in existence for us? what about production? How frequently does the Prow job run? Should we move old releases into the new production bucket?

/assign @chuckha 
/priority important-soon

**Comment by chuckha** [comment]
cc @amy

**Comment by chuckha** [comment]
/lifecycle active
@amy is working on this

**Comment by amy** [comment]
Update: The image promotion process detailed here: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io is not live yet. 

See: https://github.com/kubernetes/k8s.io/issues/157

**Comment by ncdc** [comment]
@detiber I'm thinking all that's left to close this out is to update the releasing.md documentation to talk about the image promoter?

**Comment by detiber** [comment]
@ncdc indeed, I just need to forward port the docs changes back to the `master` branch :)
