### ISSUE TITLE
Add failure events to the cluster object

### ISSUE THREAD

**Issue by ashoksekar07** [kubernetes-sigs/cluster-api-provider-aws#816]
/kind feature

**Describe the solution you'd like**
Right now, when we create a cluster in CAPA, we can see the progress of the cluster being created using the events that are part of the cluster object. This shows up when we do `kubectl describe cluster`. The events which show up are only for the success cases like, a VPC got created, subnet got created, etc. It would be good if this shows failure cases as well like SSH key not found, VPC creation failed due to out of quota error, etc. This will help the users get a better understanding of the progress. Right now, the only way to see these errors is by looking at the logs which is not ideal.

**Environment:**
- Cluster-api-provider-aws version: 0.2.1
- Kubernetes version: (use `kubectl version`): 1.14.1

**Comment by ncdc** [comment]
@ashoksekar07 if we added Creating/Created/Failed events for the various cluster-scoped AWS resources:
- Internet gateways
- NAT gateways
- Subnets
- VPCs

would that give you enough information for starters?

**Comment by ashoksekar07** [comment]
@ncdc That would be a good start. It would be better if we can get other events like success/failure to create bastion node, load balancer, etc. so we can pinpoint the reason for a cluster creation failure.

**Comment by ncdc** [comment]
Fixed in #910 
/close
