### ISSUE TITLE
Additional control plane machines that should join the cluster may inadvertently form new clusters instead

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#828]
/kind bug

**What steps did you take and what happened:**
- Create a cluster with multiple control plane nodes
- Remove one of the control plane nodes from the etcd member list
- `kubectl delete` the machine for that node
- While the machine is still being deleted (deletion timestamp is set but the machine resource still exists while the AWS infra is being deleted), create a new control plane machine
- The new control plane machine ran `kubeadm init` instead of `kubeadm join`

**What did you expect to happen:**
The new control plane machine should always just the cluster

**Anything else you would like to add:**
It looks like possibly `GetControlPlaneMachines` in the machine actuator code needs to ignore machines that have a non-zero deletion timestamp. Otherwise, `isNodeJoin` may ask AWS if the deleted machine's ec2 instance is still either pending or running, and this won't be the case. If this happens, `isNodeJoin` returns false, causing CAPA to consider this new machine to be the first control plane node.

**Environment:**

- Cluster-api-provider-aws version: master / commit f9051c978d278dd575f39dce071fe6234431b44a

**Comment by ncdc** [comment]
cc @ashish-amarnath

**Comment by ncdc** [comment]
I would love someone to double check my assessment of this issue - thanks!

**Comment by ashish-amarnath** [comment]
@ncdc your assessment is correct. I'll 👀 at your PR.
