### ISSUE TITLE
Add a retry to resource tagging

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#836]
/kind bug

**What steps did you take and what happened:**
It is hard to reproduce this, but if a resource fails to tag after creation we will orphan the resource and the cluster will likely encounter problems.

We have reports of security groups failing to tag after being created (thanks amazon) and then on the subsequent try, cluster-api cannot create a duplicate security group but also can't use the existing one as it is improperly tagged. We should retry tags once or twice on create.

Optionally, and I think others should weigh in here, like @detiber, if we find a resource with a name we expect but it has no tags should we try and add the tags to the existing resource if is the resource we expect? For example on security groups, we should check if the data matches what we expect, then tag it assuming the tags after create failed?

cc @Lokicity @vivgoyal

**Comment by detiber** [comment]
This is very likely to be related to the eventual consistency of the AWS APIs: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency

+1 to attempting to re-tag the resource assuming it matches the naming we expect.

**Comment by ncdc** [comment]
@detiber is this still active for you?

**Comment by calebamiles** [comment]
@detiber, @chuckha what I was asking in the meeting is whether we were already using "resource waiters" everywhere possible. In my experience using resource waiters can be helpful for hiding the polling logic to ensure that a specific API object has a desired state.

- [an example](https://github.com/cloudfoundry/bosh-aws-light-stemcell-builder/blob/master/src/light-stemcell-builder/driver/copy_ami_driver.go#L70) where we wait for an AMI to available before attempting to make it public
- [the SDK](https://docs.aws.amazon.com/sdk-for-go/api/), search for "API Request Pagination and Resource Waiters"

**Comment by detiber** [comment]
@calebamiles I think it would definitely help to use the waiters, but according to the docs, it is likely not sufficient and we should also add backoffs and retries to subsequent commands for a given resource as well: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency

**Comment by ncdc** [comment]
Fixed in v0.3.7
/close
