### ISSUE TITLE
Switch to go modules

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-provider-aws#837]
/kind feature

Would make #659 obsolete

**Comment by detiber** [comment]
/milestone Next
/priority backlog

Setting priority based on k8s publishing gomod info only for v1.15+ and dependency on controller-tools and controller-runtime forcing kubernetes 1.13 currently.

**Comment by vincepri** [comment]
/priority important-soon
/assign @chuckha 


I opened up a PR today to move `release-0.1` CAPI branch to https://github.com/kubernetes-sigs/cluster-api/pull/1132 and some utilities for vendoring that you might find useful https://github.com/kubernetes-sigs/cluster-api/pull/1134
