### ISSUE TITLE
Switch to containerd deb/rpm packages

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-provider-aws#848]
/kind feature

Installing binaries makes CVE detection and mitigation really hard. e.g. SSM / Vulnerability scanners can report on versions of installed packages, but not on binaries.

Is there any reason we can't use the docker repo's? they have debs and rpm's for up to containerd 1.2.5

**Comment by detiber** [comment]
Unless things have changed, the debs/rpms provided by the docker repo do not have the cri plugin enabled by default, which is why we currently use the binary release.

**Comment by moshloop** [comment]
/close
moving to image-builder repo
