### ISSUE TITLE
support alternative cri implementations

### ISSUE THREAD

**Issue by stevenolen** [kubernetes-sigs/cluster-api-provider-aws#856]
/kind feature

**Describe the solution you'd like**
Support for CRI implementations beyond `containerd`, namely `docker`. A good first pass may just be to avoid overwriting the `criSocket` value in `nodeRegistration` if it is set by the machine spec.

**Anything else you would like to add:**
Our current container environment is dependent on the use of `docker`, which requires setting `kubeadmConfiguration.[init,join].nodeRegistration.criSocket` as well as an alternative ami with `docker` installed in order to suggest to `kubeadm` that `docker` be used over `containerd`. 

A useful comment from @detiber on slack:
> Longer term, my plan was to add the container runtime to the ami naming convention we use, and make it selectable via the providerConfig

I do think it would be useful to support multiple different CRI implementations via swapping out of amis, but I think there would always be a need to use a custom ami (for ex. we build amis for our kubernetes clusters with system dependencies specific to our use-cases).

**Environment:**

- Cluster-api-provider-aws version: master/0.3.2
- Kubernetes version: (use `kubectl version`): 1.13.7
- OS (e.g. from `/etc/os-release`): ubuntu-18.04

**Comment by sethp-nr** [comment]
A lot of the node bootstrapping flow is going to be different circa v1alpha2, at which point I think this issue would partially be against the [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm) repository, if it were still valid. 

That said,

> A good first pass may just be to avoid overwriting the criSocket value in nodeRegistration if it is set by the machine spec.

Seems like a very reasonable short-term change to make to better support the existing custom AMI flow.

/assign
/lifecycle active
