### ISSUE TITLE
Switch to distroless image

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#865]
/kind feature

**Describe the solution you'd like**
Switch to the distroless image to minimize possible attack vectors.

**Anything else you would like to add:**
CAPV PR that made this change: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/397

**Environment:**

- Cluster-api-provider-aws version: master + release-0.3
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by vincepri** [comment]
This should be already the case, we use `go_image` which builds from https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L52

**Comment by ncdc** [comment]
TIL, thanks
/close
