### ISSUE TITLE
Handle stopped/ terminated ec2 instances

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-sigs/cluster-api-provider-aws#866]
/kind feature

**Describe the solution you'd like**
When an EC2 instance backing a k8s node is stopped or terminated (generalized on 'goes away'), capa actuator should update the actual state of the machine object to "vm-lost" (or something) so the machine goes into an error state. 

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
This is implemented in master. Also xref https://github.com/kubernetes-sigs/cluster-api/issues/1205
/close
