### ISSUE TITLE
Variants and providerconfig

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#88]
We need to start thinking about how to structure versioning of `providerconfig` to handle variants (discussed in #69).

**Comment by detiber** [comment]
Personally, I foresee each variant having separate providerconfigs and being versioned independently. The current code in the actuator to decode from `*runtime.RawExtension` would need to be extended to be able to handle the multiple types that could be returned and also call the custom methods for the proper variant associated with the returned config.
