### ISSUE TITLE
[v1alpha2] Remove bootstrapping code (kubeadm, cloud-init)

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#884]
/kind feature

**Describe the solution you'd like**
In CAPI v1alpha2, the bootstrap logic is externalized to bootstrap providers. As part of the next release, we should remove all the code that generates user-data for AWS instances.

**Comment by chuckha** [comment]
Doing the kubeadm stuff, not cloud init yet

/assign
/lifecycle active

**Comment by chuckha** [comment]
ok, never mind, i'm not ready to break master. Will revisit in a bit.

/remove-lifecycle active

**Comment by detiber** [comment]
We may not be able to fully remove, since we'll still need to inject cloud-init data into the bastion host.

**Comment by ncdc** [comment]
Agreed - we chatted about this but it didn't get recorded above.

**Comment by ncdc** [comment]
@rudoi are you working on this? If not, I can take it on. LMK!

**Comment by rudoi** [comment]
@ncdc no I haven't done any work on this.

/unassign

thanks!
