### ISSUE TITLE
[v1alpha2] Implement finalizers and handle deletion in AWSMachine controller

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#920]
/kind feature

**Describe the solution you'd like**
The v1alpha2 `AWSMachine` controller doesn't have support for deletion and finalizers. The code should be ported from the old [actuator](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.3/pkg/cloud/aws/actuators/machine/actuator.go#L244) and [cluster-api machine controller](https://github.com/kubernetes-sigs/cluster-api/blob/release-0.1/pkg/controller/machine/machine_controller.go#L145-L195).

**Comment by ncdc** [comment]
@vincepri you want this critical-urgent or important-soon?

**Comment by vincepri** [comment]
I categorized it as P0 because it's the last (and required) functionality to finish up the AWSMachine controller

**Comment by ncdc** [comment]
I agree - just checking b/c you mixed the 2 😄 
/priority critical-urgent

**Comment by vincepri** [comment]
Whoops, thanks for catching that!
