### ISSUE TITLE
No Dockerfile for manager in releases 0.2 and 0.3

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/cluster-api-provider-aws#924]
There is no `Dockerfile` for building manager image in any of the release versions. But I see the Dockerfile in `master` branch. `manager` image is necessary while using CAPA.

cc @figo

**Comment by detiber** [comment]
The container images are built using Bazel for the `release-0.2` and `release-0.3` branches.

**Comment by ncdc** [comment]
@jiatongw did Jason's answer clear things up?

**Comment by jiatongw** [comment]
Thanks @detiber . 
Hi Andy, it's clear for me now. Do we need to consider to add a second way to make the build more flexible and compatible to more users? For some reasons, although it's officially provided bazel build,I am now writing my own Dockerfile to build.

**Comment by ncdc** [comment]
We will be using the Dockerfile in master going forward. I guess what I'm asking is if you need one for 0.3.x?

**Comment by jiatongw** [comment]
> We will be using the Dockerfile in master going forward. I guess what I'm asking is if you need one for 0.3.x?

Yes. For each build I am using a specific tag to checkout to the related version

**Comment by jiatongw** [comment]
But that's fine if we don't have plan to use Dockerfile in each release. ^^

**Comment by ncdc** [comment]
Going forward, any release branched from master will have a Dockerfile. I'm guessing you'd just need one for 0.3.x in the short term, right?

**Comment by jiatongw** [comment]
Ah, yup. Sorry I misunderstood what you said.

**Comment by jiatongw** [comment]
I think it's save to close now. Thanks!
/close
