### ISSUE TITLE
Add documentation for how to create a control plane that spans multiple AZs

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#930]
I generate the file which is controlplane-machine-ha, and find that the master machineList file no specified detail of HA.

in fact, the user want to create a cluster is high available, that means is the cluster is HA with whole region, whole VPC. not create three master with same subnet.

/kind feature

**Comment by vincepri** [comment]
To accomplish this today, you'll need to have 3 different subnets in a VPC and specify the `AvailabilityZone` field manually for each Machine.

**Comment by sethp-nr** [comment]
FWIW, what @vincepri suggested is (almost) what we do – we specify the subnets directly – and it works really well.

We've found that the examples in this repo are a helpful starting point, but we pretty quickly ran into the need to template out our own configs that matched our needs.

**Comment by detiber** [comment]
It is also possible to define multiple subnets when creating a Cluster with a "managed VPC" by setting Cluster.Spec.ProviderSpec.NetworkConfig.Subnets[*].AvailabilityZone for each Availability zone you wanted created in the managed VPC. When paired with setting the `AvailabilityZone` on the Machine, this allows you to pre-create Cluster and Machine resources without needing to pre-define the VPC or know the Subnets in advance before creating the Machines.

**Comment by Sn0rt** [comment]
I successfully created a cluster of ha, but in a semi-manual manner.
I create a three node HA-Cluster, but the subnet and route table set is manually.

**Comment by Sn0rt** [comment]
> It is also possible to define multiple subnets when creating a Cluster with a "managed VPC" by setting Cluster.Spec.ProviderSpec.NetworkConfig.Subnets[*].AvailabilityZone for each Availability zone you wanted created in the managed VPC. When paired with setting the `AvailabilityZone` on the Machine, this allows you to pre-create Cluster and Machine resources without needing to pre-define the VPC or know the Subnets in advance before creating the Machines.

is it means the HA info is cluster level not control-panel machine level ?

**Comment by detiber** [comment]
It is both, since the shared infrastructure is created at the "Cluster level" and each control plane Machine needs to specify which subnet/AZ it should belong in.

**Comment by chuckha** [comment]
This is something that was brought up in the meeting: https://blog.scottlowe.org/2019/09/05/highly-available-kubernetes-clusters-on-aws-with-cluster-api/

We could adopt some of this for the v0.4 milestone and rework them for the v0.5 milestone

**Comment by detiber** [comment]
Bumping this to v0.5.x, since we are nearing the v0.5.0 release
/milestone v0.5.x

**Comment by scottslowe** [comment]
With v1alpha3 and the KubeadmControlPlane, it looks like the only way to accomplish this is to provide a `networkSpec` laying out the subnets and AZs, and then the KCP will "do the right thing" and spread control plane nodes across AZs. Should I write-up a document to that end?

**Comment by scottslowe** [comment]
@vincepri @detiber Would adapting this content work to help close this issue? https://blog.scottlowe.org/2020/03/26/ha-kubernetes-clusters-on-aws-with-cluster-api-v1alpha3/

**Comment by vincepri** [comment]
+1 from me
