### ISSUE TITLE
[v1alpha2] Implement AWSCluster controller

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#933]
/kind feature

**Describe the solution you'd like**
- [ ] Update Cluster API module dependency to the latest master release.
- [ ] Scaffold a new controller and type with kubebuilder using `kubebuilder create api --version v1alpha2 --group infrastructure --resource=true --controller=true --kind AWSCluster --make=false`.
- [ ] Migrate `AWSClusterProviderSpec` fields to the newly created `AWSClusterSpec`.
- [ ] Migrate `AWSClusterProviderStatus` fields to the newly created `AWSClusterStatus`.
- [ ] Add `Status.Ready` boolean field to comply with Cluster API expectations.
- [ ] Migrate Actuator and v1alpha1 Cluster API controller logic to AWSCluster controller.

**Comment by ncdc** [comment]
Fixed by #942 
/close
