### ISSUE TITLE
[0.3] If all control plane machine(s) are deleted after the Cluster is marked ready, new control plane machines will not be reconciled.

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#936]
/kind bug

**What steps did you take and what happened:**
I created a control plane Machine, which deployed successfully. But because I had chosen the wrong AMIs, additional machines deployed, but failed to bootstrap. I decided to delete all machines and re-deploy with the correct AMI. I deleted the control plane Machine, and created a new control plane Machine, but it could not be reconciled. The log showed:

```
0727 00:37:23.358498       1 machine_controller.go:115] Reconciling Machine "moocow-controlplane-0"
I0727 00:37:23.358681       1 actuator.go:418] [machine-actuator] "level"=0 "msg"="Checking if machine exists in cluster"  "cluster-name"="moocow" "machine-name"="moocow-con
trolplane-0" "machine-namespace"="default"
I0727 00:37:23.361420       1 machine_controller.go:219] Reconciling machine object moocow-controlplane-0 triggers idempotent create.
I0727 00:37:23.361453       1 actuator.go:116] [machine-actuator] "level"=0 "msg"="Processing machine creation" "cluster-name"="moocow" "machine-name"="moocow-controlplane-0
" "namespace"="default" 
I0727 00:37:23.363489       1 actuator.go:132] [machine-actuator] "level"=0 "msg"="Retrieving machines for cluster" "cluster-name"="moocow" "machine-name"="moocow-controlpla
ne-0" "namespace"="default" 
I0727 00:37:26.274379       1 actuator.go:156] [machine-actuator] "level"=0 "msg"="Machine will join the cluster" "cluster-name"="moocow" "machine-name"="moocow-controlplane
-0" "namespace"="default" 
W0727 00:37:26.292608       1 machine_controller.go:226] Failed to create machine "moocow-controlplane-0": failed to create new bootstrap token: Post https://moocow-apiserve
r-732964184.us-west-2.elb.amazonaws.com:6443/api/v1/namespaces/kube-system/secrets: EOF
```

**What did you expect to happen:**
The new control plane Machine would be successfully reconciled.

**Anything else you would like to add:**
I edited the Cluster object and removed the `aws.cluster.sigs.k8s.io/control-plane-ready` annotation. Then the new control plane Machine was successfully reconciled.

I think the fix is to remove the aws.cluster.sigs.k8s.io/control-plane-ready annotation when all control plane machines are deleted.

I realize that scaling the control plane to zero is not supported, but the only alternative to removing this annotation is deleting and creating the Cluster. That seems a heavy burden to bear if the user intends to delete the control plane but wants to keep the cluster infrastructure.

**Environment:**

- Cluster-api-provider-aws version: v0.3.6 
- Kubernetes version: v1.15.1
- OS (e.g. from `/etc/os-release`):  Ubuntu 18.04

**Comment by detiber** [comment]
@ncdc We'll likely need to track something similar for v1alpha2 as well.

**Comment by ncdc** [comment]
@detiber yes but in the kubeadm bootstrapper repo most likely

**Comment by dlipovetsky** [comment]
/lifecycle active
I can take this up today. Should I work off the release-0.3 branch?

**Comment by ncdc** [comment]
@dlipovetsky thanks! And yes, release-0.3

**Comment by ncdc** [comment]
941 has merged.
/close
