### ISSUE TITLE
Document manual release-blocking test for HA cluster

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#937]
/kind feature

**Describe the solution you'd like**

Create a manual test plan for testing HA cluster creation using:
- Default Ubuntu-based AWS images for k8s v1.15.x
- 3 Control Plane Machines
- 1 MachineDeployment for Worker nodes
- Calico for CNI

Where each Control Plane Machine is deployed to a different AWS AZ:
- Cluster.Spec.ProviderSpec.NetworkConfig.Subnets[*].AvailabilityZone set appropriately for multiple Availability Zones
- MachineSpec.ProviderSpec.AvailabilityZone set appropriately for each Control Plane Machine 

Scenarios to test:
- `clusterctl create cluster` succeeds
- Created cluster passes Sonobuoy Conformance test
- Scale up/down of MachineDeployment works as expected
- `clusterctl delete cluster` succeeds

**Comment by ncdc** [comment]
@detiber can we retarget this to v0.5.0?
