### ISSUE TITLE
Document manual release-blocking test for non-HA cluster

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#938]
/kind feature

**Describe the solution you'd like**

Create a manual test plan for testing HA cluster creation using:
- Default Ubuntu-based AWS images for k8s v1.15.x
- 1 Control Plane Machine
- 1 MachineDeployment for Worker nodes
- Calico for CNI

Scenarios to test:
- `clusterctl create cluster` succeeds
- Created cluster passes Sonobuoy Conformance test
- Scale up/down of MachineDeployment works as expected
- `clusterctl delete cluster` succeeds

**Comment by ncdc** [comment]
@detiber can we retarget this to v0.5.0?
