### ISSUE TITLE
Document manual release-blocking test for AWS functionality

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#940]
/kind feature

**Describe the solution you'd like**
Given a cluster, such as the one defined in #938, and a group of worker Nodes managed by a MachineDeployment, ensure that the AWS cloud provider functionality works as expected:

- Service w/ Type=LoadBalancer is created/deleted on request as appropriate
- Dynamic Persistent Volumes backed by EBS are functional

**Comment by ncdc** [comment]
@detiber can we retarget this to v0.5.0?
