### ISSUE TITLE
Cluster deletion fails because there is no VPC present.

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#943]
/kind bug

**What steps did you take and what happened:**
I tried to create a cluster and it failed because I was hitting maximum VPC limit in my AWS account. Next I tried to delete the cluster but it failed because it couldn't find any avaialble VPC.

**What did you expect to happen:**
I would expect deletion to proceed to next steps if there is no VPC present.

**Anything else you would like to add:**
E0731 16:53:33.832490       1 cluster_controller.go:166] Error reconciling cluster object lcm-085950f4; failed to reconcile network for cluster "xxx-085950f4": failed to create new vpc: failed to create vpc: VpcLimitExceeded: The maximum number of VPCs has been reached.

E0731 16:58:50.271866       1 actuator.go:223] [cluster-actuator] "msg"="Error deleting cluster" "error"="failed to delete vpc \"\": MissingParameter: The request must contain the parameter vpcId\n\tstatus code: 400, request id: 912dc23a-4ab6-4106-95c7-c3202bc150a6"  "cluster-name"="xxx-085950f4" "cluster-namespace"="4d95faba9cb7ee388671ac3cef6ee79b39c25f15"

**Environment:**

- Cluster-api-provider-aws version: 0.3.6
- Kubernetes version: (use `kubectl version`): 1.14.1

**Comment by vivgoyal** [comment]
@detiber I am not sure if this goes here but I am also seeing similar sort of error with instance/subnets deletion. It may be happening at other places too.

I0807 22:15:25.007734       1 actuator.go:248] [machine-actuator] "level"=0 "msg"="Deleting machine in cluster"  "cluster-name"="kkkk-730159" "machine-name"="control-plane-kkkk-730159-2" "machine-namespace"="512eae6d04d45be2e8aff9470334dd8fecb09c50"

I0807 22:15:25.010275       1 instances.go:105] [machine-actuator]/cluster.k8s.io/v1alpha1/512eae6d04d45be2e8aff9470334dd8fecb09c50/kkkk-730159/control-plane-kkkk-730159-2 "level"=2 "msg"="Looking for instance by id"  "instance-id"="i-xxxxx"

E0807 22:15:25.688663       1 machine_controller.go:164] Failed to delete machine "control-plane-kkkk-730159-2": failed to get instance: InvalidInstanceID.NotFound: The instance ID 'i-xxxxx' does not exist

**Comment by ncdc** [comment]
Please file new issues

On Aug 7, 2019, at 6:30 PM, vivgoyal <notifications@github.com<mailto:notifications@github.com>> wrote:


@detiber<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdetiber&data=02%7C01%7Cgoldsteina%40vmware.com%7C2e1f1a5ccb9f41e40a2308d71b86d14b%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637008138160805598&sdata=DpxTqVVmtVTxByFwJRhjNdEBQsYGQOx4N8ikhX0zaF4%3D&reserved=0> I am not sure if this goes here but I am also seeing similar sort of error with instance/subnets deletion. It may be happening at other places too.

I0807 22:15:25.007734 1 actuator.go:248] [machine-actuator] "level"=0 "msg"="Deleting machine in cluster" "cluster-name"="kkkk-730159" "machine-name"="control-plane-kkkk-730159-2" "machine-namespace"="512eae6d04d45be2e8aff9470334dd8fecb09c50"

I0807 22:15:25.010275 1 instances.go:105] [machine-actuator]/cluster.k8s.io/v1alpha1/512eae6d04d45be2e8aff9470334dd8fecb09c50/kkkk-730159/control-plane-kkkk-730159-2<http://cluster.k8s.io/v1alpha1/512eae6d04d45be2e8aff9470334dd8fecb09c50/kkkk-730159/control-plane-kkkk-730159-2> "level"=2 "msg"="Looking for instance by id" "instance-id"="i-xxxxx"

E0807 22:15:25.688663 1 machine_controller.go:164] Failed to delete machine "control-plane-kkkk-730159-2": failed to get instance: InvalidInstanceID.NotFound: The instance ID 'i-xxxxx' does not exist

**Comment by detiber** [comment]
I created a PR to address the case where a Machine is missing an instanceID: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/984

I was not able to see an obvious place where we would hit issues with the other resources, though (since we are generally querying the resources before deletion). If you do hit an issue with one of the other resources, please do create a new issue with logs and resource output to help further debugging.

**Comment by vivgoyal** [comment]
Sure. I dont have a repro right now. If it happens again, I would go ahead and create one but for now this should be good.

**Comment by ncdc** [comment]
Fixed in #955 
/close
