### ISSUE TITLE
Remove bastion host requirement

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#947]
/kind feature

**Describe the solution you'd like**
With the announcement of AWS Session Manager support for tunneling of SSH and SCP, we can remove the Bastion host requirement. 

This would require a few different tasks:
- Add installation of SSM agent >= 2.3.672.0 on Cluster API images: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-ssm-agent.html
- Documentation updates for how to access instances: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html
- Remove management of the bastion instance

**Comment by underrun** [comment]
If the goal is to replace the bastion requirement with SSM, I would like to see this made optional as well as moving to SSM. 

In production environments I'd like to be able to eliminate/minimize the possibility of direct node access and allow this type/level of access to be controlled and managed explicitly/externally to cluster lifecycle.

This feels like the right issue as we're talking about removing requirements, but if this should be an additional issue, please let me know.

**Comment by alexbrand** [comment]
Having the option to have SSM installed on the nodes would be great!
