### ISSUE TITLE
premission required:  failed to describe vpc attribute

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#950]
/kind bug

`
E0802 03:18:33.901229       1 cluster_controller.go:166] Error reconciling cluster object manage-cluster; failed to reconcile network for cluster "manage-cluster": failed to to set vpc attributes for "vpc-0a42fc6644d299113": failed to describe vpc attribute: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: db498bbf-e4ed-45d2-9ab1-140e8f94c9be
`

**Comment by detiber** [comment]
Closing, since #951 has merged
/close
