### ISSUE TITLE
quickstart script for Getting started with cluster-api-provider-aws

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-aws#956]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
There is too much troubleshooting involved to get the "Getting started with cluster-api-provider-aws" working.
There is a need to build a quickstart script that would seamlessly build a default setup to be able to understand how it works and then help towards enhancing it further.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
I propose we close this now that we have the v1alpha2 quickstart docs - thoughts?

**Comment by vincepri** [comment]
+1 as well, we can always reopen if necessary later

/close
