### ISSUE TITLE
Support alternative identity partitions for IAM roles

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#959]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In the IAM roles produced by clusterawsadm, ARNs are generated in the format `arn:aws`. However, AWS has completely separate identity partitions, namely `arn:aws-us-gov` for GovCloud and `arn:aws-cn` for AWS China.

For clusterawsadm to be able to support these environments, would need to add a parameter along the lines of `--identity-partition` defaulting to AWS, but being able to swap it out.

Potentially, the different name should be represented in the CFN template, and names of the policies and roles too in case a user wants to use multiple identity partitions in the same AWS account.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.3.6
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
There's no other hardcoding of the `arn:aws` identity partition in the codebase in the controller code.

**Comment by aaroniscode** [comment]
Going to take a stab at this. I'm pretty sure the `/` commands won't work, but:
/assign
/lifecycle-active
