### ISSUE TITLE
Cluster with reused name in different namespace fails to boot

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#969]
/kind bug

**What steps did you take and what happened:**
1. Boot a cluster with a given name in the default namespace
2. Wait for that cluster to successfully come up
3. Create a new namespace
4. Boot a cluster with an identical name to the first in the new namespace
5. Cluster does not create a new VPC or any associated resources

**What did you expect to happen:**
A new VPC, set of machines, and associated resources should have been booted

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
The cluster name needs to be unique per <AWS account, region>.

**Comment by detiber** [comment]
Currently we treat the cluster name as a unique value. We have a few options here:
- Add some type of validation that the cluster name is indeed unique
  - This would still present issues where the controllers are scoped to a single namespace or running under different management clusters
- Prefix everywhere we use the cluster name for naming, tagging, etc with the namespace name
  - This would still present issues where multiple management clusters are in use
  - This could also lead to exceeding string lengths in various places and would need to be accounted for.
- Generate some type of unique identifier that can be pre/post pended to the cluster name
  - This unique identifier would need to be generated and saved to the spec to persist across pivot or a backup/restore (resource UUID does not persist, nor does Status)
  - string lengths should also be accounted for
  - may need to also tag resources with the namespace to help for easier identification of resources in AWS, or some other method to easily differentiate between clusters if running on a single management cluster.

**Comment by detiber** [comment]
@ncdc that limitation only exists because of the current design, but we do need to have a unique "cluster name" that we set that is used for the integrated or external cloud-provider integration.

**Comment by ncdc** [comment]
@detiber which is still per account+region, unless I'm mistaken?

**Comment by detiber** [comment]
@ncdc correct

**Comment by vincepri** [comment]
I really like the 3rd option @detiber suggested, which might be part of a larger naming refactor. AWS resources are notoriously limited in how many chars they can use, it'd be great if we could come up with a consistent naming scheme that can be used across all resources and solve this issue as well.

**Comment by detiber** [comment]
There are multiple issues related to clusters with the same name in different namespaces, including breakage with cloud-provider integration based on the tagging scheme we use.

We would need to update the naming/tagging that we do for our resource ownership, but also for the cloud-provider integration tags. We'd likely also need to update the way we are handling setting the Cluster Name in the kubeadm config as well.

**Comment by ncdc** [comment]
Going through open unassigned issues in the v0.5.0 milestone. We have a decent amount of work left to do on CAPI features (control plane, clusterctl, etc). While this is an unfortunately ugly bug, I think we need to defer it to v0.5.

/milestone Next
/remove-priority important-soon
/priority important-longterm
