### ISSUE TITLE
Bootstrap failure detection

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#972]
**Describe the solution you'd like**
If bootstrapping doesn't succeed, set AWSMachine.Status.FailureReason and FailureMessage to indicate there was an error. 

**Anything else you would like to add:**
More information in https://github.com/kubernetes-sigs/cluster-api/issues/2554.

We may need to amend the bootstrap provider contract to require them to write a sentinel file indicating success to a specific location because not all bootstrap providers will necessarily use cloud-init and have that as a consistent means for checking success/failure. I will probably write up a separate proposal for that.

/kind feature

-------------------
(original bug report)

**What steps did you take and what happened:**
For some reason, Cloud init has failed. And for some other, possibly related, possibly unrelated, reason, your control plane has restarted. You're going to get continued error messages about "Unable to acquire control plane lock- requeueing"

**What did you expect to happen:**
The machine failed to boot. It should have been terminated and a new machine booted in its place.

**Comment by ncdc** [comment]
Thanks for the writeup @liztio.

@detiber @randomvariable is there any easy & consistent way, as an external/AWS client, to know if cloud-init failed?

**Comment by ncdc** [comment]
@liztio you could potentially retitle this to "Bad user experience if CoudInit fails"

**Comment by detiber** [comment]
@ncdc we've discussed a few different ways of determining the status of cloud-init.

- Having a process write back to the management cluster to update the status of it's resource
  - requires having a connection back to the management server (no worky with kind clusters without some type of reverse proxy)
- Having a process write to an S3 bucket or some other aws facility
  - Adds a new AWS dependency
- Leverage SSM to run a remote command on the host to query status
  - Requires us to ensure the SSM agent is installed as part of the AMI baking process
- Have the controller remote into the instance and query the cloud-init status/parse the output
  - Requires the private ssh key, which we don't require today, should likely avoid this scenario in favor of SSM

The simplest solution we could probably put in place today is to do a simple timeout to mark the Machine as bad and terminate the backing instance (and any other cleanup that would be needed for the control plane locking.

**Comment by randomvariable** [comment]
Same thoughts, but using SNS+SQS which is the model used in autoscaling lifecycle hooks, i.e. CAPA listens to an SQS queue subscribed to an SNS stream that instances post status to. At what stages in the instance bootstrapping process you'd want to do that - there's some guidance in the [AutoScaling docs themselves](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html).

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/16#issuecomment-424078441 has the previous discussions.

**Comment by detiber** [comment]
I'm not sure if there is any cloud-init data that is logged to the console, but we could potentially use EC2.GetConsoleOutput to parse that output as well.

**Comment by liztio** [comment]
I think it'd be good if we had some way of annotating which control plane node had been selected as the initial one. Either an annotation or updating the control-plane lock.

**Comment by liztio** [comment]
We could also change the error message from "failed to acquire lock" to "awaiting first control plane boot"

**Comment by ncdc** [comment]
We can change the log message, but it's important to remember that it's not ultimately a user-facing message.

@liztio re the control plane lock, could you please file a separate issue for discussing improvements to it (such as keeping track of the initial machine)?

**Comment by randomvariable** [comment]
> I'm not sure if there is any cloud-init data that is logged to the console, but we could potentially use EC2.GetConsoleOutput to parse that output as well.

Would prefer not to have to parse console output across distros and account for line returns etc... think it would be extremely brittle.

Not only that, it's only the last 64KB and only supported on Nitro (KVM) backed instances

**Comment by liztio** [comment]
@ncdc what do you mean by "not a user-facing message?" I think people are going to have to consume these logs one way or another, these things are going to fail sometimes

**Comment by liztio** [comment]
Created #981

**Comment by ncdc** [comment]
If someone else manages the Cluster API installation, I, as a user, may not have access to view the log messages in the CAPI and CAPA controllers. We should therefore both improve the log message, and improve the UX for the end user when you get into a situation where the lock is stale for whatever reason.

**Comment by enxebre** [comment]
> > I'm not sure if there is any cloud-init data that is logged to the console, but we could potentially use EC2.GetConsoleOutput to parse that output as well.
> 
> Would prefer not to have to parse console output across distros and account for line returns etc... think it would be extremely brittle.
> 
> Not only that, it's only the last 64KB and only supported on Nitro (KVM) backed instances.
> 
> There is also [EventBridge](https://aws.amazon.com/about-aws/whats-new/2019/07/introducing-amazon-eventbridge/), the rebranded CloudWatch Events. Not in all regions though.

Another possibility might be have something like AWSMachineStatus.console and dump the raw EC2.GetConsoleOutput there with no parsing.
That at least would give a place to look at when something goes wrong while booting the instance before it evens runs a kubelet, e.g cloud init failures, ignition failures, systemd failures...

**Comment by randomvariable** [comment]
Here's the doc that was started a while back... didn't reach any firm conclusions
https://docs.google.com/document/d/1FVRxo9toKSUmvKIUFFzPFhnFrfdR9s7S6Bl4shovNlg/edit

The case against doing AWSMAchineStatus.console was we probably don't want to spam that much data into etcd.
