### ISSUE TITLE
cluster names with . in the name error as ELB can't contain characters that are not letters, or digits or the dash

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes-sigs/cluster-api-provider-aws#977]
/kind bug

**What steps did you take and what happened:**
Created a cluster with a `.` in the name, ie:

```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: pks.xxx-yyy.com
```
**What did you expect to happen:**
Cluster to come up. Perhaps either converting or removing invalid characters.

**Anything else you would like to add:**
Relevant error message below:
```
E0807 19:23:44.275408       1 cluster_controller.go:229] Error reconciling cluster object pks.xxx-yyy.com; failed to reconcile load balancers for cluster "pks.xxx-yyy.com": unexpected aws error: ValidationError: LoadBalancer name cannot contain characters that are not letters, or digits or the dash.
	status code: 400, request id: df02fe97-b948-11e9-8552-478f3e294fff
```

**Environment:**

- Cluster-api-provider-aws version: v0.3.7
- Kubernetes version: (use `kubectl version`): 1.15.2
- OS (e.g. from `/etc/os-release`): MacOS 10.14.6 (running `clusterctl`)

**Comment by detiber** [comment]
I'm wondering if we should consider this more broadly as a validation/translation issue around cluster name, since we also have other cases where a cluster name may be too long when we are munging the name for resource creation.

**Comment by rudoi** [comment]
@detiber I agree with tackling this broadly. There are a bunch of places across all the providers where the cluster name is used to name resources, and I think there are a bunch of issues out there that basically have "lol we should probably handle that..." in a comment :laugh:.

Could it be validating webhook time?

**Comment by ncdc** [comment]
I think we're finally at a point where we could consider upgrading to kubebuilder v2, which is supposed to have better support for webhooks.

**Comment by detiber** [comment]
> Could it be validating webhook time?

Maybe? we probably need to start with documenting what the limitations are for where we use Cluster.Name currently.
