### ISSUE TITLE
meaning kubeconfig name: rename the kubeconfig to <CLUSTER>-kubeconfig

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#987]
/kind feature

can we consider to rename the kubeconfig as <CLUSTER>-kubeconfig ?

```
clusterctl alpha phases get-kubeconfig --provider aws --cluster-name aws-eni --kubeconfig boots -v=5
```

**Comment by vincepri** [comment]
@Sn0rt Which kubeconfig are you referring to in this issue? It's not clear to me what's being suggested here, there seems to be already a kubeconfig flag in the command?

**Comment by Sn0rt** [comment]
> @Sn0rt Which kubeconfig are you referring to in this issue? It's not clear to me what's being suggested here, there seems to be already a kubeconfig flag in the command?

ok, got it. If the default name of kubeconfig is <CLUSTERNAME>-kubeconfig will be better, what do you think ?
